// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package segmentation

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

// ErrNoDictionary is the sentinel returned by LoadBRKDictionary when no .brk
// blob has been supplied. Callers can detect this via errors.Is to fall back
// to the rules-based goWordBreakIterator path.
//
// This sentinel exists because Gocene cannot, at build time, produce or bundle
// the ICU4J/ICU4C compiled rule files (.brk) that Apache Lucene ships in its
// analysis/icu JAR. The blobs are generated by an offline ICU compilation
// pipeline against the ICU4C source tree; see Lucene's
// org.apache.lucene.analysis.icu.RBBIRuleCompiler. Bundling them requires an
// external procurement step tracked separately in the project backlog.
var ErrNoDictionary = errors.New("icu: no .brk dictionary supplied")

// ErrInvalidBRK is returned when a .brk byte stream fails header validation.
var ErrInvalidBRK = errors.New("icu: invalid .brk dictionary content")

// BRKDataFormatID is the ICU dataFormat identifier for compiled
// RuleBasedBreakIterator blobs. The four bytes spell "Brk " in ASCII.
//
// Source: icu4c/source/common/rbbidata.h (kDataFormat).
var BRKDataFormatID = [4]byte{'B', 'r', 'k', ' '}

// ICUDataMagic1 and ICUDataMagic2 are the two byte-fields at offsets 2 and 3
// of every ICU data file's MappedData prefix. They are stored as raw bytes
// (not endian-swapped) so they identify the file format regardless of the
// host endianness recorded in UDataInfo.isBigEndian.
//
// Source: icu4c/source/common/udata.h (MappedData).
const (
	ICUDataMagic1 byte = 0xda
	ICUDataMagic2 byte = 0x27
)

// RBBIDataMagic is the kRBBI_DataMagic constant at the start of the
// RBBIDataHeader: 0xb1a0. Multi-byte fields in the header are encoded in the
// endianness reported by UDataInfo.isBigEndian.
//
// Source: icu4c/source/common/rbbidata.h (kRBBIDataMagic).
const RBBIDataMagic uint32 = 0x0000b1a0

// minBRKSize is a conservative lower bound on the size of a valid .brk file.
// MappedData (4 bytes) + UDataInfo (20 bytes) = 24 bytes minimum header,
// plus the 84-byte RBBIDataHeader.
const minBRKSize = 24 + 84

// pickByteOrder returns the binary.ByteOrder matching the ICU data file's
// recorded endianness.
func pickByteOrder(isBigEndian bool) binary.ByteOrder {
	if isBigEndian {
		return binary.BigEndian
	}
	return binary.LittleEndian
}

// BRKDictionary is an in-memory representation of a parsed ICU
// RuleBasedBreakIterator binary blob (a .brk file).
//
// The struct captures the metadata required to detect, identify, and route a
// dictionary to the correct script consumer (CJK Default.brk vs Myanmar
// MyanmarSyllable.brk vs future Khmer/Thai/Lao variants). The raw Rules byte
// slice holds the post-header bytes verbatim so a future RBBI execution engine
// can interpret them without re-reading the source.
//
// Deviation: Gocene does not currently execute compiled RBBI rules. A parsed
// BRKDictionary is therefore a passive container — it proves a blob is
// well-formed and identifies its target script, but it does not perform
// dictionary-based segmentation. The placeholder RuleBasedBreakIterator
// returned by AsBreakIterator falls through to goWordBreakIterator. Wiring a
// real RBBI engine is tracked as a backlog task; see the package README.
type BRKDictionary struct {
	// FormatVersion is the four-byte UDataInfo.formatVersion field
	// (typically 6.0.0.0 for ICU 70+ RBBI files).
	FormatVersion [4]byte

	// DataVersion is the four-byte UDataInfo.dataVersion field (Unicode
	// version stamp).
	DataVersion [4]byte

	// IsBigEndian mirrors UDataInfo.isBigEndian. ICU data is normally
	// stored little-endian on disk; we record the flag for completeness.
	IsBigEndian bool

	// CharsetFamily mirrors UDataInfo.charsetFamily (0 = ASCII, 1 = EBCDIC).
	CharsetFamily byte

	// HeaderSize is the size in bytes of the leading UDataInfo header
	// (always a multiple of 16).
	HeaderSize uint16

	// Length is the total length, in bytes, of the RBBI payload as recorded
	// in RBBIDataHeader.fLength.
	Length uint32

	// CatCount is the number of character categories
	// (RBBIDataHeader.fCatCount). Used to size the trie row stride.
	CatCount uint32

	// Rules is the raw blob, including both the UDataInfo header and the
	// RBBIDataHeader plus its trailing tables. Stored verbatim so a future
	// RBBI executor can reinterpret it without re-reading the source.
	Rules []byte
}

// LoadBRKDictionary reads a compiled ICU RuleBasedBreakIterator blob from r
// and returns a parsed BRKDictionary.
//
// LoadBRKDictionary validates the UDataInfo header (magic, dataFormat,
// endianness) and the RBBIDataHeader (kRBBI_DataMagic, length consistency).
// It does NOT execute the rules — see BRKDictionary for the deviation note.
//
// If r is nil, LoadBRKDictionary returns ErrNoDictionary so callers can detect
// the "no dictionary supplied" branch via errors.Is without bespoke nil
// checks. Other parse failures return errors wrapping ErrInvalidBRK.
func LoadBRKDictionary(r io.Reader) (*BRKDictionary, error) {
	if r == nil {
		return nil, ErrNoDictionary
	}
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("icu: reading .brk blob: %w", err)
	}
	return ParseBRKDictionary(data)
}

// ParseBRKDictionary parses an in-memory .brk byte slice and returns the
// validated BRKDictionary. The slice is retained in BRKDictionary.Rules; the
// caller must not mutate it after the call.
//
// ParseBRKDictionary returns an error wrapping ErrInvalidBRK on any
// inconsistency. It returns ErrNoDictionary when data is nil or empty so the
// caller-facing contract matches LoadBRKDictionary.
func ParseBRKDictionary(data []byte) (*BRKDictionary, error) {
	if len(data) == 0 {
		return nil, ErrNoDictionary
	}
	if len(data) < minBRKSize {
		return nil, fmt.Errorf("%w: blob too small (%d bytes, need >= %d)",
			ErrInvalidBRK, len(data), minBRKSize)
	}

	// MappedData prefix (icu4c/source/common/udata.h):
	//   uint16 headerSize       (offset 0; written in host endianness)
	//   uint8  magic1           (offset 2; raw byte 0xda)
	//   uint8  magic2           (offset 3; raw byte 0x27)
	//
	// UDataInfo (immediately after MappedData):
	//   uint16 size             (offset 4; written in host endianness)
	//   uint16 reservedWord     (offset 6)
	//   uint8  isBigEndian      (offset 8)
	//   uint8  charsetFamily    (offset 9)
	//   uint8  sizeofUChar      (offset 10)
	//   uint8  reservedByte     (offset 11)
	//   uint8  dataFormat[4]    (offset 12)  must be "Brk "
	//   uint8  formatVersion[4] (offset 16)
	//   uint8  dataVersion[4]   (offset 20)
	if data[2] != ICUDataMagic1 || data[3] != ICUDataMagic2 {
		return nil, fmt.Errorf("%w: bad ICU magic %02x %02x (want %02x %02x)",
			ErrInvalidBRK, data[2], data[3], ICUDataMagic1, ICUDataMagic2)
	}

	isBigEndian := data[8] != 0
	endian := pickByteOrder(isBigEndian)
	headerSize := endian.Uint16(data[0:2])
	if int(headerSize) < 24 || int(headerSize) > len(data) {
		return nil, fmt.Errorf("%w: UDataInfo headerSize %d out of range",
			ErrInvalidBRK, headerSize)
	}

	dict := &BRKDictionary{
		HeaderSize:    headerSize,
		IsBigEndian:   isBigEndian,
		CharsetFamily: data[9],
	}
	copy(dict.FormatVersion[:], data[16:20])
	copy(dict.DataVersion[:], data[20:24])

	if data[12] != BRKDataFormatID[0] || data[13] != BRKDataFormatID[1] ||
		data[14] != BRKDataFormatID[2] || data[15] != BRKDataFormatID[3] {
		return nil, fmt.Errorf("%w: dataFormat %q is not %q",
			ErrInvalidBRK, data[12:16], BRKDataFormatID[:])
	}

	// RBBIDataHeader layout (icu4c/source/common/rbbidata.h):
	//   uint32 fMagic          (offset headerSize+0)  must be RBBIDataMagic
	//   uint8  fFormatVersion[4](offset headerSize+4)
	//   uint32 fLength         (offset headerSize+8)
	//   uint32 fCatCount       (offset headerSize+12)
	//   ... (remaining table offsets follow)
	rbbiBase := int(headerSize)
	if rbbiBase+16 > len(data) {
		return nil, fmt.Errorf("%w: RBBIDataHeader truncated", ErrInvalidBRK)
	}
	rbbiMagic := endian.Uint32(data[rbbiBase : rbbiBase+4])
	if rbbiMagic != RBBIDataMagic {
		return nil, fmt.Errorf("%w: bad RBBIDataHeader magic 0x%08x (want 0x%08x)",
			ErrInvalidBRK, rbbiMagic, RBBIDataMagic)
	}
	dict.Length = endian.Uint32(data[rbbiBase+8 : rbbiBase+12])
	dict.CatCount = endian.Uint32(data[rbbiBase+12 : rbbiBase+16])

	if dict.Length == 0 || int(dict.Length) > len(data)-rbbiBase {
		return nil, fmt.Errorf("%w: RBBI fLength %d inconsistent with blob (%d bytes after UDataInfo)",
			ErrInvalidBRK, dict.Length, len(data)-rbbiBase)
	}

	dict.Rules = data
	return dict, nil
}

// AsBreakIterator returns a RuleBasedBreakIterator backed by this dictionary.
//
// Deviation: until Gocene ships a native RBBI execution engine, the returned
// iterator falls through to goWordBreakIterator (the rules-based UAX#29
// approximation). The dictionary metadata is preserved on the iterator so
// future revisions can switch execution paths without changing the call site.
//
// Callers that need to know whether dictionary execution is *actually*
// happening should inspect HasDictionaryExecution.
func (d *BRKDictionary) AsBreakIterator() RuleBasedBreakIterator {
	return &dictionaryBackedBreakIterator{
		goWordBreakIterator: goWordBreakIterator{},
		dict:                d,
	}
}

// HasDictionaryExecution reports whether AsBreakIterator returns an iterator
// that actually executes the dictionary's compiled rules.
//
// This is hard-coded to false until an RBBI engine ships; see the package
// README for the tracking backlog task.
func (d *BRKDictionary) HasDictionaryExecution() bool {
	return false
}

// dictionaryBackedBreakIterator carries dictionary metadata alongside the
// rules-based goWordBreakIterator. Behaviourally identical to
// goWordBreakIterator until an RBBI engine lands.
type dictionaryBackedBreakIterator struct {
	goWordBreakIterator
	dict *BRKDictionary
}

// Clone returns an independent copy preserving the dictionary reference.
func (d *dictionaryBackedBreakIterator) Clone() RuleBasedBreakIterator {
	cp := *d
	return &cp
}

// Dictionary returns the BRKDictionary this iterator was constructed from.
// Useful for tests and for code that wants to inspect the loaded metadata.
func (d *dictionaryBackedBreakIterator) Dictionary() *BRKDictionary {
	return d.dict
}
