// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package index

import (
	"fmt"
	"sync"

	"github.com/FlavioCFOliveira/Gocene/store"
)

// tempOutputCreator is a local interface used to detect if a Directory supports
// the creation of temporary outputs. Since CreateTempOutput is not part of the
// global store.Directory interface, we use a type assertion at runtime.
type tempOutputCreator interface {
	CreateTempOutput(prefix, suffix string, ctx store.IOContext) (store.IndexOutput, error)
}

// TrackingTmpOutputDirectoryWrapper is a directory wrapper that tracks the mapping
// between requested file names and the actual temporary file names generated by the
// underlying directory.
//
// This is the Go port of Lucene's org.apache.lucene.index.TrackingTmpOutputDirectoryWrapper.
type TrackingTmpOutputDirectoryWrapper struct {
	*store.FilterDirectory
	mu        sync.RWMutex
	fileNames map[string]string
}

// NewTrackingTmpOutputDirectoryWrapper creates a new TrackingTmpOutputDirectoryWrapper
// wrapping the provided directory.
func NewTrackingTmpOutputDirectoryWrapper(in store.Directory) *TrackingTmpOutputDirectoryWrapper {
	return &TrackingTmpOutputDirectoryWrapper{
		FilterDirectory: store.NewFilterDirectory(in),
		fileNames:       make(map[string]string),
	}
}

// CreateOutput overrides the standard CreateOutput to always create a temporary file
// via the wrapped directory's CreateTempOutput, recording the mapping from the
// requested name to the generated temporary name.
func (d *TrackingTmpOutputDirectoryWrapper) CreateOutput(name string, ctx store.IOContext) (store.IndexOutput, error) {
	in := d.GetDelegate()
	toc, ok := in.(tempOutputCreator)
	if !ok {
		return nil, fmt.Errorf("TrackingTmpOutputDirectoryWrapper: delegate %T does not support CreateTempOutput", in)
	}

	// Lucene's implementation calls createTempOutput(name, "", context)
	output, err := toc.CreateTempOutput(name, "", ctx)
	if err != nil {
		return nil, err
	}

	d.mu.Lock()
	d.fileNames[name] = output.GetName()
	d.mu.Unlock()

	return output, nil
}

// OpenInput overrides the standard OpenInput to resolve the requested name
// against the tracked temporary file names before delegating the open operation.
func (d *TrackingTmpOutputDirectoryWrapper) OpenInput(name string, ctx store.IOContext) (store.IndexInput, error) {
	d.mu.RLock()
	tmpName, ok := d.fileNames[name]
	d.mu.RUnlock()

	// keep the original file name if no match, it might be a temp file already
	if !ok {
		tmpName = name
	}

	return d.FilterDirectory.OpenInput(tmpName, ctx)
}

// GetTemporaryFiles returns a copy of the mapping from original names to
// generated temporary file names.
func (d *TrackingTmpOutputDirectoryWrapper) GetTemporaryFiles() map[string]string {
	d.mu.RLock()
	defer d.mu.RUnlock()

	res := make(map[string]string, len(d.fileNames))
	for k, v := range d.fileNames {
		res[k] = v
	}
	return res
}
