// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

// TrackingTmpOutputDirectoryWrapper
// Source: lucene/core/src/java/org/apache/lucene/index/TrackingTmpOutputDirectoryWrapper.java
// Purpose: A FilterDirectory that intercepts CreateOutput and instead allocates
// a unique temporary output via the wrapped directory's CreateTempOutput,
// recording the mapping from the caller-supplied logical name to the actual
// temporary file name. OpenInput transparently resolves logical names back
// to the stored temp names so callers can read what they wrote without
// knowing the rename happened.

package index

import (
	"fmt"
	"sync"

	"github.com/FlavioCFOliveira/Gocene/store"
)

// tempOutputCreator is the structural interface used to obtain
// CreateTempOutput from a Directory at runtime. Gocene's Directory
// interface does not declare CreateTempOutput, mirroring the upstream
// optional method on FilterDirectory's delegate.
type tempOutputCreator interface {
	CreateTempOutput(prefix, suffix string, ctx store.IOContext) (store.IndexOutput, error)
}

// TrackingTmpOutputDirectoryWrapper wraps a Directory and rewrites all
// CreateOutput calls to CreateTempOutput on the delegate, tracking the
// mapping from the caller-supplied logical name to the generated temp
// file name. OpenInput consults the mapping and transparently resolves
// logical names. Unknown names pass through untouched, in case the file
// is already a temporary file produced elsewhere.
//
// This is the Go port of Lucene's
// org.apache.lucene.index.TrackingTmpOutputDirectoryWrapper.
type TrackingTmpOutputDirectoryWrapper struct {
	*store.FilterDirectory

	// in is the delegate directory; retained explicitly so the wrapper can
	// invoke CreateTempOutput without requiring it to be part of the
	// Directory interface.
	in store.Directory

	// fileNames maps the caller-supplied logical file name to the actual
	// temp file name generated by the delegate's CreateTempOutput.
	fileNames map[string]string

	// mu guards fileNames.
	mu sync.RWMutex
}

// NewTrackingTmpOutputDirectoryWrapper creates a new wrapper around in.
// The delegate must implement CreateTempOutput; CreateOutput will fail
// with a descriptive error otherwise.
func NewTrackingTmpOutputDirectoryWrapper(in store.Directory) *TrackingTmpOutputDirectoryWrapper {
	return &TrackingTmpOutputDirectoryWrapper{
		FilterDirectory: store.NewFilterDirectory(in),
		in:              in,
		fileNames:       make(map[string]string),
	}
}

// CreateOutput allocates a temporary file on the delegate using
// CreateTempOutput(name, "", ctx) and records the mapping from name to
// the returned IndexOutput's GetName().
func (d *TrackingTmpOutputDirectoryWrapper) CreateOutput(name string, ctx store.IOContext) (store.IndexOutput, error) {
	toc, ok := d.in.(tempOutputCreator)
	if !ok {
		return nil, fmt.Errorf("TrackingTmpOutputDirectoryWrapper: delegate %T does not support CreateTempOutput", d.in)
	}

	output, err := toc.CreateTempOutput(name, "", ctx)
	if err != nil {
		return nil, err
	}

	d.mu.Lock()
	d.fileNames[name] = output.GetName()
	d.mu.Unlock()

	return output, nil
}

// OpenInput resolves name through the temp-file mapping, falling back to
// the original name when no mapping exists (the file may already be a
// temporary file produced outside this wrapper).
func (d *TrackingTmpOutputDirectoryWrapper) OpenInput(name string, ctx store.IOContext) (store.IndexInput, error) {
	d.mu.RLock()
	tmpName, ok := d.fileNames[name]
	d.mu.RUnlock()
	if !ok {
		tmpName = name
	}
	return d.FilterDirectory.OpenInput(tmpName, ctx)
}

// GetTemporaryFiles returns a snapshot of the logical-name to temp-name
// mapping. Mutating the returned map does not affect the wrapper.
func (d *TrackingTmpOutputDirectoryWrapper) GetTemporaryFiles() map[string]string {
	d.mu.RLock()
	defer d.mu.RUnlock()

	out := make(map[string]string, len(d.fileNames))
	for k, v := range d.fileNames {
		out[k] = v
	}
	return out
}
