// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package hunspell

import "fmt"

// EntrySuggestion is a suggestion to add/edit dictionary entries to generate
// a given list of words, as produced by WordFormGenerator.Compress.
//
// This is the Go port of
// org.apache.lucene.analysis.hunspell.EntrySuggestion from Apache Lucene 10.4.0.
type EntrySuggestion struct {
	toEdit         []DictEntry
	toAdd          []DictEntry
	extraGenerated []string
}

// NewEntrySuggestion constructs an EntrySuggestion.
func NewEntrySuggestion(toEdit, toAdd []DictEntry, extraGenerated []string) *EntrySuggestion {
	return &EntrySuggestion{
		toEdit:         append([]DictEntry(nil), toEdit...),
		toAdd:          append([]DictEntry(nil), toAdd...),
		extraGenerated: append([]string(nil), extraGenerated...),
	}
}

// GetEntriesToEdit returns the entries that need flag changes.
func (e *EntrySuggestion) GetEntriesToEdit() []DictEntry { return e.toEdit }

// GetEntriesToAdd returns new entries to be added.
func (e *EntrySuggestion) GetEntriesToAdd() []DictEntry { return e.toAdd }

// GetExtraGeneratedWords returns additional words generated by the suggestion.
func (e *EntrySuggestion) GetExtraGeneratedWords() []string { return e.extraGenerated }

func (e *EntrySuggestion) String() string {
	return fmt.Sprintf("EntrySuggestion{toEdit=%v, toAdd=%v, extra=%v}",
		e.toEdit, e.toAdd, e.extraGenerated)
}
