// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.
//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0

package search

// Ported from Apache Lucene 10.4.0:
//   lucene/core/src/java/org/apache/lucene/search/DisjunctionMaxScorer.java

import (
	"fmt"

	"github.com/FlavioCFOliveira/Gocene/util"
)

// DisjunctionMaxScorer is the Scorer for DisjunctionMaxQuery.
//
// The union of all documents generated by the subquery scorers is produced in
// document-number order. The score for each document is the maximum of the
// scores computed by the subquery scorers that generate that document, plus
// tieBreakerMultiplier times the sum of the scores for the other subqueries
// that generate the document.
//
// Mirrors org.apache.lucene.search.DisjunctionMaxScorer (Lucene 10.4.0).
//
// Deviations from Java:
//   - Java DisjunctionMaxScorer extends DisjunctionScorer; Go embeds
//     *DisjunctionScorer and overrides Score() / GetMaxScore() directly.
//   - DisjunctionScoreBlockBoundaryPropagator is not in Gocene; the
//     TOP_SCORES block-boundary propagation path is omitted.
//   - advanceShallow / setMinCompetitiveScore are not on Gocene's Scorer
//     interface; those paths are omitted.
type DisjunctionMaxScorer struct {
	*DisjunctionScorer
	subScorers           []Scorer
	tieBreakerMultiplier float32
}

// NewDisjunctionMaxScorer creates a DisjunctionMaxScorer.
//
// Mirrors DisjunctionMaxScorer(float, List<Scorer>, ScoreMode, long).
func NewDisjunctionMaxScorer(
	tieBreakerMultiplier float32,
	subScorers []Scorer,
	scoreMode ScoreMode,
	leadCost int64,
) (*DisjunctionMaxScorer, error) {
	if tieBreakerMultiplier < 0 || tieBreakerMultiplier > 1 {
		return nil, fmt.Errorf("tieBreakerMultiplier must be in [0, 1], got %g", tieBreakerMultiplier)
	}
	base := newDisjunctionScorer(subScorers, scoreMode, leadCost)
	return &DisjunctionMaxScorer{
		DisjunctionScorer:    base,
		subScorers:           subScorers,
		tieBreakerMultiplier: tieBreakerMultiplier,
	}, nil
}

// Score returns the score for the current document.
//
// The score is max(subScores) + tieBreakerMultiplier * sum(remaining subScores).
//
// Mirrors DisjunctionMaxScorer.score(DisiWrapper topList).
func (s *DisjunctionMaxScorer) Score() float32 {
	v, _ := s.scoreWithError()
	return v
}

func (s *DisjunctionMaxScorer) scoreWithError() (float32, error) {
	topList, err := s.DisjunctionScorer.getSubMatches()
	if err != nil {
		return 0, err
	}
	return s.scoreTopList(topList), nil
}

// scoreTopList computes the DisjunctionMax formula over the top-list chain.
func (s *DisjunctionMaxScorer) scoreTopList(topList *DisiWrapper) float32 {
	var scoreMax float32
	var otherScoreSum float64
	for w := topList; w != nil; w = w.next {
		subScore := w.scorable.Score()
		if subScore >= scoreMax {
			otherScoreSum += float64(scoreMax)
			scoreMax = subScore
		} else {
			otherScoreSum += float64(subScore)
		}
	}
	return float32(float64(scoreMax) + otherScoreSum*float64(s.tieBreakerMultiplier))
}

// GetMaxScore returns an upper bound on the score for any document up to upTo.
//
// Mirrors DisjunctionMaxScorer.getMaxScore(int).
func (s *DisjunctionMaxScorer) GetMaxScore(upTo int) float32 {
	var scoreMax float32
	var otherScoreSum float64
	for _, sc := range s.subScorers {
		if sc.DocID() <= upTo {
			subScore := sc.GetMaxScore(upTo)
			if subScore >= scoreMax {
				otherScoreSum += float64(scoreMax)
				scoreMax = subScore
			} else {
				otherScoreSum += float64(subScore)
			}
		}
	}

	if s.tieBreakerMultiplier == 0 {
		return scoreMax
	}
	// Apply relative-error correction to account for floating-point summation
	// order differences, mirroring the Java getMaxScore implementation.
	n := len(s.subScorers) - 1
	if n > 0 {
		otherScoreSum *= (1 + 2*util.MathSumRelativeErrorBound(n))
	}
	return float32(float64(scoreMax) + otherScoreSum*float64(s.tieBreakerMultiplier))
}

// AdvanceShallow returns NO_MORE_DOCS, the default defined by
// org.apache.lucene.search.Scorer#advanceShallow. This scorer does not expose
// per-block impact information, so the whole remaining postings list is treated
// as a single block.
func (s *DisjunctionMaxScorer) AdvanceShallow(target int) (int, error) {
	return NO_MORE_DOCS, nil
}

var _ Scorer = (*DisjunctionMaxScorer)(nil)
