// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package search

import (
	"fmt"
	"math"
)

// LuceneLMDirichletSimilarity mirrors LMDirichletSimilarity (Zhai & Lafferty
// SIGIR 2001) — Bayesian smoothing using Dirichlet priors. Score is the
// boost-weighted `log(1 + freq/(mu*P)) + log(mu/(dl+mu))`, floored at zero
// (Java returns 0 when the raw score is negative).
//
// The legacy [LMDirichletSimilarity] struct is preserved untouched.
type LuceneLMDirichletSimilarity struct {
	*LuceneLMSimilarity
	mu float32
}

// NewLuceneLMDirichletSimilarity returns LMDirichletSimilarity with the
// default collection model and mu=2000.
func NewLuceneLMDirichletSimilarity() *LuceneLMDirichletSimilarity {
	return NewLuceneLMDirichletSimilarityWithMu(2000)
}

// NewLuceneLMDirichletSimilarityWithMu returns LMDirichletSimilarity with
// the default collection model and the supplied mu. Panics if mu is NaN,
// infinite, or negative.
func NewLuceneLMDirichletSimilarityWithMu(mu float32) *LuceneLMDirichletSimilarity {
	return NewLuceneLMDirichletSimilarityFull(NewLuceneDefaultCollectionModel(), true, mu)
}

// NewLuceneLMDirichletSimilarityFull mirrors the (collectionModel,
// discountOverlaps, mu) constructor.
func NewLuceneLMDirichletSimilarityFull(collectionModel LuceneLMCollectionModel, discountOverlaps bool, mu float32) *LuceneLMDirichletSimilarity {
	if math.IsNaN(float64(mu)) || math.IsInf(float64(mu), 0) || mu < 0 {
		panic(fmt.Sprintf("illegal mu value: %v, must be a non-negative finite value", mu))
	}
	d := &LuceneLMDirichletSimilarity{mu: mu}
	score := func(stats *LuceneBasicStats, freq, docLen float64) float64 {
		p := stats.CollectionProbability()
		muF := float64(mu)
		raw := stats.Boost() * (math.Log(1+freq/(muF*p)) + math.Log(muF/(docLen+muF)))
		if raw > 0 {
			return raw
		}
		return 0
	}
	subExplain := func(stats *LuceneBasicStats, freq, docLen float64) []Explanation {
		subs := make([]Explanation, 0, 6)
		if stats.Boost() != 1.0 {
			subs = append(subs, NewExplanation(true, float32(stats.Boost()), "query boost"))
		}
		subs = append(subs, NewExplanation(true, mu, "mu"))
		p := stats.CollectionProbability()
		explP := NewExplanation(true, float32(p),
			"P, probability that the current term is generated by the collection")
		explFreq := NewExplanation(true, float32(freq),
			"freq, number of occurrences of term in the document")
		muF := float64(mu)
		weight := NewExplanation(true, float32(math.Log(1+freq/(muF*p))),
			"term weight, computed as log(1 + freq /(mu * P)) from:")
		weight.AddDetail(explFreq)
		weight.AddDetail(explP)
		subs = append(subs, weight)
		subs = append(subs, NewExplanation(true, float32(math.Log(muF/(docLen+muF))),
			"document norm, computed as log(mu / (dl + mu))"))
		subs = append(subs, NewExplanation(true, float32(docLen), "dl, length of field"))
		return subs
	}
	d.LuceneLMSimilarity = NewLuceneLMSimilarity(collectionModel,
		fmt.Sprintf("Dirichlet(%f)", mu),
		score, subExplain, discountOverlaps)
	return d
}

// GetMu returns the mu parameter.
func (s *LuceneLMDirichletSimilarity) GetMu() float32 { return s.mu }

// Compile-time guarantee.
var _ LuceneSimilarity = (*LuceneLMDirichletSimilarity)(nil)
