// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package search

import (
	"fmt"
	"math"
)

// LuceneLMJelinekMercerSimilarity mirrors LMJelinekMercerSimilarity
// (Zhai & Lafferty SIGIR 2001) — linear interpolation smoothing.
//
//	score = boost * log(1 + ((1-lambda) * freq / dl) / (lambda * P))
//
// where P is the collection probability, lambda is the interpolation
// parameter (0 < lambda <= 1).
//
// The legacy [LMJelinekMercerSimilarity] struct is preserved untouched.
type LuceneLMJelinekMercerSimilarity struct {
	*LuceneLMSimilarity
	lambda float32
}

// NewLuceneLMJelinekMercerSimilarity returns LMJelinekMercerSimilarity with
// the default collection model and the supplied lambda. Panics if lambda
// is NaN or outside (0, 1].
func NewLuceneLMJelinekMercerSimilarity(lambda float32) *LuceneLMJelinekMercerSimilarity {
	return NewLuceneLMJelinekMercerSimilarityFull(NewLuceneDefaultCollectionModel(), true, lambda)
}

// NewLuceneLMJelinekMercerSimilarityFull mirrors the (collectionModel,
// discountOverlaps, lambda) constructor.
func NewLuceneLMJelinekMercerSimilarityFull(collectionModel LuceneLMCollectionModel, discountOverlaps bool, lambda float32) *LuceneLMJelinekMercerSimilarity {
	if math.IsNaN(float64(lambda)) || lambda <= 0 || lambda > 1 {
		panic("lambda must be in the range (0 .. 1]")
	}
	j := &LuceneLMJelinekMercerSimilarity{lambda: lambda}
	score := func(stats *LuceneBasicStats, freq, docLen float64) float64 {
		p := stats.CollectionProbability()
		if p == 0 || docLen == 0 {
			return 0
		}
		l := float64(lambda)
		return stats.Boost() * math.Log(1+((1-l)*freq/docLen)/(l*p))
	}
	subExplain := func(stats *LuceneBasicStats, freq, docLen float64) []Explanation {
		subs := make([]Explanation, 0, 5)
		if stats.Boost() != 1.0 {
			subs = append(subs, NewExplanation(true, float32(stats.Boost()), "boost"))
		}
		subs = append(subs, NewExplanation(true, lambda, "lambda"))
		p := stats.CollectionProbability()
		subs = append(subs, NewExplanation(true, float32(p),
			"P, probability that the current term is generated by the collection"))
		subs = append(subs, NewExplanation(true, float32(freq),
			"freq, number of occurrences of term in the document"))
		subs = append(subs, NewExplanation(true, float32(docLen), "dl, length of field"))
		return subs
	}
	j.LuceneLMSimilarity = NewLuceneLMSimilarity(collectionModel,
		fmt.Sprintf("Jelinek-Mercer(%f)", lambda),
		score, subExplain, discountOverlaps)
	return j
}

// GetLambda returns the lambda parameter.
func (s *LuceneLMJelinekMercerSimilarity) GetLambda() float32 { return s.lambda }

// Compile-time guarantee.
var _ LuceneSimilarity = (*LuceneLMJelinekMercerSimilarity)(nil)
