// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package word2vec

import (
	"archive/zip"
	"bufio"
	"encoding/base64"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/FlavioCFOliveira/Gocene/util"
)

const modelFileNamePrefix = "syn0"

// Dl4jModelReader reads the file generated by the DeepLearning4J library and
// produces a Word2VecModel with normalized vectors.
//
// The Dl4J zip format stores a "syn0*" entry whose first line is
// "<dictionarySize> <vectorDimension>" and subsequent lines are
// "<term> <f1> <f2> ... <fn>". Terms may be base64-encoded when the line
// starts with "b64:".
//
// This is the Go port of
// org.apache.lucene.analysis.synonym.word2vec.Dl4jModelReader from
// Apache Lucene 10.4.0.
//
// Deviation: Java uses ZipInputStream (streaming). Go's archive/zip requires
// an io.ReaderAt+size pair. Dl4jModelReader therefore reads the entire stream
// into memory first. For the expected use case (loading a model file once at
// startup) this is acceptable. The Close method is a no-op since the bytes
// are managed by the garbage collector.
type Dl4jModelReader struct {
	data []byte
}

// NewDl4jModelReader creates a Dl4jModelReader from the given stream.
// The entire stream is buffered into memory.
func NewDl4jModelReader(r io.Reader) (*Dl4jModelReader, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("dl4j: read stream: %w", err)
	}
	return &Dl4jModelReader{data: data}, nil
}

// Read parses the Dl4J zip and returns a Word2VecModel.
func (dr *Dl4jModelReader) Read() (*Word2VecModel, error) {
	zr, err := zip.NewReader(newReaderAt(dr.data), int64(len(dr.data)))
	if err != nil {
		return nil, fmt.Errorf("dl4j: open zip: %w", err)
	}

	for _, f := range zr.File {
		if !strings.HasPrefix(f.Name, modelFileNamePrefix) {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return nil, fmt.Errorf("dl4j: open entry %s: %w", f.Name, err)
		}
		defer rc.Close() //nolint:errcheck

		scanner := bufio.NewScanner(rc)
		scanner.Buffer(make([]byte, 1024*1024), 10*1024*1024)

		// Header line: <dictionarySize> <vectorDimension>
		if !scanner.Scan() {
			return nil, fmt.Errorf("dl4j: missing header in %s", f.Name)
		}
		header := strings.Fields(scanner.Text())
		if len(header) < 2 {
			return nil, fmt.Errorf("dl4j: bad header %q in %s", scanner.Text(), f.Name)
		}
		dictSize, err := strconv.Atoi(header[0])
		if err != nil {
			return nil, fmt.Errorf("dl4j: parse dictionarySize: %w", err)
		}
		vecDim, err := strconv.Atoi(header[1])
		if err != nil {
			return nil, fmt.Errorf("dl4j: parse vectorDimension: %w", err)
		}

		model := NewWord2VecModel(dictSize, vecDim)

		// First data line — used to detect base64 encoding.
		var isB64 bool
		if scanner.Scan() {
			tokens := strings.Fields(scanner.Text())
			if len(tokens) > 0 {
				isB64 = strings.HasPrefix(strings.ToLower(tokens[0]), "b64:")
			}
			entry, err := extractTermAndVector(tokens, vecDim, isB64)
			if err != nil {
				return nil, err
			}
			model.AddTermAndVector(entry)
		}

		for scanner.Scan() {
			tokens := strings.Fields(scanner.Text())
			if len(tokens) == 0 {
				continue
			}
			entry, err := extractTermAndVector(tokens, vecDim, isB64)
			if err != nil {
				return nil, err
			}
			model.AddTermAndVector(entry)
		}
		if err := scanner.Err(); err != nil {
			return nil, fmt.Errorf("dl4j: scan: %w", err)
		}
		return model, nil
	}

	return nil, fmt.Errorf(
		"dl4j: cannot read Dl4j word2vec model — '%s' file is missing in the zip",
		modelFileNamePrefix,
	)
}

// Close is a no-op; the underlying data is garbage-collected.
func (dr *Dl4jModelReader) Close() error { return nil }

// extractTermAndVector parses one data line into a TermAndVector.
func extractTermAndVector(tokens []string, vectorDimension int, isB64 bool) (*util.TermAndVector, error) {
	if len(tokens) == 0 {
		return nil, fmt.Errorf("dl4j: empty token line")
	}
	var term *util.BytesRef
	if isB64 {
		term = decodeB64Term(tokens[0])
	} else {
		term = util.NewBytesRef([]byte(tokens[0]))
	}

	vector := make([]float32, len(tokens)-1)
	if vectorDimension != len(vector) {
		return nil, fmt.Errorf(
			"dl4j: word2vec model file corrupted. Declared vectors of size %d but found vector of size %d for word %s",
			vectorDimension, len(vector), tokens[0],
		)
	}
	for i := 1; i < len(tokens); i++ {
		v, err := strconv.ParseFloat(tokens[i], 32)
		if err != nil {
			return nil, fmt.Errorf("dl4j: parse float token %q: %w", tokens[i], err)
		}
		vector[i-1] = float32(v)
	}
	return util.NewTermAndVector(term, vector), nil
}

// decodeB64Term decodes a base64-encoded term (format "b64:<base64data>").
func decodeB64Term(token string) *util.BytesRef {
	buf, err := base64.StdEncoding.DecodeString(token[4:])
	if err != nil {
		// Fallback: treat as raw bytes.
		return util.NewBytesRef([]byte(token))
	}
	return util.NewBytesRef(buf)
}

// readerAt wraps a byte slice as io.ReaderAt.
type readerAt struct{ data []byte }

func newReaderAt(data []byte) *readerAt { return &readerAt{data: data} }

func (r *readerAt) ReadAt(p []byte, off int64) (int, error) {
	if off >= int64(len(r.data)) {
		return 0, io.EOF
	}
	n := copy(p, r.data[off:])
	if n < len(p) {
		return n, io.EOF
	}
	return n, nil
}

func (r *readerAt) Len() int64 { return int64(len(r.data)) }
