// Package queryparser provides query parsing functionality for Gocene.
// This package implements Lucene's classic query parser for parsing query strings.
package queryparser

import "fmt"

// ParseException is thrown when there is a parsing error in the query string.
// It is generated by the query parser when encountering syntax errors or invalid tokens.
// In Go, this is implemented as a standard error type with additional context.
type ParseException struct {
	Message string
	Cause   error
	Query   string // The query string that caused the error
	Line    int    // Line number where the error occurred
	Column  int    // Column number where the error occurred
}

// Error implements the error interface.
func (e *ParseException) Error() string {
	if e.Query != "" {
		return fmt.Sprintf("Cannot parse '%s': %s", e.Query, e.Message)
	}
	return e.Message
}

// Unwrap returns the underlying cause of the error.
func (e *ParseException) Unwrap() error {
	return e.Cause
}

// NewParseException creates a new ParseException with the given message.
func NewParseException(message string) *ParseException {
	return &ParseException{Message: message}
}

// NewParseExceptionWithCause creates a new ParseException with a cause.
func NewParseExceptionWithCause(message string, cause error) *ParseException {
	return &ParseException{Message: message, Cause: cause}
}

// NewParseExceptionWithQuery creates a new ParseException with query context.
func NewParseExceptionWithQuery(query string, cause error) *ParseException {
	msg := fmt.Sprintf("Cannot parse '%s': %s", query, cause.Error())
	return &ParseException{
		Message: msg,
		Query:   query,
		Cause:   cause,
	}
}

// NewParseExceptionWithLocation creates a new ParseException with location information.
func NewParseExceptionWithLocation(query string, line, column int, cause error) *ParseException {
	msg := fmt.Sprintf("Cannot parse '%s' at line %d, column %d: %s", query, line, column, cause.Error())
	return &ParseException{
		Message:  msg,
		Query:    query,
		Line:     line,
		Column:   column,
		Cause:    cause,
	}
}
