package queryparser

import "fmt"

// TokenMgrError is thrown when there is a lexical error in the token manager.
// This error is generated by the token manager when encountering invalid characters
// or sequences during tokenization of the query string.
// In Java Lucene, this extends Error. In Go, we implement it as a custom error type.
type TokenMgrError struct {
	Message   string
	ErrorCode int
	EOFSeen   bool
	LexState  int
	ErrorLine int
	ErrorCol  int
	ErrorAfter string
	CurChar   rune
}

// Error codes for TokenMgrError, matching Lucene's Java implementation.
const (
	// LexicalError indicates a lexical error occurred.
	LexicalError = 0
	// StaticLexerError indicates an attempt was made to create a second instance of a static token manager.
	StaticLexerError = 1
	// InvalidLexicalState indicates an attempt to change to an invalid lexical state.
	InvalidLexicalState = 2
	// LoopDetected indicates an infinite loop was detected in the token manager.
	LoopDetected = 3
)

// Error implements the error interface.
func (e *TokenMgrError) Error() string {
	return e.Message
}

// NewTokenMgrError creates a new TokenMgrError with the given message and error code.
func NewTokenMgrError(message string, errorCode int) *TokenMgrError {
	return &TokenMgrError{
		Message:   message,
		ErrorCode: errorCode,
	}
}

// NewTokenMgrErrorFull creates a full TokenMgrError with all location information.
// This matches the full constructor from Lucene's Java implementation.
func NewTokenMgrErrorFull(eofSeen bool, lexState, errorLine, errorColumn int, errorAfter string, curChar rune, reason int) *TokenMgrError {
	msg := LexicalErrorMsg(eofSeen, lexState, errorLine, errorColumn, errorAfter, curChar)
	return &TokenMgrError{
		Message:    msg,
		ErrorCode:  reason,
		EOFSeen:    eofSeen,
		LexState:   lexState,
		ErrorLine:  errorLine,
		ErrorCol:   errorColumn,
		ErrorAfter: errorAfter,
		CurChar:    curChar,
	}
}

// LexicalErrorMsg generates a detailed error message for lexical errors.
// This is the Go equivalent of JavaCC's LexicalErr method.
func LexicalErrorMsg(eofSeen bool, lexState, errorLine, errorColumn int, errorAfter string, curChar rune) string {
	encountered := ""
	if eofSeen {
		encountered = "<EOF>"
	} else {
		encountered = fmt.Sprintf("'%s' (%d)", addEscapes(string(curChar)), int(curChar))
	}

	afterMsg := ""
	if errorAfter != "" {
		afterMsg = fmt.Sprintf(" after prefix \"%s\"", addEscapes(errorAfter))
	}

	lexStateMsg := ""
	if lexState != 0 {
		lexStateMsg = fmt.Sprintf(" (in lexical state %d)", lexState)
	}

	return fmt.Sprintf("Lexical error at line %d, column %d. Encountered: %s%s%s",
		errorLine, errorColumn, encountered, afterMsg, lexStateMsg)
}

// addEscapes replaces unprintable characters with their escaped equivalents.
// This matches the JavaCC addEscapes method.
func addEscapes(str string) string {
	retval := make([]rune, 0, len(str)*2)
	for _, ch := range str {
		switch ch {
		case '\b':
			retval = append(retval, '\\', 'b')
		case '\t':
			retval = append(retval, '\\', 't')
		case '\n':
			retval = append(retval, '\\', 'n')
		case '\f':
			retval = append(retval, '\\', 'f')
		case '\r':
			retval = append(retval, '\\', 'r')
		case '"':
			retval = append(retval, '\\', '"')
		case '\'':
			retval = append(retval, '\\', '\'')
		case '\\':
			retval = append(retval, '\\', '\\')
		default:
			if ch < 0x20 || ch > 0x7e {
				retval = append(retval, []rune(fmt.Sprintf("\\u%04x", ch))...)
			} else {
				retval = append(retval, ch)
			}
		}
	}
	return string(retval)
}
