// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.
//
// Port of org.apache.lucene.util.automaton.CaseFolding from Apache Lucene
// 10.4.0. The upstream tables were generated with ICU4J v77.1.0.0 against
// Unicode 16.0.0. Go's standard library tracks the Unicode version embedded
// in the toolchain (Go 1.24+ ships Unicode 15.1), so simple
// upper/lower mappings come from unicode.ToUpper / unicode.ToLower and the
// special-casing branches below are taken verbatim from Lucene to preserve
// byte-for-byte parity on the special-cased code points. Code points that
// changed status between Unicode 15.1 and 16.0 may therefore expand to a
// slightly different simple-folding set than the JVM port; the explicit
// switch arms always agree.

package automaton

import "unicode"

// CaseFoldingExpand invokes fn with c itself and every Unicode case-folding
// variant defined by Lucene's CaseFolding table. fn is called at least once
// (for c) and may be called multiple times for the same variant; callers that
// require a unique, sorted set must deduplicate. The function is the Go
// counterpart of the Java static CaseFolding.expand(int, IntConsumer).
func CaseFoldingExpand(c rune, fn func(rune)) {
	// add the codepoint itself
	fn(c)

	// add uppercase from tables (simple, single-codepoint mapping)
	if upper := unicode.ToUpper(c); upper != c {
		fn(upper)
	}

	// add lowercase from tables (simple, single-codepoint mapping)
	if lower := unicode.ToLower(c); lower != c {
		fn(lower)
	}

	// add special casing variants — verbatim port of the upstream switch
	switch c {
	case 0x004B: // LATIN CAPITAL LETTER K
		fn(0x212A) // KELVIN SIGN
	case 0x0053: // LATIN CAPITAL LETTER S
		fn(0x017F) // LATIN SMALL LETTER LONG S
	case 0x006B: // LATIN SMALL LETTER K
		fn(0x212A) // KELVIN SIGN
	case 0x0073: // LATIN SMALL LETTER S
		fn(0x017F) // LATIN SMALL LETTER LONG S
	case 0x00B5: // MICRO SIGN
		fn(0x03BC) // GREEK SMALL LETTER MU
	case 0x00C5: // LATIN CAPITAL LETTER A WITH RING ABOVE
		fn(0x212B) // ANGSTROM SIGN
	case 0x00DF: // LATIN SMALL LETTER SHARP S
		fn(0x1E9E) // LATIN CAPITAL LETTER SHARP S
	case 0x00E5: // LATIN SMALL LETTER A WITH RING ABOVE
		fn(0x212B) // ANGSTROM SIGN
	case 0x017F: // LATIN SMALL LETTER LONG S
		fn(0x0073) // LATIN SMALL LETTER S
	case 0x01C4: // LATIN CAPITAL LETTER DZ WITH CARON
		fn(0x01C5) // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
	case 0x01C6: // LATIN SMALL LETTER DZ WITH CARON
		fn(0x01C5) // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
	case 0x01C7: // LATIN CAPITAL LETTER LJ
		fn(0x01C8) // LATIN CAPITAL LETTER L WITH SMALL LETTER J
	case 0x01C9: // LATIN SMALL LETTER LJ
		fn(0x01C8) // LATIN CAPITAL LETTER L WITH SMALL LETTER J
	case 0x01CA: // LATIN CAPITAL LETTER NJ
		fn(0x01CB) // LATIN CAPITAL LETTER N WITH SMALL LETTER J
	case 0x01CC: // LATIN SMALL LETTER NJ
		fn(0x01CB) // LATIN CAPITAL LETTER N WITH SMALL LETTER J
	case 0x01F1: // LATIN CAPITAL LETTER DZ
		fn(0x01F2) // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
	case 0x01F3: // LATIN SMALL LETTER DZ
		fn(0x01F2) // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
	case 0x0345: // COMBINING GREEK YPOGEGRAMMENI
		fn(0x03B9) // GREEK SMALL LETTER IOTA
		fn(0x1FBE) // GREEK PROSGEGRAMMENI
	case 0x0390: // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
		fn(0x1FD3) // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
	case 0x0392: // GREEK CAPITAL LETTER BETA
		fn(0x03D0) // GREEK BETA SYMBOL
	case 0x0395: // GREEK CAPITAL LETTER EPSILON
		fn(0x03F5) // GREEK LUNATE EPSILON SYMBOL
	case 0x0398: // GREEK CAPITAL LETTER THETA
		fn(0x03D1) // GREEK THETA SYMBOL
		fn(0x03F4) // GREEK CAPITAL THETA SYMBOL
	case 0x0399: // GREEK CAPITAL LETTER IOTA
		fn(0x0345) // COMBINING GREEK YPOGEGRAMMENI
		fn(0x1FBE) // GREEK PROSGEGRAMMENI
	case 0x039A: // GREEK CAPITAL LETTER KAPPA
		fn(0x03F0) // GREEK KAPPA SYMBOL
	case 0x039C: // GREEK CAPITAL LETTER MU
		fn(0x00B5) // MICRO SIGN
	case 0x03A0: // GREEK CAPITAL LETTER PI
		fn(0x03D6) // GREEK PI SYMBOL
	case 0x03A1: // GREEK CAPITAL LETTER RHO
		fn(0x03F1) // GREEK RHO SYMBOL
	case 0x03A3: // GREEK CAPITAL LETTER SIGMA
		fn(0x03C2) // GREEK SMALL LETTER FINAL SIGMA
	case 0x03A6: // GREEK CAPITAL LETTER PHI
		fn(0x03D5) // GREEK PHI SYMBOL
	case 0x03A9: // GREEK CAPITAL LETTER OMEGA
		fn(0x2126) // OHM SIGN
	case 0x03B0: // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
		fn(0x1FE3) // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
	case 0x03B2: // GREEK SMALL LETTER BETA
		fn(0x03D0) // GREEK BETA SYMBOL
	case 0x03B5: // GREEK SMALL LETTER EPSILON
		fn(0x03F5) // GREEK LUNATE EPSILON SYMBOL
	case 0x03B8: // GREEK SMALL LETTER THETA
		fn(0x03D1) // GREEK THETA SYMBOL
		fn(0x03F4) // GREEK CAPITAL THETA SYMBOL
	case 0x03B9: // GREEK SMALL LETTER IOTA
		fn(0x0345) // COMBINING GREEK YPOGEGRAMMENI
		fn(0x1FBE) // GREEK PROSGEGRAMMENI
	case 0x03BA: // GREEK SMALL LETTER KAPPA
		fn(0x03F0) // GREEK KAPPA SYMBOL
	case 0x03BC: // GREEK SMALL LETTER MU
		fn(0x00B5) // MICRO SIGN
	case 0x03C0: // GREEK SMALL LETTER PI
		fn(0x03D6) // GREEK PI SYMBOL
	case 0x03C1: // GREEK SMALL LETTER RHO
		fn(0x03F1) // GREEK RHO SYMBOL
	case 0x03C2: // GREEK SMALL LETTER FINAL SIGMA
		fn(0x03C3) // GREEK SMALL LETTER SIGMA
	case 0x03C3: // GREEK SMALL LETTER SIGMA
		fn(0x03C2) // GREEK SMALL LETTER FINAL SIGMA
	case 0x03C6: // GREEK SMALL LETTER PHI
		fn(0x03D5) // GREEK PHI SYMBOL
	case 0x03C9: // GREEK SMALL LETTER OMEGA
		fn(0x2126) // OHM SIGN
	case 0x03D0: // GREEK BETA SYMBOL
		fn(0x03B2) // GREEK SMALL LETTER BETA
	case 0x03D1: // GREEK THETA SYMBOL
		fn(0x03B8) // GREEK SMALL LETTER THETA
		fn(0x03F4) // GREEK CAPITAL THETA SYMBOL
	case 0x03D5: // GREEK PHI SYMBOL
		fn(0x03C6) // GREEK SMALL LETTER PHI
	case 0x03D6: // GREEK PI SYMBOL
		fn(0x03C0) // GREEK SMALL LETTER PI
	case 0x03F0: // GREEK KAPPA SYMBOL
		fn(0x03BA) // GREEK SMALL LETTER KAPPA
	case 0x03F1: // GREEK RHO SYMBOL
		fn(0x03C1) // GREEK SMALL LETTER RHO
	case 0x03F4: // GREEK CAPITAL THETA SYMBOL
		fn(0x0398) // GREEK CAPITAL LETTER THETA
		fn(0x03D1) // GREEK THETA SYMBOL
	case 0x03F5: // GREEK LUNATE EPSILON SYMBOL
		fn(0x03B5) // GREEK SMALL LETTER EPSILON
	case 0x0412: // CYRILLIC CAPITAL LETTER VE
		fn(0x1C80) // CYRILLIC SMALL LETTER ROUNDED VE
	case 0x0414: // CYRILLIC CAPITAL LETTER DE
		fn(0x1C81) // CYRILLIC SMALL LETTER LONG-LEGGED DE
	case 0x041E: // CYRILLIC CAPITAL LETTER O
		fn(0x1C82) // CYRILLIC SMALL LETTER NARROW O
	case 0x0421: // CYRILLIC CAPITAL LETTER ES
		fn(0x1C83) // CYRILLIC SMALL LETTER WIDE ES
	case 0x0422: // CYRILLIC CAPITAL LETTER TE
		fn(0x1C84) // CYRILLIC SMALL LETTER TALL TE
		fn(0x1C85) // CYRILLIC SMALL LETTER THREE-LEGGED TE
	case 0x042A: // CYRILLIC CAPITAL LETTER HARD SIGN
		fn(0x1C86) // CYRILLIC SMALL LETTER TALL HARD SIGN
	case 0x0432: // CYRILLIC SMALL LETTER VE
		fn(0x1C80) // CYRILLIC SMALL LETTER ROUNDED VE
	case 0x0434: // CYRILLIC SMALL LETTER DE
		fn(0x1C81) // CYRILLIC SMALL LETTER LONG-LEGGED DE
	case 0x043E: // CYRILLIC SMALL LETTER O
		fn(0x1C82) // CYRILLIC SMALL LETTER NARROW O
	case 0x0441: // CYRILLIC SMALL LETTER ES
		fn(0x1C83) // CYRILLIC SMALL LETTER WIDE ES
	case 0x0442: // CYRILLIC SMALL LETTER TE
		fn(0x1C84) // CYRILLIC SMALL LETTER TALL TE
		fn(0x1C85) // CYRILLIC SMALL LETTER THREE-LEGGED TE
	case 0x044A: // CYRILLIC SMALL LETTER HARD SIGN
		fn(0x1C86) // CYRILLIC SMALL LETTER TALL HARD SIGN
	case 0x0462: // CYRILLIC CAPITAL LETTER YAT
		fn(0x1C87) // CYRILLIC SMALL LETTER TALL YAT
	case 0x0463: // CYRILLIC SMALL LETTER YAT
		fn(0x1C87) // CYRILLIC SMALL LETTER TALL YAT
	case 0x1C80: // CYRILLIC SMALL LETTER ROUNDED VE
		fn(0x0432) // CYRILLIC SMALL LETTER VE
	case 0x1C81: // CYRILLIC SMALL LETTER LONG-LEGGED DE
		fn(0x0434) // CYRILLIC SMALL LETTER DE
	case 0x1C82: // CYRILLIC SMALL LETTER NARROW O
		fn(0x043E) // CYRILLIC SMALL LETTER O
	case 0x1C83: // CYRILLIC SMALL LETTER WIDE ES
		fn(0x0441) // CYRILLIC SMALL LETTER ES
	case 0x1C84: // CYRILLIC SMALL LETTER TALL TE
		fn(0x0442) // CYRILLIC SMALL LETTER TE
		fn(0x1C85) // CYRILLIC SMALL LETTER THREE-LEGGED TE
	case 0x1C85: // CYRILLIC SMALL LETTER THREE-LEGGED TE
		fn(0x0442) // CYRILLIC SMALL LETTER TE
		fn(0x1C84) // CYRILLIC SMALL LETTER TALL TE
	case 0x1C86: // CYRILLIC SMALL LETTER TALL HARD SIGN
		fn(0x044A) // CYRILLIC SMALL LETTER HARD SIGN
	case 0x1C87: // CYRILLIC SMALL LETTER TALL YAT
		fn(0x0463) // CYRILLIC SMALL LETTER YAT
	case 0x1C88: // CYRILLIC SMALL LETTER UNBLENDED UK
		fn(0xA64B) // CYRILLIC SMALL LETTER MONOGRAPH UK
	case 0x1E60: // LATIN CAPITAL LETTER S WITH DOT ABOVE
		fn(0x1E9B) // LATIN SMALL LETTER LONG S WITH DOT ABOVE
	case 0x1E61: // LATIN SMALL LETTER S WITH DOT ABOVE
		fn(0x1E9B) // LATIN SMALL LETTER LONG S WITH DOT ABOVE
	case 0x1E9B: // LATIN SMALL LETTER LONG S WITH DOT ABOVE
		fn(0x1E61) // LATIN SMALL LETTER S WITH DOT ABOVE
	case 0x1FBE: // GREEK PROSGEGRAMMENI
		fn(0x0345) // COMBINING GREEK YPOGEGRAMMENI
		fn(0x03B9) // GREEK SMALL LETTER IOTA
	case 0x1FD3: // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
		fn(0x0390) // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
	case 0x1FE3: // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
		fn(0x03B0) // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
	case 0x2126: // OHM SIGN
		fn(0x03A9) // GREEK CAPITAL LETTER OMEGA
	case 0x212A: // KELVIN SIGN
		fn(0x004B) // LATIN CAPITAL LETTER K
	case 0x212B: // ANGSTROM SIGN
		fn(0x00C5) // LATIN CAPITAL LETTER A WITH RING ABOVE
	case 0xA64A: // CYRILLIC CAPITAL LETTER MONOGRAPH UK
		fn(0x1C88) // CYRILLIC SMALL LETTER UNBLENDED UK
	case 0xA64B: // CYRILLIC SMALL LETTER MONOGRAPH UK
		fn(0x1C88) // CYRILLIC SMALL LETTER UNBLENDED UK
	case 0xFB05: // LATIN SMALL LIGATURE LONG S T
		fn(0xFB06) // LATIN SMALL LIGATURE ST
	case 0xFB06: // LATIN SMALL LIGATURE ST
		fn(0xFB05) // LATIN SMALL LIGATURE LONG S T
	}
}
