// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from org.tartarus.snowball.ext.ArmenianStemmer.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

var armenianA0 = []*snowball.Among{
	snowball.NewAmong("րորդ", -1, 1),
	snowball.NewAmong("երորդ", 0, 1),
	snowball.NewAmong("ալի", -1, 1),
	snowball.NewAmong("ակի", -1, 1),
	snowball.NewAmong("որակ", -1, 1),
	snowball.NewAmong("եղ", -1, 1),
	snowball.NewAmong("ական", -1, 1),
	snowball.NewAmong("արան", -1, 1),
	snowball.NewAmong("են", -1, 1),
	snowball.NewAmong("եկեն", 8, 1),
	snowball.NewAmong("երեն", 8, 1),
	snowball.NewAmong("որէն", -1, 1),
	snowball.NewAmong("ին", -1, 1),
	snowball.NewAmong("գին", 12, 1),
	snowball.NewAmong("ովին", 12, 1),
	snowball.NewAmong("լայն", -1, 1),
	snowball.NewAmong("վուն", -1, 1),
	snowball.NewAmong("պես", -1, 1),
	snowball.NewAmong("իվ", -1, 1),
	snowball.NewAmong("ատ", -1, 1),
	snowball.NewAmong("ավետ", -1, 1),
	snowball.NewAmong("կոտ", -1, 1),
	snowball.NewAmong("բար", -1, 1),
}

var armenianA1 = []*snowball.Among{
	snowball.NewAmong("ա", -1, 1),
	snowball.NewAmong("ացա", 0, 1),
	snowball.NewAmong("եցա", 0, 1),
	snowball.NewAmong("վե", -1, 1),
	snowball.NewAmong("ացրի", -1, 1),
	snowball.NewAmong("ացի", -1, 1),
	snowball.NewAmong("եցի", -1, 1),
	snowball.NewAmong("վեցի", 6, 1),
	snowball.NewAmong("ալ", -1, 1),
	snowball.NewAmong("ըալ", 8, 1),
	snowball.NewAmong("անալ", 8, 1),
	snowball.NewAmong("ենալ", 8, 1),
	snowball.NewAmong("ացնալ", 8, 1),
	snowball.NewAmong("ել", -1, 1),
	snowball.NewAmong("ըել", 13, 1),
	snowball.NewAmong("նել", 13, 1),
	snowball.NewAmong("ցնել", 15, 1),
	snowball.NewAmong("եցնել", 16, 1),
	snowball.NewAmong("չել", 13, 1),
	snowball.NewAmong("վել", 13, 1),
	snowball.NewAmong("ացվել", 19, 1),
	snowball.NewAmong("եցվել", 19, 1),
	snowball.NewAmong("տել", 13, 1),
	snowball.NewAmong("ատել", 22, 1),
	snowball.NewAmong("ոտել", 22, 1),
	snowball.NewAmong("կոտել", 24, 1),
	snowball.NewAmong("ված", -1, 1),
	snowball.NewAmong("ում", -1, 1),
	snowball.NewAmong("վում", 27, 1),
	snowball.NewAmong("ան", -1, 1),
	snowball.NewAmong("ցան", 29, 1),
	snowball.NewAmong("ացան", 30, 1),
	snowball.NewAmong("ացրին", -1, 1),
	snowball.NewAmong("ացին", -1, 1),
	snowball.NewAmong("եցին", -1, 1),
	snowball.NewAmong("վեցին", 34, 1),
	snowball.NewAmong("ալիս", -1, 1),
	snowball.NewAmong("ելիս", -1, 1),
	snowball.NewAmong("ավ", -1, 1),
	snowball.NewAmong("ացավ", 38, 1),
	snowball.NewAmong("եցավ", 38, 1),
	snowball.NewAmong("ալով", -1, 1),
	snowball.NewAmong("ելով", -1, 1),
	snowball.NewAmong("ար", -1, 1),
	snowball.NewAmong("ացար", 43, 1),
	snowball.NewAmong("եցար", 43, 1),
	snowball.NewAmong("ացրիր", -1, 1),
	snowball.NewAmong("ացիր", -1, 1),
	snowball.NewAmong("եցիր", -1, 1),
	snowball.NewAmong("վեցիր", 48, 1),
	snowball.NewAmong("աց", -1, 1),
	snowball.NewAmong("եց", -1, 1),
	snowball.NewAmong("ացրեց", 51, 1),
	snowball.NewAmong("ալուց", -1, 1),
	snowball.NewAmong("ելուց", -1, 1),
	snowball.NewAmong("ալու", -1, 1),
	snowball.NewAmong("ելու", -1, 1),
	snowball.NewAmong("աք", -1, 1),
	snowball.NewAmong("ցաք", 57, 1),
	snowball.NewAmong("ացաք", 58, 1),
	snowball.NewAmong("ացրիք", -1, 1),
	snowball.NewAmong("ացիք", -1, 1),
	snowball.NewAmong("եցիք", -1, 1),
	snowball.NewAmong("վեցիք", 62, 1),
	snowball.NewAmong("անք", -1, 1),
	snowball.NewAmong("ցանք", 64, 1),
	snowball.NewAmong("ացանք", 65, 1),
	snowball.NewAmong("ացրինք", -1, 1),
	snowball.NewAmong("ացինք", -1, 1),
	snowball.NewAmong("եցինք", -1, 1),
	snowball.NewAmong("վեցինք", 69, 1),
}

var armenianA2 = []*snowball.Among{
	snowball.NewAmong("որդ", -1, 1),
	snowball.NewAmong("ույթ", -1, 1),
	snowball.NewAmong("ուհի", -1, 1),
	snowball.NewAmong("ցի", -1, 1),
	snowball.NewAmong("իլ", -1, 1),
	snowball.NewAmong("ակ", -1, 1),
	snowball.NewAmong("յակ", 5, 1),
	snowball.NewAmong("անակ", 5, 1),
	snowball.NewAmong("իկ", -1, 1),
	snowball.NewAmong("ուկ", -1, 1),
	snowball.NewAmong("ան", -1, 1),
	snowball.NewAmong("պան", 10, 1),
	snowball.NewAmong("ստան", 10, 1),
	snowball.NewAmong("արան", 10, 1),
	snowball.NewAmong("եղէն", -1, 1),
	snowball.NewAmong("յուն", -1, 1),
	snowball.NewAmong("ություն", 15, 1),
	snowball.NewAmong("ածո", -1, 1),
	snowball.NewAmong("իչ", -1, 1),
	snowball.NewAmong("ուս", -1, 1),
	snowball.NewAmong("ուստ", -1, 1),
	snowball.NewAmong("գար", -1, 1),
	snowball.NewAmong("վոր", -1, 1),
	snowball.NewAmong("ավոր", 22, 1),
	snowball.NewAmong("ոց", -1, 1),
	snowball.NewAmong("անօց", -1, 1),
	snowball.NewAmong("ու", -1, 1),
	snowball.NewAmong("ք", -1, 1),
	snowball.NewAmong("չեք", 27, 1),
	snowball.NewAmong("իք", 27, 1),
	snowball.NewAmong("ալիք", 29, 1),
	snowball.NewAmong("անիք", 29, 1),
	snowball.NewAmong("վածք", 27, 1),
	snowball.NewAmong("ույք", 27, 1),
	snowball.NewAmong("ենք", 27, 1),
	snowball.NewAmong("ոնք", 27, 1),
	snowball.NewAmong("ունք", 27, 1),
	snowball.NewAmong("մունք", 36, 1),
	snowball.NewAmong("իչք", 27, 1),
	snowball.NewAmong("արք", 27, 1),
}

var armenianA3 = []*snowball.Among{
	snowball.NewAmong("սա", -1, 1),
	snowball.NewAmong("վա", -1, 1),
	snowball.NewAmong("ամբ", -1, 1),
	snowball.NewAmong("դ", -1, 1),
	snowball.NewAmong("անդ", 3, 1),
	snowball.NewAmong("ությանդ", 4, 1),
	snowball.NewAmong("վանդ", 4, 1),
	snowball.NewAmong("ոջդ", 3, 1),
	snowball.NewAmong("երդ", 3, 1),
	snowball.NewAmong("ներդ", 8, 1),
	snowball.NewAmong("ուդ", 3, 1),
	snowball.NewAmong("ը", -1, 1),
	snowball.NewAmong("անը", 11, 1),
	snowball.NewAmong("ությանը", 12, 1),
	snowball.NewAmong("վանը", 12, 1),
	snowball.NewAmong("ոջը", 11, 1),
	snowball.NewAmong("երը", 11, 1),
	snowball.NewAmong("ները", 16, 1),
	snowball.NewAmong("ի", -1, 1),
	snowball.NewAmong("վի", 18, 1),
	snowball.NewAmong("երի", 18, 1),
	snowball.NewAmong("ների", 20, 1),
	snowball.NewAmong("անում", -1, 1),
	snowball.NewAmong("երում", -1, 1),
	snowball.NewAmong("ներում", 23, 1),
	snowball.NewAmong("ն", -1, 1),
	snowball.NewAmong("ան", 25, 1),
	snowball.NewAmong("ության", 26, 1),
	snowball.NewAmong("վան", 26, 1),
	snowball.NewAmong("ին", 25, 1),
	snowball.NewAmong("երին", 29, 1),
	snowball.NewAmong("ներին", 30, 1),
	snowball.NewAmong("ությանն", 25, 1),
	snowball.NewAmong("երն", 25, 1),
	snowball.NewAmong("ներն", 33, 1),
	snowball.NewAmong("ուն", 25, 1),
	snowball.NewAmong("ոջ", -1, 1),
	snowball.NewAmong("ությանս", -1, 1),
	snowball.NewAmong("վանս", -1, 1),
	snowball.NewAmong("ոջս", -1, 1),
	snowball.NewAmong("ով", -1, 1),
	snowball.NewAmong("անով", 40, 1),
	snowball.NewAmong("վով", 40, 1),
	snowball.NewAmong("երով", 40, 1),
	snowball.NewAmong("ներով", 43, 1),
	snowball.NewAmong("եր", -1, 1),
	snowball.NewAmong("ներ", 45, 1),
	snowball.NewAmong("ց", -1, 1),
	snowball.NewAmong("ից", 47, 1),
	snowball.NewAmong("վանից", 48, 1),
	snowball.NewAmong("ոջից", 48, 1),
	snowball.NewAmong("վից", 48, 1),
	snowball.NewAmong("երից", 48, 1),
	snowball.NewAmong("ներից", 52, 1),
	snowball.NewAmong("ցից", 48, 1),
	snowball.NewAmong("ոց", 47, 1),
	snowball.NewAmong("ուց", 47, 1),
}

// armenianGV contains the vowel grouping for Armenian (Unicode range 1377–1413).
var armenianGV = []byte{209, 4, 128, 0, 18}

// ArmenianStemmer implements the Snowball stemming algorithm for Armenian.
// It mirrors org.tartarus.snowball.ext.ArmenianStemmer.
type ArmenianStemmer struct {
	snowball.SnowballProgram
	iP2 int
	iPV int
}

// NewArmenianStemmer constructs an ArmenianStemmer.
func NewArmenianStemmer() *ArmenianStemmer {
	return &ArmenianStemmer{}
}

func (s *ArmenianStemmer) rMarkRegions() bool {
	s.iPV = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
lab0:
	for {
	golab1:
		for {
			lab2:
			for {
				if !s.InGrouping(armenianGV, 1377, 1413) {
					break lab2
				}
				break golab1
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
		s.iPV = s.Cursor
	golab3:
		for {
			lab4:
			for {
				if !s.OutGrouping(armenianGV, 1377, 1413) {
					break lab4
				}
				break golab3
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
	golab5:
		for {
			lab6:
			for {
				if !s.InGrouping(armenianGV, 1377, 1413) {
					break lab6
				}
				break golab5
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
	golab7:
		for {
			lab8:
			for {
				if !s.OutGrouping(armenianGV, 1377, 1413) {
					break lab8
				}
				break golab7
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab0
	}
	s.Cursor = v1
	return true
}

func (s *ArmenianStemmer) rR2() bool {
	return s.iP2 <= s.Cursor
}

func (s *ArmenianStemmer) rAdjective() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(armenianA0) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

func (s *ArmenianStemmer) rVerb() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(armenianA1) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

func (s *ArmenianStemmer) rNoun() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(armenianA2) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

func (s *ArmenianStemmer) rEnding() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(armenianA3) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR2() {
		return false
	}
	s.SliceDel()
	return true
}

// Stem applies the Armenian stemming algorithm to the current word.
func (s *ArmenianStemmer) Stem() bool {
	s.rMarkRegions()
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	if s.Cursor < s.iPV {
		return false
	}
	v3 := s.LimitBackward
	s.LimitBackward = s.iPV
	v4 := s.Limit - s.Cursor
	s.rEnding()
	s.Cursor = s.Limit - v4
	v5 := s.Limit - s.Cursor
	s.rVerb()
	s.Cursor = s.Limit - v5
	v6 := s.Limit - s.Cursor
	s.rAdjective()
	s.Cursor = s.Limit - v6
	v7 := s.Limit - s.Cursor
	s.rNoun()
	s.Cursor = s.Limit - v7
	s.LimitBackward = v3
	s.Cursor = s.LimitBackward
	return true
}
