// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// BasqueStemmer implements the Basque Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.BasqueStemmer
// from Apache Lucene 10.4.0.
type BasqueStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewBasqueStemmer constructs a BasqueStemmer.
func NewBasqueStemmer() *BasqueStemmer {
	return &BasqueStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*BasqueStemmer)(nil)

var basqueA0 = []*snowball.Among{
	snowball.NewAmong("idea", -1, 1),
	snowball.NewAmong("bidea", 0, 1),
	snowball.NewAmong("kidea", 0, 1),
	snowball.NewAmong("pidea", 0, 1),
	snowball.NewAmong("kundea", -1, 1),
	snowball.NewAmong("galea", -1, 1),
	snowball.NewAmong("tailea", -1, 1),
	snowball.NewAmong("tzailea", -1, 1),
	snowball.NewAmong("gunea", -1, 1),
	snowball.NewAmong("kunea", -1, 1),
	snowball.NewAmong("tzaga", -1, 1),
	snowball.NewAmong("gaia", -1, 1),
	snowball.NewAmong("aldia", -1, 1),
	snowball.NewAmong("taldia", 12, 1),
	snowball.NewAmong("karia", -1, 1),
	snowball.NewAmong("garria", -1, 2),
	snowball.NewAmong("karria", -1, 1),
	snowball.NewAmong("ka", -1, 1),
	snowball.NewAmong("tzaka", 17, 1),
	snowball.NewAmong("la", -1, 1),
	snowball.NewAmong("mena", -1, 1),
	snowball.NewAmong("pena", -1, 1),
	snowball.NewAmong("kina", -1, 1),
	snowball.NewAmong("ezina", -1, 1),
	snowball.NewAmong("tezina", 23, 1),
	snowball.NewAmong("kuna", -1, 1),
	snowball.NewAmong("tuna", -1, 1),
	snowball.NewAmong("kizuna", -1, 1),
	snowball.NewAmong("era", -1, 1),
	snowball.NewAmong("bera", 28, 1),
	snowball.NewAmong("arabera", 29, 4),
	snowball.NewAmong("kera", 28, 1),
	snowball.NewAmong("pera", 28, 1),
	snowball.NewAmong("orra", -1, 1),
	snowball.NewAmong("korra", 33, 1),
	snowball.NewAmong("dura", -1, 1),
	snowball.NewAmong("gura", -1, 1),
	snowball.NewAmong("kura", -1, 1),
	snowball.NewAmong("tura", -1, 1),
	snowball.NewAmong("eta", -1, 1),
	snowball.NewAmong("keta", 39, 1),
	snowball.NewAmong("gailua", -1, 1),
	snowball.NewAmong("eza", -1, 1),
	snowball.NewAmong("erreza", 42, 1),
	snowball.NewAmong("tza", -1, 2),
	snowball.NewAmong("gaitza", 44, 1),
	snowball.NewAmong("kaitza", 44, 1),
	snowball.NewAmong("kuntza", 44, 1),
	snowball.NewAmong("ide", -1, 1),
	snowball.NewAmong("bide", 48, 1),
	snowball.NewAmong("kide", 48, 1),
	snowball.NewAmong("pide", 48, 1),
	snowball.NewAmong("kunde", -1, 1),
	snowball.NewAmong("tzake", -1, 1),
	snowball.NewAmong("tzeke", -1, 1),
	snowball.NewAmong("le", -1, 1),
	snowball.NewAmong("gale", 55, 1),
	snowball.NewAmong("taile", 55, 1),
	snowball.NewAmong("tzaile", 55, 1),
	snowball.NewAmong("gune", -1, 1),
	snowball.NewAmong("kune", -1, 1),
	snowball.NewAmong("tze", -1, 1),
	snowball.NewAmong("atze", 61, 1),
	snowball.NewAmong("gai", -1, 1),
	snowball.NewAmong("aldi", -1, 1),
	snowball.NewAmong("taldi", 64, 1),
	snowball.NewAmong("ki", -1, 1),
	snowball.NewAmong("ari", -1, 1),
	snowball.NewAmong("kari", 67, 1),
	snowball.NewAmong("lari", 67, 1),
	snowball.NewAmong("tari", 67, 1),
	snowball.NewAmong("etari", 70, 1),
	snowball.NewAmong("garri", -1, 2),
	snowball.NewAmong("karri", -1, 1),
	snowball.NewAmong("arazi", -1, 1),
	snowball.NewAmong("tarazi", 74, 1),
	snowball.NewAmong("an", -1, 1),
	snowball.NewAmong("ean", 76, 1),
	snowball.NewAmong("rean", 77, 1),
	snowball.NewAmong("kan", 76, 1),
	snowball.NewAmong("etan", 76, 1),
	snowball.NewAmong("atseden", -1, 3),
	snowball.NewAmong("men", -1, 1),
	snowball.NewAmong("pen", -1, 1),
	snowball.NewAmong("kin", -1, 1),
	snowball.NewAmong("rekin", 84, 1),
	snowball.NewAmong("ezin", -1, 1),
	snowball.NewAmong("tezin", 86, 1),
	snowball.NewAmong("tun", -1, 1),
	snowball.NewAmong("kizun", -1, 1),
	snowball.NewAmong("go", -1, 1),
	snowball.NewAmong("ago", 90, 1),
	snowball.NewAmong("tio", -1, 1),
	snowball.NewAmong("dako", -1, 1),
	snowball.NewAmong("or", -1, 1),
	snowball.NewAmong("kor", 94, 1),
	snowball.NewAmong("tzat", -1, 1),
	snowball.NewAmong("du", -1, 1),
	snowball.NewAmong("gailu", -1, 1),
	snowball.NewAmong("tu", -1, 1),
	snowball.NewAmong("atu", 99, 1),
	snowball.NewAmong("aldatu", 100, 1),
	snowball.NewAmong("tatu", 100, 1),
	snowball.NewAmong("baditu", 99, 5),
	snowball.NewAmong("ez", -1, 1),
	snowball.NewAmong("errez", 104, 1),
	snowball.NewAmong("tzez", 104, 1),
	snowball.NewAmong("gaitz", -1, 1),
	snowball.NewAmong("kaitz", -1, 1),
}

var basqueA1 = []*snowball.Among{
	snowball.NewAmong("ada", -1, 1),
	snowball.NewAmong("kada", 0, 1),
	snowball.NewAmong("anda", -1, 1),
	snowball.NewAmong("denda", -1, 1),
	snowball.NewAmong("gabea", -1, 1),
	snowball.NewAmong("kabea", -1, 1),
	snowball.NewAmong("aldea", -1, 1),
	snowball.NewAmong("kaldea", 6, 1),
	snowball.NewAmong("taldea", 6, 1),
	snowball.NewAmong("ordea", -1, 1),
	snowball.NewAmong("zalea", -1, 1),
	snowball.NewAmong("tzalea", 10, 1),
	snowball.NewAmong("gilea", -1, 1),
	snowball.NewAmong("emea", -1, 1),
	snowball.NewAmong("kumea", -1, 1),
	snowball.NewAmong("nea", -1, 1),
	snowball.NewAmong("enea", 15, 1),
	snowball.NewAmong("zionea", 15, 1),
	snowball.NewAmong("unea", 15, 1),
	snowball.NewAmong("gunea", 18, 1),
	snowball.NewAmong("pea", -1, 1),
	snowball.NewAmong("aurrea", -1, 1),
	snowball.NewAmong("tea", -1, 1),
	snowball.NewAmong("kotea", 22, 1),
	snowball.NewAmong("artea", 22, 1),
	snowball.NewAmong("ostea", 22, 1),
	snowball.NewAmong("etxea", -1, 1),
	snowball.NewAmong("ga", -1, 1),
	snowball.NewAmong("anga", 27, 1),
	snowball.NewAmong("gaia", -1, 1),
	snowball.NewAmong("aldia", -1, 1),
	snowball.NewAmong("taldia", 30, 1),
	snowball.NewAmong("handia", -1, 1),
	snowball.NewAmong("mendia", -1, 1),
	snowball.NewAmong("geia", -1, 1),
	snowball.NewAmong("egia", -1, 1),
	snowball.NewAmong("degia", 35, 1),
	snowball.NewAmong("tegia", 35, 1),
	snowball.NewAmong("nahia", -1, 1),
	snowball.NewAmong("ohia", -1, 1),
	snowball.NewAmong("kia", -1, 1),
	snowball.NewAmong("tokia", 40, 1),
	snowball.NewAmong("oia", -1, 1),
	snowball.NewAmong("koia", 42, 1),
	snowball.NewAmong("aria", -1, 1),
	snowball.NewAmong("karia", 44, 1),
	snowball.NewAmong("laria", 44, 1),
	snowball.NewAmong("taria", 44, 1),
	snowball.NewAmong("eria", -1, 1),
	snowball.NewAmong("keria", 48, 1),
	snowball.NewAmong("teria", 48, 1),
	snowball.NewAmong("garria", -1, 2),
	snowball.NewAmong("larria", -1, 1),
	snowball.NewAmong("kirria", -1, 1),
	snowball.NewAmong("duria", -1, 1),
	snowball.NewAmong("asia", -1, 1),
	snowball.NewAmong("tia", -1, 1),
	snowball.NewAmong("ezia", -1, 1),
	snowball.NewAmong("bizia", -1, 1),
	snowball.NewAmong("ontzia", -1, 1),
	snowball.NewAmong("ka", -1, 1),
	snowball.NewAmong("joka", 60, 3),
	snowball.NewAmong("aurka", 60, 10),
	snowball.NewAmong("ska", 60, 1),
	snowball.NewAmong("xka", 60, 1),
	snowball.NewAmong("zka", 60, 1),
	snowball.NewAmong("gibela", -1, 1),
	snowball.NewAmong("gela", -1, 1),
	snowball.NewAmong("kaila", -1, 1),
	snowball.NewAmong("skila", -1, 1),
	snowball.NewAmong("tila", -1, 1),
	snowball.NewAmong("ola", -1, 1),
	snowball.NewAmong("na", -1, 1),
	snowball.NewAmong("kana", 72, 1),
	snowball.NewAmong("ena", 72, 1),
	snowball.NewAmong("garrena", 74, 1),
	snowball.NewAmong("gerrena", 74, 1),
	snowball.NewAmong("urrena", 74, 1),
	snowball.NewAmong("zaina", 72, 1),
	snowball.NewAmong("tzaina", 78, 1),
	snowball.NewAmong("kina", 72, 1),
	snowball.NewAmong("mina", 72, 1),
	snowball.NewAmong("garna", 72, 1),
	snowball.NewAmong("una", 72, 1),
	snowball.NewAmong("duna", 83, 1),
	snowball.NewAmong("asuna", 83, 1),
	snowball.NewAmong("tasuna", 85, 1),
	snowball.NewAmong("ondoa", -1, 1),
	snowball.NewAmong("kondoa", 87, 1),
	snowball.NewAmong("ngoa", -1, 1),
	snowball.NewAmong("zioa", -1, 1),
	snowball.NewAmong("koa", -1, 1),
	snowball.NewAmong("takoa", 91, 1),
	snowball.NewAmong("zkoa", 91, 1),
	snowball.NewAmong("noa", -1, 1),
	snowball.NewAmong("zinoa", 94, 1),
	snowball.NewAmong("aroa", -1, 1),
	snowball.NewAmong("taroa", 96, 1),
	snowball.NewAmong("zaroa", 96, 1),
	snowball.NewAmong("eroa", -1, 1),
	snowball.NewAmong("oroa", -1, 1),
	snowball.NewAmong("osoa", -1, 1),
	snowball.NewAmong("toa", -1, 1),
	snowball.NewAmong("ttoa", 102, 1),
	snowball.NewAmong("ztoa", 102, 1),
	snowball.NewAmong("txoa", -1, 1),
	snowball.NewAmong("tzoa", -1, 1),
	snowball.NewAmong("ñoa", -1, 1),
	snowball.NewAmong("ra", -1, 1),
	snowball.NewAmong("ara", 108, 1),
	snowball.NewAmong("dara", 109, 1),
	snowball.NewAmong("liara", 109, 1),
	snowball.NewAmong("tiara", 109, 1),
	snowball.NewAmong("tara", 109, 1),
	snowball.NewAmong("etara", 113, 1),
	snowball.NewAmong("tzara", 109, 1),
	snowball.NewAmong("bera", 108, 1),
	snowball.NewAmong("kera", 108, 1),
	snowball.NewAmong("pera", 108, 1),
	snowball.NewAmong("ora", 108, 2),
	snowball.NewAmong("tzarra", 108, 1),
	snowball.NewAmong("korra", 108, 1),
	snowball.NewAmong("tra", 108, 1),
	snowball.NewAmong("sa", -1, 1),
	snowball.NewAmong("osa", 123, 1),
	snowball.NewAmong("ta", -1, 1),
	snowball.NewAmong("eta", 125, 1),
	snowball.NewAmong("keta", 126, 1),
	snowball.NewAmong("sta", 125, 1),
	snowball.NewAmong("dua", -1, 1),
	snowball.NewAmong("mendua", 129, 1),
	snowball.NewAmong("ordua", 129, 1),
	snowball.NewAmong("lekua", -1, 1),
	snowball.NewAmong("burua", -1, 1),
	snowball.NewAmong("durua", -1, 1),
	snowball.NewAmong("tsua", -1, 1),
	snowball.NewAmong("tua", -1, 1),
	snowball.NewAmong("mentua", 136, 1),
	snowball.NewAmong("estua", 136, 1),
	snowball.NewAmong("txua", -1, 1),
	snowball.NewAmong("zua", -1, 1),
	snowball.NewAmong("tzua", 140, 1),
	snowball.NewAmong("za", -1, 1),
	snowball.NewAmong("eza", 142, 1),
	snowball.NewAmong("eroza", 142, 1),
	snowball.NewAmong("tza", 142, 2),
	snowball.NewAmong("koitza", 145, 1),
	snowball.NewAmong("antza", 145, 1),
	snowball.NewAmong("gintza", 145, 1),
	snowball.NewAmong("kintza", 145, 1),
	snowball.NewAmong("kuntza", 145, 1),
	snowball.NewAmong("gabe", -1, 1),
	snowball.NewAmong("kabe", -1, 1),
	snowball.NewAmong("kide", -1, 1),
	snowball.NewAmong("alde", -1, 1),
	snowball.NewAmong("kalde", 154, 1),
	snowball.NewAmong("talde", 154, 1),
	snowball.NewAmong("orde", -1, 1),
	snowball.NewAmong("ge", -1, 1),
	snowball.NewAmong("zale", -1, 1),
	snowball.NewAmong("tzale", 159, 1),
	snowball.NewAmong("gile", -1, 1),
	snowball.NewAmong("eme", -1, 1),
	snowball.NewAmong("kume", -1, 1),
	snowball.NewAmong("ne", -1, 1),
	snowball.NewAmong("zione", 164, 1),
	snowball.NewAmong("une", 164, 1),
	snowball.NewAmong("gune", 166, 1),
	snowball.NewAmong("pe", -1, 1),
	snowball.NewAmong("aurre", -1, 1),
	snowball.NewAmong("te", -1, 1),
	snowball.NewAmong("kote", 170, 1),
	snowball.NewAmong("arte", 170, 1),
	snowball.NewAmong("oste", 170, 1),
	snowball.NewAmong("etxe", -1, 1),
	snowball.NewAmong("gai", -1, 1),
	snowball.NewAmong("di", -1, 1),
	snowball.NewAmong("aldi", 176, 1),
	snowball.NewAmong("taldi", 177, 1),
	snowball.NewAmong("geldi", 176, 8),
	snowball.NewAmong("handi", 176, 1),
	snowball.NewAmong("mendi", 176, 1),
	snowball.NewAmong("gei", -1, 1),
	snowball.NewAmong("egi", -1, 1),
	snowball.NewAmong("degi", 183, 1),
	snowball.NewAmong("tegi", 183, 1),
	snowball.NewAmong("nahi", -1, 1),
	snowball.NewAmong("ohi", -1, 1),
	snowball.NewAmong("ki", -1, 1),
	snowball.NewAmong("toki", 188, 1),
	snowball.NewAmong("oi", -1, 1),
	snowball.NewAmong("goi", 190, 1),
	snowball.NewAmong("koi", 190, 1),
	snowball.NewAmong("ari", -1, 1),
	snowball.NewAmong("kari", 193, 1),
	snowball.NewAmong("lari", 193, 1),
	snowball.NewAmong("tari", 193, 1),
	snowball.NewAmong("garri", -1, 2),
	snowball.NewAmong("larri", -1, 1),
	snowball.NewAmong("kirri", -1, 1),
	snowball.NewAmong("duri", -1, 1),
	snowball.NewAmong("asi", -1, 1),
	snowball.NewAmong("ti", -1, 1),
	snowball.NewAmong("ontzi", -1, 1),
	snowball.NewAmong("ñi", -1, 1),
	snowball.NewAmong("ak", -1, 1),
	snowball.NewAmong("ek", -1, 1),
	snowball.NewAmong("tarik", -1, 1),
	snowball.NewAmong("gibel", -1, 1),
	snowball.NewAmong("ail", -1, 1),
	snowball.NewAmong("kail", 209, 1),
	snowball.NewAmong("kan", -1, 1),
	snowball.NewAmong("tan", -1, 1),
	snowball.NewAmong("etan", 212, 1),
	snowball.NewAmong("en", -1, 4),
	snowball.NewAmong("ren", 214, 2),
	snowball.NewAmong("garren", 215, 1),
	snowball.NewAmong("gerren", 215, 1),
	snowball.NewAmong("urren", 215, 1),
	snowball.NewAmong("ten", 214, 4),
	snowball.NewAmong("tzen", 214, 4),
	snowball.NewAmong("zain", -1, 1),
	snowball.NewAmong("tzain", 221, 1),
	snowball.NewAmong("kin", -1, 1),
	snowball.NewAmong("min", -1, 1),
	snowball.NewAmong("dun", -1, 1),
	snowball.NewAmong("asun", -1, 1),
	snowball.NewAmong("tasun", 226, 1),
	snowball.NewAmong("aizun", -1, 1),
	snowball.NewAmong("ondo", -1, 1),
	snowball.NewAmong("kondo", 229, 1),
	snowball.NewAmong("go", -1, 1),
	snowball.NewAmong("ngo", 231, 1),
	snowball.NewAmong("zio", -1, 1),
	snowball.NewAmong("ko", -1, 1),
	snowball.NewAmong("trako", 234, 5),
	snowball.NewAmong("tako", 234, 1),
	snowball.NewAmong("etako", 236, 1),
	snowball.NewAmong("eko", 234, 1),
	snowball.NewAmong("tariko", 234, 1),
	snowball.NewAmong("sko", 234, 1),
	snowball.NewAmong("tuko", 234, 1),
	snowball.NewAmong("minutuko", 241, 6),
	snowball.NewAmong("zko", 234, 1),
	snowball.NewAmong("no", -1, 1),
	snowball.NewAmong("zino", 244, 1),
	snowball.NewAmong("ro", -1, 1),
	snowball.NewAmong("aro", 246, 1),
	snowball.NewAmong("igaro", 247, 9),
	snowball.NewAmong("taro", 247, 1),
	snowball.NewAmong("zaro", 247, 1),
	snowball.NewAmong("ero", 246, 1),
	snowball.NewAmong("giro", 246, 1),
	snowball.NewAmong("oro", 246, 1),
	snowball.NewAmong("oso", -1, 1),
	snowball.NewAmong("to", -1, 1),
	snowball.NewAmong("tto", 255, 1),
	snowball.NewAmong("zto", 255, 1),
	snowball.NewAmong("txo", -1, 1),
	snowball.NewAmong("tzo", -1, 1),
	snowball.NewAmong("gintzo", 259, 1),
	snowball.NewAmong("ño", -1, 1),
	snowball.NewAmong("zp", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("dar", 263, 1),
	snowball.NewAmong("behar", 263, 1),
	snowball.NewAmong("zehar", 263, 7),
	snowball.NewAmong("liar", 263, 1),
	snowball.NewAmong("tiar", 263, 1),
	snowball.NewAmong("tar", 263, 1),
	snowball.NewAmong("tzar", 263, 1),
	snowball.NewAmong("or", -1, 2),
	snowball.NewAmong("kor", 271, 1),
	snowball.NewAmong("os", -1, 1),
	snowball.NewAmong("ket", -1, 1),
	snowball.NewAmong("du", -1, 1),
	snowball.NewAmong("mendu", 275, 1),
	snowball.NewAmong("ordu", 275, 1),
	snowball.NewAmong("leku", -1, 1),
	snowball.NewAmong("buru", -1, 2),
	snowball.NewAmong("duru", -1, 1),
	snowball.NewAmong("tsu", -1, 1),
	snowball.NewAmong("tu", -1, 1),
	snowball.NewAmong("tatu", 282, 4),
	snowball.NewAmong("mentu", 282, 1),
	snowball.NewAmong("estu", 282, 1),
	snowball.NewAmong("txu", -1, 1),
	snowball.NewAmong("zu", -1, 1),
	snowball.NewAmong("tzu", 287, 1),
	snowball.NewAmong("gintzu", 288, 1),
	snowball.NewAmong("z", -1, 1),
	snowball.NewAmong("ez", 290, 1),
	snowball.NewAmong("eroz", 290, 1),
	snowball.NewAmong("tz", 290, 1),
	snowball.NewAmong("koitz", 293, 1),
}

var basqueA2 = []*snowball.Among{
	snowball.NewAmong("zlea", -1, 2),
	snowball.NewAmong("keria", -1, 1),
	snowball.NewAmong("la", -1, 1),
	snowball.NewAmong("era", -1, 1),
	snowball.NewAmong("dade", -1, 1),
	snowball.NewAmong("tade", -1, 1),
	snowball.NewAmong("date", -1, 1),
	snowball.NewAmong("tate", -1, 1),
	snowball.NewAmong("gi", -1, 1),
	snowball.NewAmong("ki", -1, 1),
	snowball.NewAmong("ik", -1, 1),
	snowball.NewAmong("lanik", 10, 1),
	snowball.NewAmong("rik", 10, 1),
	snowball.NewAmong("larik", 12, 1),
	snowball.NewAmong("ztik", 10, 1),
	snowball.NewAmong("go", -1, 1),
	snowball.NewAmong("ro", -1, 1),
	snowball.NewAmong("ero", 16, 1),
	snowball.NewAmong("to", -1, 1),
}

// basqueGV: vowels (a e i o u)
var basqueGV = []byte{17, 65, 16}

func (s *BasqueStemmer) rMarkRegions() bool {
	s.iPV = s.Limit
	s.iP1 = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
	lab0: for {
		lab1: for {
			v2 := s.Cursor
			lab2: for {
				if !s.InGrouping(basqueGV, 97, 117) {
					break lab2
				}
				lab3: for {
					v3 := s.Cursor
					lab4: for {
						if !s.OutGrouping(basqueGV, 97, 117) {
							break lab4
						}
					golab5:
						for {
							lab6: for {
								if !s.InGrouping(basqueGV, 97, 117) {
									break lab6
								}
								break golab5
							}
							if s.Cursor >= s.Limit {
								break lab4
							}
							s.Cursor++
						}
						break lab3
					}
					s.Cursor = v3
					if !s.InGrouping(basqueGV, 97, 117) {
						break lab2
					}
				golab7:
					for {
						lab8: for {
							if !s.OutGrouping(basqueGV, 97, 117) {
								break lab8
							}
							break golab7
						}
						if s.Cursor >= s.Limit {
							break lab2
						}
						s.Cursor++
					}
					break lab3
				}
				break lab1
			}
			s.Cursor = v2
			if !s.OutGrouping(basqueGV, 97, 117) {
				break lab0
			}
			lab9: for {
				v6 := s.Cursor
				lab10: for {
					if !s.OutGrouping(basqueGV, 97, 117) {
						break lab10
					}
				golab11:
					for {
						lab12: for {
							if !s.InGrouping(basqueGV, 97, 117) {
								break lab12
							}
							break golab11
						}
						if s.Cursor >= s.Limit {
							break lab10
						}
						s.Cursor++
					}
					break lab9
				}
				s.Cursor = v6
				if !s.InGrouping(basqueGV, 97, 117) {
					break lab0
				}
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
				break lab9
			}
			break lab1
		}
		s.iPV = s.Cursor
		break lab0
	}
	s.Cursor = v1
	v8 := s.Cursor
	lab13: for {
	golab14:
		for {
			lab15: for {
				if !s.InGrouping(basqueGV, 97, 117) {
					break lab15
				}
				break golab14
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab16:
		for {
			lab17: for {
				if !s.OutGrouping(basqueGV, 97, 117) {
					break lab17
				}
				break golab16
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
	golab18:
		for {
			lab19: for {
				if !s.InGrouping(basqueGV, 97, 117) {
					break lab19
				}
				break golab18
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab20:
		for {
			lab21: for {
				if !s.OutGrouping(basqueGV, 97, 117) {
					break lab21
				}
				break golab20
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab13
	}
	s.Cursor = v8
	return true
}

func (s *BasqueStemmer) rRV() bool { return s.iPV <= s.Cursor }
func (s *BasqueStemmer) rR1() bool { return s.iP1 <= s.Cursor }
func (s *BasqueStemmer) rR2() bool { return s.iP2 <= s.Cursor }

func (s *BasqueStemmer) rAditzak() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(basqueA0)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	case 3:
		s.SliceFromStr("atseden")
	case 4:
		s.SliceFromStr("arabera")
	case 5:
		s.SliceFromStr("baditu")
	}
	return true
}

func (s *BasqueStemmer) rIzenak() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(basqueA1)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	case 3:
		s.SliceFromStr("jok")
	case 4:
		if !s.rR1() {
			return false
		}
		s.SliceDel()
	case 5:
		s.SliceFromStr("tra")
	case 6:
		s.SliceFromStr("minutu")
	case 7:
		s.SliceFromStr("zehar")
	case 8:
		s.SliceFromStr("geldi")
	case 9:
		s.SliceFromStr("igaro")
	case 10:
		s.SliceFromStr("aurka")
	}
	return true
}

func (s *BasqueStemmer) rAdjetiboak() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(basqueA2)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		s.SliceDel()
	case 2:
		s.SliceFromStr("z")
	}
	return true
}

// Stem applies the Basque stemming algorithm to the current word.
func (s *BasqueStemmer) Stem() bool {
	s.rMarkRegions()
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit

	for {
		v2 := s.Limit - s.Cursor
		lab0: for {
			if !s.rAditzak() {
				break lab0
			}
			continue
		}
		s.Cursor = s.Limit - v2
		break
	}

	for {
		v3 := s.Limit - s.Cursor
		lab1: for {
			if !s.rIzenak() {
				break lab1
			}
			continue
		}
		s.Cursor = s.Limit - v3
		break
	}

	v4 := s.Limit - s.Cursor
	s.rAdjetiboak()
	s.Cursor = s.Limit - v4

	s.Cursor = s.LimitBackward
	return true
}
