// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from org.tartarus.snowball.ext.CatalanStemmer.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

var catalanA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 7),
	snowball.NewAmong("·", 0, 6),
	snowball.NewAmong("à", 0, 1),
	snowball.NewAmong("á", 0, 1),
	snowball.NewAmong("è", 0, 2),
	snowball.NewAmong("é", 0, 2),
	snowball.NewAmong("ì", 0, 3),
	snowball.NewAmong("í", 0, 3),
	snowball.NewAmong("ï", 0, 3),
	snowball.NewAmong("ò", 0, 4),
	snowball.NewAmong("ó", 0, 4),
	snowball.NewAmong("ú", 0, 5),
	snowball.NewAmong("ü", 0, 5),
}

var catalanA1 = []*snowball.Among{
	snowball.NewAmong("la", -1, 1),
	snowball.NewAmong("-la", 0, 1),
	snowball.NewAmong("sela", 0, 1),
	snowball.NewAmong("le", -1, 1),
	snowball.NewAmong("me", -1, 1),
	snowball.NewAmong("-me", 4, 1),
	snowball.NewAmong("se", -1, 1),
	snowball.NewAmong("-te", -1, 1),
	snowball.NewAmong("hi", -1, 1),
	snowball.NewAmong("'hi", 8, 1),
	snowball.NewAmong("li", -1, 1),
	snowball.NewAmong("-li", 10, 1),
	snowball.NewAmong("'l", -1, 1),
	snowball.NewAmong("'m", -1, 1),
	snowball.NewAmong("-m", -1, 1),
	snowball.NewAmong("'n", -1, 1),
	snowball.NewAmong("-n", -1, 1),
	snowball.NewAmong("ho", -1, 1),
	snowball.NewAmong("'ho", 17, 1),
	snowball.NewAmong("lo", -1, 1),
	snowball.NewAmong("selo", 19, 1),
	snowball.NewAmong("'s", -1, 1),
	snowball.NewAmong("las", -1, 1),
	snowball.NewAmong("selas", 22, 1),
	snowball.NewAmong("les", -1, 1),
	snowball.NewAmong("-les", 24, 1),
	snowball.NewAmong("'ls", -1, 1),
	snowball.NewAmong("-ls", -1, 1),
	snowball.NewAmong("'ns", -1, 1),
	snowball.NewAmong("-ns", -1, 1),
	snowball.NewAmong("ens", -1, 1),
	snowball.NewAmong("los", -1, 1),
	snowball.NewAmong("selos", 31, 1),
	snowball.NewAmong("nos", -1, 1),
	snowball.NewAmong("-nos", 33, 1),
	snowball.NewAmong("vos", -1, 1),
	snowball.NewAmong("us", -1, 1),
	snowball.NewAmong("-us", 36, 1),
	snowball.NewAmong("'t", -1, 1),
}

var catalanA2 = []*snowball.Among{
	snowball.NewAmong("ica", -1, 4),
	snowball.NewAmong("lógica", 0, 3),
	snowball.NewAmong("enca", -1, 1),
	snowball.NewAmong("ada", -1, 2),
	snowball.NewAmong("ancia", -1, 1),
	snowball.NewAmong("encia", -1, 1),
	snowball.NewAmong("ència", -1, 1),
	snowball.NewAmong("ícia", -1, 1),
	snowball.NewAmong("logia", -1, 3),
	snowball.NewAmong("inia", -1, 1),
	snowball.NewAmong("íinia", 9, 1),
	snowball.NewAmong("eria", -1, 1),
	snowball.NewAmong("ària", -1, 1),
	snowball.NewAmong("atòria", -1, 1),
	snowball.NewAmong("alla", -1, 1),
	snowball.NewAmong("ella", -1, 1),
	snowball.NewAmong("ívola", -1, 1),
	snowball.NewAmong("ima", -1, 1),
	snowball.NewAmong("íssima", 17, 1),
	snowball.NewAmong("quíssima", 18, 5),
	snowball.NewAmong("ana", -1, 1),
	snowball.NewAmong("ina", -1, 1),
	snowball.NewAmong("era", -1, 1),
	snowball.NewAmong("sfera", 22, 1),
	snowball.NewAmong("ora", -1, 1),
	snowball.NewAmong("dora", 24, 1),
	snowball.NewAmong("adora", 25, 1),
	snowball.NewAmong("adura", -1, 1),
	snowball.NewAmong("esa", -1, 1),
	snowball.NewAmong("osa", -1, 1),
	snowball.NewAmong("assa", -1, 1),
	snowball.NewAmong("essa", -1, 1),
	snowball.NewAmong("issa", -1, 1),
	snowball.NewAmong("eta", -1, 1),
	snowball.NewAmong("ita", -1, 1),
	snowball.NewAmong("ota", -1, 1),
	snowball.NewAmong("ista", -1, 1),
	snowball.NewAmong("ialista", 36, 1),
	snowball.NewAmong("ionista", 36, 1),
	snowball.NewAmong("iva", -1, 1),
	snowball.NewAmong("ativa", 39, 1),
	snowball.NewAmong("nça", -1, 1),
	snowball.NewAmong("logía", -1, 3),
	snowball.NewAmong("ic", -1, 4),
	snowball.NewAmong("ístic", 43, 1),
	snowball.NewAmong("enc", -1, 1),
	snowball.NewAmong("esc", -1, 1),
	snowball.NewAmong("ud", -1, 1),
	snowball.NewAmong("atge", -1, 1),
	snowball.NewAmong("ble", -1, 1),
	snowball.NewAmong("able", 49, 1),
	snowball.NewAmong("ible", 49, 1),
	snowball.NewAmong("isme", -1, 1),
	snowball.NewAmong("ialisme", 52, 1),
	snowball.NewAmong("ionisme", 52, 1),
	snowball.NewAmong("ivisme", 52, 1),
	snowball.NewAmong("aire", -1, 1),
	snowball.NewAmong("icte", -1, 1),
	snowball.NewAmong("iste", -1, 1),
	snowball.NewAmong("ici", -1, 1),
	snowball.NewAmong("íci", -1, 1),
	snowball.NewAmong("logi", -1, 3),
	snowball.NewAmong("ari", -1, 1),
	snowball.NewAmong("tori", -1, 1),
	snowball.NewAmong("al", -1, 1),
	snowball.NewAmong("il", -1, 1),
	snowball.NewAmong("all", -1, 1),
	snowball.NewAmong("ell", -1, 1),
	snowball.NewAmong("ívol", -1, 1),
	snowball.NewAmong("isam", -1, 1),
	snowball.NewAmong("issem", -1, 1),
	snowball.NewAmong("ìssem", -1, 1),
	snowball.NewAmong("íssem", -1, 1),
	snowball.NewAmong("íssim", -1, 1),
	snowball.NewAmong("quíssim", 73, 5),
	snowball.NewAmong("amen", -1, 1),
	snowball.NewAmong("ìssin", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("ificar", 77, 1),
	snowball.NewAmong("egar", 77, 1),
	snowball.NewAmong("ejar", 77, 1),
	snowball.NewAmong("itar", 77, 1),
	snowball.NewAmong("itzar", 77, 1),
	snowball.NewAmong("fer", -1, 1),
	snowball.NewAmong("or", -1, 1),
	snowball.NewAmong("dor", 84, 1),
	snowball.NewAmong("dur", -1, 1),
	snowball.NewAmong("doras", -1, 1),
	snowball.NewAmong("ics", -1, 4),
	snowball.NewAmong("lógics", 88, 3),
	snowball.NewAmong("uds", -1, 1),
	snowball.NewAmong("nces", -1, 1),
	snowball.NewAmong("ades", -1, 2),
	snowball.NewAmong("ancies", -1, 1),
	snowball.NewAmong("encies", -1, 1),
	snowball.NewAmong("ències", -1, 1),
	snowball.NewAmong("ícies", -1, 1),
	snowball.NewAmong("logies", -1, 3),
	snowball.NewAmong("inies", -1, 1),
	snowball.NewAmong("ínies", -1, 1),
	snowball.NewAmong("eries", -1, 1),
	snowball.NewAmong("àries", -1, 1),
	snowball.NewAmong("atòries", -1, 1),
	snowball.NewAmong("bles", -1, 1),
	snowball.NewAmong("ables", 103, 1),
	snowball.NewAmong("ibles", 103, 1),
	snowball.NewAmong("imes", -1, 1),
	snowball.NewAmong("íssimes", 106, 1),
	snowball.NewAmong("quíssimes", 107, 5),
	snowball.NewAmong("formes", -1, 1),
	snowball.NewAmong("ismes", -1, 1),
	snowball.NewAmong("ialismes", 110, 1),
	snowball.NewAmong("ines", -1, 1),
	snowball.NewAmong("eres", -1, 1),
	snowball.NewAmong("ores", -1, 1),
	snowball.NewAmong("dores", 114, 1),
	snowball.NewAmong("idores", 115, 1),
	snowball.NewAmong("dures", -1, 1),
	snowball.NewAmong("eses", -1, 1),
	snowball.NewAmong("oses", -1, 1),
	snowball.NewAmong("asses", -1, 1),
	snowball.NewAmong("ictes", -1, 1),
	snowball.NewAmong("ites", -1, 1),
	snowball.NewAmong("otes", -1, 1),
	snowball.NewAmong("istes", -1, 1),
	snowball.NewAmong("ialistes", 124, 1),
	snowball.NewAmong("ionistes", 124, 1),
	snowball.NewAmong("iques", -1, 4),
	snowball.NewAmong("lógiques", 127, 3),
	snowball.NewAmong("ives", -1, 1),
	snowball.NewAmong("atives", 129, 1),
	snowball.NewAmong("logíes", -1, 3),
	snowball.NewAmong("allengües", -1, 1),
	snowball.NewAmong("icis", -1, 1),
	snowball.NewAmong("ícis", -1, 1),
	snowball.NewAmong("logis", -1, 3),
	snowball.NewAmong("aris", -1, 1),
	snowball.NewAmong("toris", -1, 1),
	snowball.NewAmong("ls", -1, 1),
	snowball.NewAmong("als", 138, 1),
	snowball.NewAmong("ells", 138, 1),
	snowball.NewAmong("ims", -1, 1),
	snowball.NewAmong("íssims", 141, 1),
	snowball.NewAmong("quíssims", 142, 5),
	snowball.NewAmong("ions", -1, 1),
	snowball.NewAmong("cions", 144, 1),
	snowball.NewAmong("acions", 145, 2),
	snowball.NewAmong("esos", -1, 1),
	snowball.NewAmong("osos", -1, 1),
	snowball.NewAmong("assos", -1, 1),
	snowball.NewAmong("issos", -1, 1),
	snowball.NewAmong("ers", -1, 1),
	snowball.NewAmong("ors", -1, 1),
	snowball.NewAmong("dors", 152, 1),
	snowball.NewAmong("adors", 153, 1),
	snowball.NewAmong("idors", 153, 1),
	snowball.NewAmong("ats", -1, 1),
	snowball.NewAmong("itats", 156, 1),
	snowball.NewAmong("bilitats", 157, 1),
	snowball.NewAmong("ivitats", 157, 1),
	snowball.NewAmong("ativitats", 159, 1),
	snowball.NewAmong("ïtats", 156, 1),
	snowball.NewAmong("ets", -1, 1),
	snowball.NewAmong("ants", -1, 1),
	snowball.NewAmong("ents", -1, 1),
	snowball.NewAmong("ments", 164, 1),
	snowball.NewAmong("aments", 165, 1),
	snowball.NewAmong("ots", -1, 1),
	snowball.NewAmong("uts", -1, 1),
	snowball.NewAmong("ius", -1, 1),
	snowball.NewAmong("trius", 169, 1),
	snowball.NewAmong("atius", 169, 1),
	snowball.NewAmong("ès", -1, 1),
	snowball.NewAmong("és", -1, 1),
	snowball.NewAmong("ís", -1, 1),
	snowball.NewAmong("dís", 174, 1),
	snowball.NewAmong("ós", -1, 1),
	snowball.NewAmong("itat", -1, 1),
	snowball.NewAmong("bilitat", 177, 1),
	snowball.NewAmong("ivitat", 177, 1),
	snowball.NewAmong("ativitat", 179, 1),
	snowball.NewAmong("ïtat", -1, 1),
	snowball.NewAmong("et", -1, 1),
	snowball.NewAmong("ant", -1, 1),
	snowball.NewAmong("ent", -1, 1),
	snowball.NewAmong("ient", 184, 1),
	snowball.NewAmong("ment", 184, 1),
	snowball.NewAmong("ament", 186, 1),
	snowball.NewAmong("isament", 187, 1),
	snowball.NewAmong("ot", -1, 1),
	snowball.NewAmong("isseu", -1, 1),
	snowball.NewAmong("ìsseu", -1, 1),
	snowball.NewAmong("ísseu", -1, 1),
	snowball.NewAmong("triu", -1, 1),
	snowball.NewAmong("íssiu", -1, 1),
	snowball.NewAmong("atiu", -1, 1),
	snowball.NewAmong("ó", -1, 1),
	snowball.NewAmong("ió", 196, 1),
	snowball.NewAmong("ció", 197, 1),
	snowball.NewAmong("ació", 198, 1),
}

var catalanA3 = []*snowball.Among{
	snowball.NewAmong("aba", -1, 1),
	snowball.NewAmong("esca", -1, 1),
	snowball.NewAmong("isca", -1, 1),
	snowball.NewAmong("ïsca", -1, 1),
	snowball.NewAmong("ada", -1, 1),
	snowball.NewAmong("ida", -1, 1),
	snowball.NewAmong("uda", -1, 1),
	snowball.NewAmong("ïda", -1, 1),
	snowball.NewAmong("ia", -1, 1),
	snowball.NewAmong("aria", 8, 1),
	snowball.NewAmong("iria", 8, 1),
	snowball.NewAmong("ara", -1, 1),
	snowball.NewAmong("iera", -1, 1),
	snowball.NewAmong("ira", -1, 1),
	snowball.NewAmong("adora", -1, 1),
	snowball.NewAmong("ïra", -1, 1),
	snowball.NewAmong("ava", -1, 1),
	snowball.NewAmong("ixa", -1, 1),
	snowball.NewAmong("itza", -1, 1),
	snowball.NewAmong("ía", -1, 1),
	snowball.NewAmong("aría", 19, 1),
	snowball.NewAmong("ería", 19, 1),
	snowball.NewAmong("iría", 19, 1),
	snowball.NewAmong("ïa", -1, 1),
	snowball.NewAmong("isc", -1, 1),
	snowball.NewAmong("ïsc", -1, 1),
	snowball.NewAmong("ad", -1, 1),
	snowball.NewAmong("ed", -1, 1),
	snowball.NewAmong("id", -1, 1),
	snowball.NewAmong("ie", -1, 1),
	snowball.NewAmong("re", -1, 1),
	snowball.NewAmong("dre", 30, 1),
	snowball.NewAmong("ase", -1, 1),
	snowball.NewAmong("iese", -1, 1),
	snowball.NewAmong("aste", -1, 1),
	snowball.NewAmong("iste", -1, 1),
	snowball.NewAmong("ii", -1, 1),
	snowball.NewAmong("ini", -1, 1),
	snowball.NewAmong("esqui", -1, 1),
	snowball.NewAmong("eixi", -1, 1),
	snowball.NewAmong("itzi", -1, 1),
	snowball.NewAmong("am", -1, 1),
	snowball.NewAmong("em", -1, 1),
	snowball.NewAmong("arem", 42, 1),
	snowball.NewAmong("irem", 42, 1),
	snowball.NewAmong("àrem", 42, 1),
	snowball.NewAmong("írem", 42, 1),
	snowball.NewAmong("àssem", 42, 1),
	snowball.NewAmong("éssem", 42, 1),
	snowball.NewAmong("iguem", 42, 1),
	snowball.NewAmong("ïguem", 42, 1),
	snowball.NewAmong("avem", 42, 1),
	snowball.NewAmong("àvem", 42, 1),
	snowball.NewAmong("ávem", 42, 1),
	snowball.NewAmong("irèem", 42, 1),
	snowball.NewAmong("íem", 42, 1),
	snowball.NewAmong("aríem", 55, 1),
	snowball.NewAmong("iríem", 55, 1),
	snowball.NewAmong("assim", -1, 1),
	snowball.NewAmong("essim", -1, 1),
	snowball.NewAmong("issim", -1, 1),
	snowball.NewAmong("àssim", -1, 1),
	snowball.NewAmong("èssim", -1, 1),
	snowball.NewAmong("éssim", -1, 1),
	snowball.NewAmong("íssim", -1, 1),
	snowball.NewAmong("ïm", -1, 1),
	snowball.NewAmong("an", -1, 1),
	snowball.NewAmong("aban", 66, 1),
	snowball.NewAmong("arian", 66, 1),
	snowball.NewAmong("aran", 66, 1),
	snowball.NewAmong("ieran", 66, 1),
	snowball.NewAmong("iran", 66, 1),
	snowball.NewAmong("ían", 66, 1),
	snowball.NewAmong("arían", 72, 1),
	snowball.NewAmong("eríen", 72, 1),
	snowball.NewAmong("iríen", 72, 1),
	snowball.NewAmong("en", -1, 1),
	snowball.NewAmong("ien", 76, 1),
	snowball.NewAmong("arien", 77, 1),
	snowball.NewAmong("irien", 77, 1),
	snowball.NewAmong("aren", 76, 1),
	snowball.NewAmong("eren", 76, 1),
	snowball.NewAmong("iren", 76, 1),
	snowball.NewAmong("àren", 76, 1),
	snowball.NewAmong("ïren", 76, 1),
	snowball.NewAmong("asen", 76, 1),
	snowball.NewAmong("iesen", 76, 1),
	snowball.NewAmong("assen", 76, 1),
	snowball.NewAmong("essen", 76, 1),
	snowball.NewAmong("issen", 76, 1),
	snowball.NewAmong("éssen", 76, 1),
	snowball.NewAmong("ïssen", 76, 1),
	snowball.NewAmong("esquen", 76, 1),
	snowball.NewAmong("isquen", 76, 1),
	snowball.NewAmong("ïsquen", 76, 1),
	snowball.NewAmong("aven", 76, 1),
	snowball.NewAmong("ixen", 76, 1),
	snowball.NewAmong("eixen", 96, 1),
	snowball.NewAmong("ïxen", 76, 1),
	snowball.NewAmong("ïen", 76, 1),
	snowball.NewAmong("in", -1, 1),
	snowball.NewAmong("inin", 100, 1),
	snowball.NewAmong("sin", 100, 1),
	snowball.NewAmong("isin", 102, 1),
	snowball.NewAmong("assin", 102, 1),
	snowball.NewAmong("essin", 102, 1),
	snowball.NewAmong("issin", 102, 1),
	snowball.NewAmong("ïssin", 102, 1),
	snowball.NewAmong("esquin", 100, 1),
	snowball.NewAmong("eixin", 100, 1),
	snowball.NewAmong("aron", -1, 1),
	snowball.NewAmong("ieron", -1, 1),
	snowball.NewAmong("arán", -1, 1),
	snowball.NewAmong("erán", -1, 1),
	snowball.NewAmong("irán", -1, 1),
	snowball.NewAmong("iïn", -1, 1),
	snowball.NewAmong("ado", -1, 1),
	snowball.NewAmong("ido", -1, 1),
	snowball.NewAmong("ando", -1, 2),
	snowball.NewAmong("iendo", -1, 1),
	snowball.NewAmong("io", -1, 1),
	snowball.NewAmong("ixo", -1, 1),
	snowball.NewAmong("eixo", 121, 1),
	snowball.NewAmong("ïxo", -1, 1),
	snowball.NewAmong("itzo", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("tzar", 125, 1),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("eixer", 127, 1),
	snowball.NewAmong("ir", -1, 1),
	snowball.NewAmong("ador", -1, 1),
	snowball.NewAmong("as", -1, 1),
	snowball.NewAmong("abas", 131, 1),
	snowball.NewAmong("adas", 131, 1),
	snowball.NewAmong("idas", 131, 1),
	snowball.NewAmong("aras", 131, 1),
	snowball.NewAmong("ieras", 131, 1),
	snowball.NewAmong("ías", 131, 1),
	snowball.NewAmong("arías", 137, 1),
	snowball.NewAmong("erías", 137, 1),
	snowball.NewAmong("irías", 137, 1),
	snowball.NewAmong("ids", -1, 1),
	snowball.NewAmong("es", -1, 1),
	snowball.NewAmong("ades", 142, 1),
	snowball.NewAmong("ides", 142, 1),
	snowball.NewAmong("udes", 142, 1),
	snowball.NewAmong("ïdes", 142, 1),
	snowball.NewAmong("atges", 142, 1),
	snowball.NewAmong("ies", 142, 1),
	snowball.NewAmong("aries", 148, 1),
	snowball.NewAmong("iries", 148, 1),
	snowball.NewAmong("ares", 142, 1),
	snowball.NewAmong("ires", 142, 1),
	snowball.NewAmong("adores", 142, 1),
	snowball.NewAmong("ïres", 142, 1),
	snowball.NewAmong("ases", 142, 1),
	snowball.NewAmong("ieses", 142, 1),
	snowball.NewAmong("asses", 142, 1),
	snowball.NewAmong("esses", 142, 1),
	snowball.NewAmong("isses", 142, 1),
	snowball.NewAmong("ïsses", 142, 1),
	snowball.NewAmong("ques", 142, 1),
	snowball.NewAmong("esques", 161, 1),
	snowball.NewAmong("ïsques", 161, 1),
	snowball.NewAmong("aves", 142, 1),
	snowball.NewAmong("ixes", 142, 1),
	snowball.NewAmong("eixes", 165, 1),
	snowball.NewAmong("ïxes", 142, 1),
	snowball.NewAmong("ïes", 142, 1),
	snowball.NewAmong("abais", -1, 1),
	snowball.NewAmong("arais", -1, 1),
	snowball.NewAmong("ierais", -1, 1),
	snowball.NewAmong("íais", -1, 1),
	snowball.NewAmong("aríais", 172, 1),
	snowball.NewAmong("eríais", 172, 1),
	snowball.NewAmong("iríais", 172, 1),
	snowball.NewAmong("aseis", -1, 1),
	snowball.NewAmong("ieseis", -1, 1),
	snowball.NewAmong("asteis", -1, 1),
	snowball.NewAmong("isteis", -1, 1),
	snowball.NewAmong("inis", -1, 1),
	snowball.NewAmong("sis", -1, 1),
	snowball.NewAmong("isis", 181, 1),
	snowball.NewAmong("assis", 181, 1),
	snowball.NewAmong("essis", 181, 1),
	snowball.NewAmong("issis", 181, 1),
	snowball.NewAmong("ïssis", 181, 1),
	snowball.NewAmong("esquis", -1, 1),
	snowball.NewAmong("eixis", -1, 1),
	snowball.NewAmong("itzis", -1, 1),
	snowball.NewAmong("áis", -1, 1),
	snowball.NewAmong("aréis", -1, 1),
	snowball.NewAmong("eréis", -1, 1),
	snowball.NewAmong("iréis", -1, 1),
	snowball.NewAmong("ams", -1, 1),
	snowball.NewAmong("ados", -1, 1),
	snowball.NewAmong("idos", -1, 1),
	snowball.NewAmong("amos", -1, 1),
	snowball.NewAmong("ábamos", 197, 1),
	snowball.NewAmong("áramos", 197, 1),
	snowball.NewAmong("iéramos", 197, 1),
	snowball.NewAmong("íamos", 197, 1),
	snowball.NewAmong("aríamos", 201, 1),
	snowball.NewAmong("eríamos", 201, 1),
	snowball.NewAmong("iríamos", 201, 1),
	snowball.NewAmong("aremos", -1, 1),
	snowball.NewAmong("eremos", -1, 1),
	snowball.NewAmong("iremos", -1, 1),
	snowball.NewAmong("ásemos", -1, 1),
	snowball.NewAmong("iésemos", -1, 1),
	snowball.NewAmong("imos", -1, 1),
	snowball.NewAmong("adors", -1, 1),
	snowball.NewAmong("ass", -1, 1),
	snowball.NewAmong("erass", 212, 1),
	snowball.NewAmong("ess", -1, 1),
	snowball.NewAmong("ats", -1, 1),
	snowball.NewAmong("its", -1, 1),
	snowball.NewAmong("ents", -1, 1),
	snowball.NewAmong("às", -1, 1),
	snowball.NewAmong("aràs", 218, 1),
	snowball.NewAmong("iràs", 218, 1),
	snowball.NewAmong("arás", -1, 1),
	snowball.NewAmong("erás", -1, 1),
	snowball.NewAmong("irás", -1, 1),
	snowball.NewAmong("és", -1, 1),
	snowball.NewAmong("arés", 224, 1),
	snowball.NewAmong("ís", -1, 1),
	snowball.NewAmong("iïs", -1, 1),
	snowball.NewAmong("at", -1, 1),
	snowball.NewAmong("it", -1, 1),
	snowball.NewAmong("ant", -1, 1),
	snowball.NewAmong("ent", -1, 1),
	snowball.NewAmong("int", -1, 1),
	snowball.NewAmong("ut", -1, 1),
	snowball.NewAmong("ït", -1, 1),
	snowball.NewAmong("au", -1, 1),
	snowball.NewAmong("erau", 235, 1),
	snowball.NewAmong("ieu", -1, 1),
	snowball.NewAmong("ineu", -1, 1),
	snowball.NewAmong("areu", -1, 1),
	snowball.NewAmong("ireu", -1, 1),
	snowball.NewAmong("àreu", -1, 1),
	snowball.NewAmong("íreu", -1, 1),
	snowball.NewAmong("asseu", -1, 1),
	snowball.NewAmong("esseu", -1, 1),
	snowball.NewAmong("eresseu", 244, 1),
	snowball.NewAmong("àsseu", -1, 1),
	snowball.NewAmong("ésseu", -1, 1),
	snowball.NewAmong("igueu", -1, 1),
	snowball.NewAmong("ïgueu", -1, 1),
	snowball.NewAmong("àveu", -1, 1),
	snowball.NewAmong("áveu", -1, 1),
	snowball.NewAmong("itzeu", -1, 1),
	snowball.NewAmong("ìeu", -1, 1),
	snowball.NewAmong("irìeu", 253, 1),
	snowball.NewAmong("íeu", -1, 1),
	snowball.NewAmong("aríeu", 255, 1),
	snowball.NewAmong("iríeu", 255, 1),
	snowball.NewAmong("assiu", -1, 1),
	snowball.NewAmong("issiu", -1, 1),
	snowball.NewAmong("àssiu", -1, 1),
	snowball.NewAmong("èssiu", -1, 1),
	snowball.NewAmong("éssiu", -1, 1),
	snowball.NewAmong("íssiu", -1, 1),
	snowball.NewAmong("ïu", -1, 1),
	snowball.NewAmong("ix", -1, 1),
	snowball.NewAmong("eix", 265, 1),
	snowball.NewAmong("ïx", -1, 1),
	snowball.NewAmong("itz", -1, 1),
	snowball.NewAmong("ià", -1, 1),
	snowball.NewAmong("arà", -1, 1),
	snowball.NewAmong("irà", -1, 1),
	snowball.NewAmong("itzà", -1, 1),
	snowball.NewAmong("ará", -1, 1),
	snowball.NewAmong("erá", -1, 1),
	snowball.NewAmong("irá", -1, 1),
	snowball.NewAmong("irè", -1, 1),
	snowball.NewAmong("aré", -1, 1),
	snowball.NewAmong("eré", -1, 1),
	snowball.NewAmong("iré", -1, 1),
	snowball.NewAmong("í", -1, 1),
	snowball.NewAmong("iï", -1, 1),
	snowball.NewAmong("ió", -1, 1),
}

var catalanA4 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("i", -1, 1),
	snowball.NewAmong("ïn", -1, 1),
	snowball.NewAmong("o", -1, 1),
	snowball.NewAmong("ir", -1, 1),
	snowball.NewAmong("s", -1, 1),
	snowball.NewAmong("is", 6, 1),
	snowball.NewAmong("os", 6, 1),
	snowball.NewAmong("ïs", 6, 1),
	snowball.NewAmong("it", -1, 1),
	snowball.NewAmong("eu", -1, 1),
	snowball.NewAmong("iu", -1, 1),
	snowball.NewAmong("iqu", -1, 2),
	snowball.NewAmong("itz", -1, 1),
	snowball.NewAmong("à", -1, 1),
	snowball.NewAmong("á", -1, 1),
	snowball.NewAmong("é", -1, 1),
	snowball.NewAmong("ì", -1, 1),
	snowball.NewAmong("í", -1, 1),
	snowball.NewAmong("ï", -1, 1),
	snowball.NewAmong("ó", -1, 1),
}

// catalanGV is the vowel grouping for Catalan (a–ü, range 97–252).
var catalanGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 129, 81, 6, 10}

// CatalanStemmer implements the Snowball stemming algorithm for Catalan.
// It mirrors org.tartarus.snowball.ext.CatalanStemmer.
type CatalanStemmer struct {
	snowball.SnowballProgram
	iP2 int
	iP1 int
}

// NewCatalanStemmer constructs a CatalanStemmer.
func NewCatalanStemmer() *CatalanStemmer {
	return &CatalanStemmer{}
}

func (s *CatalanStemmer) rMarkRegions() bool {
	s.iP1 = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
lab0:
	for {
	golab1:
		for {
			lab2:
			for {
				if !s.InGrouping(catalanGV, 97, 252) {
					break lab2
				}
				break golab1
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
	golab3:
		for {
			lab4:
			for {
				if !s.OutGrouping(catalanGV, 97, 252) {
					break lab4
				}
				break golab3
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
	golab5:
		for {
			lab6:
			for {
				if !s.InGrouping(catalanGV, 97, 252) {
					break lab6
				}
				break golab5
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
	golab7:
		for {
			lab8:
			for {
				if !s.OutGrouping(catalanGV, 97, 252) {
					break lab8
				}
				break golab7
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab0
	}
	s.Cursor = v1
	return true
}

func (s *CatalanStemmer) rCleaning() bool {
	for {
		v1 := s.Cursor
		lab0:
		for {
			s.Bra = s.Cursor
			amongVar := s.FindAmong(catalanA0)
			s.Ket = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("a")
			case 2:
				s.SliceFromStr("e")
			case 3:
				s.SliceFromStr("i")
			case 4:
				s.SliceFromStr("o")
			case 5:
				s.SliceFromStr("u")
			case 6:
				s.SliceFromStr(".")
			case 7:
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *CatalanStemmer) rR1() bool { return s.iP1 <= s.Cursor }
func (s *CatalanStemmer) rR2() bool { return s.iP2 <= s.Cursor }

func (s *CatalanStemmer) rAttachedPronoun() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(catalanA1) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	s.SliceDel()
	return true
}

func (s *CatalanStemmer) rStandardSuffix() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(catalanA2)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR1() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	case 3:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("log")
	case 4:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("ic")
	case 5:
		if !s.rR1() {
			return false
		}
		s.SliceFromStr("c")
	}
	return true
}

func (s *CatalanStemmer) rVerbSuffix() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(catalanA3)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR1() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	}
	return true
}

func (s *CatalanStemmer) rResidualSuffix() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(catalanA4)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR1() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR1() {
			return false
		}
		s.SliceFromStr("ic")
	}
	return true
}

// Stem applies the Catalan stemming algorithm to the current word.
func (s *CatalanStemmer) Stem() bool {
	s.rMarkRegions()
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	v2 := s.Limit - s.Cursor
	s.rAttachedPronoun()
	s.Cursor = s.Limit - v2
	v3 := s.Limit - s.Cursor
lab0:
	for {
		lab1:
		for {
			v4 := s.Limit - s.Cursor
			lab2:
			for {
				if !s.rStandardSuffix() {
					break lab2
				}
				break lab1
			}
			s.Cursor = s.Limit - v4
			if !s.rVerbSuffix() {
				break lab0
			}
			break lab1
		}
		break lab0
	}
	s.Cursor = s.Limit - v3
	v5 := s.Limit - s.Cursor
	s.rResidualSuffix()
	s.Cursor = s.Limit - v5
	s.Cursor = s.LimitBackward
	v6 := s.Cursor
	s.rCleaning()
	s.Cursor = v6
	return true
}
