// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// DanishStemmer implements the Danish Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.DanishStemmer
// from Apache Lucene 10.4.0.
type DanishStemmer struct {
	*snowball.SnowballProgram
	iX  int
	iP1 int
	sCh []rune
}

// NewDanishStemmer creates a new DanishStemmer.
func NewDanishStemmer() *DanishStemmer {
	return &DanishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var danishA0 = []*snowball.Among{
	snowball.NewAmong("hed", -1, 1),
	snowball.NewAmong("ethed", 0, 1),
	snowball.NewAmong("ered", -1, 1),
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("erede", 3, 1),
	snowball.NewAmong("ende", 3, 1),
	snowball.NewAmong("erende", 5, 1),
	snowball.NewAmong("ene", 3, 1),
	snowball.NewAmong("erne", 3, 1),
	snowball.NewAmong("ere", 3, 1),
	snowball.NewAmong("en", -1, 1),
	snowball.NewAmong("heden", 10, 1),
	snowball.NewAmong("eren", 10, 1),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("heder", 13, 1),
	snowball.NewAmong("erer", 13, 1),
	snowball.NewAmong("s", -1, 2),
	snowball.NewAmong("heds", 16, 1),
	snowball.NewAmong("es", 16, 1),
	snowball.NewAmong("endes", 18, 1),
	snowball.NewAmong("erendes", 19, 1),
	snowball.NewAmong("enes", 18, 1),
	snowball.NewAmong("ernes", 18, 1),
	snowball.NewAmong("eres", 18, 1),
	snowball.NewAmong("ens", 16, 1),
	snowball.NewAmong("hedens", 24, 1),
	snowball.NewAmong("erens", 24, 1),
	snowball.NewAmong("ers", 16, 1),
	snowball.NewAmong("ets", 16, 1),
	snowball.NewAmong("erets", 28, 1),
	snowball.NewAmong("et", -1, 1),
	snowball.NewAmong("eret", 30, 1),
}

var danishA1 = []*snowball.Among{
	snowball.NewAmong("gd", -1, -1),
	snowball.NewAmong("dt", -1, -1),
	snowball.NewAmong("gt", -1, -1),
	snowball.NewAmong("kt", -1, -1),
}

var danishA2 = []*snowball.Among{
	snowball.NewAmong("ig", -1, 1),
	snowball.NewAmong("lig", 0, 1),
	snowball.NewAmong("elig", 1, 1),
	snowball.NewAmong("els", -1, 1),
	snowball.NewAmong("løst", -1, 2),
}

var danishGC = []byte{119, 223, 119, 1}
var danishGV = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128}
var danishGSEnding = []byte{239, 254, 42, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16}

func (s *DanishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	v1 := p.Cursor
	c := p.Cursor + 3
	if c > p.Limit {
		return false
	}
	p.Cursor = c
	s.iX = p.Cursor
	p.Cursor = v1
golab0:
	for {
		v2 := p.Cursor
	lab1:
		for {
			if !p.InGrouping(danishGV, 97, 248) {
				break lab1
			}
			p.Cursor = v2
			break golab0
		}
		p.Cursor = v2
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab2:
	for {
		if p.OutGrouping(danishGV, 97, 248) {
			break golab2
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP1 = p.Cursor
lab4:
	for {
		if s.iP1 >= s.iX {
			break lab4
		}
		s.iP1 = s.iX
		break
	}
	return true
}

func (s *DanishStemmer) rMainSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(danishA0)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		p.SliceDel()
	case 2:
		if !p.InGroupingB(danishGSEnding, 97, 229) {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *DanishStemmer) rConsonantPair() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
	if p.Cursor < s.iP1 {
		return false
	}
	v3 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	if p.FindAmongB(danishA1) == 0 {
		p.LimitBackward = v3
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v3
	p.Cursor = p.Limit - v1
	if p.Cursor <= p.LimitBackward {
		return false
	}
	p.Cursor--
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *DanishStemmer) rOtherSuffix() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("st") {
			break lab0
		}
		p.Bra = p.Cursor
		if !p.EqSBStr("ig") {
			break lab0
		}
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v1
	if p.Cursor < s.iP1 {
		return false
	}
	v3 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(danishA2)
	if amongVar == 0 {
		p.LimitBackward = v3
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v3
	switch amongVar {
	case 1:
		p.SliceDel()
		v4 := p.Limit - p.Cursor
		s.rConsonantPair()
		p.Cursor = p.Limit - v4
	case 2:
		p.SliceFromStr("løs")
	}
	return true
}

func (s *DanishStemmer) rUndouble() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	if !p.InGroupingB(danishGC, 98, 122) {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	s.sCh = p.SliceTo(s.sCh)
	p.LimitBackward = v2
	if !p.EqSB(s.sCh) {
		return false
	}
	p.SliceDel()
	return true
}

// Stem applies the Danish Snowball stemming algorithm.
func (s *DanishStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rMarkRegions()
	p.Cursor = v1
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v2 := p.Limit - p.Cursor
	s.rMainSuffix()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
	s.rConsonantPair()
	p.Cursor = p.Limit - v3
	v4 := p.Limit - p.Cursor
	s.rOtherSuffix()
	p.Cursor = p.Limit - v4
	v5 := p.Limit - p.Cursor
	s.rUndouble()
	p.Cursor = p.Limit - v5
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*DanishStemmer)(nil)
