// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// DutchStemmer implements the Dutch Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.DutchStemmer
// from Apache Lucene 10.4.0.
type DutchStemmer struct {
	*snowball.SnowballProgram
	iP2     int
	iP1     int
	bEFound bool
}

// NewDutchStemmer creates a new DutchStemmer.
func NewDutchStemmer() *DutchStemmer {
	return &DutchStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var dutchA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 6),
	snowball.NewAmong("á", 0, 1),
	snowball.NewAmong("ä", 0, 1),
	snowball.NewAmong("é", 0, 2),
	snowball.NewAmong("ë", 0, 2),
	snowball.NewAmong("í", 0, 3),
	snowball.NewAmong("ï", 0, 3),
	snowball.NewAmong("ó", 0, 4),
	snowball.NewAmong("ö", 0, 4),
	snowball.NewAmong("ú", 0, 5),
	snowball.NewAmong("ü", 0, 5),
}

var dutchA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("I", 0, 2),
	snowball.NewAmong("Y", 0, 1),
}

var dutchA2 = []*snowball.Among{
	snowball.NewAmong("dd", -1, -1),
	snowball.NewAmong("kk", -1, -1),
	snowball.NewAmong("tt", -1, -1),
}

var dutchA3 = []*snowball.Among{
	snowball.NewAmong("ene", -1, 2),
	snowball.NewAmong("se", -1, 3),
	snowball.NewAmong("en", -1, 2),
	snowball.NewAmong("heden", 2, 1),
	snowball.NewAmong("s", -1, 3),
}

var dutchA4 = []*snowball.Among{
	snowball.NewAmong("end", -1, 1),
	snowball.NewAmong("ig", -1, 2),
	snowball.NewAmong("ing", -1, 1),
	snowball.NewAmong("lijk", -1, 3),
	snowball.NewAmong("baar", -1, 4),
	snowball.NewAmong("bar", -1, 5),
}

var dutchA5 = []*snowball.Among{
	snowball.NewAmong("aa", -1, -1),
	snowball.NewAmong("ee", -1, -1),
	snowball.NewAmong("oo", -1, -1),
	snowball.NewAmong("uu", -1, -1),
}

var dutchGV = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128}
var dutchGVI = []byte{1, 0, 0, 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128}
var dutchGVJ = []byte{17, 67, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128}

func (s *DutchStemmer) rPrelude() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	for {
		v2 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(dutchA0)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("a")
			case 2:
				p.SliceFromStr("e")
			case 3:
				p.SliceFromStr("i")
			case 4:
				p.SliceFromStr("o")
			case 5:
				p.SliceFromStr("u")
			case 6:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v2
		break
	}
	p.Cursor = v1
	v3 := p.Cursor
lab1:
	for {
		p.Bra = p.Cursor
		if !p.EqSStr("y") {
			p.Cursor = v3
			break lab1
		}
		p.Ket = p.Cursor
		p.SliceFromStr("Y")
		break
	}
	for {
		v4 := p.Cursor
	lab2:
		for {
		golab3:
			for {
				v5 := p.Cursor
			lab4:
				for {
					if !p.InGrouping(dutchGV, 97, 232) {
						break lab4
					}
					p.Bra = p.Cursor
				lab5:
					for {
						v6 := p.Cursor
					lab6:
						for {
							if !p.EqSStr("i") {
								break lab6
							}
							p.Ket = p.Cursor
							if !p.InGrouping(dutchGV, 97, 232) {
								break lab6
							}
							p.SliceFromStr("I")
							break lab5
						}
						p.Cursor = v6
						if !p.EqSStr("y") {
							break lab4
						}
						p.Ket = p.Cursor
						p.SliceFromStr("Y")
						break
					}
					p.Cursor = v5
					break golab3
				}
				p.Cursor = v5
				if p.Cursor >= p.Limit {
					break lab2
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v4
		break
	}
	return true
}

func (s *DutchStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	s.iP2 = p.Limit
golab0:
	for {
	lab1:
		for {
			if !p.InGrouping(dutchGV, 97, 232) {
				break lab1
			}
			break golab0
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab2:
	for {
	lab3:
		for {
			if !p.OutGrouping(dutchGV, 97, 232) {
				break lab3
			}
			break golab2
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP1 = p.Cursor
lab4:
	for {
		if s.iP1 >= 3 {
			break lab4
		}
		s.iP1 = 3
		break
	}
golab5:
	for {
	lab6:
		for {
			if !p.InGrouping(dutchGV, 97, 232) {
				break lab6
			}
			break golab5
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab7:
	for {
	lab8:
		for {
			if !p.OutGrouping(dutchGV, 97, 232) {
				break lab8
			}
			break golab7
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP2 = p.Cursor
	return true
}

func (s *DutchStemmer) rPostlude() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(dutchA1)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("y")
			case 2:
				p.SliceFromStr("i")
			case 3:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v1
		break
	}
	return true
}

func (s *DutchStemmer) rR1() bool { return s.iP1 <= s.SnowballProgram.Cursor }
func (s *DutchStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *DutchStemmer) rUndouble() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
	if p.FindAmongB(dutchA2) == 0 {
		return false
	}
	p.Cursor = p.Limit - v1
	p.Ket = p.Cursor
	if p.Cursor <= p.LimitBackward {
		return false
	}
	p.Cursor--
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *DutchStemmer) rEEnding() bool {
	p := s.SnowballProgram
	s.bEFound = false
	p.Ket = p.Cursor
	if !p.EqSBStr("e") {
		return false
	}
	p.Bra = p.Cursor
	if !s.rR1() {
		return false
	}
	v1 := p.Limit - p.Cursor
	if !p.OutGroupingB(dutchGV, 97, 232) {
		return false
	}
	p.Cursor = p.Limit - v1
	p.SliceDel()
	s.bEFound = true
	if !s.rUndouble() {
		return false
	}
	return true
}

func (s *DutchStemmer) rEnEnding() bool {
	p := s.SnowballProgram
	if !s.rR1() {
		return false
	}
	v1 := p.Limit - p.Cursor
	if !p.OutGroupingB(dutchGV, 97, 232) {
		return false
	}
	p.Cursor = p.Limit - v1
lab0:
	for {
		v2 := p.Limit - p.Cursor
	lab1:
		for {
			if !p.EqSBStr("gem") {
				break lab1
			}
			break lab0
		}
		p.Cursor = p.Limit - v2
		break
	}
	p.SliceDel()
	if !s.rUndouble() {
		return false
	}
	return true
}

func (s *DutchStemmer) rStandardSuffix() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(dutchA3)
		if amongVar == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		switch amongVar {
		case 1:
			if !s.rR1() {
				break lab0
			}
			p.SliceFromStr("heid")
		case 2:
			if !s.rEnEnding() {
				break lab0
			}
		case 3:
			if !s.rR1() {
				break lab0
			}
			if !p.OutGroupingB(dutchGVJ, 97, 232) {
				break lab0
			}
			p.SliceDel()
		}
		break
	}
	p.Cursor = p.Limit - v1
	v2 := p.Limit - p.Cursor
	s.rEEnding()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
lab1:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("heid") {
			break lab1
		}
		p.Bra = p.Cursor
		if !s.rR2() {
			break lab1
		}
		v4 := p.Limit - p.Cursor
	lab2:
		for {
			if !p.EqSBStr("c") {
				break lab2
			}
			break lab1
		}
		p.Cursor = p.Limit - v4
		p.SliceDel()
		p.Ket = p.Cursor
		if !p.EqSBStr("en") {
			break lab1
		}
		p.Bra = p.Cursor
		if !s.rEnEnding() {
			break lab1
		}
		break
	}
	p.Cursor = p.Limit - v3
	v5 := p.Limit - p.Cursor
lab3:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(dutchA4)
		if amongVar == 0 {
			break lab3
		}
		p.Bra = p.Cursor
		switch amongVar {
		case 1:
			if !s.rR2() {
				break lab3
			}
			p.SliceDel()
		lab4:
			for {
				v6 := p.Limit - p.Cursor
			lab5:
				for {
					p.Ket = p.Cursor
					if !p.EqSBStr("ig") {
						break lab5
					}
					p.Bra = p.Cursor
					if !s.rR2() {
						break lab5
					}
					v7 := p.Limit - p.Cursor
				lab6:
					for {
						if !p.EqSBStr("e") {
							break lab6
						}
						p.Cursor = p.Limit - v6
						break lab5
					}
					p.Cursor = p.Limit - v7
					p.SliceDel()
					break lab4
				}
				p.Cursor = p.Limit - v6
				if !s.rUndouble() {
					break lab3
				}
				break
			}
		case 2:
			if !s.rR2() {
				break lab3
			}
			v8 := p.Limit - p.Cursor
		lab7:
			for {
				if !p.EqSBStr("e") {
					break lab7
				}
				break lab3
			}
			p.Cursor = p.Limit - v8
			p.SliceDel()
		case 3:
			if !s.rR2() {
				break lab3
			}
			p.SliceDel()
			if !s.rEEnding() {
				break lab3
			}
		case 4:
			if !s.rR2() {
				break lab3
			}
			p.SliceDel()
		case 5:
			if !s.rR2() {
				break lab3
			}
			if !s.bEFound {
				break lab3
			}
			p.SliceDel()
		}
		break
	}
	p.Cursor = p.Limit - v5
	v9 := p.Limit - p.Cursor
lab8:
	for {
		if !p.OutGroupingB(dutchGVI, 73, 232) {
			break lab8
		}
		v10 := p.Limit - p.Cursor
		if p.FindAmongB(dutchA5) == 0 {
			break lab8
		}
		if !p.OutGroupingB(dutchGV, 97, 232) {
			break lab8
		}
		p.Cursor = p.Limit - v10
		p.Ket = p.Cursor
		if p.Cursor <= p.LimitBackward {
			break lab8
		}
		p.Cursor--
		p.Bra = p.Cursor
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v9
	return true
}

// Stem applies the Dutch Snowball stemming algorithm.
func (s *DutchStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rPrelude()
	p.Cursor = v1
	v2 := p.Cursor
	s.rMarkRegions()
	p.Cursor = v2
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	s.rStandardSuffix()
	p.Cursor = p.LimitBackward
	v4 := p.Cursor
	s.rPostlude()
	p.Cursor = v4
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*DutchStemmer)(nil)
