// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// EnglishStemmer implements the English Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.EnglishStemmer
// from Apache Lucene 10.4.0.
type EnglishStemmer struct {
	*snowball.SnowballProgram
	bYFound bool
	iP2     int
	iP1     int
}

// NewEnglishStemmer creates a new EnglishStemmer.
func NewEnglishStemmer() *EnglishStemmer {
	return &EnglishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var englishA0 = []*snowball.Among{
	snowball.NewAmong("arsen", -1, -1),
	snowball.NewAmong("commun", -1, -1),
	snowball.NewAmong("gener", -1, -1),
}

var englishA1 = []*snowball.Among{
	snowball.NewAmong("'", -1, 1),
	snowball.NewAmong("'s'", 0, 1),
	snowball.NewAmong("'s", -1, 1),
}

var englishA2 = []*snowball.Among{
	snowball.NewAmong("ied", -1, 2),
	snowball.NewAmong("s", -1, 3),
	snowball.NewAmong("ies", 1, 2),
	snowball.NewAmong("sses", 1, 1),
	snowball.NewAmong("ss", 1, -1),
	snowball.NewAmong("us", 1, -1),
}

var englishA3 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("bb", 0, 2),
	snowball.NewAmong("dd", 0, 2),
	snowball.NewAmong("ff", 0, 2),
	snowball.NewAmong("gg", 0, 2),
	snowball.NewAmong("bl", 0, 1),
	snowball.NewAmong("mm", 0, 2),
	snowball.NewAmong("nn", 0, 2),
	snowball.NewAmong("pp", 0, 2),
	snowball.NewAmong("rr", 0, 2),
	snowball.NewAmong("at", 0, 1),
	snowball.NewAmong("tt", 0, 2),
	snowball.NewAmong("iz", 0, 1),
}

var englishA4 = []*snowball.Among{
	snowball.NewAmong("ed", -1, 2),
	snowball.NewAmong("eed", 0, 1),
	snowball.NewAmong("ing", -1, 2),
	snowball.NewAmong("edly", -1, 2),
	snowball.NewAmong("eedly", 3, 1),
	snowball.NewAmong("ingly", -1, 2),
}

var englishA5 = []*snowball.Among{
	snowball.NewAmong("anci", -1, 3),
	snowball.NewAmong("enci", -1, 2),
	snowball.NewAmong("ogi", -1, 13),
	snowball.NewAmong("li", -1, 15),
	snowball.NewAmong("bli", 3, 12),
	snowball.NewAmong("abli", 4, 4),
	snowball.NewAmong("alli", 3, 8),
	snowball.NewAmong("fulli", 3, 9),
	snowball.NewAmong("lessli", 3, 14),
	snowball.NewAmong("ousli", 3, 10),
	snowball.NewAmong("entli", 3, 5),
	snowball.NewAmong("aliti", -1, 8),
	snowball.NewAmong("biliti", -1, 12),
	snowball.NewAmong("iviti", -1, 11),
	snowball.NewAmong("tional", -1, 1),
	snowball.NewAmong("ational", 14, 7),
	snowball.NewAmong("alism", -1, 8),
	snowball.NewAmong("ation", -1, 7),
	snowball.NewAmong("ization", 17, 6),
	snowball.NewAmong("izer", -1, 6),
	snowball.NewAmong("ator", -1, 7),
	snowball.NewAmong("iveness", -1, 11),
	snowball.NewAmong("fulness", -1, 9),
	snowball.NewAmong("ousness", -1, 10),
}

var englishA6 = []*snowball.Among{
	snowball.NewAmong("icate", -1, 4),
	snowball.NewAmong("ative", -1, 6),
	snowball.NewAmong("alize", -1, 3),
	snowball.NewAmong("iciti", -1, 4),
	snowball.NewAmong("ical", -1, 4),
	snowball.NewAmong("tional", -1, 1),
	snowball.NewAmong("ational", 5, 2),
	snowball.NewAmong("ful", -1, 5),
	snowball.NewAmong("ness", -1, 5),
}

var englishA7 = []*snowball.Among{
	snowball.NewAmong("ic", -1, 1),
	snowball.NewAmong("ance", -1, 1),
	snowball.NewAmong("ence", -1, 1),
	snowball.NewAmong("able", -1, 1),
	snowball.NewAmong("ible", -1, 1),
	snowball.NewAmong("ate", -1, 1),
	snowball.NewAmong("ive", -1, 1),
	snowball.NewAmong("ize", -1, 1),
	snowball.NewAmong("iti", -1, 1),
	snowball.NewAmong("al", -1, 1),
	snowball.NewAmong("ism", -1, 1),
	snowball.NewAmong("ion", -1, 2),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("ous", -1, 1),
	snowball.NewAmong("ant", -1, 1),
	snowball.NewAmong("ent", -1, 1),
	snowball.NewAmong("ment", 15, 1),
	snowball.NewAmong("ement", 16, 1),
}

var englishA8 = []*snowball.Among{
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("l", -1, 2),
}

var englishA9 = []*snowball.Among{
	snowball.NewAmong("succeed", -1, -1),
	snowball.NewAmong("proceed", -1, -1),
	snowball.NewAmong("exceed", -1, -1),
	snowball.NewAmong("canning", -1, -1),
	snowball.NewAmong("inning", -1, -1),
	snowball.NewAmong("earring", -1, -1),
	snowball.NewAmong("herring", -1, -1),
	snowball.NewAmong("outing", -1, -1),
}

var englishA10 = []*snowball.Among{
	snowball.NewAmong("andes", -1, -1),
	snowball.NewAmong("atlas", -1, -1),
	snowball.NewAmong("bias", -1, -1),
	snowball.NewAmong("cosmos", -1, -1),
	snowball.NewAmong("dying", -1, 3),
	snowball.NewAmong("early", -1, 9),
	snowball.NewAmong("gently", -1, 7),
	snowball.NewAmong("howe", -1, -1),
	snowball.NewAmong("idly", -1, 6),
	snowball.NewAmong("lying", -1, 4),
	snowball.NewAmong("news", -1, -1),
	snowball.NewAmong("only", -1, 10),
	snowball.NewAmong("singly", -1, 11),
	snowball.NewAmong("skies", -1, 2),
	snowball.NewAmong("skis", -1, 1),
	snowball.NewAmong("sky", -1, -1),
	snowball.NewAmong("tying", -1, 5),
	snowball.NewAmong("ugly", -1, 8),
}

var englishGAeo = []byte{17, 64}
var englishGV = []byte{17, 65, 16, 1}
var englishGVWXY = []byte{1, 17, 65, 208, 1}
var englishGValidLI = []byte{55, 141, 2}

func (s *EnglishStemmer) rPrelude() bool {
	p := s.SnowballProgram
	s.bYFound = false
	v1 := p.Cursor
lab0:
	for {
		p.Bra = p.Cursor
		if !p.EqSStr("'") {
			break lab0
		}
		p.Ket = p.Cursor
		p.SliceDel()
		break
	}
	p.Cursor = v1
	v2 := p.Cursor
lab1:
	for {
		p.Bra = p.Cursor
		if !p.EqSStr("y") {
			break lab1
		}
		p.Ket = p.Cursor
		p.SliceFromStr("Y")
		s.bYFound = true
		break
	}
	p.Cursor = v2
	v3 := p.Cursor
	// lab2
	for {
		for {
			v4 := p.Cursor
		lab3:
			for {
			golab4:
				for {
					v5 := p.Cursor
				lab5:
					for {
						if !p.InGrouping(englishGV, 97, 121) {
							break lab5
						}
						p.Bra = p.Cursor
						if !p.EqSStr("y") {
							break lab5
						}
						p.Ket = p.Cursor
						p.Cursor = v5
						break golab4
					}
					p.Cursor = v5
					if p.Cursor >= p.Limit {
						break lab3
					}
					p.Cursor++
				}
				p.SliceFromStr("Y")
				s.bYFound = true
				continue
			}
			p.Cursor = v4
			break
		}
		break
	}
	p.Cursor = v3
	return true
}

func (s *EnglishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
lab0:
	for {
	lab1:
		for {
			v2 := p.Cursor
		lab2:
			for {
				if p.FindAmong(englishA0) == 0 {
					break lab2
				}
				break lab1
			}
			p.Cursor = v2
		golab3:
			for {
				if p.InGrouping(englishGV, 97, 121) {
					break golab3
				}
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
		golab5:
			for {
				if p.OutGrouping(englishGV, 97, 121) {
					break golab5
				}
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			break
		}
		s.iP1 = p.Cursor
	golab7:
		for {
			if p.InGrouping(englishGV, 97, 121) {
				break golab7
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
	golab9:
		for {
			if p.OutGrouping(englishGV, 97, 121) {
				break golab9
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iP2 = p.Cursor
		break
	}
	p.Cursor = v1
	return true
}

func (s *EnglishStemmer) rShortv() bool {
	p := s.SnowballProgram
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			if !p.OutGroupingB(englishGVWXY, 89, 121) {
				break lab1
			}
			if !p.InGroupingB(englishGV, 97, 121) {
				break lab1
			}
			if !p.OutGroupingB(englishGV, 97, 121) {
				break lab1
			}
			break lab0
		}
		p.Cursor = p.Limit - v1
		if !p.OutGroupingB(englishGV, 97, 121) {
			return false
		}
		if !p.InGroupingB(englishGV, 97, 121) {
			return false
		}
		if p.Cursor > p.LimitBackward {
			return false
		}
		break
	}
	return true
}

func (s *EnglishStemmer) rR1() bool { return s.iP1 <= s.SnowballProgram.Cursor }
func (s *EnglishStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *EnglishStemmer) rStep1a() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(englishA1) == 0 {
			p.Cursor = p.Limit - v1
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceDel()
		break
	}
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA2)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		p.SliceFromStr("ss")
	case 2:
	lab1:
		for {
			v2 := p.Limit - p.Cursor
		lab2:
			for {
				c := p.Cursor - 2
				if c < p.LimitBackward {
					break lab2
				}
				p.Cursor = c
				p.SliceFromStr("i")
				break lab1
			}
			p.Cursor = p.Limit - v2
			p.SliceFromStr("ie")
			break
		}
	case 3:
		if p.Cursor <= p.LimitBackward {
			return false
		}
		p.Cursor--
	golab3:
		for {
			if p.InGroupingB(englishGV, 97, 121) {
				break golab3
			}
			if p.Cursor <= p.LimitBackward {
				return false
			}
			p.Cursor--
		}
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rStep1b() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA4)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rR1() {
			return false
		}
		p.SliceFromStr("ee")
	case 2:
		v1 := p.Limit - p.Cursor
	golab0:
		for {
			if p.InGroupingB(englishGV, 97, 121) {
				break golab0
			}
			if p.Cursor <= p.LimitBackward {
				return false
			}
			p.Cursor--
		}
		p.Cursor = p.Limit - v1
		p.SliceDel()
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		v3 := p.Limit - p.Cursor
		amongVar2 := p.FindAmongB(englishA3)
		switch amongVar2 {
		case 1:
			p.SliceFromStr("e")
			return false
		case 2:
			v4 := p.Limit - p.Cursor
		lab2:
			for {
				if !p.InGroupingB(englishGAeo, 97, 111) {
					break lab2
				}
				if p.Cursor > p.LimitBackward {
					break lab2
				}
				return false
			}
			p.Cursor = p.Limit - v4
		case 3:
			if p.Cursor != s.iP1 {
				return false
			}
			v5 := p.Limit - p.Cursor
			if !s.rShortv() {
				return false
			}
			p.Cursor = p.Limit - v5
			p.SliceFromStr("e")
			return false
		}
		p.Cursor = p.Limit - v3
		p.Ket = p.Cursor
		if p.Cursor <= p.LimitBackward {
			return false
		}
		p.Cursor--
		p.Bra = p.Cursor
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rStep1c() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			if !p.EqSBStr("y") {
				break lab1
			}
			break lab0
		}
		p.Cursor = p.Limit - v1
		if !p.EqSBStr("Y") {
			return false
		}
		break
	}
	p.Bra = p.Cursor
	if !p.OutGroupingB(englishGV, 97, 121) {
		return false
	}
lab2:
	for {
		if p.Cursor > p.LimitBackward {
			break lab2
		}
		return false
	}
	p.SliceFromStr("i")
	return true
}

func (s *EnglishStemmer) rStep2() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA5)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceFromStr("tion")
	case 2:
		p.SliceFromStr("ence")
	case 3:
		p.SliceFromStr("ance")
	case 4:
		p.SliceFromStr("able")
	case 5:
		p.SliceFromStr("ent")
	case 6:
		p.SliceFromStr("ize")
	case 7:
		p.SliceFromStr("ate")
	case 8:
		p.SliceFromStr("al")
	case 9:
		p.SliceFromStr("ful")
	case 10:
		p.SliceFromStr("ous")
	case 11:
		p.SliceFromStr("ive")
	case 12:
		p.SliceFromStr("ble")
	case 13:
		if !p.EqSBStr("l") {
			return false
		}
		p.SliceFromStr("og")
	case 14:
		p.SliceFromStr("less")
	case 15:
		if !p.InGroupingB(englishGValidLI, 99, 116) {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rStep3() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA6)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceFromStr("tion")
	case 2:
		p.SliceFromStr("ate")
	case 3:
		p.SliceFromStr("al")
	case 4:
		p.SliceFromStr("ic")
	case 5:
		p.SliceDel()
	case 6:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rStep4() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA7)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	if !s.rR2() {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceDel()
	case 2:
	lab0:
		for {
			v1 := p.Limit - p.Cursor
		lab1:
			for {
				if !p.EqSBStr("s") {
					break lab1
				}
				break lab0
			}
			p.Cursor = p.Limit - v1
			if !p.EqSBStr("t") {
				return false
			}
			break
		}
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rStep5() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(englishA8)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
	lab0:
		for {
			v1 := p.Limit - p.Cursor
		lab1:
			for {
				if !s.rR2() {
					break lab1
				}
				break lab0
			}
			p.Cursor = p.Limit - v1
			if !s.rR1() {
				return false
			}
			v2 := p.Limit - p.Cursor
		lab2:
			for {
				if !s.rShortv() {
					break lab2
				}
				return false
			}
			p.Cursor = p.Limit - v2
			break
		}
		p.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		if !p.EqSBStr("l") {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *EnglishStemmer) rException2() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(englishA9) == 0 {
		return false
	}
	p.Bra = p.Cursor
	if p.Cursor > p.LimitBackward {
		return false
	}
	return true
}

func (s *EnglishStemmer) rException1() bool {
	p := s.SnowballProgram
	p.Bra = p.Cursor
	amongVar := p.FindAmong(englishA10)
	if amongVar == 0 {
		return false
	}
	p.Ket = p.Cursor
	if p.Cursor < p.Limit {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceFromStr("ski")
	case 2:
		p.SliceFromStr("sky")
	case 3:
		p.SliceFromStr("die")
	case 4:
		p.SliceFromStr("lie")
	case 5:
		p.SliceFromStr("tie")
	case 6:
		p.SliceFromStr("idl")
	case 7:
		p.SliceFromStr("gentl")
	case 8:
		p.SliceFromStr("ugli")
	case 9:
		p.SliceFromStr("earli")
	case 10:
		p.SliceFromStr("onli")
	case 11:
		p.SliceFromStr("singl")
	}
	return true
}

func (s *EnglishStemmer) rPostlude() bool {
	p := s.SnowballProgram
	if !s.bYFound {
		return false
	}
	for {
		v1 := p.Cursor
	lab0:
		for {
		golab1:
			for {
				v2 := p.Cursor
			lab2:
				for {
					p.Bra = p.Cursor
					if !p.EqSStr("Y") {
						break lab2
					}
					p.Ket = p.Cursor
					p.Cursor = v2
					break golab1
				}
				p.Cursor = v2
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			p.SliceFromStr("y")
			continue
		}
		p.Cursor = v1
		break
	}
	return true
}

// Stem applies the English Snowball stemming algorithm.
func (s *EnglishStemmer) Stem() bool {
	p := s.SnowballProgram
lab0:
	for {
		v1 := p.Cursor
	lab1:
		for {
			if !s.rException1() {
				break lab1
			}
			break lab0
		}
		p.Cursor = v1
	lab2:
		for {
			v2 := p.Cursor
		lab3:
			for {
				c := p.Cursor + 3
				if c > p.Limit {
					break lab3
				}
				p.Cursor = c
				break lab2
			}
			p.Cursor = v2
			break lab0
		}
		p.Cursor = v1
		s.rPrelude()
		s.rMarkRegions()
		p.LimitBackward = p.Cursor
		p.Cursor = p.Limit
		v5 := p.Limit - p.Cursor
		s.rStep1a()
		p.Cursor = p.Limit - v5
	lab4:
		for {
			v6 := p.Limit - p.Cursor
		lab5:
			for {
				if !s.rException2() {
					break lab5
				}
				break lab4
			}
			p.Cursor = p.Limit - v6
			v7 := p.Limit - p.Cursor
			s.rStep1b()
			p.Cursor = p.Limit - v7
			v8 := p.Limit - p.Cursor
			s.rStep1c()
			p.Cursor = p.Limit - v8
			v9 := p.Limit - p.Cursor
			s.rStep2()
			p.Cursor = p.Limit - v9
			v10 := p.Limit - p.Cursor
			s.rStep3()
			p.Cursor = p.Limit - v10
			v11 := p.Limit - p.Cursor
			s.rStep4()
			p.Cursor = p.Limit - v11
			v12 := p.Limit - p.Cursor
			s.rStep5()
			p.Cursor = p.Limit - v12
			break
		}
		p.Cursor = p.LimitBackward
		v13 := p.Cursor
		s.rPostlude()
		p.Cursor = v13
		break
	}
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*EnglishStemmer)(nil)
