// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// EstonianStemmer implements the Estonian Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.EstonianStemmer
// from Apache Lucene 10.4.0.
type EstonianStemmer struct {
	*snowball.SnowballProgram
	iP1 int
}

// NewEstonianStemmer constructs an EstonianStemmer.
func NewEstonianStemmer() *EstonianStemmer {
	return &EstonianStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*EstonianStemmer)(nil)

var estonianA0 = []*snowball.Among{
	snowball.NewAmong("gi", -1, 1),
	snowball.NewAmong("ki", -1, 2),
}

var estonianA1 = []*snowball.Among{
	snowball.NewAmong("da", -1, 3),
	snowball.NewAmong("mata", -1, 1),
	snowball.NewAmong("b", -1, 3),
	snowball.NewAmong("ksid", -1, 1),
	snowball.NewAmong("nuksid", 3, 1),
	snowball.NewAmong("me", -1, 3),
	snowball.NewAmong("sime", 5, 1),
	snowball.NewAmong("ksime", 6, 1),
	snowball.NewAmong("nuksime", 7, 1),
	snowball.NewAmong("akse", -1, 2),
	snowball.NewAmong("dakse", 9, 1),
	snowball.NewAmong("takse", 9, 1),
	snowball.NewAmong("site", -1, 1),
	snowball.NewAmong("ksite", 12, 1),
	snowball.NewAmong("nuksite", 13, 1),
	snowball.NewAmong("n", -1, 3),
	snowball.NewAmong("sin", 15, 1),
	snowball.NewAmong("ksin", 16, 1),
	snowball.NewAmong("nuksin", 17, 1),
	snowball.NewAmong("daks", -1, 1),
	snowball.NewAmong("taks", -1, 1),
}

var estonianA2 = []*snowball.Among{
	snowball.NewAmong("aa", -1, -1),
	snowball.NewAmong("ee", -1, -1),
	snowball.NewAmong("ii", -1, -1),
	snowball.NewAmong("oo", -1, -1),
	snowball.NewAmong("uu", -1, -1),
	snowball.NewAmong("ää", -1, -1),
	snowball.NewAmong("õõ", -1, -1),
	snowball.NewAmong("öö", -1, -1),
	snowball.NewAmong("üü", -1, -1),
}

var estonianA3 = []*snowball.Among{
	snowball.NewAmong("i", -1, 1),
}

var estonianA4 = []*snowball.Among{
	snowball.NewAmong("lane", -1, 1),
	snowball.NewAmong("line", -1, 3),
	snowball.NewAmong("mine", -1, 2),
	snowball.NewAmong("lasse", -1, 1),
	snowball.NewAmong("lisse", -1, 3),
	snowball.NewAmong("misse", -1, 2),
	snowball.NewAmong("lasi", -1, 1),
	snowball.NewAmong("lisi", -1, 3),
	snowball.NewAmong("misi", -1, 2),
	snowball.NewAmong("last", -1, 1),
	snowball.NewAmong("list", -1, 3),
	snowball.NewAmong("mist", -1, 2),
}

var estonianA5 = []*snowball.Among{
	snowball.NewAmong("ga", -1, 1),
	snowball.NewAmong("ta", -1, 1),
	snowball.NewAmong("le", -1, 1),
	snowball.NewAmong("sse", -1, 1),
	snowball.NewAmong("l", -1, 1),
	snowball.NewAmong("s", -1, 1),
	snowball.NewAmong("ks", 5, 1),
	snowball.NewAmong("t", -1, 2),
	snowball.NewAmong("lt", 7, 1),
	snowball.NewAmong("st", 7, 1),
}

var estonianA6 = []*snowball.Among{
	snowball.NewAmong("", -1, 2),
	snowball.NewAmong("las", 0, 1),
	snowball.NewAmong("lis", 0, 1),
	snowball.NewAmong("mis", 0, 1),
	snowball.NewAmong("t", 0, -1),
}

var estonianA7 = []*snowball.Among{
	snowball.NewAmong("d", -1, 4),
	snowball.NewAmong("sid", 0, 2),
	snowball.NewAmong("de", -1, 4),
	snowball.NewAmong("ikkude", 2, 1),
	snowball.NewAmong("ike", -1, 1),
	snowball.NewAmong("ikke", -1, 1),
	snowball.NewAmong("te", -1, 3),
}

var estonianA8 = []*snowball.Among{
	snowball.NewAmong("va", -1, -1),
	snowball.NewAmong("du", -1, -1),
	snowball.NewAmong("nu", -1, -1),
	snowball.NewAmong("tu", -1, -1),
}

var estonianA9 = []*snowball.Among{
	snowball.NewAmong("kk", -1, 1),
	snowball.NewAmong("pp", -1, 2),
	snowball.NewAmong("tt", -1, 3),
}

var estonianA10 = []*snowball.Among{
	snowball.NewAmong("ma", -1, 2),
	snowball.NewAmong("mai", -1, 1),
	snowball.NewAmong("m", -1, 1),
}

var estonianA11 = []*snowball.Among{
	snowball.NewAmong("joob", -1, 1),
	snowball.NewAmong("jood", -1, 1),
	snowball.NewAmong("joodakse", 1, 1),
	snowball.NewAmong("jooma", -1, 1),
	snowball.NewAmong("joomata", 3, 1),
	snowball.NewAmong("joome", -1, 1),
	snowball.NewAmong("joon", -1, 1),
	snowball.NewAmong("joote", -1, 1),
	snowball.NewAmong("joovad", -1, 1),
	snowball.NewAmong("juua", -1, 1),
	snowball.NewAmong("juuakse", 9, 1),
	snowball.NewAmong("jäi", -1, 12),
	snowball.NewAmong("jäid", 11, 12),
	snowball.NewAmong("jäime", 11, 12),
	snowball.NewAmong("jäin", 11, 12),
	snowball.NewAmong("jäite", 11, 12),
	snowball.NewAmong("jääb", -1, 12),
	snowball.NewAmong("jääd", -1, 12),
	snowball.NewAmong("jääda", 17, 12),
	snowball.NewAmong("jäädakse", 18, 12),
	snowball.NewAmong("jäädi", 17, 12),
	snowball.NewAmong("jääks", -1, 12),
	snowball.NewAmong("jääksid", 21, 12),
	snowball.NewAmong("jääksime", 21, 12),
	snowball.NewAmong("jääksin", 21, 12),
	snowball.NewAmong("jääksite", 21, 12),
	snowball.NewAmong("jääma", -1, 12),
	snowball.NewAmong("jäämata", 26, 12),
	snowball.NewAmong("jääme", -1, 12),
	snowball.NewAmong("jään", -1, 12),
	snowball.NewAmong("jääte", -1, 12),
	snowball.NewAmong("jäävad", -1, 12),
	snowball.NewAmong("jõi", -1, 1),
	snowball.NewAmong("jõid", 32, 1),
	snowball.NewAmong("jõime", 32, 1),
	snowball.NewAmong("jõin", 32, 1),
	snowball.NewAmong("jõite", 32, 1),
	snowball.NewAmong("keeb", -1, 4),
	snowball.NewAmong("keed", -1, 4),
	snowball.NewAmong("keedakse", 38, 4),
	snowball.NewAmong("keeks", -1, 4),
	snowball.NewAmong("keeksid", 40, 4),
	snowball.NewAmong("keeksime", 40, 4),
	snowball.NewAmong("keeksin", 40, 4),
	snowball.NewAmong("keeksite", 40, 4),
	snowball.NewAmong("keema", -1, 4),
	snowball.NewAmong("keemata", 45, 4),
	snowball.NewAmong("keeme", -1, 4),
	snowball.NewAmong("keen", -1, 4),
	snowball.NewAmong("kees", -1, 4),
	snowball.NewAmong("keeta", -1, 4),
	snowball.NewAmong("keete", -1, 4),
	snowball.NewAmong("keevad", -1, 4),
	snowball.NewAmong("käia", -1, 8),
	snowball.NewAmong("käiakse", 53, 8),
	snowball.NewAmong("käib", -1, 8),
	snowball.NewAmong("käid", -1, 8),
	snowball.NewAmong("käidi", 56, 8),
	snowball.NewAmong("käiks", -1, 8),
	snowball.NewAmong("käiksid", 58, 8),
	snowball.NewAmong("käiksime", 58, 8),
	snowball.NewAmong("käiksin", 58, 8),
	snowball.NewAmong("käiksite", 58, 8),
	snowball.NewAmong("käima", -1, 8),
	snowball.NewAmong("käimata", 63, 8),
	snowball.NewAmong("käime", -1, 8),
	snowball.NewAmong("käin", -1, 8),
	snowball.NewAmong("käis", -1, 8),
	snowball.NewAmong("käite", -1, 8),
	snowball.NewAmong("käivad", -1, 8),
	snowball.NewAmong("laob", -1, 16),
	snowball.NewAmong("laod", -1, 16),
	snowball.NewAmong("laoks", -1, 16),
	snowball.NewAmong("laoksid", 72, 16),
	snowball.NewAmong("laoksime", 72, 16),
	snowball.NewAmong("laoksin", 72, 16),
	snowball.NewAmong("laoksite", 72, 16),
	snowball.NewAmong("laome", -1, 16),
	snowball.NewAmong("laon", -1, 16),
	snowball.NewAmong("laote", -1, 16),
	snowball.NewAmong("laovad", -1, 16),
	snowball.NewAmong("loeb", -1, 14),
	snowball.NewAmong("loed", -1, 14),
	snowball.NewAmong("loeks", -1, 14),
	snowball.NewAmong("loeksid", 83, 14),
	snowball.NewAmong("loeksime", 83, 14),
	snowball.NewAmong("loeksin", 83, 14),
	snowball.NewAmong("loeksite", 83, 14),
	snowball.NewAmong("loeme", -1, 14),
	snowball.NewAmong("loen", -1, 14),
	snowball.NewAmong("loete", -1, 14),
	snowball.NewAmong("loevad", -1, 14),
	snowball.NewAmong("loob", -1, 7),
	snowball.NewAmong("lood", -1, 7),
	snowball.NewAmong("loodi", 93, 7),
	snowball.NewAmong("looks", -1, 7),
	snowball.NewAmong("looksid", 95, 7),
	snowball.NewAmong("looksime", 95, 7),
	snowball.NewAmong("looksin", 95, 7),
	snowball.NewAmong("looksite", 95, 7),
	snowball.NewAmong("looma", -1, 7),
	snowball.NewAmong("loomata", 100, 7),
	snowball.NewAmong("loome", -1, 7),
	snowball.NewAmong("loon", -1, 7),
	snowball.NewAmong("loote", -1, 7),
	snowball.NewAmong("loovad", -1, 7),
	snowball.NewAmong("luua", -1, 7),
	snowball.NewAmong("luuakse", 106, 7),
	snowball.NewAmong("lõi", -1, 6),
	snowball.NewAmong("lõid", 108, 6),
	snowball.NewAmong("lõime", 108, 6),
	snowball.NewAmong("lõin", 108, 6),
	snowball.NewAmong("lõite", 108, 6),
	snowball.NewAmong("lööb", -1, 5),
	snowball.NewAmong("lööd", -1, 5),
	snowball.NewAmong("löödakse", 114, 5),
	snowball.NewAmong("löödi", 114, 5),
	snowball.NewAmong("lööks", -1, 5),
	snowball.NewAmong("lööksid", 117, 5),
	snowball.NewAmong("lööksime", 117, 5),
	snowball.NewAmong("lööksin", 117, 5),
	snowball.NewAmong("lööksite", 117, 5),
	snowball.NewAmong("lööma", -1, 5),
	snowball.NewAmong("löömata", 122, 5),
	snowball.NewAmong("lööme", -1, 5),
	snowball.NewAmong("löön", -1, 5),
	snowball.NewAmong("lööte", -1, 5),
	snowball.NewAmong("löövad", -1, 5),
	snowball.NewAmong("lüüa", -1, 5),
	snowball.NewAmong("lüüakse", 128, 5),
	snowball.NewAmong("müüa", -1, 13),
	snowball.NewAmong("müüakse", 130, 13),
	snowball.NewAmong("müüb", -1, 13),
	snowball.NewAmong("müüd", -1, 13),
	snowball.NewAmong("müüdi", 133, 13),
	snowball.NewAmong("müüks", -1, 13),
	snowball.NewAmong("müüksid", 135, 13),
	snowball.NewAmong("müüksime", 135, 13),
	snowball.NewAmong("müüksin", 135, 13),
	snowball.NewAmong("müüksite", 135, 13),
	snowball.NewAmong("müüma", -1, 13),
	snowball.NewAmong("müümata", 140, 13),
	snowball.NewAmong("müüme", -1, 13),
	snowball.NewAmong("müün", -1, 13),
	snowball.NewAmong("müüs", -1, 13),
	snowball.NewAmong("müüte", -1, 13),
	snowball.NewAmong("müüvad", -1, 13),
	snowball.NewAmong("näeb", -1, 18),
	snowball.NewAmong("näed", -1, 18),
	snowball.NewAmong("näeks", -1, 18),
	snowball.NewAmong("näeksid", 149, 18),
	snowball.NewAmong("näeksime", 149, 18),
	snowball.NewAmong("näeksin", 149, 18),
	snowball.NewAmong("näeksite", 149, 18),
	snowball.NewAmong("näeme", -1, 18),
	snowball.NewAmong("näen", -1, 18),
	snowball.NewAmong("näete", -1, 18),
	snowball.NewAmong("näevad", -1, 18),
	snowball.NewAmong("nägema", -1, 18),
	snowball.NewAmong("nägemata", 158, 18),
	snowball.NewAmong("näha", -1, 18),
	snowball.NewAmong("nähakse", 160, 18),
	snowball.NewAmong("nähti", -1, 18),
	snowball.NewAmong("põeb", -1, 15),
	snowball.NewAmong("põed", -1, 15),
	snowball.NewAmong("põeks", -1, 15),
	snowball.NewAmong("põeksid", 165, 15),
	snowball.NewAmong("põeksime", 165, 15),
	snowball.NewAmong("põeksin", 165, 15),
	snowball.NewAmong("põeksite", 165, 15),
	snowball.NewAmong("põeme", -1, 15),
	snowball.NewAmong("põen", -1, 15),
	snowball.NewAmong("põete", -1, 15),
	snowball.NewAmong("põevad", -1, 15),
	snowball.NewAmong("saab", -1, 2),
	snowball.NewAmong("saad", -1, 2),
	snowball.NewAmong("saada", 175, 2),
	snowball.NewAmong("saadakse", 176, 2),
	snowball.NewAmong("saadi", 175, 2),
	snowball.NewAmong("saaks", -1, 2),
	snowball.NewAmong("saaksid", 179, 2),
	snowball.NewAmong("saaksime", 179, 2),
	snowball.NewAmong("saaksin", 179, 2),
	snowball.NewAmong("saaksite", 179, 2),
	snowball.NewAmong("saama", -1, 2),
	snowball.NewAmong("saamata", 184, 2),
	snowball.NewAmong("saame", -1, 2),
	snowball.NewAmong("saan", -1, 2),
	snowball.NewAmong("saate", -1, 2),
	snowball.NewAmong("saavad", -1, 2),
	snowball.NewAmong("sai", -1, 2),
	snowball.NewAmong("said", 190, 2),
	snowball.NewAmong("saime", 190, 2),
	snowball.NewAmong("sain", 190, 2),
	snowball.NewAmong("saite", 190, 2),
	snowball.NewAmong("sõi", -1, 9),
	snowball.NewAmong("sõid", 195, 9),
	snowball.NewAmong("sõime", 195, 9),
	snowball.NewAmong("sõin", 195, 9),
	snowball.NewAmong("sõite", 195, 9),
	snowball.NewAmong("sööb", -1, 9),
	snowball.NewAmong("sööd", -1, 9),
	snowball.NewAmong("söödakse", 201, 9),
	snowball.NewAmong("söödi", 201, 9),
	snowball.NewAmong("sööks", -1, 9),
	snowball.NewAmong("sööksid", 204, 9),
	snowball.NewAmong("sööksime", 204, 9),
	snowball.NewAmong("sööksin", 204, 9),
	snowball.NewAmong("sööksite", 204, 9),
	snowball.NewAmong("sööma", -1, 9),
	snowball.NewAmong("söömata", 209, 9),
	snowball.NewAmong("sööme", -1, 9),
	snowball.NewAmong("söön", -1, 9),
	snowball.NewAmong("sööte", -1, 9),
	snowball.NewAmong("söövad", -1, 9),
	snowball.NewAmong("süüa", -1, 9),
	snowball.NewAmong("süüakse", 215, 9),
	snowball.NewAmong("teeb", -1, 17),
	snowball.NewAmong("teed", -1, 17),
	snowball.NewAmong("teeks", -1, 17),
	snowball.NewAmong("teeksid", 219, 17),
	snowball.NewAmong("teeksime", 219, 17),
	snowball.NewAmong("teeksin", 219, 17),
	snowball.NewAmong("teeksite", 219, 17),
	snowball.NewAmong("teeme", -1, 17),
	snowball.NewAmong("teen", -1, 17),
	snowball.NewAmong("teete", -1, 17),
	snowball.NewAmong("teevad", -1, 17),
	snowball.NewAmong("tegema", -1, 17),
	snowball.NewAmong("tegemata", 228, 17),
	snowball.NewAmong("teha", -1, 17),
	snowball.NewAmong("tehakse", 230, 17),
	snowball.NewAmong("tehti", -1, 17),
	snowball.NewAmong("toob", -1, 10),
	snowball.NewAmong("tood", -1, 10),
	snowball.NewAmong("toodi", 234, 10),
	snowball.NewAmong("tooks", -1, 10),
	snowball.NewAmong("tooksid", 236, 10),
	snowball.NewAmong("tooksime", 236, 10),
	snowball.NewAmong("tooksin", 236, 10),
	snowball.NewAmong("tooksite", 236, 10),
	snowball.NewAmong("tooma", -1, 10),
	snowball.NewAmong("toomata", 241, 10),
	snowball.NewAmong("toome", -1, 10),
	snowball.NewAmong("toon", -1, 10),
	snowball.NewAmong("toote", -1, 10),
	snowball.NewAmong("toovad", -1, 10),
	snowball.NewAmong("tuua", -1, 10),
	snowball.NewAmong("tuuakse", 247, 10),
	snowball.NewAmong("tõi", -1, 10),
	snowball.NewAmong("tõid", 249, 10),
	snowball.NewAmong("tõime", 249, 10),
	snowball.NewAmong("tõin", 249, 10),
	snowball.NewAmong("tõite", 249, 10),
	snowball.NewAmong("viia", -1, 3),
	snowball.NewAmong("viiakse", 254, 3),
	snowball.NewAmong("viib", -1, 3),
	snowball.NewAmong("viid", -1, 3),
	snowball.NewAmong("viidi", 257, 3),
	snowball.NewAmong("viiks", -1, 3),
	snowball.NewAmong("viiksid", 259, 3),
	snowball.NewAmong("viiksime", 259, 3),
	snowball.NewAmong("viiksin", 259, 3),
	snowball.NewAmong("viiksite", 259, 3),
	snowball.NewAmong("viima", -1, 3),
	snowball.NewAmong("viimata", 264, 3),
	snowball.NewAmong("viime", -1, 3),
	snowball.NewAmong("viin", -1, 3),
	snowball.NewAmong("viisime", -1, 3),
	snowball.NewAmong("viisin", -1, 3),
	snowball.NewAmong("viisite", -1, 3),
	snowball.NewAmong("viite", -1, 3),
	snowball.NewAmong("viivad", -1, 3),
	snowball.NewAmong("võib", -1, 11),
	snowball.NewAmong("võid", -1, 11),
	snowball.NewAmong("võida", 274, 11),
	snowball.NewAmong("võidakse", 275, 11),
	snowball.NewAmong("võidi", 274, 11),
	snowball.NewAmong("võiks", -1, 11),
	snowball.NewAmong("võiksid", 278, 11),
	snowball.NewAmong("võiksime", 278, 11),
	snowball.NewAmong("võiksin", 278, 11),
	snowball.NewAmong("võiksite", 278, 11),
	snowball.NewAmong("võima", -1, 11),
	snowball.NewAmong("võimata", 283, 11),
	snowball.NewAmong("võime", -1, 11),
	snowball.NewAmong("võin", -1, 11),
	snowball.NewAmong("võis", -1, 11),
	snowball.NewAmong("võite", -1, 11),
	snowball.NewAmong("võivad", -1, 11),
}

// estonianGV1: vowels (a e i o u ä õ ö ü)
var estonianGV1 = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 48, 8}

// estonianGRV: reduced vowels (a e i o u)
var estonianGRV = []byte{17, 65, 16}

// estonianGKI: consonants valid before -ki
var estonianGKI = []byte{
	117, 66, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	128, 0, 0, 0, 16,
}

// estonianGGI: consonants valid before -gi
var estonianGGI = []byte{21, 123, 243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 48, 8}

func (s *EstonianStemmer) rMarkRegions() bool {
	s.iP1 = s.Limit
golab0:
	for {
		v1 := s.Cursor
		lab1: for {
			if !s.InGrouping(estonianGV1, 97, 252) {
				break lab1
			}
			s.Cursor = v1
			break golab0
		}
		s.Cursor = v1
		if s.Cursor >= s.Limit {
			return false
		}
		s.Cursor++
	}
golab2:
	for {
		lab3: for {
			if !s.OutGrouping(estonianGV1, 97, 252) {
				break lab3
			}
			break golab2
		}
		if s.Cursor >= s.Limit {
			return false
		}
		s.Cursor++
	}
	s.iP1 = s.Cursor
	return true
}

func (s *EstonianStemmer) rLONGV() bool {
	return s.FindAmongB(estonianA2) != 0
}

func (s *EstonianStemmer) rEmphasis() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA0)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	v3 := s.Limit - s.Cursor
	c := s.Cursor - 4
	if c < s.LimitBackward {
		return false
	}
	s.Cursor = c
	s.Cursor = s.Limit - v3
	switch amongVar {
	case 1:
		v4 := s.Limit - s.Cursor
		if !s.InGroupingB(estonianGGI, 97, 252) {
			return false
		}
		s.Cursor = s.Limit - v4
		v5 := s.Limit - s.Cursor
		lab0: for {
			if !s.rLONGV() {
				break lab0
			}
			return false
		}
		s.Cursor = s.Limit - v5
		s.SliceDel()
	case 2:
		if !s.InGroupingB(estonianGKI, 98, 382) {
			return false
		}
		s.SliceDel()
	}
	return true
}

func (s *EstonianStemmer) rVerb() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA1)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("a")
	case 3:
		if !s.InGroupingB(estonianGV1, 97, 252) {
			return false
		}
		s.SliceDel()
	}
	return true
}

func (s *EstonianStemmer) rIPlural() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	if s.FindAmongB(estonianA3) == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	if !s.InGroupingB(estonianGRV, 97, 117) {
		return false
	}
	s.SliceDel()
	return true
}

func (s *EstonianStemmer) rSpecialNounEndings() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA4)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	switch amongVar {
	case 1:
		s.SliceFromStr("lase")
	case 2:
		s.SliceFromStr("mise")
	case 3:
		s.SliceFromStr("lise")
	}
	return true
}

func (s *EstonianStemmer) rCaseEnding() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA5)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	switch amongVar {
	case 1:
		lab0: for {
			v3 := s.Limit - s.Cursor
			lab1: for {
				if !s.InGroupingB(estonianGRV, 97, 117) {
					break lab1
				}
				break lab0
			}
			s.Cursor = s.Limit - v3
			if !s.rLONGV() {
				return false
			}
			break lab0
		}
	case 2:
		v4 := s.Limit - s.Cursor
		c := s.Cursor - 4
		if c < s.LimitBackward {
			return false
		}
		s.Cursor = c
		s.Cursor = s.Limit - v4
	}
	s.SliceDel()
	return true
}

func (s *EstonianStemmer) rPluralThreeFirstCases() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA7)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	switch amongVar {
	case 1:
		s.SliceFromStr("iku")
	case 2:
		v3 := s.Limit - s.Cursor
		lab0: for {
			if !s.rLONGV() {
				break lab0
			}
			return false
		}
		s.Cursor = s.Limit - v3
		s.SliceDel()
	case 3:
		lab1: for {
			v4 := s.Limit - s.Cursor
			lab2: for {
				v5 := s.Limit - s.Cursor
				c := s.Cursor - 4
				if c < s.LimitBackward {
					break lab2
				}
				s.Cursor = c
				s.Cursor = s.Limit - v5
				av := s.FindAmongB(estonianA6)
				switch av {
				case 1:
					s.SliceFromStr("e")
				case 2:
					s.SliceDel()
				}
				break lab1
			}
			s.Cursor = s.Limit - v4
			s.SliceFromStr("t")
			break lab1
		}
	case 4:
		lab3: for {
			v6 := s.Limit - s.Cursor
			lab4: for {
				if !s.InGroupingB(estonianGRV, 97, 117) {
					break lab4
				}
				break lab3
			}
			s.Cursor = s.Limit - v6
			if !s.rLONGV() {
				return false
			}
			break lab3
		}
		s.SliceDel()
	}
	return true
}

func (s *EstonianStemmer) rNu() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	if s.FindAmongB(estonianA8) == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	s.SliceDel()
	return true
}

func (s *EstonianStemmer) rUndoubleKpt() bool {
	if !s.InGroupingB(estonianGV1, 97, 252) {
		return false
	}
	if s.iP1 > s.Cursor {
		return false
	}
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA9)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		s.SliceFromStr("k")
	case 2:
		s.SliceFromStr("p")
	case 3:
		s.SliceFromStr("t")
	}
	return true
}

func (s *EstonianStemmer) rDegrees() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(estonianA10)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	switch amongVar {
	case 1:
		if !s.InGroupingB(estonianGRV, 97, 117) {
			return false
		}
		s.SliceDel()
	case 2:
		s.SliceDel()
	}
	return true
}

func (s *EstonianStemmer) rSubstantive() bool {
	v1 := s.Limit - s.Cursor
	s.rSpecialNounEndings()
	s.Cursor = s.Limit - v1

	v2 := s.Limit - s.Cursor
	s.rCaseEnding()
	s.Cursor = s.Limit - v2

	v3 := s.Limit - s.Cursor
	s.rPluralThreeFirstCases()
	s.Cursor = s.Limit - v3

	v4 := s.Limit - s.Cursor
	s.rDegrees()
	s.Cursor = s.Limit - v4

	v5 := s.Limit - s.Cursor
	s.rIPlural()
	s.Cursor = s.Limit - v5

	v6 := s.Limit - s.Cursor
	s.rNu()
	s.Cursor = s.Limit - v6

	return true
}

func (s *EstonianStemmer) rVerbExceptions() bool {
	s.Bra = s.Cursor
	amongVar := s.FindAmong(estonianA11)
	if amongVar == 0 {
		return false
	}
	s.Ket = s.Cursor
	if s.Cursor < s.Limit {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceFromStr("joo")
	case 2:
		s.SliceFromStr("saa")
	case 3:
		s.SliceFromStr("viima")
	case 4:
		s.SliceFromStr("keesi")
	case 5:
		s.SliceFromStr("löö")
	case 6:
		s.SliceFromStr("lõi")
	case 7:
		s.SliceFromStr("loo")
	case 8:
		s.SliceFromStr("käisi")
	case 9:
		s.SliceFromStr("söö")
	case 10:
		s.SliceFromStr("too")
	case 11:
		s.SliceFromStr("võisi")
	case 12:
		s.SliceFromStr("jääma")
	case 13:
		s.SliceFromStr("müüsi")
	case 14:
		s.SliceFromStr("luge")
	case 15:
		s.SliceFromStr("põde")
	case 16:
		s.SliceFromStr("ladu")
	case 17:
		s.SliceFromStr("tegi")
	case 18:
		s.SliceFromStr("nägi")
	}
	return true
}

// Stem applies the Estonian stemming algorithm to the current word.
func (s *EstonianStemmer) Stem() bool {
	v1 := s.Cursor
	lab0: for {
		if !s.rVerbExceptions() {
			break lab0
		}
		return false
	}
	s.Cursor = v1

	v2 := s.Cursor
	s.rMarkRegions()
	s.Cursor = v2
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit

	v3 := s.Limit - s.Cursor
	s.rEmphasis()
	s.Cursor = s.Limit - v3

	v4 := s.Limit - s.Cursor
	lab1: for {
		lab2: for {
			v5 := s.Limit - s.Cursor
			lab3: for {
				if !s.rVerb() {
					break lab3
				}
				break lab2
			}
			s.Cursor = s.Limit - v5
			s.rSubstantive()
			break lab2
		}
		break lab1
	}
	s.Cursor = s.Limit - v4

	v6 := s.Limit - s.Cursor
	s.rUndoubleKpt()
	s.Cursor = s.Limit - v6

	s.Cursor = s.LimitBackward
	return true
}
