// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// FinnishStemmer implements the Finnish Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.FinnishStemmer
// from Apache Lucene 10.4.0.
type FinnishStemmer struct {
	*snowball.SnowballProgram
	bEndingRemoved bool
	sX             []rune
	iP2            int
	iP1            int
}

// NewFinnishStemmer creates a new FinnishStemmer.
func NewFinnishStemmer() *FinnishStemmer {
	return &FinnishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var finnishA0 = []*snowball.Among{
	snowball.NewAmong("pa", -1, 1),
	snowball.NewAmong("sti", -1, 2),
	snowball.NewAmong("kaan", -1, 1),
	snowball.NewAmong("han", -1, 1),
	snowball.NewAmong("kin", -1, 1),
	snowball.NewAmong("hän", -1, 1),
	snowball.NewAmong("kään", -1, 1),
	snowball.NewAmong("ko", -1, 1),
	snowball.NewAmong("pä", -1, 1),
	snowball.NewAmong("kö", -1, 1),
}

var finnishA1 = []*snowball.Among{
	snowball.NewAmong("lla", -1, -1),
	snowball.NewAmong("na", -1, -1),
	snowball.NewAmong("ssa", -1, -1),
	snowball.NewAmong("ta", -1, -1),
	snowball.NewAmong("lta", 3, -1),
	snowball.NewAmong("sta", 3, -1),
}

var finnishA2 = []*snowball.Among{
	snowball.NewAmong("llä", -1, -1),
	snowball.NewAmong("nä", -1, -1),
	snowball.NewAmong("ssä", -1, -1),
	snowball.NewAmong("tä", -1, -1),
	snowball.NewAmong("ltä", 3, -1),
	snowball.NewAmong("stä", 3, -1),
}

var finnishA3 = []*snowball.Among{
	snowball.NewAmong("lle", -1, -1),
	snowball.NewAmong("ine", -1, -1),
}

var finnishA4 = []*snowball.Among{
	snowball.NewAmong("nsa", -1, 3),
	snowball.NewAmong("mme", -1, 3),
	snowball.NewAmong("nne", -1, 3),
	snowball.NewAmong("ni", -1, 2),
	snowball.NewAmong("si", -1, 1),
	snowball.NewAmong("an", -1, 4),
	snowball.NewAmong("en", -1, 6),
	snowball.NewAmong("än", -1, 5),
	snowball.NewAmong("nsä", -1, 3),
}

var finnishA5 = []*snowball.Among{
	snowball.NewAmong("aa", -1, -1),
	snowball.NewAmong("ee", -1, -1),
	snowball.NewAmong("ii", -1, -1),
	snowball.NewAmong("oo", -1, -1),
	snowball.NewAmong("uu", -1, -1),
	snowball.NewAmong("ää", -1, -1),
	snowball.NewAmong("öö", -1, -1),
}

// finnishA6 is built lazily in init to reference r_VI and r_LONG callbacks.
var finnishA6 []*snowball.Among

func init() {
	// Entries with method callbacks reference rVI and rLONG on SnowballProgram,
	// but the methods belong to FinnishStemmer. We store a sentinel result of -2
	// and dispatch in rCaseEnding as the Java Among.method field indicates.
	// We use NewAmongMethod with a nil receiver placeholder; the actual dispatch
	// is handled inside rCaseEnding by checking result values 13 and 14.
	//
	// Java source indices with callbacks:
	//   index 13: "den" result=-1, method=r_VI
	//   index 14: "seen" result=-1, method=r_LONG
	//   index 16: "tten" result=-1, method=r_VI
	//   index 18: "siin" result=-1, method=r_VI
	//
	// We assign special result values to distinguish them:
	//   r_VI  callbacks → result 10
	//   r_LONG callbacks → result 11
	finnishA6 = []*snowball.Among{
		snowball.NewAmong("a", -1, 8),
		snowball.NewAmong("lla", 0, -1),
		snowball.NewAmong("na", 0, -1),
		snowball.NewAmong("ssa", 0, -1),
		snowball.NewAmong("ta", 0, -1),
		snowball.NewAmong("lta", 4, -1),
		snowball.NewAmong("sta", 4, -1),
		snowball.NewAmong("tta", 4, 2),
		snowball.NewAmong("lle", -1, -1),
		snowball.NewAmong("ine", -1, -1),
		snowball.NewAmong("ksi", -1, -1),
		snowball.NewAmong("n", -1, 7),
		snowball.NewAmong("han", 11, 1),
		snowball.NewAmong("den", 11, 10),  // r_VI callback
		snowball.NewAmong("seen", 11, 11), // r_LONG callback
		snowball.NewAmong("hen", 11, 2),
		snowball.NewAmong("tten", 11, 10), // r_VI callback
		snowball.NewAmong("hin", 11, 3),
		snowball.NewAmong("siin", 11, 10), // r_VI callback
		snowball.NewAmong("hon", 11, 4),
		snowball.NewAmong("hän", 11, 5),
		snowball.NewAmong("hön", 11, 6),
		snowball.NewAmong("ä", -1, 8),
		snowball.NewAmong("llä", 22, -1),
		snowball.NewAmong("nä", 22, -1),
		snowball.NewAmong("ssä", 22, -1),
		snowball.NewAmong("tä", 22, -1),
		snowball.NewAmong("ltä", 26, -1),
		snowball.NewAmong("stä", 26, -1),
		snowball.NewAmong("ttä", 26, 2),
	}
}

var finnishA7 = []*snowball.Among{
	snowball.NewAmong("eja", -1, -1),
	snowball.NewAmong("mma", -1, 1),
	snowball.NewAmong("imma", 1, -1),
	snowball.NewAmong("mpa", -1, 1),
	snowball.NewAmong("impa", 3, -1),
	snowball.NewAmong("mmi", -1, 1),
	snowball.NewAmong("immi", 5, -1),
	snowball.NewAmong("mpi", -1, 1),
	snowball.NewAmong("impi", 7, -1),
	snowball.NewAmong("ejä", -1, -1),
	snowball.NewAmong("mmä", -1, 1),
	snowball.NewAmong("immä", 10, -1),
	snowball.NewAmong("mpä", -1, 1),
	snowball.NewAmong("impä", 12, -1),
}

var finnishA8 = []*snowball.Among{
	snowball.NewAmong("i", -1, -1),
	snowball.NewAmong("j", -1, -1),
}

var finnishA9 = []*snowball.Among{
	snowball.NewAmong("mma", -1, 1),
	snowball.NewAmong("imma", 0, -1),
}

var finnishGAEI = []byte{17, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8}
var finnishGC = []byte{119, 223, 119, 1}
var finnishGV1 = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32}
var finnishGV2 = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32}
var finnishGParticleEnd = []byte{17, 97, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32}

func (s *FinnishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	s.iP2 = p.Limit
golab0:
	for {
		v1 := p.Cursor
	lab1:
		for {
			if !p.InGrouping(finnishGV1, 97, 246) {
				break lab1
			}
			p.Cursor = v1
			break golab0
		}
		p.Cursor = v1
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab2:
	for {
		if p.OutGrouping(finnishGV1, 97, 246) {
			break golab2
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP1 = p.Cursor
golab4:
	for {
		v3 := p.Cursor
	lab5:
		for {
			if !p.InGrouping(finnishGV1, 97, 246) {
				break lab5
			}
			p.Cursor = v3
			break golab4
		}
		p.Cursor = v3
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab6:
	for {
		if p.OutGrouping(finnishGV1, 97, 246) {
			break golab6
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP2 = p.Cursor
	return true
}

func (s *FinnishStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *FinnishStemmer) rLONG() bool {
	return s.SnowballProgram.FindAmongB(finnishA5) != 0
}

func (s *FinnishStemmer) rVI() bool {
	p := s.SnowballProgram
	if !p.EqSBStr("i") {
		return false
	}
	return p.InGroupingB(finnishGV2, 97, 246)
}

func (s *FinnishStemmer) rParticleEtc() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(finnishA0)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		if !p.InGroupingB(finnishGParticleEnd, 97, 246) {
			return false
		}
	case 2:
		if !s.rR2() {
			return false
		}
	}
	p.SliceDel()
	return true
}

func (s *FinnishStemmer) rPossessive() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(finnishA4)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		v3 := p.Limit - p.Cursor
	lab0:
		for {
			if !p.EqSBStr("k") {
				break lab0
			}
			return false
		}
		p.Cursor = p.Limit - v3
		p.SliceDel()
	case 2:
		p.SliceDel()
		p.Ket = p.Cursor
		if !p.EqSBStr("kse") {
			return false
		}
		p.Bra = p.Cursor
		p.SliceFromStr("ksi")
	case 3:
		p.SliceDel()
	case 4:
		if p.FindAmongB(finnishA1) == 0 {
			return false
		}
		p.SliceDel()
	case 5:
		if p.FindAmongB(finnishA2) == 0 {
			return false
		}
		p.SliceDel()
	case 6:
		if p.FindAmongB(finnishA3) == 0 {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *FinnishStemmer) rCaseEnding() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(finnishA6)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		if !p.EqSBStr("a") {
			return false
		}
	case 2:
		if !p.EqSBStr("e") {
			return false
		}
	case 3:
		if !p.EqSBStr("i") {
			return false
		}
	case 4:
		if !p.EqSBStr("o") {
			return false
		}
	case 5:
		if !p.EqSBStr("ä") {
			return false
		}
	case 6:
		if !p.EqSBStr("ö") {
			return false
		}
	case 7:
		v3 := p.Limit - p.Cursor
	lab0:
		for {
			v4 := p.Limit - p.Cursor
		lab1:
			for {
				v5 := p.Limit - p.Cursor
			lab2:
				for {
					if !s.rLONG() {
						break lab2
					}
					break lab1
				}
				p.Cursor = p.Limit - v5
				if !p.EqSBStr("ie") {
					p.Cursor = p.Limit - v3
					break lab0
				}
			}
			p.Cursor = p.Limit - v4
			if p.Cursor <= p.LimitBackward {
				p.Cursor = p.Limit - v3
				break lab0
			}
			p.Cursor--
			p.Bra = p.Cursor
			break
		}
	case 8:
		if !p.InGroupingB(finnishGV1, 97, 246) {
			return false
		}
		if !p.InGroupingB(finnishGC, 98, 122) {
			return false
		}
	case 10: // r_VI callback
		if !s.rVI() {
			return false
		}
	case 11: // r_LONG callback
		if !s.rLONG() {
			return false
		}
	}
	p.SliceDel()
	s.bEndingRemoved = true
	return true
}

func (s *FinnishStemmer) rOtherEndings() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP2 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP2
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(finnishA7)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		v3 := p.Limit - p.Cursor
	lab0:
		for {
			if !p.EqSBStr("po") {
				break lab0
			}
			return false
		}
		p.Cursor = p.Limit - v3
	}
	p.SliceDel()
	return true
}

func (s *FinnishStemmer) rIPlural() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	if p.FindAmongB(finnishA8) == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	p.SliceDel()
	return true
}

func (s *FinnishStemmer) rTPlural() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	if !p.EqSBStr("t") {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	v3 := p.Limit - p.Cursor
	if !p.InGroupingB(finnishGV1, 97, 246) {
		p.LimitBackward = v2
		return false
	}
	p.Cursor = p.Limit - v3
	p.SliceDel()
	p.LimitBackward = v2
	if p.Cursor < s.iP2 {
		return false
	}
	v5 := p.LimitBackward
	p.LimitBackward = s.iP2
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(finnishA9)
	if amongVar == 0 {
		p.LimitBackward = v5
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v5
	switch amongVar {
	case 1:
		v6 := p.Limit - p.Cursor
	lab0:
		for {
			if !p.EqSBStr("po") {
				break lab0
			}
			return false
		}
		p.Cursor = p.Limit - v6
	}
	p.SliceDel()
	return true
}

func (s *FinnishStemmer) rTidy() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	v3 := p.Limit - p.Cursor
lab0:
	for {
		v4 := p.Limit - p.Cursor
		if !s.rLONG() {
			break lab0
		}
		p.Cursor = p.Limit - v4
		p.Ket = p.Cursor
		if p.Cursor <= p.LimitBackward {
			break lab0
		}
		p.Cursor--
		p.Bra = p.Cursor
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v3
	v5 := p.Limit - p.Cursor
lab1:
	for {
		p.Ket = p.Cursor
		if !p.InGroupingB(finnishGAEI, 97, 228) {
			break lab1
		}
		p.Bra = p.Cursor
		if !p.InGroupingB(finnishGC, 98, 122) {
			break lab1
		}
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v5
	v6 := p.Limit - p.Cursor
lab2:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("j") {
			break lab2
		}
		p.Bra = p.Cursor
	lab3:
		for {
			v7 := p.Limit - p.Cursor
		lab4:
			for {
				if !p.EqSBStr("o") {
					break lab4
				}
				break lab3
			}
			p.Cursor = p.Limit - v7
			if !p.EqSBStr("u") {
				break lab2
			}
			break
		}
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v6
	v8 := p.Limit - p.Cursor
lab5:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("o") {
			break lab5
		}
		p.Bra = p.Cursor
		if !p.EqSBStr("j") {
			break lab5
		}
		p.SliceDel()
		break
	}
	p.Cursor = p.Limit - v8
	p.LimitBackward = v2
golab6:
	for {
		v9 := p.Limit - p.Cursor
	lab7:
		for {
			if !p.OutGroupingB(finnishGV1, 97, 246) {
				break lab7
			}
			p.Cursor = p.Limit - v9
			break golab6
		}
		p.Cursor = p.Limit - v9
		if p.Cursor <= p.LimitBackward {
			return false
		}
		p.Cursor--
	}
	p.Ket = p.Cursor
	if !p.InGroupingB(finnishGC, 98, 122) {
		return false
	}
	p.Bra = p.Cursor
	s.sX = p.SliceTo(s.sX)
	if !p.EqSB(s.sX) {
		return false
	}
	p.SliceDel()
	return true
}

// Stem applies the Finnish Snowball stemming algorithm.
func (s *FinnishStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rMarkRegions()
	p.Cursor = v1
	s.bEndingRemoved = false
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v2 := p.Limit - p.Cursor
	s.rParticleEtc()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
	s.rPossessive()
	p.Cursor = p.Limit - v3
	v4 := p.Limit - p.Cursor
	s.rCaseEnding()
	p.Cursor = p.Limit - v4
	v5 := p.Limit - p.Cursor
	s.rOtherEndings()
	p.Cursor = p.Limit - v5
lab0:
	for {
	lab1:
		for {
			if !s.bEndingRemoved {
				break lab1
			}
			v7 := p.Limit - p.Cursor
			s.rIPlural()
			p.Cursor = p.Limit - v7
			break lab0
		}
		v8 := p.Limit - p.Cursor
		s.rTPlural()
		p.Cursor = p.Limit - v8
		break
	}
	v9 := p.Limit - p.Cursor
	s.rTidy()
	p.Cursor = p.Limit - v9
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*FinnishStemmer)(nil)
