// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// FrenchStemmer implements the French Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.FrenchStemmer
// from Apache Lucene 10.4.0.
type FrenchStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewFrenchStemmer constructs a FrenchStemmer.
func NewFrenchStemmer() *FrenchStemmer {
	return &FrenchStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*FrenchStemmer)(nil)

var frenchA0 = []*snowball.Among{
	snowball.NewAmong("col", -1, -1),
	snowball.NewAmong("par", -1, -1),
	snowball.NewAmong("tap", -1, -1),
}

var frenchA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 7),
	snowball.NewAmong("H", 0, 6),
	snowball.NewAmong("He", 1, 4),
	snowball.NewAmong("Hi", 1, 5),
	snowball.NewAmong("I", 0, 1),
	snowball.NewAmong("U", 0, 2),
	snowball.NewAmong("Y", 0, 3),
}

var frenchA2 = []*snowball.Among{
	snowball.NewAmong("iqU", -1, 3),
	snowball.NewAmong("abl", -1, 3),
	snowball.NewAmong("Ièr", -1, 4),
	snowball.NewAmong("ièr", -1, 4),
	snowball.NewAmong("eus", -1, 2),
	snowball.NewAmong("iv", -1, 1),
}

var frenchA3 = []*snowball.Among{
	snowball.NewAmong("ic", -1, 2),
	snowball.NewAmong("abil", -1, 1),
	snowball.NewAmong("iv", -1, 3),
}

var frenchA4 = []*snowball.Among{
	snowball.NewAmong("iqUe", -1, 1),
	snowball.NewAmong("atrice", -1, 2),
	snowball.NewAmong("ance", -1, 1),
	snowball.NewAmong("ence", -1, 5),
	snowball.NewAmong("logie", -1, 3),
	snowball.NewAmong("able", -1, 1),
	snowball.NewAmong("isme", -1, 1),
	snowball.NewAmong("euse", -1, 11),
	snowball.NewAmong("iste", -1, 1),
	snowball.NewAmong("ive", -1, 8),
	snowball.NewAmong("if", -1, 8),
	snowball.NewAmong("usion", -1, 4),
	snowball.NewAmong("ation", -1, 2),
	snowball.NewAmong("ution", -1, 4),
	snowball.NewAmong("ateur", -1, 2),
	snowball.NewAmong("iqUes", -1, 1),
	snowball.NewAmong("atrices", -1, 2),
	snowball.NewAmong("ances", -1, 1),
	snowball.NewAmong("ences", -1, 5),
	snowball.NewAmong("logies", -1, 3),
	snowball.NewAmong("ables", -1, 1),
	snowball.NewAmong("ismes", -1, 1),
	snowball.NewAmong("euses", -1, 11),
	snowball.NewAmong("istes", -1, 1),
	snowball.NewAmong("ives", -1, 8),
	snowball.NewAmong("ifs", -1, 8),
	snowball.NewAmong("usions", -1, 4),
	snowball.NewAmong("ations", -1, 2),
	snowball.NewAmong("utions", -1, 4),
	snowball.NewAmong("ateurs", -1, 2),
	snowball.NewAmong("ments", -1, 15),
	snowball.NewAmong("ements", 30, 6),
	snowball.NewAmong("issements", 31, 12),
	snowball.NewAmong("ités", -1, 7),
	snowball.NewAmong("ment", -1, 15),
	snowball.NewAmong("ement", 34, 6),
	snowball.NewAmong("issement", 35, 12),
	snowball.NewAmong("amment", 34, 13),
	snowball.NewAmong("emment", 34, 14),
	snowball.NewAmong("aux", -1, 10),
	snowball.NewAmong("eaux", 39, 9),
	snowball.NewAmong("eux", -1, 1),
	snowball.NewAmong("ité", -1, 7),
}

var frenchA5 = []*snowball.Among{
	snowball.NewAmong("ira", -1, 1),
	snowball.NewAmong("ie", -1, 1),
	snowball.NewAmong("isse", -1, 1),
	snowball.NewAmong("issante", -1, 1),
	snowball.NewAmong("i", -1, 1),
	snowball.NewAmong("irai", 4, 1),
	snowball.NewAmong("ir", -1, 1),
	snowball.NewAmong("iras", -1, 1),
	snowball.NewAmong("ies", -1, 1),
	snowball.NewAmong("îmes", -1, 1),
	snowball.NewAmong("isses", -1, 1),
	snowball.NewAmong("issantes", -1, 1),
	snowball.NewAmong("îtes", -1, 1),
	snowball.NewAmong("is", -1, 1),
	snowball.NewAmong("irais", 13, 1),
	snowball.NewAmong("issais", 13, 1),
	snowball.NewAmong("irions", -1, 1),
	snowball.NewAmong("issions", -1, 1),
	snowball.NewAmong("irons", -1, 1),
	snowball.NewAmong("issons", -1, 1),
	snowball.NewAmong("issants", -1, 1),
	snowball.NewAmong("it", -1, 1),
	snowball.NewAmong("irait", 21, 1),
	snowball.NewAmong("issait", 21, 1),
	snowball.NewAmong("issant", -1, 1),
	snowball.NewAmong("iraIent", -1, 1),
	snowball.NewAmong("issaIent", -1, 1),
	snowball.NewAmong("irent", -1, 1),
	snowball.NewAmong("issent", -1, 1),
	snowball.NewAmong("iront", -1, 1),
	snowball.NewAmong("ît", -1, 1),
	snowball.NewAmong("iriez", -1, 1),
	snowball.NewAmong("issiez", -1, 1),
	snowball.NewAmong("irez", -1, 1),
	snowball.NewAmong("issez", -1, 1),
}

var frenchA6 = []*snowball.Among{
	snowball.NewAmong("a", -1, 3),
	snowball.NewAmong("era", 0, 2),
	snowball.NewAmong("asse", -1, 3),
	snowball.NewAmong("ante", -1, 3),
	snowball.NewAmong("ée", -1, 2),
	snowball.NewAmong("ai", -1, 3),
	snowball.NewAmong("erai", 5, 2),
	snowball.NewAmong("er", -1, 2),
	snowball.NewAmong("as", -1, 3),
	snowball.NewAmong("eras", 8, 2),
	snowball.NewAmong("âmes", -1, 3),
	snowball.NewAmong("asses", -1, 3),
	snowball.NewAmong("antes", -1, 3),
	snowball.NewAmong("âtes", -1, 3),
	snowball.NewAmong("ées", -1, 2),
	snowball.NewAmong("ais", -1, 3),
	snowball.NewAmong("erais", 15, 2),
	snowball.NewAmong("ions", -1, 1),
	snowball.NewAmong("erions", 17, 2),
	snowball.NewAmong("assions", 17, 3),
	snowball.NewAmong("erons", -1, 2),
	snowball.NewAmong("ants", -1, 3),
	snowball.NewAmong("és", -1, 2),
	snowball.NewAmong("ait", -1, 3),
	snowball.NewAmong("erait", 23, 2),
	snowball.NewAmong("ant", -1, 3),
	snowball.NewAmong("aIent", -1, 3),
	snowball.NewAmong("eraIent", 26, 2),
	snowball.NewAmong("èrent", -1, 2),
	snowball.NewAmong("assent", -1, 3),
	snowball.NewAmong("eront", -1, 2),
	snowball.NewAmong("ât", -1, 3),
	snowball.NewAmong("ez", -1, 2),
	snowball.NewAmong("iez", 32, 2),
	snowball.NewAmong("eriez", 33, 2),
	snowball.NewAmong("assiez", 33, 3),
	snowball.NewAmong("erez", 32, 2),
	snowball.NewAmong("é", -1, 2),
}

var frenchA7 = []*snowball.Among{
	snowball.NewAmong("e", -1, 3),
	snowball.NewAmong("Ière", 0, 2),
	snowball.NewAmong("ière", 0, 2),
	snowball.NewAmong("ion", -1, 1),
	snowball.NewAmong("Ier", -1, 2),
	snowball.NewAmong("ier", -1, 2),
}

var frenchA8 = []*snowball.Among{
	snowball.NewAmong("ell", -1, -1),
	snowball.NewAmong("eill", -1, -1),
	snowball.NewAmong("enn", -1, -1),
	snowball.NewAmong("onn", -1, -1),
	snowball.NewAmong("ett", -1, -1),
}

// frenchGV: vowels (a e i o u â à ë é ê è ï î ô ù û)
var frenchGV = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 130, 103, 8, 5}

// frenchGKeepWithS: letters that keep a preceding 's' in residual
var frenchGKeepWithS = []byte{1, 65, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128}

func (s *FrenchStemmer) rPrelude() bool {
	for {
		v1 := s.Cursor
		lab0: for {
		golab1:
			for {
				v2 := s.Cursor
				lab2: for {
					lab3: for {
						v3 := s.Cursor
						lab4: for {
							if !s.InGrouping(frenchGV, 97, 251) {
								break lab4
							}
							s.Bra = s.Cursor
							lab5: for {
								v4 := s.Cursor
								lab6: for {
									if !s.EqSStr("u") {
										break lab6
									}
									s.Ket = s.Cursor
									if !s.InGrouping(frenchGV, 97, 251) {
										break lab6
									}
									s.SliceFromStr("U")
									break lab5
								}
								s.Cursor = v4
								lab7: for {
									if !s.EqSStr("i") {
										break lab7
									}
									s.Ket = s.Cursor
									if !s.InGrouping(frenchGV, 97, 251) {
										break lab7
									}
									s.SliceFromStr("I")
									break lab5
								}
								s.Cursor = v4
								if !s.EqSStr("y") {
									break lab4
								}
								s.Ket = s.Cursor
								s.SliceFromStr("Y")
								break lab5
							}
							break lab3
						}
						s.Cursor = v3
						lab8: for {
							s.Bra = s.Cursor
							if !s.EqSStr("ë") {
								break lab8
							}
							s.Ket = s.Cursor
							s.SliceFromStr("He")
							break lab3
						}
						s.Cursor = v3
						lab9: for {
							s.Bra = s.Cursor
							if !s.EqSStr("ï") {
								break lab9
							}
							s.Ket = s.Cursor
							s.SliceFromStr("Hi")
							break lab3
						}
						s.Cursor = v3
						lab10: for {
							s.Bra = s.Cursor
							if !s.EqSStr("y") {
								break lab10
							}
							s.Ket = s.Cursor
							if !s.InGrouping(frenchGV, 97, 251) {
								break lab10
							}
							s.SliceFromStr("Y")
							break lab3
						}
						s.Cursor = v3
						if !s.EqSStr("q") {
							break lab2
						}
						s.Bra = s.Cursor
						if !s.EqSStr("u") {
							break lab2
						}
						s.Ket = s.Cursor
						s.SliceFromStr("U")
						break lab3
					}
					s.Cursor = v2
					break golab1
				}
				s.Cursor = v2
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *FrenchStemmer) rMarkRegions() bool {
	s.iPV = s.Limit
	s.iP1 = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
	lab0: for {
		lab1: for {
			v2 := s.Cursor
			lab2: for {
				if !s.InGrouping(frenchGV, 97, 251) {
					break lab2
				}
				if !s.InGrouping(frenchGV, 97, 251) {
					break lab2
				}
				if s.Cursor >= s.Limit {
					break lab2
				}
				s.Cursor++
				break lab1
			}
			s.Cursor = v2
			lab3: for {
				if s.FindAmong(frenchA0) == 0 {
					break lab3
				}
				break lab1
			}
			s.Cursor = v2
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		golab4:
			for {
				lab5: for {
					if !s.InGrouping(frenchGV, 97, 251) {
						break lab5
					}
					break golab4
				}
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			break lab1
		}
		s.iPV = s.Cursor
		break lab0
	}
	s.Cursor = v1
	v4 := s.Cursor
	lab6: for {
	golab7:
		for {
			lab8: for {
				if !s.InGrouping(frenchGV, 97, 251) {
					break lab8
				}
				break golab7
			}
			if s.Cursor >= s.Limit {
				break lab6
			}
			s.Cursor++
		}
	golab9:
		for {
			lab10: for {
				if !s.OutGrouping(frenchGV, 97, 251) {
					break lab10
				}
				break golab9
			}
			if s.Cursor >= s.Limit {
				break lab6
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
	golab11:
		for {
			lab12: for {
				if !s.InGrouping(frenchGV, 97, 251) {
					break lab12
				}
				break golab11
			}
			if s.Cursor >= s.Limit {
				break lab6
			}
			s.Cursor++
		}
	golab13:
		for {
			lab14: for {
				if !s.OutGrouping(frenchGV, 97, 251) {
					break lab14
				}
				break golab13
			}
			if s.Cursor >= s.Limit {
				break lab6
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab6
	}
	s.Cursor = v4
	return true
}

func (s *FrenchStemmer) rPostlude() bool {
	for {
		v1 := s.Cursor
		lab0: for {
			s.Bra = s.Cursor
			amongVar := s.FindAmong(frenchA1)
			s.Ket = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("i")
			case 2:
				s.SliceFromStr("u")
			case 3:
				s.SliceFromStr("y")
			case 4:
				s.SliceFromStr("ë")
			case 5:
				s.SliceFromStr("ï")
			case 6:
				s.SliceDel()
			case 7:
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *FrenchStemmer) rRV() bool {
	return s.iPV <= s.Cursor
}

func (s *FrenchStemmer) rR1() bool {
	return s.iP1 <= s.Cursor
}

func (s *FrenchStemmer) rR2() bool {
	return s.iP2 <= s.Cursor
}

func (s *FrenchStemmer) rStandardSuffix() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(frenchA4)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v1 := s.Limit - s.Cursor
		lab0: for {
			s.Ket = s.Cursor
			if !s.EqSBStr("ic") {
				s.Cursor = s.Limit - v1
				break lab0
			}
			s.Bra = s.Cursor
			lab1: for {
				v2 := s.Limit - s.Cursor
				lab2: for {
					if !s.rR2() {
						break lab2
					}
					s.SliceDel()
					break lab1
				}
				s.Cursor = s.Limit - v2
				s.SliceFromStr("iqU")
				break lab1
			}
			break lab0
		}
	case 3:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("log")
	case 4:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("u")
	case 5:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("ent")
	case 6:
		if !s.rRV() {
			return false
		}
		s.SliceDel()
		v3 := s.Limit - s.Cursor
		lab3: for {
			s.Ket = s.Cursor
			av := s.FindAmongB(frenchA2)
			if av == 0 {
				s.Cursor = s.Limit - v3
				break lab3
			}
			s.Bra = s.Cursor
			switch av {
			case 1:
				if !s.rR2() {
					s.Cursor = s.Limit - v3
					break lab3
				}
				s.SliceDel()
				s.Ket = s.Cursor
				if !s.EqSBStr("at") {
					s.Cursor = s.Limit - v3
					break lab3
				}
				s.Bra = s.Cursor
				if !s.rR2() {
					s.Cursor = s.Limit - v3
					break lab3
				}
				s.SliceDel()
			case 2:
				lab4: for {
					v4 := s.Limit - s.Cursor
					lab5: for {
						if !s.rR2() {
							break lab5
						}
						s.SliceDel()
						break lab4
					}
					s.Cursor = s.Limit - v4
					if !s.rR1() {
						s.Cursor = s.Limit - v3
						break lab3
					}
					s.SliceFromStr("eux")
					break lab4
				}
			case 3:
				if !s.rR2() {
					s.Cursor = s.Limit - v3
					break lab3
				}
				s.SliceDel()
			case 4:
				if !s.rRV() {
					s.Cursor = s.Limit - v3
					break lab3
				}
				s.SliceFromStr("i")
			}
			break lab3
		}
	case 7:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v5 := s.Limit - s.Cursor
		lab6: for {
			s.Ket = s.Cursor
			av := s.FindAmongB(frenchA3)
			if av == 0 {
				s.Cursor = s.Limit - v5
				break lab6
			}
			s.Bra = s.Cursor
			switch av {
			case 1:
				lab7: for {
					v6 := s.Limit - s.Cursor
					lab8: for {
						if !s.rR2() {
							break lab8
						}
						s.SliceDel()
						break lab7
					}
					s.Cursor = s.Limit - v6
					s.SliceFromStr("abl")
					break lab7
				}
			case 2:
				lab9: for {
					v7 := s.Limit - s.Cursor
					lab10: for {
						if !s.rR2() {
							break lab10
						}
						s.SliceDel()
						break lab9
					}
					s.Cursor = s.Limit - v7
					s.SliceFromStr("iqU")
					break lab9
				}
			case 3:
				if !s.rR2() {
					s.Cursor = s.Limit - v5
					break lab6
				}
				s.SliceDel()
			}
			break lab6
		}
	case 8:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v8 := s.Limit - s.Cursor
		lab11: for {
			s.Ket = s.Cursor
			if !s.EqSBStr("at") {
				s.Cursor = s.Limit - v8
				break lab11
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v8
				break lab11
			}
			s.SliceDel()
			s.Ket = s.Cursor
			if !s.EqSBStr("ic") {
				s.Cursor = s.Limit - v8
				break lab11
			}
			s.Bra = s.Cursor
			lab12: for {
				v9 := s.Limit - s.Cursor
				lab13: for {
					if !s.rR2() {
						break lab13
					}
					s.SliceDel()
					break lab12
				}
				s.Cursor = s.Limit - v9
				s.SliceFromStr("iqU")
				break lab12
			}
			break lab11
		}
	case 9:
		s.SliceFromStr("eau")
	case 10:
		if !s.rR1() {
			return false
		}
		s.SliceFromStr("al")
	case 11:
		lab14: for {
			v10 := s.Limit - s.Cursor
			lab15: for {
				if !s.rR2() {
					break lab15
				}
				s.SliceDel()
				break lab14
			}
			s.Cursor = s.Limit - v10
			if !s.rR1() {
				return false
			}
			s.SliceFromStr("eux")
			break lab14
		}
	case 12:
		if !s.rR1() {
			return false
		}
		if !s.OutGroupingB(frenchGV, 97, 251) {
			return false
		}
		s.SliceDel()
	case 13:
		if !s.rRV() {
			return false
		}
		s.SliceFromStr("ant")
		return false
	case 14:
		if !s.rRV() {
			return false
		}
		s.SliceFromStr("ent")
		return false
	case 15:
		v11 := s.Limit - s.Cursor
		if !s.InGroupingB(frenchGV, 97, 251) {
			return false
		}
		if !s.rRV() {
			return false
		}
		s.Cursor = s.Limit - v11
		s.SliceDel()
		return false
	}
	return true
}

func (s *FrenchStemmer) rIVerbSuffix() bool {
	if s.Cursor < s.iPV {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iPV
	s.Ket = s.Cursor
	if s.FindAmongB(frenchA5) == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	v3 := s.Limit - s.Cursor
	lab0: for {
		if !s.EqSBStr("H") {
			break lab0
		}
		s.LimitBackward = v2
		return false
	}
	s.Cursor = s.Limit - v3
	if !s.OutGroupingB(frenchGV, 97, 251) {
		s.LimitBackward = v2
		return false
	}
	s.SliceDel()
	s.LimitBackward = v2
	return true
}

func (s *FrenchStemmer) rVerbSuffix() bool {
	if s.Cursor < s.iPV {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iPV
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(frenchA6)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			s.LimitBackward = v2
			return false
		}
		s.SliceDel()
	case 2:
		s.SliceDel()
	case 3:
		s.SliceDel()
		v3 := s.Limit - s.Cursor
		lab0: for {
			s.Ket = s.Cursor
			if !s.EqSBStr("e") {
				s.Cursor = s.Limit - v3
				break lab0
			}
			s.Bra = s.Cursor
			s.SliceDel()
			break lab0
		}
	}
	s.LimitBackward = v2
	return true
}

func (s *FrenchStemmer) rResidualSuffix() bool {
	v1 := s.Limit - s.Cursor
	lab0: for {
		s.Ket = s.Cursor
		if !s.EqSBStr("s") {
			s.Cursor = s.Limit - v1
			break lab0
		}
		s.Bra = s.Cursor
		v2 := s.Limit - s.Cursor
		lab1: for {
			v3 := s.Limit - s.Cursor
			lab2: for {
				if !s.EqSBStr("Hi") {
					break lab2
				}
				break lab1
			}
			s.Cursor = s.Limit - v3
			if !s.OutGroupingB(frenchGKeepWithS, 97, 232) {
				s.Cursor = s.Limit - v1
				break lab0
			}
			break lab1
		}
		s.Cursor = s.Limit - v2
		s.SliceDel()
		break lab0
	}
	if s.Cursor < s.iPV {
		return false
	}
	v5 := s.LimitBackward
	s.LimitBackward = s.iPV
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(frenchA7)
	if amongVar == 0 {
		s.LimitBackward = v5
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			s.LimitBackward = v5
			return false
		}
		lab3: for {
			v6 := s.Limit - s.Cursor
			lab4: for {
				if !s.EqSBStr("s") {
					break lab4
				}
				break lab3
			}
			s.Cursor = s.Limit - v6
			if !s.EqSBStr("t") {
				s.LimitBackward = v5
				return false
			}
			break lab3
		}
		s.SliceDel()
	case 2:
		s.SliceFromStr("i")
	case 3:
		s.SliceDel()
	}
	s.LimitBackward = v5
	return true
}

func (s *FrenchStemmer) rUnDouble() bool {
	v1 := s.Limit - s.Cursor
	if s.FindAmongB(frenchA8) == 0 {
		return false
	}
	s.Cursor = s.Limit - v1
	s.Ket = s.Cursor
	if s.Cursor <= s.LimitBackward {
		return false
	}
	s.Cursor--
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

func (s *FrenchStemmer) rUnAccent() bool {
	v1 := 1
	for {
		lab0: for {
			if !s.OutGroupingB(frenchGV, 97, 251) {
				break lab0
			}
			v1--
			continue
		}
		break
	}
	if v1 > 0 {
		return false
	}
	s.Ket = s.Cursor
	lab1: for {
		v3 := s.Limit - s.Cursor
		lab2: for {
			if !s.EqSBStr("é") {
				break lab2
			}
			break lab1
		}
		s.Cursor = s.Limit - v3
		if !s.EqSBStr("è") {
			return false
		}
		break lab1
	}
	s.Bra = s.Cursor
	s.SliceFromStr("e")
	return true
}

// Stem applies the French stemming algorithm to the current word.
func (s *FrenchStemmer) Stem() bool {
	v1 := s.Cursor
	s.rPrelude()
	s.Cursor = v1
	s.rMarkRegions()
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit

	v3 := s.Limit - s.Cursor
	lab0: for {
		lab1: for {
			v4 := s.Limit - s.Cursor
			lab2: for {
				v5 := s.Limit - s.Cursor
				lab3: for {
					v6 := s.Limit - s.Cursor
					lab4: for {
						if !s.rStandardSuffix() {
							break lab4
						}
						break lab3
					}
					s.Cursor = s.Limit - v6
					lab5: for {
						if !s.rIVerbSuffix() {
							break lab5
						}
						break lab3
					}
					s.Cursor = s.Limit - v6
					if !s.rVerbSuffix() {
						break lab2
					}
					break lab3
				}
				s.Cursor = s.Limit - v5
				v7 := s.Limit - s.Cursor
				lab6: for {
					s.Ket = s.Cursor
					lab7: for {
						v8 := s.Limit - s.Cursor
						lab8: for {
							if !s.EqSBStr("Y") {
								break lab8
							}
							s.Bra = s.Cursor
							s.SliceFromStr("i")
							break lab7
						}
						s.Cursor = s.Limit - v8
						if !s.EqSBStr("ç") {
							s.Cursor = s.Limit - v7
							break lab6
						}
						s.Bra = s.Cursor
						s.SliceFromStr("c")
						break lab7
					}
					break lab6
				}
				break lab1
			}
			s.Cursor = s.Limit - v4
			if !s.rResidualSuffix() {
				break lab0
			}
			break lab1
		}
		break lab0
	}
	s.Cursor = s.Limit - v3

	v9 := s.Limit - s.Cursor
	s.rUnDouble()
	s.Cursor = s.Limit - v9

	v10 := s.Limit - s.Cursor
	s.rUnAccent()
	s.Cursor = s.Limit - v10

	s.Cursor = s.LimitBackward
	v11 := s.Cursor
	s.rPostlude()
	s.Cursor = v11
	return true
}
