// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// GermanStemmer implements the German Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.GermanStemmer
// from Apache Lucene 10.4.0.
type GermanStemmer struct {
	*snowball.SnowballProgram
	iX  int
	iP2 int
	iP1 int
}

// NewGermanStemmer creates a new GermanStemmer.
func NewGermanStemmer() *GermanStemmer {
	return &GermanStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var germanA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 5),
	snowball.NewAmong("ae", 0, 2),
	snowball.NewAmong("oe", 0, 3),
	snowball.NewAmong("qu", 0, -1),
	snowball.NewAmong("ue", 0, 4),
	snowball.NewAmong("ß", 0, 1),
}

var germanA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 5),
	snowball.NewAmong("U", 0, 2),
	snowball.NewAmong("Y", 0, 1),
	snowball.NewAmong("ä", 0, 3),
	snowball.NewAmong("ö", 0, 4),
	snowball.NewAmong("ü", 0, 2),
}

var germanA2 = []*snowball.Among{
	snowball.NewAmong("e", -1, 3),
	snowball.NewAmong("em", -1, 1),
	snowball.NewAmong("en", -1, 3),
	snowball.NewAmong("ern", -1, 2),
	snowball.NewAmong("er", -1, 2),
	snowball.NewAmong("s", -1, 4),
	snowball.NewAmong("es", 5, 3),
}

var germanA3 = []*snowball.Among{
	snowball.NewAmong("en", -1, 1),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("st", -1, 2),
	snowball.NewAmong("est", 2, 1),
}

var germanA4 = []*snowball.Among{
	snowball.NewAmong("ig", -1, 1),
	snowball.NewAmong("lich", -1, 1),
}

var germanA5 = []*snowball.Among{
	snowball.NewAmong("end", -1, 1),
	snowball.NewAmong("ig", -1, 2),
	snowball.NewAmong("ung", -1, 1),
	snowball.NewAmong("lich", -1, 3),
	snowball.NewAmong("isch", -1, 2),
	snowball.NewAmong("ik", -1, 2),
	snowball.NewAmong("heit", -1, 3),
	snowball.NewAmong("keit", -1, 4),
}

var germanGV = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32, 8}
var germanGSEnding = []byte{117, 30, 5}
var germanGStEnding = []byte{117, 30, 4}

func (s *GermanStemmer) rPrelude() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	for {
		v2 := p.Cursor
	lab0:
		for {
		golab1:
			for {
				v3 := p.Cursor
			lab2:
				for {
					if !p.InGrouping(germanGV, 97, 252) {
						break lab2
					}
					p.Bra = p.Cursor
				lab3:
					for {
						v4 := p.Cursor
					lab4:
						for {
							if !p.EqSStr("u") {
								break lab4
							}
							p.Ket = p.Cursor
							if !p.InGrouping(germanGV, 97, 252) {
								break lab4
							}
							p.SliceFromStr("U")
							break lab3
						}
						p.Cursor = v4
						if !p.EqSStr("y") {
							break lab2
						}
						p.Ket = p.Cursor
						if !p.InGrouping(germanGV, 97, 252) {
							break lab2
						}
						p.SliceFromStr("Y")
						break
					}
					p.Cursor = v3
					break golab1
				}
				p.Cursor = v3
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v2
		break
	}
	p.Cursor = v1
	for {
		v5 := p.Cursor
	lab5:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(germanA0)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("ss")
			case 2:
				p.SliceFromStr("ä")
			case 3:
				p.SliceFromStr("ö")
			case 4:
				p.SliceFromStr("ü")
			case 5:
				if p.Cursor >= p.Limit {
					break lab5
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v5
		break
	}
	return true
}

func (s *GermanStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
	c := p.Cursor + 3
	if c > p.Limit {
		return false
	}
	p.Cursor = c
	s.iX = p.Cursor
	p.Cursor = v1
golab0:
	for {
	lab1:
		for {
			if !p.InGrouping(germanGV, 97, 252) {
				break lab1
			}
			break golab0
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab2:
	for {
	lab3:
		for {
			if !p.OutGrouping(germanGV, 97, 252) {
				break lab3
			}
			break golab2
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP1 = p.Cursor
lab4:
	for {
		if s.iP1 >= s.iX {
			break lab4
		}
		s.iP1 = s.iX
		break
	}
golab5:
	for {
	lab6:
		for {
			if !p.InGrouping(germanGV, 97, 252) {
				break lab6
			}
			break golab5
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab7:
	for {
	lab8:
		for {
			if !p.OutGrouping(germanGV, 97, 252) {
				break lab8
			}
			break golab7
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP2 = p.Cursor
	return true
}

func (s *GermanStemmer) rPostlude() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(germanA1)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("y")
			case 2:
				p.SliceFromStr("u")
			case 3:
				p.SliceFromStr("a")
			case 4:
				p.SliceFromStr("o")
			case 5:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			}
			continue
		}
		p.Cursor = v1
		break
	}
	return true
}

func (s *GermanStemmer) rR1() bool { return s.iP1 <= s.SnowballProgram.Cursor }
func (s *GermanStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *GermanStemmer) rStandardSuffix() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(germanA2)
		if amongVar == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		if !s.rR1() {
			break lab0
		}
		switch amongVar {
		case 1:
			v2 := p.Limit - p.Cursor
		lab1:
			for {
				if !p.EqSBStr("syst") {
					break lab1
				}
				break lab0
			}
			p.Cursor = p.Limit - v2
			p.SliceDel()
		case 2:
			p.SliceDel()
		case 3:
			p.SliceDel()
			v3 := p.Limit - p.Cursor
		lab2:
			for {
				p.Ket = p.Cursor
				if !p.EqSBStr("s") {
					p.Cursor = p.Limit - v3
					break lab2
				}
				p.Bra = p.Cursor
				if !p.EqSBStr("nis") {
					p.Cursor = p.Limit - v3
					break lab2
				}
				p.SliceDel()
				break
			}
		case 4:
			if !p.InGroupingB(germanGSEnding, 98, 116) {
				break lab0
			}
			p.SliceDel()
		}
		break
	}
	p.Cursor = p.Limit - v1
	v4 := p.Limit - p.Cursor
lab3:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(germanA3)
		if amongVar == 0 {
			break lab3
		}
		p.Bra = p.Cursor
		if !s.rR1() {
			break lab3
		}
		switch amongVar {
		case 1:
			p.SliceDel()
		case 2:
			if !p.InGroupingB(germanGStEnding, 98, 116) {
				break lab3
			}
			c := p.Cursor - 3
			if c < p.LimitBackward {
				break lab3
			}
			p.Cursor = c
			p.SliceDel()
		}
		break
	}
	p.Cursor = p.Limit - v4
	v5 := p.Limit - p.Cursor
lab4:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(germanA5)
		if amongVar == 0 {
			break lab4
		}
		p.Bra = p.Cursor
		if !s.rR2() {
			break lab4
		}
		switch amongVar {
		case 1:
			p.SliceDel()
			v6 := p.Limit - p.Cursor
		lab5:
			for {
				p.Ket = p.Cursor
				if !p.EqSBStr("ig") {
					p.Cursor = p.Limit - v6
					break lab5
				}
				p.Bra = p.Cursor
				v7 := p.Limit - p.Cursor
			lab6:
				for {
					if !p.EqSBStr("e") {
						break lab6
					}
					p.Cursor = p.Limit - v6
					break lab5
				}
				p.Cursor = p.Limit - v7
				if !s.rR2() {
					p.Cursor = p.Limit - v6
					break lab5
				}
				p.SliceDel()
				break
			}
		case 2:
			v8 := p.Limit - p.Cursor
		lab7:
			for {
				if !p.EqSBStr("e") {
					break lab7
				}
				break lab4
			}
			p.Cursor = p.Limit - v8
			p.SliceDel()
		case 3:
			p.SliceDel()
			v9 := p.Limit - p.Cursor
		lab8:
			for {
				p.Ket = p.Cursor
			lab9:
				for {
					v10 := p.Limit - p.Cursor
				lab10:
					for {
						if !p.EqSBStr("er") {
							break lab10
						}
						break lab9
					}
					p.Cursor = p.Limit - v10
					if !p.EqSBStr("en") {
						p.Cursor = p.Limit - v9
						break lab8
					}
					break
				}
				p.Bra = p.Cursor
				if !s.rR1() {
					p.Cursor = p.Limit - v9
					break lab8
				}
				p.SliceDel()
				break
			}
		case 4:
			p.SliceDel()
			v11 := p.Limit - p.Cursor
		lab11:
			for {
				p.Ket = p.Cursor
				if p.FindAmongB(germanA4) == 0 {
					p.Cursor = p.Limit - v11
					break lab11
				}
				p.Bra = p.Cursor
				if !s.rR2() {
					p.Cursor = p.Limit - v11
					break lab11
				}
				p.SliceDel()
				break
			}
		}
		break
	}
	p.Cursor = p.Limit - v5
	return true
}

// Stem applies the German Snowball stemming algorithm.
func (s *GermanStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rPrelude()
	p.Cursor = v1
	v2 := p.Cursor
	s.rMarkRegions()
	p.Cursor = v2
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	s.rStandardSuffix()
	p.Cursor = p.LimitBackward
	v4 := p.Cursor
	s.rPostlude()
	p.Cursor = v4
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*GermanStemmer)(nil)
