// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// GreekStemmer implements the Greek Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.GreekStemmer
// from Apache Lucene 10.4.0.
type GreekStemmer struct {
	*snowball.SnowballProgram
	bTest1 bool
}

// NewGreekStemmer creates a new GreekStemmer.
func NewGreekStemmer() *GreekStemmer {
	return &GreekStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

// greekA0: uppercase-to-lowercase mapping for Greek characters.
var greekA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 25),
	snowball.NewAmong("Ά", 0, 1),
	snowball.NewAmong("Έ", 0, 5),
	snowball.NewAmong("Ή", 0, 7),
	snowball.NewAmong("Ί", 0, 9),
	snowball.NewAmong("Ό", 0, 15),
	snowball.NewAmong("Ύ", 0, 20),
	snowball.NewAmong("Ώ", 0, 24),
	snowball.NewAmong("ΐ", 0, 7),
	snowball.NewAmong("Α", 0, 1),
	snowball.NewAmong("Β", 0, 2),
	snowball.NewAmong("Γ", 0, 3),
	snowball.NewAmong("Δ", 0, 4),
	snowball.NewAmong("Ε", 0, 5),
	snowball.NewAmong("Ζ", 0, 6),
	snowball.NewAmong("Η", 0, 7),
	snowball.NewAmong("Θ", 0, 8),
	snowball.NewAmong("Ι", 0, 9),
	snowball.NewAmong("Κ", 0, 10),
	snowball.NewAmong("Λ", 0, 11),
	snowball.NewAmong("Μ", 0, 12),
	snowball.NewAmong("Ν", 0, 13),
	snowball.NewAmong("Ξ", 0, 14),
	snowball.NewAmong("Ο", 0, 15),
	snowball.NewAmong("Π", 0, 16),
	snowball.NewAmong("Ρ", 0, 17),
	snowball.NewAmong("Σ", 0, 18),
	snowball.NewAmong("Τ", 0, 19),
	snowball.NewAmong("Υ", 0, 20),
	snowball.NewAmong("Φ", 0, 21),
	snowball.NewAmong("Χ", 0, 22),
	snowball.NewAmong("Ψ", 0, 23),
	snowball.NewAmong("Ω", 0, 24),
	snowball.NewAmong("Ϊ", 0, 9),
	snowball.NewAmong("Ϋ", 0, 20),
	snowball.NewAmong("ά", 0, 1),
	snowball.NewAmong("έ", 0, 5),
	snowball.NewAmong("ή", 0, 7),
	snowball.NewAmong("ί", 0, 9),
	snowball.NewAmong("ΰ", 0, 20),
	snowball.NewAmong("ς", 0, 18),
	snowball.NewAmong("ϊ", 0, 7),
	snowball.NewAmong("ϋ", 0, 20),
	snowball.NewAmong("ό", 0, 15),
	snowball.NewAmong("ύ", 0, 20),
	snowball.NewAmong("ώ", 0, 24),
}

var greekA1 = []*snowball.Among{
	snowball.NewAmong("σκαγια", -1, 2),
	snowball.NewAmong("φαγια", -1, 1),
	snowball.NewAmong("ολογια", -1, 3),
	snowball.NewAmong("σογια", -1, 4),
	snowball.NewAmong("τατογια", -1, 5),
	snowball.NewAmong("κρεατα", -1, 6),
	snowball.NewAmong("περατα", -1, 7),
	snowball.NewAmong("τερατα", -1, 8),
	snowball.NewAmong("γεγονοτα", -1, 11),
	snowball.NewAmong("καθεστωτα", -1, 10),
	snowball.NewAmong("φωτα", -1, 9),
	snowball.NewAmong("περατη", -1, 7),
	snowball.NewAmong("σκαγιων", -1, 2),
	snowball.NewAmong("φαγιων", -1, 1),
	snowball.NewAmong("ολογιων", -1, 3),
	snowball.NewAmong("σογιων", -1, 4),
	snowball.NewAmong("τατογιων", -1, 5),
	snowball.NewAmong("κρεατων", -1, 6),
	snowball.NewAmong("περατων", -1, 7),
	snowball.NewAmong("τερατων", -1, 8),
	snowball.NewAmong("γεγονοτων", -1, 11),
	snowball.NewAmong("καθεστωτων", -1, 10),
	snowball.NewAmong("φωτων", -1, 9),
	snowball.NewAmong("κρεας", -1, 6),
	snowball.NewAmong("περας", -1, 7),
	snowball.NewAmong("τερας", -1, 8),
	snowball.NewAmong("γεγονος", -1, 11),
	snowball.NewAmong("κρεατος", -1, 6),
	snowball.NewAmong("περατος", -1, 7),
	snowball.NewAmong("τερατος", -1, 8),
	snowball.NewAmong("γεγονοτος", -1, 11),
	snowball.NewAmong("καθεστωτος", -1, 10),
	snowball.NewAmong("φωτος", -1, 9),
	snowball.NewAmong("καθεστως", -1, 10),
	snowball.NewAmong("φως", -1, 9),
	snowball.NewAmong("σκαγιου", -1, 2),
	snowball.NewAmong("φαγιου", -1, 1),
	snowball.NewAmong("ολογιου", -1, 3),
	snowball.NewAmong("σογιου", -1, 4),
	snowball.NewAmong("τατογιου", -1, 5),
}

var greekA2 = []*snowball.Among{
	snowball.NewAmong("πα", -1, 1),
	snowball.NewAmong("ξαναπα", 0, 1),
	snowball.NewAmong("επα", 0, 1),
	snowball.NewAmong("περιπα", 0, 1),
	snowball.NewAmong("αναμπα", 0, 1),
	snowball.NewAmong("εμπα", 0, 1),
	snowball.NewAmong("β", -1, 2),
	snowball.NewAmong("δανε", -1, 1),
	snowball.NewAmong("βαθυρι", -1, 2),
	snowball.NewAmong("βαρκ", -1, 2),
	snowball.NewAmong("μαρκ", -1, 2),
	snowball.NewAmong("λ", -1, 2),
	snowball.NewAmong("μ", -1, 2),
	snowball.NewAmong("κορν", -1, 2),
	snowball.NewAmong("αθρο", -1, 1),
	snowball.NewAmong("συναθρο", 14, 1),
	snowball.NewAmong("π", -1, 2),
	snowball.NewAmong("ιμπ", 16, 2),
	snowball.NewAmong("ρ", -1, 2),
	snowball.NewAmong("μαρ", 18, 2),
	snowball.NewAmong("αμπαρ", 18, 2),
	snowball.NewAmong("γκρ", 18, 2),
	snowball.NewAmong("βολβορ", 18, 2),
	snowball.NewAmong("γλυκορ", 18, 2),
	snowball.NewAmong("πιπεπορ", 18, 2),
	snowball.NewAmong("πρ", 18, 2),
	snowball.NewAmong("μπρ", 25, 2),
	snowball.NewAmong("αρρ", 18, 2),
	snowball.NewAmong("γλυκυρ", 18, 2),
	snowball.NewAmong("πολυρ", 18, 2),
	snowball.NewAmong("λου", -1, 2),
}

var greekA3 = []*snowball.Among{
	snowball.NewAmong("ιζα", -1, 1),
	snowball.NewAmong("ιζε", -1, 1),
	snowball.NewAmong("ιζαμε", -1, 1),
	snowball.NewAmong("ιζουμε", -1, 1),
	snowball.NewAmong("ιζανε", -1, 1),
	snowball.NewAmong("ιζουνε", -1, 1),
	snowball.NewAmong("ιζατε", -1, 1),
	snowball.NewAmong("ιζετε", -1, 1),
	snowball.NewAmong("ιζει", -1, 1),
	snowball.NewAmong("ιζαν", -1, 1),
	snowball.NewAmong("ιζουν", -1, 1),
	snowball.NewAmong("ιζες", -1, 1),
	snowball.NewAmong("ιζεις", -1, 1),
	snowball.NewAmong("ιζω", -1, 1),
}

var greekA4 = []*snowball.Among{
	snowball.NewAmong("βι", -1, 1),
	snowball.NewAmong("λι", -1, 1),
	snowball.NewAmong("αλ", -1, 1),
	snowball.NewAmong("εν", -1, 1),
	snowball.NewAmong("σ", -1, 1),
	snowball.NewAmong("χ", -1, 1),
	snowball.NewAmong("υψ", -1, 1),
	snowball.NewAmong("ζω", -1, 1),
}

var greekA5 = []*snowball.Among{
	snowball.NewAmong("ωθηκα", -1, 1),
	snowball.NewAmong("ωθηκε", -1, 1),
	snowball.NewAmong("ωθηκαμε", -1, 1),
	snowball.NewAmong("ωθηκανε", -1, 1),
	snowball.NewAmong("ωθηκατε", -1, 1),
	snowball.NewAmong("ωθηκαν", -1, 1),
	snowball.NewAmong("ωθηκες", -1, 1),
}

var greekA6 = []*snowball.Among{
	snowball.NewAmong("ξαναπα", -1, 1),
	snowball.NewAmong("επα", -1, 1),
	snowball.NewAmong("περιπα", -1, 1),
	snowball.NewAmong("αναμπα", -1, 1),
	snowball.NewAmong("εμπα", -1, 1),
	snowball.NewAmong("χαρτοπα", -1, 1),
	snowball.NewAmong("εξαρχα", -1, 1),
	snowball.NewAmong("γε", -1, 2),
	snowball.NewAmong("γκε", -1, 2),
	snowball.NewAmong("κλε", -1, 1),
	snowball.NewAmong("εκλε", 9, 1),
	snowball.NewAmong("απεκλε", 10, 1),
	snowball.NewAmong("αποκλε", 9, 1),
	snowball.NewAmong("εσωκλε", 9, 1),
	snowball.NewAmong("δανε", -1, 1),
	snowball.NewAmong("πε", -1, 1),
	snowball.NewAmong("επε", 15, 1),
	snowball.NewAmong("μετεπε", 16, 1),
	snowball.NewAmong("εσε", -1, 1),
	snowball.NewAmong("γκ", -1, 2),
	snowball.NewAmong("μ", -1, 2),
	snowball.NewAmong("πουκαμ", 20, 2),
	snowball.NewAmong("κομ", 20, 2),
	snowball.NewAmong("αν", -1, 2),
	snowball.NewAmong("ολο", -1, 2),
	snowball.NewAmong("αθρο", -1, 1),
	snowball.NewAmong("συναθρο", 25, 1),
	snowball.NewAmong("π", -1, 2),
	snowball.NewAmong("λαρ", -1, 2),
	snowball.NewAmong("δημοκρατ", -1, 2),
	snowball.NewAmong("αφ", -1, 2),
	snowball.NewAmong("γιγαντοαφ", 30, 2),
}

var greekA7 = []*snowball.Among{
	snowball.NewAmong("ισα", -1, 1),
	snowball.NewAmong("ισαμε", -1, 1),
	snowball.NewAmong("ισανε", -1, 1),
	snowball.NewAmong("ισε", -1, 1),
	snowball.NewAmong("ισατε", -1, 1),
	snowball.NewAmong("ισαν", -1, 1),
	snowball.NewAmong("ισες", -1, 1),
}

var greekA8 = []*snowball.Among{
	snowball.NewAmong("ξαναπα", -1, 1),
	snowball.NewAmong("επα", -1, 1),
	snowball.NewAmong("περιπα", -1, 1),
	snowball.NewAmong("αναμπα", -1, 1),
	snowball.NewAmong("εμπα", -1, 1),
	snowball.NewAmong("χαρτοπα", -1, 1),
	snowball.NewAmong("εξαρχα", -1, 1),
	snowball.NewAmong("κλε", -1, 1),
	snowball.NewAmong("εκλε", 7, 1),
	snowball.NewAmong("απεκλε", 8, 1),
	snowball.NewAmong("αποκλε", 7, 1),
	snowball.NewAmong("εσωκλε", 7, 1),
	snowball.NewAmong("δανε", -1, 1),
	snowball.NewAmong("πε", -1, 1),
	snowball.NewAmong("επε", 13, 1),
	snowball.NewAmong("μετεπε", 14, 1),
	snowball.NewAmong("εσε", -1, 1),
	snowball.NewAmong("αθρο", -1, 1),
	snowball.NewAmong("συναθρο", 17, 1),
}

var greekA9 = []*snowball.Among{
	snowball.NewAmong("ισουμε", -1, 1),
	snowball.NewAmong("ισουνε", -1, 1),
	snowball.NewAmong("ισετε", -1, 1),
	snowball.NewAmong("ισει", -1, 1),
	snowball.NewAmong("ισουν", -1, 1),
	snowball.NewAmong("ισεις", -1, 1),
	snowball.NewAmong("ισω", -1, 1),
}

var greekA10 = []*snowball.Among{
	snowball.NewAmong("ατα", -1, 2),
	snowball.NewAmong("φα", -1, 2),
	snowball.NewAmong("ηφα", 1, 2),
	snowball.NewAmong("μεγ", -1, 2),
	snowball.NewAmong("λυγ", -1, 2),
	snowball.NewAmong("ηδ", -1, 2),
	snowball.NewAmong("κλε", -1, 1),
	snowball.NewAmong("εσωκλε", 6, 1),
	snowball.NewAmong("πλε", -1, 1),
	snowball.NewAmong("δανε", -1, 1),
	snowball.NewAmong("σε", -1, 1),
	snowball.NewAmong("ασε", 10, 1),
	snowball.NewAmong("καθ", -1, 2),
	snowball.NewAmong("εχθ", -1, 2),
	snowball.NewAmong("κακ", -1, 2),
	snowball.NewAmong("μακ", -1, 2),
	snowball.NewAmong("σκ", -1, 2),
	snowball.NewAmong("φιλ", -1, 2),
	snowball.NewAmong("κυλ", -1, 2),
	snowball.NewAmong("μ", -1, 2),
	snowball.NewAmong("γεμ", 19, 2),
	snowball.NewAmong("αχν", -1, 2),
	snowball.NewAmong("συναθρο", -1, 1),
	snowball.NewAmong("π", -1, 2),
	snowball.NewAmong("απ", 23, 2),
	snowball.NewAmong("εμπ", 23, 2),
	snowball.NewAmong("ευπ", 23, 2),
	snowball.NewAmong("αρ", -1, 2),
	snowball.NewAmong("αορ", -1, 2),
	snowball.NewAmong("γυρ", -1, 2),
	snowball.NewAmong("χρ", -1, 2),
	snowball.NewAmong("χωρ", -1, 2),
	snowball.NewAmong("κτ", -1, 2),
	snowball.NewAmong("ακτ", 32, 2),
	snowball.NewAmong("χτ", -1, 2),
	snowball.NewAmong("αχτ", 34, 2),
	snowball.NewAmong("ταχ", -1, 2),
	snowball.NewAmong("σχ", -1, 2),
	snowball.NewAmong("ασχ", 37, 2),
	snowball.NewAmong("υψ", -1, 2),
}

var greekA11 = []*snowball.Among{
	snowball.NewAmong("ιστα", -1, 1),
	snowball.NewAmong("ιστε", -1, 1),
	snowball.NewAmong("ιστη", -1, 1),
	snowball.NewAmong("ιστοι", -1, 1),
	snowball.NewAmong("ιστων", -1, 1),
	snowball.NewAmong("ιστο", -1, 1),
	snowball.NewAmong("ιστες", -1, 1),
	snowball.NewAmong("ιστης", -1, 1),
	snowball.NewAmong("ιστος", -1, 1),
	snowball.NewAmong("ιστους", -1, 1),
	snowball.NewAmong("ιστου", -1, 1),
}

var greekA12 = []*snowball.Among{
	snowball.NewAmong("εγκλε", -1, 1),
	snowball.NewAmong("αποκλε", -1, 1),
	snowball.NewAmong("δανε", -1, 2),
	snowball.NewAmong("αντιδανε", 2, 2),
	snowball.NewAmong("σε", -1, 1),
	snowball.NewAmong("μετασε", 4, 1),
	snowball.NewAmong("μικροσε", 4, 1),
}

var greekA13 = []*snowball.Among{
	snowball.NewAmong("ατομικ", -1, 2),
	snowball.NewAmong("εθνικ", -1, 4),
	snowball.NewAmong("τοπικ", -1, 7),
	snowball.NewAmong("εκλεκτικ", -1, 5),
	snowball.NewAmong("σκεπτικ", -1, 6),
	snowball.NewAmong("γνωστικ", -1, 3),
	snowball.NewAmong("αγνωστικ", 5, 1),
	snowball.NewAmong("αλεξανδριν", -1, 8),
	snowball.NewAmong("θεατριν", -1, 10),
	snowball.NewAmong("βυζαντιν", -1, 9),
}

var greekA14 = []*snowball.Among{
	snowball.NewAmong("ισμοι", -1, 1),
	snowball.NewAmong("ισμων", -1, 1),
	snowball.NewAmong("ισμο", -1, 1),
	snowball.NewAmong("ισμος", -1, 1),
	snowball.NewAmong("ισμους", -1, 1),
	snowball.NewAmong("ισμου", -1, 1),
}

var greekA15 = []*snowball.Among{
	snowball.NewAmong("σ", -1, 1),
	snowball.NewAmong("χ", -1, 1),
}

var greekA16 = []*snowball.Among{
	snowball.NewAmong("ουδακια", -1, 1),
	snowball.NewAmong("αρακια", -1, 1),
	snowball.NewAmong("ουδακι", -1, 1),
	snowball.NewAmong("αρακι", -1, 1),
}

var greekA17 = []*snowball.Among{
	snowball.NewAmong("β", -1, 2),
	snowball.NewAmong("βαμβ", 0, 1),
	snowball.NewAmong("σλοβ", 0, 1),
	snowball.NewAmong("τσεχοσλοβ", 2, 1),
	snowball.NewAmong("καρδ", -1, 2),
	snowball.NewAmong("ζ", -1, 2),
	snowball.NewAmong("τζ", 5, 1),
	snowball.NewAmong("κ", -1, 1),
	snowball.NewAmong("καπακ", 7, 1),
	snowball.NewAmong("σοκ", 7, 1),
	snowball.NewAmong("σκ", 7, 1),
	snowball.NewAmong("βαλ", -1, 2),
	snowball.NewAmong("μαλ", -1, 1),
	snowball.NewAmong("γλ", -1, 2),
	snowball.NewAmong("τριπολ", -1, 2),
	snowball.NewAmong("πλ", -1, 1),
	snowball.NewAmong("λουλ", -1, 1),
	snowball.NewAmong("φυλ", -1, 1),
	snowball.NewAmong("καιμ", -1, 1),
	snowball.NewAmong("κλιμ", -1, 1),
	snowball.NewAmong("φαρμ", -1, 1),
	snowball.NewAmong("γιαν", -1, 2),
	snowball.NewAmong("σπαν", -1, 1),
	snowball.NewAmong("ηγουμεν", -1, 2),
	snowball.NewAmong("κον", -1, 1),
	snowball.NewAmong("μακρυν", -1, 2),
	snowball.NewAmong("π", -1, 2),
	snowball.NewAmong("κατραπ", 26, 1),
	snowball.NewAmong("ρ", -1, 1),
	snowball.NewAmong("βρ", 28, 1),
	snowball.NewAmong("λαβρ", 29, 1),
	snowball.NewAmong("αμβρ", 29, 1),
	snowball.NewAmong("μερ", 28, 1),
	snowball.NewAmong("πατερ", 28, 2),
	snowball.NewAmong("ανθρ", 28, 1),
	snowball.NewAmong("κορ", 28, 1),
	snowball.NewAmong("σ", -1, 1),
	snowball.NewAmong("ναγκασ", 36, 1),
	snowball.NewAmong("τοσ", 36, 2),
	snowball.NewAmong("μουστ", -1, 1),
	snowball.NewAmong("ρυ", -1, 1),
	snowball.NewAmong("φ", -1, 1),
	snowball.NewAmong("σφ", 41, 1),
	snowball.NewAmong("αλισφ", 42, 1),
	snowball.NewAmong("νυφ", 41, 2),
	snowball.NewAmong("χ", -1, 1),
}

var greekA18 = []*snowball.Among{
	snowball.NewAmong("ακια", -1, 1),
	snowball.NewAmong("αρακια", 0, 1),
	snowball.NewAmong("ιτσα", -1, 1),
	snowball.NewAmong("ακι", -1, 1),
	snowball.NewAmong("αρακι", 3, 1),
	snowball.NewAmong("ιτσων", -1, 1),
	snowball.NewAmong("ιτσας", -1, 1),
	snowball.NewAmong("ιτσες", -1, 1),
}

var greekA19 = []*snowball.Among{
	snowball.NewAmong("ψαλ", -1, 1),
	snowball.NewAmong("αιφν", -1, 1),
	snowball.NewAmong("ολο", -1, 1),
	snowball.NewAmong("ιρ", -1, 1),
}

var greekA20 = []*snowball.Among{
	snowball.NewAmong("ε", -1, 1),
	snowball.NewAmong("παιχν", -1, 1),
}

var greekA21 = []*snowball.Among{
	snowball.NewAmong("ιδια", -1, 1),
	snowball.NewAmong("ιδιων", -1, 1),
	snowball.NewAmong("ιδιο", -1, 1),
}

var greekA22 = []*snowball.Among{
	snowball.NewAmong("ιβ", -1, 1),
	snowball.NewAmong("δ", -1, 1),
	snowball.NewAmong("φραγκ", -1, 1),
	snowball.NewAmong("λυκ", -1, 1),
	snowball.NewAmong("οβελ", -1, 1),
	snowball.NewAmong("μην", -1, 1),
	snowball.NewAmong("ρ", -1, 1),
}

var greekA23 = []*snowball.Among{
	snowball.NewAmong("ισκε", -1, 1),
	snowball.NewAmong("ισκο", -1, 1),
	snowball.NewAmong("ισκος", -1, 1),
	snowball.NewAmong("ισκου", -1, 1),
}

var greekA24 = []*snowball.Among{
	snowball.NewAmong("αδων", -1, 1),
	snowball.NewAmong("αδες", -1, 1),
}

var greekA25 = []*snowball.Among{
	snowball.NewAmong("γιαγι", -1, -1),
	snowball.NewAmong("θει", -1, -1),
	snowball.NewAmong("οκ", -1, -1),
	snowball.NewAmong("μαμ", -1, -1),
	snowball.NewAmong("μαν", -1, -1),
	snowball.NewAmong("μπαμπ", -1, -1),
	snowball.NewAmong("πεθερ", -1, -1),
	snowball.NewAmong("πατερ", -1, -1),
	snowball.NewAmong("κυρ", -1, -1),
	snowball.NewAmong("νταντ", -1, -1),
}

var greekA26 = []*snowball.Among{
	snowball.NewAmong("εδων", -1, 1),
	snowball.NewAmong("εδες", -1, 1),
}

var greekA27 = []*snowball.Among{
	snowball.NewAmong("μιλ", -1, 1),
	snowball.NewAmong("δαπ", -1, 1),
	snowball.NewAmong("γηπ", -1, 1),
	snowball.NewAmong("ιπ", -1, 1),
	snowball.NewAmong("εμπ", -1, 1),
	snowball.NewAmong("οπ", -1, 1),
	snowball.NewAmong("κρασπ", -1, 1),
	snowball.NewAmong("υπ", -1, 1),
}

var greekA28 = []*snowball.Among{
	snowball.NewAmong("ουδων", -1, 1),
	snowball.NewAmong("ουδες", -1, 1),
}

var greekA29 = []*snowball.Among{
	snowball.NewAmong("τραγ", -1, 1),
	snowball.NewAmong("φε", -1, 1),
	snowball.NewAmong("καλιακ", -1, 1),
	snowball.NewAmong("αρκ", -1, 1),
	snowball.NewAmong("σκ", -1, 1),
	snowball.NewAmong("πεταλ", -1, 1),
	snowball.NewAmong("βελ", -1, 1),
	snowball.NewAmong("λουλ", -1, 1),
	snowball.NewAmong("φλ", -1, 1),
	snowball.NewAmong("χν", -1, 1),
	snowball.NewAmong("πλεξ", -1, 1),
	snowball.NewAmong("σπ", -1, 1),
	snowball.NewAmong("φρ", -1, 1),
	snowball.NewAmong("σ", -1, 1),
	snowball.NewAmong("λιχ", -1, 1),
}

var greekA30 = []*snowball.Among{
	snowball.NewAmong("εων", -1, 1),
	snowball.NewAmong("εως", -1, 1),
}

var greekA31 = []*snowball.Among{
	snowball.NewAmong("δ", -1, 1),
	snowball.NewAmong("ιδ", 0, 1),
	snowball.NewAmong("θ", -1, 1),
	snowball.NewAmong("γαλ", -1, 1),
	snowball.NewAmong("ελ", -1, 1),
	snowball.NewAmong("ν", -1, 1),
	snowball.NewAmong("π", -1, 1),
	snowball.NewAmong("παρ", -1, 1),
}

var greekA32 = []*snowball.Among{
	snowball.NewAmong("ια", -1, 1),
	snowball.NewAmong("ιων", -1, 1),
	snowball.NewAmong("ιου", -1, 1),
}

var greekA33 = []*snowball.Among{
	snowball.NewAmong("ικα", -1, 1),
	snowball.NewAmong("ικων", -1, 1),
	snowball.NewAmong("ικο", -1, 1),
	snowball.NewAmong("ικου", -1, 1),
}

var greekA34 = []*snowball.Among{
	snowball.NewAmong("αδ", -1, 1),
	snowball.NewAmong("συναδ", 0, 1),
	snowball.NewAmong("καταδ", 0, 1),
	snowball.NewAmong("αντιδ", -1, 1),
	snowball.NewAmong("ενδ", -1, 1),
	snowball.NewAmong("φυλοδ", -1, 1),
	snowball.NewAmong("υποδ", -1, 1),
	snowball.NewAmong("πρωτοδ", -1, 1),
	snowball.NewAmong("εξωδ", -1, 1),
	snowball.NewAmong("ηθ", -1, 1),
	snowball.NewAmong("ανηθ", 9, 1),
	snowball.NewAmong("ξικ", -1, 1),
	snowball.NewAmong("αλ", -1, 1),
	snowball.NewAmong("αμμοχαλ", 12, 1),
	snowball.NewAmong("συνομηλ", -1, 1),
	snowball.NewAmong("μπολ", -1, 1),
	snowball.NewAmong("μουλ", -1, 1),
	snowball.NewAmong("τσαμ", -1, 1),
	snowball.NewAmong("βρωμ", -1, 1),
	snowball.NewAmong("αμαν", -1, 1),
	snowball.NewAmong("μπαν", -1, 1),
	snowball.NewAmong("καλλιν", -1, 1),
	snowball.NewAmong("ποστελν", -1, 1),
	snowball.NewAmong("φιλον", -1, 1),
	snowball.NewAmong("καλπ", -1, 1),
	snowball.NewAmong("γερ", -1, 1),
	snowball.NewAmong("χασ", -1, 1),
	snowball.NewAmong("μποσ", -1, 1),
	snowball.NewAmong("πλιατσ", -1, 1),
	snowball.NewAmong("πετσ", -1, 1),
	snowball.NewAmong("πιτσ", -1, 1),
	snowball.NewAmong("φυσ", -1, 1),
	snowball.NewAmong("μπαγιατ", -1, 1),
	snowball.NewAmong("νιτ", -1, 1),
	snowball.NewAmong("πικαντ", -1, 1),
	snowball.NewAmong("σερτ", -1, 1),
}

var greekA35 = []*snowball.Among{
	snowball.NewAmong("αγαμε", -1, 1),
	snowball.NewAmong("ηκαμε", -1, 1),
	snowball.NewAmong("ηθηκαμε", 1, 1),
	snowball.NewAmong("ησαμε", -1, 1),
	snowball.NewAmong("ουσαμε", -1, 1),
}

var greekA36 = []*snowball.Among{
	snowball.NewAmong("βουβ", -1, 1),
	snowball.NewAmong("ξεθ", -1, 1),
	snowball.NewAmong("πεθ", -1, 1),
	snowball.NewAmong("αποθ", -1, 1),
	snowball.NewAmong("αποκ", -1, 1),
	snowball.NewAmong("ουλ", -1, 1),
	snowball.NewAmong("αναπ", -1, 1),
	snowball.NewAmong("πικρ", -1, 1),
	snowball.NewAmong("ποτ", -1, 1),
	snowball.NewAmong("αποστ", -1, 1),
	snowball.NewAmong("χ", -1, 1),
	snowball.NewAmong("σιχ", 10, 1),
}

var greekA37 = []*snowball.Among{
	snowball.NewAmong("τρ", -1, 1),
	snowball.NewAmong("τσ", -1, 1),
}

var greekA38 = []*snowball.Among{
	snowball.NewAmong("αγανε", -1, 1),
	snowball.NewAmong("ηκανε", -1, 1),
	snowball.NewAmong("ηθηκανε", 1, 1),
	snowball.NewAmong("ησανε", -1, 1),
	snowball.NewAmong("ουσανε", -1, 1),
	snowball.NewAmong("οντανε", -1, 1),
	snowball.NewAmong("ιοντανε", 5, 1),
	snowball.NewAmong("ουντανε", -1, 1),
	snowball.NewAmong("ιουντανε", 7, 1),
	snowball.NewAmong("οτανε", -1, 1),
	snowball.NewAmong("ιοτανε", 9, 1),
}

var greekA39 = []*snowball.Among{
	snowball.NewAmong("ταβ", -1, 1),
	snowball.NewAmong("νταβ", 0, 1),
	snowball.NewAmong("ψηλοταβ", 0, 1),
	snowball.NewAmong("λιβ", -1, 1),
	snowball.NewAmong("κλιβ", 3, 1),
	snowball.NewAmong("ξηροκλιβ", 4, 1),
	snowball.NewAmong("γ", -1, 1),
	snowball.NewAmong("αγ", 6, 1),
	snowball.NewAmong("τραγ", 7, 1),
	snowball.NewAmong("τσαγ", 7, 1),
	snowball.NewAmong("αθιγγ", 6, 1),
	snowball.NewAmong("τσιγγ", 6, 1),
	snowball.NewAmong("ατσιγγ", 11, 1),
	snowball.NewAmong("στεγ", 6, 1),
	snowball.NewAmong("απηγ", 6, 1),
	snowball.NewAmong("σιγ", 6, 1),
	snowball.NewAmong("ανοργ", 6, 1),
	snowball.NewAmong("ενοργ", 6, 1),
	snowball.NewAmong("καλπουζ", -1, 1),
	snowball.NewAmong("θ", -1, 1),
	snowball.NewAmong("μωαμεθ", 19, 1),
	snowball.NewAmong("πιθ", 19, 1),
	snowball.NewAmong("απιθ", 21, 1),
	snowball.NewAmong("δεκ", -1, 1),
	snowball.NewAmong("πελεκ", -1, 1),
	snowball.NewAmong("ικ", -1, 1),
	snowball.NewAmong("ανικ", 25, 1),
	snowball.NewAmong("βουλκ", -1, 1),
	snowball.NewAmong("βασκ", -1, 1),
	snowball.NewAmong("βραχυκ", -1, 1),
	snowball.NewAmong("γαλ", -1, 1),
	snowball.NewAmong("καταγαλ", 30, 1),
	snowball.NewAmong("ολογαλ", 30, 1),
	snowball.NewAmong("βαθυγαλ", 30, 1),
	snowball.NewAmong("μελ", -1, 1),
	snowball.NewAmong("καστελ", -1, 1),
	snowball.NewAmong("πορτολ", -1, 1),
	snowball.NewAmong("πλ", -1, 1),
	snowball.NewAmong("διπλ", 37, 1),
	snowball.NewAmong("λαοπλ", 37, 1),
	snowball.NewAmong("ψυχοπλ", 37, 1),
	snowball.NewAmong("ουλ", -1, 1),
	snowball.NewAmong("μ", -1, 1),
	snowball.NewAmong("ολιγοδαμ", 42, 1),
	snowball.NewAmong("μουσουλμ", 42, 1),
	snowball.NewAmong("δραδουμ", 42, 1),
	snowball.NewAmong("βραχμ", 42, 1),
	snowball.NewAmong("ν", -1, 1),
	snowball.NewAmong("αμερικαν", 47, 1),
	snowball.NewAmong("π", -1, 1),
	snowball.NewAmong("αδαπ", 49, 1),
	snowball.NewAmong("χαμηλοδαπ", 49, 1),
	snowball.NewAmong("πολυδαπ", 49, 1),
	snowball.NewAmong("κοπ", 49, 1),
	snowball.NewAmong("υποκοπ", 53, 1),
	snowball.NewAmong("τσοπ", 49, 1),
	snowball.NewAmong("σπ", 49, 1),
	snowball.NewAmong("ερ", -1, 1),
	snowball.NewAmong("γερ", 57, 1),
	snowball.NewAmong("βετερ", 57, 1),
	snowball.NewAmong("λουθηρ", -1, 1),
	snowball.NewAmong("κορμορ", -1, 1),
	snowball.NewAmong("περιτρ", -1, 1),
	snowball.NewAmong("ουρ", -1, 1),
	snowball.NewAmong("σ", -1, 1),
	snowball.NewAmong("βασ", 64, 1),
	snowball.NewAmong("πολισ", 64, 1),
	snowball.NewAmong("σαρακατσ", 64, 1),
	snowball.NewAmong("θυσ", 64, 1),
	snowball.NewAmong("διατ", -1, 1),
	snowball.NewAmong("πλατ", -1, 1),
	snowball.NewAmong("τσαρλατ", -1, 1),
	snowball.NewAmong("τετ", -1, 1),
	snowball.NewAmong("πουριτ", -1, 1),
	snowball.NewAmong("σουλτ", -1, 1),
	snowball.NewAmong("μαιντ", -1, 1),
	snowball.NewAmong("ζωντ", -1, 1),
	snowball.NewAmong("καστ", -1, 1),
	snowball.NewAmong("φ", -1, 1),
	snowball.NewAmong("διαφ", 78, 1),
	snowball.NewAmong("στεφ", 78, 1),
	snowball.NewAmong("φωτοστεφ", 80, 1),
	snowball.NewAmong("περηφ", 78, 1),
	snowball.NewAmong("υπερηφ", 82, 1),
	snowball.NewAmong("κοιλαρφ", 78, 1),
	snowball.NewAmong("πενταρφ", 78, 1),
	snowball.NewAmong("ορφ", 78, 1),
	snowball.NewAmong("χ", -1, 1),
	snowball.NewAmong("αμηχ", 87, 1),
	snowball.NewAmong("βιομηχ", 87, 1),
	snowball.NewAmong("μεγλοβιομηχ", 89, 1),
	snowball.NewAmong("καπνοβιομηχ", 89, 1),
	snowball.NewAmong("μικροβιομηχ", 89, 1),
	snowball.NewAmong("πολυμηχ", 87, 1),
	snowball.NewAmong("λιχ", 87, 1),
}

var greekA40 = []*snowball.Among{
	snowball.NewAmong("ησετε", -1, 1),
}

var greekA41 = []*snowball.Among{
	snowball.NewAmong("ενδ", -1, 1),
	snowball.NewAmong("συνδ", -1, 1),
	snowball.NewAmong("οδ", -1, 1),
	snowball.NewAmong("διαθ", -1, 1),
	snowball.NewAmong("καθ", -1, 1),
	snowball.NewAmong("ραθ", -1, 1),
	snowball.NewAmong("ταθ", -1, 1),
	snowball.NewAmong("τιθ", -1, 1),
	snowball.NewAmong("εκθ", -1, 1),
	snowball.NewAmong("ενθ", -1, 1),
	snowball.NewAmong("συνθ", -1, 1),
	snowball.NewAmong("ροθ", -1, 1),
	snowball.NewAmong("υπερθ", -1, 1),
	snowball.NewAmong("σθ", -1, 1),
	snowball.NewAmong("ευθ", -1, 1),
	snowball.NewAmong("αρκ", -1, 1),
	snowball.NewAmong("ωφελ", -1, 1),
	snowball.NewAmong("βολ", -1, 1),
	snowball.NewAmong("αιν", -1, 1),
	snowball.NewAmong("πον", -1, 1),
	snowball.NewAmong("ρον", -1, 1),
	snowball.NewAmong("συν", -1, 1),
	snowball.NewAmong("βαρ", -1, 1),
	snowball.NewAmong("βρ", -1, 1),
	snowball.NewAmong("αιρ", -1, 1),
	snowball.NewAmong("φορ", -1, 1),
	snowball.NewAmong("ευρ", -1, 1),
	snowball.NewAmong("πυρ", -1, 1),
	snowball.NewAmong("χωρ", -1, 1),
	snowball.NewAmong("νετ", -1, 1),
	snowball.NewAmong("σχ", -1, 1),
}

var greekA42 = []*snowball.Among{
	snowball.NewAmong("παγ", -1, 1),
	snowball.NewAmong("δ", -1, 1),
	snowball.NewAmong("αδ", 1, 1),
	snowball.NewAmong("θ", -1, 1),
	snowball.NewAmong("αθ", 3, 1),
	snowball.NewAmong("τοκ", -1, 1),
	snowball.NewAmong("σκ", -1, 1),
	snowball.NewAmong("παρακαλ", -1, 1),
	snowball.NewAmong("σκελ", -1, 1),
	snowball.NewAmong("απλ", -1, 1),
	snowball.NewAmong("εμ", -1, 1),
	snowball.NewAmong("αν", -1, 1),
	snowball.NewAmong("βεν", -1, 1),
	snowball.NewAmong("βαρον", -1, 1),
	snowball.NewAmong("κοπ", -1, 1),
	snowball.NewAmong("σερπ", -1, 1),
	snowball.NewAmong("αβαρ", -1, 1),
	snowball.NewAmong("εναρ", -1, 1),
	snowball.NewAmong("αβρ", -1, 1),
	snowball.NewAmong("μπορ", -1, 1),
	snowball.NewAmong("θαρρ", -1, 1),
	snowball.NewAmong("ντρ", -1, 1),
	snowball.NewAmong("υ", -1, 1),
	snowball.NewAmong("νιφ", -1, 1),
	snowball.NewAmong("συρφ", -1, 1),
}

var greekA43 = []*snowball.Among{
	snowball.NewAmong("οντας", -1, 1),
	snowball.NewAmong("ωντας", -1, 1),
}

var greekA44 = []*snowball.Among{
	snowball.NewAmong("ομαστε", -1, 1),
	snowball.NewAmong("ιομαστε", 0, 1),
}

var greekA45 = []*snowball.Among{
	snowball.NewAmong("π", -1, 1),
	snowball.NewAmong("απ", 0, 1),
	snowball.NewAmong("ακαταπ", 1, 1),
	snowball.NewAmong("συμπ", 0, 1),
	snowball.NewAmong("ασυμπ", 3, 1),
	snowball.NewAmong("αμεταμφ", -1, 1),
}

var greekA46 = []*snowball.Among{
	snowball.NewAmong("ζ", -1, 1),
	snowball.NewAmong("αλ", -1, 1),
	snowball.NewAmong("παρακαλ", 1, 1),
	snowball.NewAmong("εκτελ", -1, 1),
	snowball.NewAmong("μ", -1, 1),
	snowball.NewAmong("ξ", -1, 1),
	snowball.NewAmong("προ", -1, 1),
	snowball.NewAmong("αρ", -1, 1),
	snowball.NewAmong("νισ", -1, 1),
}

var greekA47 = []*snowball.Among{
	snowball.NewAmong("ηθηκα", -1, 1),
	snowball.NewAmong("ηθηκε", -1, 1),
	snowball.NewAmong("ηθηκες", -1, 1),
}

var greekA48 = []*snowball.Among{
	snowball.NewAmong("πιθ", -1, 1),
	snowball.NewAmong("οθ", -1, 1),
	snowball.NewAmong("ναρθ", -1, 1),
	snowball.NewAmong("σκουλ", -1, 1),
	snowball.NewAmong("σκωλ", -1, 1),
	snowball.NewAmong("σφ", -1, 1),
}

var greekA49 = []*snowball.Among{
	snowball.NewAmong("θ", -1, 1),
	snowball.NewAmong("διαθ", 0, 1),
	snowball.NewAmong("παρακαταθ", 0, 1),
	snowball.NewAmong("συνθ", 0, 1),
	snowball.NewAmong("προσθ", 0, 1),
}

var greekA50 = []*snowball.Among{
	snowball.NewAmong("ηκα", -1, 1),
	snowball.NewAmong("ηκε", -1, 1),
	snowball.NewAmong("ηκες", -1, 1),
}

var greekA51 = []*snowball.Among{
	snowball.NewAmong("φαγ", -1, 1),
	snowball.NewAmong("ληγ", -1, 1),
	snowball.NewAmong("φρυδ", -1, 1),
	snowball.NewAmong("μαντιλ", -1, 1),
	snowball.NewAmong("μαλλ", -1, 1),
	snowball.NewAmong("ομ", -1, 1),
	snowball.NewAmong("βλεπ", -1, 1),
	snowball.NewAmong("ποδαρ", -1, 1),
	snowball.NewAmong("κυματ", -1, 1),
	snowball.NewAmong("πρωτ", -1, 1),
	snowball.NewAmong("λαχ", -1, 1),
	snowball.NewAmong("παντaχ", -1, 1),
}

var greekA52 = []*snowball.Among{
	snowball.NewAmong("τσα", -1, 1),
	snowball.NewAmong("χαδ", -1, 1),
	snowball.NewAmong("μεδ", -1, 1),
	snowball.NewAmong("λαμπιδ", -1, 1),
	snowball.NewAmong("δε", -1, 1),
	snowball.NewAmong("πλε", -1, 1),
	snowball.NewAmong("μεσαζ", -1, 1),
	snowball.NewAmong("δεσποζ", -1, 1),
	snowball.NewAmong("αιθ", -1, 1),
	snowball.NewAmong("φαρμακ", -1, 1),
	snowball.NewAmong("αγκ", -1, 1),
	snowball.NewAmong("ανηκ", -1, 1),
	snowball.NewAmong("λ", -1, 1),
	snowball.NewAmong("μ", -1, 1),
	snowball.NewAmong("αμ", 13, 1),
	snowball.NewAmong("βρομ", 13, 1),
	snowball.NewAmong("υποτειν", -1, 1),
	snowball.NewAmong("εκλιπ", -1, 1),
	snowball.NewAmong("ρ", -1, 1),
	snowball.NewAmong("ενδιαφερ", 18, 1),
	snowball.NewAmong("αναρρ", 18, 1),
	snowball.NewAmong("πατ", -1, 1),
	snowball.NewAmong("καθαρευ", -1, 1),
	snowball.NewAmong("δευτερευ", -1, 1),
	snowball.NewAmong("λεχ", -1, 1),
}

var greekA53 = []*snowball.Among{
	snowball.NewAmong("ουσα", -1, 1),
	snowball.NewAmong("ουσε", -1, 1),
	snowball.NewAmong("ουσες", -1, 1),
}

var greekA54 = []*snowball.Among{
	snowball.NewAmong("πελ", -1, 1),
	snowball.NewAmong("λλ", -1, 1),
	snowball.NewAmong("σμην", -1, 1),
	snowball.NewAmong("ρπ", -1, 1),
	snowball.NewAmong("πρ", -1, 1),
	snowball.NewAmong("φρ", -1, 1),
	snowball.NewAmong("χορτ", -1, 1),
	snowball.NewAmong("οφ", -1, 1),
	snowball.NewAmong("ψοφ", 7, -1),
	snowball.NewAmong("σφ", -1, 1),
	snowball.NewAmong("λοχ", -1, 1),
	snowball.NewAmong("ναυλοχ", 10, -1),
}

var greekA55 = []*snowball.Among{
	snowball.NewAmong("αμαλλι", -1, 1),
	snowball.NewAmong("λ", -1, 1),
	snowball.NewAmong("αμαλ", 1, 1),
	snowball.NewAmong("μ", -1, 1),
	snowball.NewAmong("ουλαμ", 3, 1),
	snowball.NewAmong("εν", -1, 1),
	snowball.NewAmong("δερβεν", 5, 1),
	snowball.NewAmong("π", -1, 1),
	snowball.NewAmong("αειπ", 7, 1),
	snowball.NewAmong("αρτιπ", 7, 1),
	snowball.NewAmong("συμπ", 7, 1),
	snowball.NewAmong("νεοπ", 7, 1),
	snowball.NewAmong("κροκαλοπ", 7, 1),
	snowball.NewAmong("ολοπ", 7, 1),
	snowball.NewAmong("προσωποπ", 7, 1),
	snowball.NewAmong("σιδηροπ", 7, 1),
	snowball.NewAmong("δροσοπ", 7, 1),
	snowball.NewAmong("ασπ", 7, 1),
	snowball.NewAmong("ανυπ", 7, 1),
	snowball.NewAmong("ρ", -1, 1),
	snowball.NewAmong("ασπαρ", 19, 1),
	snowball.NewAmong("χαρ", 19, 1),
	snowball.NewAmong("αχαρ", 21, 1),
	snowball.NewAmong("απερ", 19, 1),
	snowball.NewAmong("τρ", 19, 1),
	snowball.NewAmong("ουρ", 19, 1),
	snowball.NewAmong("τ", -1, 1),
	snowball.NewAmong("διατ", 26, 1),
	snowball.NewAmong("επιτ", 26, 1),
	snowball.NewAmong("συντ", 26, 1),
	snowball.NewAmong("ομοτ", 26, 1),
	snowball.NewAmong("νομοτ", 30, 1),
	snowball.NewAmong("αποτ", 26, 1),
	snowball.NewAmong("υποτ", 26, 1),
	snowball.NewAmong("αβαστ", 26, 1),
	snowball.NewAmong("αιμοστ", 26, 1),
	snowball.NewAmong("προστ", 26, 1),
	snowball.NewAmong("ανυστ", 26, 1),
	snowball.NewAmong("ναυ", -1, 1),
	snowball.NewAmong("αφ", -1, 1),
	snowball.NewAmong("ξεφ", -1, 1),
	snowball.NewAmong("αδηφ", -1, 1),
	snowball.NewAmong("παμφ", -1, 1),
	snowball.NewAmong("πολυφ", -1, 1),
}

var greekA56 = []*snowball.Among{
	snowball.NewAmong("αγα", -1, 1),
	snowball.NewAmong("αγε", -1, 1),
	snowball.NewAmong("αγες", -1, 1),
}

var greekA57 = []*snowball.Among{
	snowball.NewAmong("ησα", -1, 1),
	snowball.NewAmong("ησε", -1, 1),
	snowball.NewAmong("ησου", -1, 1),
}

var greekA58 = []*snowball.Among{
	snowball.NewAmong("ν", -1, 1),
	snowball.NewAmong("δωδεκαν", 0, 1),
	snowball.NewAmong("επταν", 0, 1),
	snowball.NewAmong("μεγαλον", 0, 1),
	snowball.NewAmong("ερημον", 0, 1),
	snowball.NewAmong("χερσον", 0, 1),
}

var greekA59 = []*snowball.Among{
	snowball.NewAmong("ηστε", -1, 1),
}

var greekA60 = []*snowball.Among{
	snowball.NewAmong("σβ", -1, 1),
	snowball.NewAmong("ασβ", 0, 1),
	snowball.NewAmong("απλ", -1, 1),
	snowball.NewAmong("αειμν", -1, 1),
	snowball.NewAmong("χρ", -1, 1),
	snowball.NewAmong("αχρ", 4, 1),
	snowball.NewAmong("κοινοχρ", 4, 1),
	snowball.NewAmong("δυσχρ", 4, 1),
	snowball.NewAmong("ευχρ", 4, 1),
	snowball.NewAmong("παλιμψ", -1, 1),
}

var greekA61 = []*snowball.Among{
	snowball.NewAmong("ουνε", -1, 1),
	snowball.NewAmong("ηθουνε", 0, 1),
	snowball.NewAmong("ησουνε", 0, 1),
}

var greekA62 = []*snowball.Among{
	snowball.NewAmong("σπι", -1, 1),
	snowball.NewAmong("ν", -1, 1),
	snowball.NewAmong("εξων", 1, 1),
	snowball.NewAmong("ρ", -1, 1),
	snowball.NewAmong("στραβομουτσ", -1, 1),
	snowball.NewAmong("κακομουτσ", -1, 1),
}

var greekA63 = []*snowball.Among{
	snowball.NewAmong("ουμε", -1, 1),
	snowball.NewAmong("ηθουμε", 0, 1),
	snowball.NewAmong("ησουμε", 0, 1),
}

var greekA64 = []*snowball.Among{
	snowball.NewAmong("αζ", -1, 1),
	snowball.NewAmong("ωριοπλ", -1, 1),
	snowball.NewAmong("ασους", -1, 1),
	snowball.NewAmong("παρασους", 2, 1),
	snowball.NewAmong("αλλοσους", -1, 1),
	snowball.NewAmong("φ", -1, 1),
	snowball.NewAmong("χ", -1, 1),
}

var greekA65 = []*snowball.Among{
	snowball.NewAmong("ματα", -1, 1),
	snowball.NewAmong("ματων", -1, 1),
	snowball.NewAmong("ματος", -1, 1),
}

var greekA66 = []*snowball.Among{
	snowball.NewAmong("α", -1, 1),
	snowball.NewAmong("ιουμα", 0, 1),
	snowball.NewAmong("ομουνα", 0, 1),
	snowball.NewAmong("ιομουνα", 2, 1),
	snowball.NewAmong("οσουνα", 0, 1),
	snowball.NewAmong("ιοσουνα", 4, 1),
	snowball.NewAmong("ε", -1, 1),
	snowball.NewAmong("αγατε", 6, 1),
	snowball.NewAmong("ηκατε", 6, 1),
	snowball.NewAmong("ηθηκατε", 8, 1),
	snowball.NewAmong("ησατε", 6, 1),
	snowball.NewAmong("ουσατε", 6, 1),
	snowball.NewAmong("ειτε", 6, 1),
	snowball.NewAmong("ηθειτε", 12, 1),
	snowball.NewAmong("ιεμαστε", 6, 1),
	snowball.NewAmong("ουμαστε", 6, 1),
	snowball.NewAmong("ιουμαστε", 15, 1),
	snowball.NewAmong("ιεσαστε", 6, 1),
	snowball.NewAmong("οσαστε", 6, 1),
	snowball.NewAmong("ιοσαστε", 18, 1),
	snowball.NewAmong("η", -1, 1),
	snowball.NewAmong("ι", -1, 1),
	snowball.NewAmong("αμαι", 21, 1),
	snowball.NewAmong("ιεμαι", 21, 1),
	snowball.NewAmong("ομαι", 21, 1),
	snowball.NewAmong("ουμαι", 21, 1),
	snowball.NewAmong("ασαι", 21, 1),
	snowball.NewAmong("εσαι", 21, 1),
	snowball.NewAmong("ιεσαι", 27, 1),
	snowball.NewAmong("αταi", 21, 1),
	snowball.NewAmong("εταi", 21, 1),
	snowball.NewAmong("ιεταi", 30, 1),
	snowball.NewAmong("onται", 21, 1),
	snowball.NewAmong("ουνται", 21, 1),
	snowball.NewAmong("ιουνται", 33, 1),
	snowball.NewAmong("ει", 21, 1),
	snowball.NewAmong("αει", 35, 1),
	snowball.NewAmong("ηθει", 35, 1),
	snowball.NewAmong("ησει", 35, 1),
	snowball.NewAmong("οι", 21, 1),
	snowball.NewAmong("αν", -1, 1),
	snowball.NewAmong("αγαν", 40, 1),
	snowball.NewAmong("ηκαν", 40, 1),
	snowball.NewAmong("ηθηκαν", 42, 1),
	snowball.NewAmong("ησαν", 40, 1),
	snowball.NewAmong("ουσαν", 40, 1),
	snowball.NewAmong("οντουσαν", 45, 1),
	snowball.NewAmong("ιοντουσαν", 46, 1),
	snowball.NewAmong("ονταν", 40, 1),
	snowball.NewAmong("ιονταν", 48, 1),
	snowball.NewAmong("ουνταν", 40, 1),
	snowball.NewAmong("ιουνταν", 50, 1),
	snowball.NewAmong("οταν", 40, 1),
	snowball.NewAmong("ιοταν", 52, 1),
	snowball.NewAmong("ομασταν", 40, 1),
	snowball.NewAmong("ιομασταν", 54, 1),
	snowball.NewAmong("οσασταν", 40, 1),
	snowball.NewAmong("ιοσασταν", 56, 1),
	snowball.NewAmong("ουν", -1, 1),
	snowball.NewAmong("ηθουν", 58, 1),
	snowball.NewAmong("ομουν", 58, 1),
	snowball.NewAmong("ιομουν", 60, 1),
	snowball.NewAmong("ησουν", 58, 1),
	snowball.NewAmong("οσουν", 58, 1),
	snowball.NewAmong("ιοσουν", 63, 1),
	snowball.NewAmong("ων", -1, 1),
	snowball.NewAmong("ηδων", 65, 1),
	snowball.NewAmong("ο", -1, 1),
	snowball.NewAmong("ας", -1, 1),
	snowball.NewAmong("ες", -1, 1),
	snowball.NewAmong("ηδες", 69, 1),
	snowball.NewAmong("ησες", 69, 1),
	snowball.NewAmong("ης", -1, 1),
	snowball.NewAmong("εις", -1, 1),
	snowball.NewAmong("ηθεις", 73, 1),
	snowball.NewAmong("ος", -1, 1),
	snowball.NewAmong("υς", -1, 1),
	snowball.NewAmong("ους", 76, 1),
	snowball.NewAmong("υ", -1, 1),
	snowball.NewAmong("ου", 78, 1),
	snowball.NewAmong("ω", -1, 1),
	snowball.NewAmong("αω", 80, 1),
	snowball.NewAmong("ηθω", 80, 1),
	snowball.NewAmong("ησω", 80, 1),
}

var greekA67 = []*snowball.Among{
	snowball.NewAmong("οτερ", -1, 1),
	snowball.NewAmong("εστερ", -1, 1),
	snowball.NewAmong("υτερ", -1, 1),
	snowball.NewAmong("ωτερ", -1, 1),
	snowball.NewAmong("οτατ", -1, 1),
	snowball.NewAmong("εστατ", -1, 1),
	snowball.NewAmong("υτατ", -1, 1),
	snowball.NewAmong("ωτατ", -1, 1),
}

var greekGV = []byte{81, 65, 16, 1}
var greekGV2 = []byte{81, 65, 0, 1}

func (s *GreekStemmer) rHasMinLength() bool {
	return s.SnowballProgram.Length >= 3
}

func (s *GreekStemmer) rTolower() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Limit - p.Cursor
	lab0:
		for {
			p.Ket = p.Cursor
			amongVar := p.FindAmongB(greekA0)
			p.Bra = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("α")
			case 2:
				p.SliceFromStr("β")
			case 3:
				p.SliceFromStr("γ")
			case 4:
				p.SliceFromStr("δ")
			case 5:
				p.SliceFromStr("ε")
			case 6:
				p.SliceFromStr("ζ")
			case 7:
				p.SliceFromStr("η")
			case 8:
				p.SliceFromStr("θ")
			case 9:
				p.SliceFromStr("ι")
			case 10:
				p.SliceFromStr("κ")
			case 11:
				p.SliceFromStr("λ")
			case 12:
				p.SliceFromStr("μ")
			case 13:
				p.SliceFromStr("ν")
			case 14:
				p.SliceFromStr("ξ")
			case 15:
				p.SliceFromStr("ο")
			case 16:
				p.SliceFromStr("π")
			case 17:
				p.SliceFromStr("ρ")
			case 18:
				p.SliceFromStr("σ")
			case 19:
				p.SliceFromStr("τ")
			case 20:
				p.SliceFromStr("υ")
			case 21:
				p.SliceFromStr("φ")
			case 22:
				p.SliceFromStr("χ")
			case 23:
				p.SliceFromStr("ψ")
			case 24:
				p.SliceFromStr("ω")
			case 25:
				if p.Cursor <= p.LimitBackward {
					break lab0
				}
				p.Cursor--
			}
			continue
		}
		p.Cursor = p.Limit - v1
		break
	}
	return true
}

func (s *GreekStemmer) rStep1() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(greekA1)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		p.SliceFromStr("φα")
	case 2:
		p.SliceFromStr("σκα")
	case 3:
		p.SliceFromStr("ολο")
	case 4:
		p.SliceFromStr("σο")
	case 5:
		p.SliceFromStr("τατο")
	case 6:
		p.SliceFromStr("κρε")
	case 7:
		p.SliceFromStr("περ")
	case 8:
		p.SliceFromStr("τερ")
	case 9:
		p.SliceFromStr("φω")
	case 10:
		p.SliceFromStr("καθεστ")
	case 11:
		p.SliceFromStr("γεγον")
	}
	s.bTest1 = false
	return true
}

func (s *GreekStemmer) rSteps1() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA3) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	amongVar := p.FindAmongB(greekA2)
	if amongVar == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceFromStr("ι")
	case 2:
		p.SliceFromStr("ιζ")
	}
	return true
}

func (s *GreekStemmer) rSteps2() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA5) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA4) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ων")
	return true
}

func (s *GreekStemmer) rSteps3() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA7) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			if !p.EqSBStr("ισα") {
				break lab1
			}
			if p.Cursor > p.LimitBackward {
				break lab1
			}
			p.SliceFromStr("ισ")
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		amongVar := p.FindAmongB(greekA6)
		if amongVar == 0 {
			return false
		}
		if p.Cursor > p.LimitBackward {
			return false
		}
		switch amongVar {
		case 1:
			p.SliceFromStr("ι")
		case 2:
			p.SliceFromStr("ισ")
		}
	}
	return true
}

func (s *GreekStemmer) rSteps4() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA9) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA8) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ι")
	return true
}

func (s *GreekStemmer) rSteps5() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA11) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	amongVar := p.FindAmongB(greekA10)
	if amongVar == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	switch amongVar {
	case 1:
		p.SliceFromStr("ι")
	case 2:
		p.SliceFromStr("ιστ")
	}
	return true
}

func (s *GreekStemmer) rSteps6() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA14) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			amongVar := p.FindAmongB(greekA12)
			if amongVar == 0 {
				break lab1
			}
			if p.Cursor > p.LimitBackward {
				break lab1
			}
			switch amongVar {
			case 1:
				p.SliceFromStr("ισμ")
			case 2:
				p.SliceFromStr("ι")
			}
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(greekA13)
		if amongVar == 0 {
			return false
		}
		p.Bra = p.Cursor
		switch amongVar {
		case 1:
			p.SliceFromStr("αγνωστ")
		case 2:
			p.SliceFromStr("ατομ")
		case 3:
			p.SliceFromStr("γνωστ")
		case 4:
			p.SliceFromStr("εθν")
		case 5:
			p.SliceFromStr("εκλεκτ")
		case 6:
			p.SliceFromStr("σκεπτ")
		case 7:
			p.SliceFromStr("τοπ")
		case 8:
			p.SliceFromStr("αλεξανδρ")
		case 9:
			p.SliceFromStr("βυζαντ")
		case 10:
			p.SliceFromStr("θεατρ")
		}
	}
	return true
}

func (s *GreekStemmer) rSteps7() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA16) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA15) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("αρακ")
	return true
}

func (s *GreekStemmer) rSteps8() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA18) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			amongVar := p.FindAmongB(greekA17)
			if amongVar == 0 {
				break lab1
			}
			if p.Cursor > p.LimitBackward {
				break lab1
			}
			switch amongVar {
			case 1:
				p.SliceFromStr("ακ")
			case 2:
				p.SliceFromStr("ιτσ")
			}
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if !p.EqSBStr("κορ") {
			return false
		}
		p.SliceFromStr("ιτσ")
	}
	return true
}

func (s *GreekStemmer) rSteps9() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA21) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if p.FindAmongB(greekA19) == 0 {
				break lab1
			}
			if p.Cursor > p.LimitBackward {
				break lab1
			}
			p.SliceFromStr("ιδ")
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if p.FindAmongB(greekA20) == 0 {
			return false
		}
		p.SliceFromStr("ιδ")
	}
	return true
}

func (s *GreekStemmer) rSteps10() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA23) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA22) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ισκ")
	return true
}

func (s *GreekStemmer) rStep2a() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA24) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	v1 := p.Limit - p.Cursor
lab0:
	for {
		if p.FindAmongB(greekA25) == 0 {
			break lab0
		}
		return false
	}
	p.Cursor = p.Limit - v1
	c := p.Cursor
	p.InsertStr(p.Cursor, p.Cursor, "αδ")
	p.Cursor = c
	return true
}

func (s *GreekStemmer) rStep2b() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA26) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA27) == 0 {
		return false
	}
	p.SliceFromStr("εδ")
	return true
}

func (s *GreekStemmer) rStep2c() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA28) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA29) == 0 {
		return false
	}
	p.SliceFromStr("ουδ")
	return true
}

func (s *GreekStemmer) rStep2d() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA30) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA31) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ε")
	return true
}

func (s *GreekStemmer) rStep3() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA32) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if !p.InGroupingB(greekGV, 945, 969) {
		return false
	}
	p.SliceFromStr("ι")
	return true
}

func (s *GreekStemmer) rStep4() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA33) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if !p.InGroupingB(greekGV, 945, 969) {
				break lab1
			}
			p.SliceFromStr("ικ")
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
	}
	p.Bra = p.Cursor
	if p.FindAmongB(greekA34) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ικ")
	return true
}

func (s *GreekStemmer) rStep5a() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		if !p.EqSBStr("αγαμε") {
			break lab0
		}
		if p.Cursor > p.LimitBackward {
			break lab0
		}
		p.SliceFromStr("αγαμ")
	}
	p.Cursor = p.Limit - v1
	v2 := p.Limit - p.Cursor
lab1:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(greekA35) == 0 {
			break lab1
		}
		p.Bra = p.Cursor
		p.SliceDel()
		s.bTest1 = false
	}
	p.Cursor = p.Limit - v2
	p.Ket = p.Cursor
	if !p.EqSBStr("αμε") {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA36) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("αμ")
	return true
}

func (s *GreekStemmer) rStep5b() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(greekA38) == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceDel()
		s.bTest1 = false
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if p.FindAmongB(greekA37) == 0 {
			break lab0
		}
		if p.Cursor > p.LimitBackward {
			break lab0
		}
		p.SliceFromStr("αγαν")
	}
	p.Cursor = p.Limit - v1
	p.Ket = p.Cursor
	if !p.EqSBStr("ανε") {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab1:
	for {
		v2 := p.Limit - p.Cursor
	lab2:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if !p.InGroupingB(greekGV2, 945, 969) {
				break lab2
			}
			p.SliceFromStr("αν")
			break lab1
		}
		p.Cursor = p.Limit - v2
		p.Ket = p.Cursor
	}
	p.Bra = p.Cursor
	if p.FindAmongB(greekA39) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("αν")
	return true
}

func (s *GreekStemmer) rStep5c() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(greekA40) == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceDel()
		s.bTest1 = false
	}
	p.Cursor = p.Limit - v1
	p.Ket = p.Cursor
	if !p.EqSBStr("ετε") {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab1:
	for {
		v2 := p.Limit - p.Cursor
	lab2:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if !p.InGroupingB(greekGV2, 945, 969) {
				break lab2
			}
			p.SliceFromStr("ετ")
			break lab1
		}
		p.Cursor = p.Limit - v2
	lab3:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if p.FindAmongB(greekA41) == 0 {
				break lab3
			}
			p.SliceFromStr("ετ")
			break lab1
		}
		p.Cursor = p.Limit - v2
		p.Ket = p.Cursor
	}
	p.Bra = p.Cursor
	if p.FindAmongB(greekA42) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ετ")
	return true
}

func (s *GreekStemmer) rStep5d() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA43) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if !p.EqSBStr("αρχ") {
				break lab1
			}
			if p.Cursor > p.LimitBackward {
				break lab1
			}
			p.SliceFromStr("οντ")
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if !p.EqSBStr("κρε") {
			return false
		}
		p.SliceFromStr("ωντ")
	}
	return true
}

func (s *GreekStemmer) rStep5e() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA44) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if !p.EqSBStr("ον") {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ομαστ")
	return true
}

func (s *GreekStemmer) rStep5f() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("ιεστε") {
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceDel()
		s.bTest1 = false
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if p.FindAmongB(greekA45) == 0 {
			break lab0
		}
		if p.Cursor > p.LimitBackward {
			break lab0
		}
		p.SliceFromStr("ιεστ")
	}
	p.Cursor = p.Limit - v1
	p.Ket = p.Cursor
	if !p.EqSBStr("εστε") {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA46) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ιεστ")
	return true
}

func (s *GreekStemmer) rStep5g() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(greekA47) == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceDel()
		s.bTest1 = false
	}
	p.Cursor = p.Limit - v1
	p.Ket = p.Cursor
	if p.FindAmongB(greekA50) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab1:
	for {
		v2 := p.Limit - p.Cursor
	lab2:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if p.FindAmongB(greekA48) == 0 {
				break lab2
			}
			p.SliceFromStr("ηκ")
			break lab1
		}
		p.Cursor = p.Limit - v2
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if p.FindAmongB(greekA49) == 0 {
			return false
		}
		if p.Cursor > p.LimitBackward {
			return false
		}
		p.SliceFromStr("ηκ")
	}
	return true
}

func (s *GreekStemmer) rStep5h() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA53) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if p.FindAmongB(greekA51) == 0 {
				break lab1
			}
			p.SliceFromStr("ους")
			break lab0
		}
		p.Cursor = p.Limit - v1
		p.Ket = p.Cursor
		p.Bra = p.Cursor
		if p.FindAmongB(greekA52) == 0 {
			return false
		}
		if p.Cursor > p.LimitBackward {
			return false
		}
		p.SliceFromStr("ους")
	}
	return true
}

func (s *GreekStemmer) rStep5i() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA56) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
lab0:
	for {
		v1 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if !p.EqSBStr("κολλ") {
				break lab1
			}
			p.SliceFromStr("αγ")
			break lab0
		}
		p.Cursor = p.Limit - v1
	lab2:
		for {
			v2 := p.Limit - p.Cursor
		lab3:
			for {
				p.Ket = p.Cursor
				p.Bra = p.Cursor
				amongVar := p.FindAmongB(greekA54)
				if amongVar == 0 {
					break lab3
				}
				switch amongVar {
				case 1:
					p.SliceFromStr("αγ")
				}
				break lab2
			}
			p.Cursor = p.Limit - v2
			p.Ket = p.Cursor
			p.Bra = p.Cursor
			if p.FindAmongB(greekA55) == 0 {
				return false
			}
			if p.Cursor > p.LimitBackward {
				return false
			}
			p.SliceFromStr("αγ")
		}
	}
	return true
}

func (s *GreekStemmer) rStep5j() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA57) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA58) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ης")
	return true
}

func (s *GreekStemmer) rStep5k() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA59) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA60) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ηστ")
	return true
}

func (s *GreekStemmer) rStep5l() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA61) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA62) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ουν")
	return true
}

func (s *GreekStemmer) rStep5m() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA63) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	s.bTest1 = false
	p.Ket = p.Cursor
	p.Bra = p.Cursor
	if p.FindAmongB(greekA64) == 0 {
		return false
	}
	if p.Cursor > p.LimitBackward {
		return false
	}
	p.SliceFromStr("ουμ")
	return true
}

func (s *GreekStemmer) rStep6() bool {
	p := s.SnowballProgram
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		if p.FindAmongB(greekA65) == 0 {
			break lab0
		}
		p.Bra = p.Cursor
		p.SliceFromStr("μα")
	}
	p.Cursor = p.Limit - v1
	if !s.bTest1 {
		return false
	}
	p.Ket = p.Cursor
	if p.FindAmongB(greekA66) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *GreekStemmer) rStep7() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(greekA67) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

// Stem applies the Greek Snowball stemming algorithm.
func (s *GreekStemmer) Stem() bool {
	p := s.SnowballProgram
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v1 := p.Limit - p.Cursor
	s.rTolower()
	p.Cursor = p.Limit - v1
	if !s.rHasMinLength() {
		return false
	}
	s.bTest1 = true
	v2 := p.Limit - p.Cursor
	s.rStep1()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
	s.rSteps1()
	p.Cursor = p.Limit - v3
	v4 := p.Limit - p.Cursor
	s.rSteps2()
	p.Cursor = p.Limit - v4
	v5 := p.Limit - p.Cursor
	s.rSteps3()
	p.Cursor = p.Limit - v5
	v6 := p.Limit - p.Cursor
	s.rSteps4()
	p.Cursor = p.Limit - v6
	v7 := p.Limit - p.Cursor
	s.rSteps5()
	p.Cursor = p.Limit - v7
	v8 := p.Limit - p.Cursor
	s.rSteps6()
	p.Cursor = p.Limit - v8
	v9 := p.Limit - p.Cursor
	s.rSteps7()
	p.Cursor = p.Limit - v9
	v10 := p.Limit - p.Cursor
	s.rSteps8()
	p.Cursor = p.Limit - v10
	v11 := p.Limit - p.Cursor
	s.rSteps9()
	p.Cursor = p.Limit - v11
	v12 := p.Limit - p.Cursor
	s.rSteps10()
	p.Cursor = p.Limit - v12
	v13 := p.Limit - p.Cursor
	s.rStep2a()
	p.Cursor = p.Limit - v13
	v14 := p.Limit - p.Cursor
	s.rStep2b()
	p.Cursor = p.Limit - v14
	v15 := p.Limit - p.Cursor
	s.rStep2c()
	p.Cursor = p.Limit - v15
	v16 := p.Limit - p.Cursor
	s.rStep2d()
	p.Cursor = p.Limit - v16
	v17 := p.Limit - p.Cursor
	s.rStep3()
	p.Cursor = p.Limit - v17
	v18 := p.Limit - p.Cursor
	s.rStep4()
	p.Cursor = p.Limit - v18
	v19 := p.Limit - p.Cursor
	s.rStep5a()
	p.Cursor = p.Limit - v19
	v20 := p.Limit - p.Cursor
	s.rStep5b()
	p.Cursor = p.Limit - v20
	v21 := p.Limit - p.Cursor
	s.rStep5c()
	p.Cursor = p.Limit - v21
	v22 := p.Limit - p.Cursor
	s.rStep5d()
	p.Cursor = p.Limit - v22
	v23 := p.Limit - p.Cursor
	s.rStep5e()
	p.Cursor = p.Limit - v23
	v24 := p.Limit - p.Cursor
	s.rStep5f()
	p.Cursor = p.Limit - v24
	v25 := p.Limit - p.Cursor
	s.rStep5g()
	p.Cursor = p.Limit - v25
	v26 := p.Limit - p.Cursor
	s.rStep5h()
	p.Cursor = p.Limit - v26
	v27 := p.Limit - p.Cursor
	s.rStep5j()
	p.Cursor = p.Limit - v27
	v28 := p.Limit - p.Cursor
	s.rStep5i()
	p.Cursor = p.Limit - v28
	v29 := p.Limit - p.Cursor
	s.rStep5k()
	p.Cursor = p.Limit - v29
	v30 := p.Limit - p.Cursor
	s.rStep5l()
	p.Cursor = p.Limit - v30
	v31 := p.Limit - p.Cursor
	s.rStep5m()
	p.Cursor = p.Limit - v31
	v32 := p.Limit - p.Cursor
	s.rStep6()
	p.Cursor = p.Limit - v32
	v33 := p.Limit - p.Cursor
	s.rStep7()
	p.Cursor = p.Limit - v33
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*GreekStemmer)(nil)
