// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// HindiStemmer implements the Hindi Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.HindiStemmer
// from Apache Lucene 10.4.0.
//
// Deviation from Java: Java uses java.lang.invoke.MethodHandle for the
// r_CONSONANT callback attached to some Among entries. In Go, the callback
// is passed as a func(*snowball.SnowballProgram) bool closure that
// reads only from the package-level hindiGConsonant table (no instance state).
type HindiStemmer struct {
	*snowball.SnowballProgram
}

// NewHindiStemmer creates a new HindiStemmer.
func NewHindiStemmer() *HindiStemmer {
	return &HindiStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var hindiGConsonant = []byte{255, 255, 255, 255, 159, 0, 0, 0, 248, 7}

func hindiRConsonant(p *snowball.SnowballProgram) bool {
	return p.InGroupingB(hindiGConsonant, 2325, 2399)
}

// hindiA0 is built during package init so that the method-object callbacks
// can be registered as func literals (the Java source uses MethodHandle
// bound to r_CONSONANT).
var hindiA0 []*snowball.Among

func init() {
	// Entries that have no callback use NewAmong; entries that require
	// r_CONSONANT use NewAmongMethod(hindiRConsonant).
	// Index map is faithful to the Java source order.
	hindiA0 = []*snowball.Among{
		snowball.NewAmong("आँ", -1, -1),
		snowball.NewAmong("ाँ", -1, -1),
		snowball.NewAmong("इयाँ", 1, -1),
		snowball.NewAmong("आइयाँ", 2, -1),
		snowball.NewAmong("ाइयाँ", 2, -1),
		snowball.NewAmong("ियाँ", 1, -1),
		snowball.NewAmong("आं", -1, -1),
		snowball.NewAmong("उआं", 6, -1),
		snowball.NewAmong("ुआं", 6, -1),
		snowball.NewAmong("ईं", -1, -1),
		snowball.NewAmong("आईं", 9, -1),
		snowball.NewAmong("ाईं", 9, -1),
		snowball.NewAmong("एं", -1, -1),
		snowball.NewAmong("आएं", 12, -1),
		snowball.NewAmong("उएं", 12, -1),
		snowball.NewAmong("ाएं", 12, -1),
		snowball.NewAmongMethod("ताएं", 15, -1, hindiRConsonant),
		snowball.NewAmong("अताएं", 16, -1),
		snowball.NewAmongMethod("नाएं", 15, -1, hindiRConsonant),
		snowball.NewAmong("अनाएं", 18, -1),
		snowball.NewAmong("ुएं", 12, -1),
		snowball.NewAmong("ओं", -1, -1),
		snowball.NewAmong("आओं", 21, -1),
		snowball.NewAmong("उओं", 21, -1),
		snowball.NewAmong("ाओं", 21, -1),
		snowball.NewAmongMethod("ताओं", 24, -1, hindiRConsonant),
		snowball.NewAmong("अताओं", 25, -1),
		snowball.NewAmongMethod("नाओं", 24, -1, hindiRConsonant),
		snowball.NewAmong("अनाओं", 27, -1),
		snowball.NewAmong("ुओं", 21, -1),
		snowball.NewAmong("ां", -1, -1),
		snowball.NewAmong("इयां", 30, -1),
		snowball.NewAmong("आइयां", 31, -1),
		snowball.NewAmong("ाइयां", 31, -1),
		snowball.NewAmong("ियां", 30, -1),
		snowball.NewAmong("ीं", -1, -1),
		snowball.NewAmongMethod("तीं", 35, -1, hindiRConsonant),
		snowball.NewAmong("अतीं", 36, -1),
		snowball.NewAmong("आतीं", 36, -1),
		snowball.NewAmong("ातीं", 36, -1),
		snowball.NewAmong("ें", -1, -1),
		snowball.NewAmong("ों", -1, -1),
		snowball.NewAmong("इयों", 41, -1),
		snowball.NewAmong("आइयों", 42, -1),
		snowball.NewAmong("ाइयों", 42, -1),
		snowball.NewAmong("ियों", 41, -1),
		snowball.NewAmong("अ", -1, -1),
		snowball.NewAmong("आ", -1, -1),
		snowball.NewAmong("इ", -1, -1),
		snowball.NewAmong("ई", -1, -1),
		snowball.NewAmong("आई", 49, -1),
		snowball.NewAmong("ाई", 49, -1),
		snowball.NewAmong("उ", -1, -1),
		snowball.NewAmong("ऊ", -1, -1),
		snowball.NewAmong("ए", -1, -1),
		snowball.NewAmong("आए", 54, -1),
		snowball.NewAmong("इए", 54, -1),
		snowball.NewAmong("आइए", 56, -1),
		snowball.NewAmong("ाइए", 56, -1),
		snowball.NewAmong("ाए", 54, -1),
		snowball.NewAmong("िए", 54, -1),
		snowball.NewAmong("ओ", -1, -1),
		snowball.NewAmong("आओ", 61, -1),
		snowball.NewAmong("ाओ", 61, -1),
		snowball.NewAmongMethod("कर", -1, -1, hindiRConsonant),
		snowball.NewAmong("अकर", 64, -1),
		snowball.NewAmong("आकर", 64, -1),
		snowball.NewAmong("ाकर", 64, -1),
		snowball.NewAmong("ा", -1, -1),
		snowball.NewAmong("ऊंगा", 68, -1),
		snowball.NewAmong("आऊंगा", 69, -1),
		snowball.NewAmong("ाऊंगा", 69, -1),
		snowball.NewAmong("ूंगा", 68, -1),
		snowball.NewAmong("एगा", 68, -1),
		snowball.NewAmong("आएगा", 73, -1),
		snowball.NewAmong("ाएगा", 73, -1),
		snowball.NewAmong("ेगा", 68, -1),
		snowball.NewAmongMethod("ता", 68, -1, hindiRConsonant),
		snowball.NewAmong("अता", 77, -1),
		snowball.NewAmong("आता", 77, -1),
		snowball.NewAmong("ाता", 77, -1),
		snowball.NewAmongMethod("ना", 68, -1, hindiRConsonant),
		snowball.NewAmong("अना", 81, -1),
		snowball.NewAmong("आना", 81, -1),
		snowball.NewAmong("ाना", 81, -1),
		snowball.NewAmong("आया", 68, -1),
		snowball.NewAmong("ाया", 68, -1),
		snowball.NewAmong("ि", -1, -1),
		snowball.NewAmong("ी", -1, -1),
		snowball.NewAmong("ऊंगी", 88, -1),
		snowball.NewAmong("आऊंगी", 89, -1),
		snowball.NewAmong("ाऊंगी", 89, -1),
		snowball.NewAmong("एंगी", 88, -1),
		snowball.NewAmong("आएंगी", 92, -1),
		snowball.NewAmong("ाएंगी", 92, -1),
		snowball.NewAmong("ूंगी", 88, -1),
		snowball.NewAmong("ेंगी", 88, -1),
		snowball.NewAmong("एगी", 88, -1),
		snowball.NewAmong("आएगी", 97, -1),
		snowball.NewAmong("ाएगी", 97, -1),
		snowball.NewAmong("ओगी", 88, -1),
		snowball.NewAmong("आओगी", 100, -1),
		snowball.NewAmong("ाओगी", 100, -1),
		snowball.NewAmong("ेगी", 88, -1),
		snowball.NewAmong("ोगी", 88, -1),
		snowball.NewAmongMethod("ती", 88, -1, hindiRConsonant),
		snowball.NewAmong("अती", 105, -1),
		snowball.NewAmong("आती", 105, -1),
		snowball.NewAmong("ाती", 105, -1),
		snowball.NewAmongMethod("नी", 88, -1, hindiRConsonant),
		snowball.NewAmong("अनी", 109, -1),
		snowball.NewAmong("ु", -1, -1),
		snowball.NewAmong("ू", -1, -1),
		snowball.NewAmong("े", -1, -1),
		snowball.NewAmong("एंगे", 113, -1),
		snowball.NewAmong("आएंगे", 114, -1),
		snowball.NewAmong("ाएंगे", 114, -1),
		snowball.NewAmong("ेंगे", 113, -1),
		snowball.NewAmong("ओगे", 113, -1),
		snowball.NewAmong("आओगे", 118, -1),
		snowball.NewAmong("ाओगे", 118, -1),
		snowball.NewAmong("ोगे", 113, -1),
		snowball.NewAmongMethod("ते", 113, -1, hindiRConsonant),
		snowball.NewAmong("अते", 122, -1),
		snowball.NewAmong("आते", 122, -1),
		snowball.NewAmong("ाते", 122, -1),
		snowball.NewAmongMethod("ने", 113, -1, hindiRConsonant),
		snowball.NewAmong("अने", 126, -1),
		snowball.NewAmong("आने", 126, -1),
		snowball.NewAmong("ाने", 126, -1),
		snowball.NewAmong("ो", -1, -1),
		snowball.NewAmong("्", -1, -1),
	}
}

// Stem applies the Hindi Snowball stemming algorithm.
func (s *HindiStemmer) Stem() bool {
	p := s.SnowballProgram
	if p.Cursor >= p.Limit {
		return false
	}
	p.Cursor++
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	p.Ket = p.Cursor
	if p.FindAmongB(hindiA0) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*HindiStemmer)(nil)
