// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// HungarianStemmer implements the Hungarian Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.HungarianStemmer
// from Apache Lucene 10.4.0.
type HungarianStemmer struct {
	*snowball.SnowballProgram
	iP1 int
}

// NewHungarianStemmer constructs a HungarianStemmer.
func NewHungarianStemmer() *HungarianStemmer {
	return &HungarianStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*HungarianStemmer)(nil)

var hungarianA0 = []*snowball.Among{
	snowball.NewAmong("cs", -1, -1),
	snowball.NewAmong("dzs", -1, -1),
	snowball.NewAmong("gy", -1, -1),
	snowball.NewAmong("ly", -1, -1),
	snowball.NewAmong("ny", -1, -1),
	snowball.NewAmong("sz", -1, -1),
	snowball.NewAmong("ty", -1, -1),
	snowball.NewAmong("zs", -1, -1),
}

var hungarianA1 = []*snowball.Among{
	snowball.NewAmong("á", -1, 1),
	snowball.NewAmong("é", -1, 2),
}

var hungarianA2 = []*snowball.Among{
	snowball.NewAmong("bb", -1, -1),
	snowball.NewAmong("cc", -1, -1),
	snowball.NewAmong("dd", -1, -1),
	snowball.NewAmong("ff", -1, -1),
	snowball.NewAmong("gg", -1, -1),
	snowball.NewAmong("jj", -1, -1),
	snowball.NewAmong("kk", -1, -1),
	snowball.NewAmong("ll", -1, -1),
	snowball.NewAmong("mm", -1, -1),
	snowball.NewAmong("nn", -1, -1),
	snowball.NewAmong("pp", -1, -1),
	snowball.NewAmong("rr", -1, -1),
	snowball.NewAmong("ccs", -1, -1),
	snowball.NewAmong("ss", -1, -1),
	snowball.NewAmong("zzs", -1, -1),
	snowball.NewAmong("tt", -1, -1),
	snowball.NewAmong("vv", -1, -1),
	snowball.NewAmong("ggy", -1, -1),
	snowball.NewAmong("lly", -1, -1),
	snowball.NewAmong("nny", -1, -1),
	snowball.NewAmong("tty", -1, -1),
	snowball.NewAmong("ssz", -1, -1),
	snowball.NewAmong("zz", -1, -1),
}

var hungarianA3 = []*snowball.Among{
	snowball.NewAmong("al", -1, 1),
	snowball.NewAmong("el", -1, 1),
}

var hungarianA4 = []*snowball.Among{
	snowball.NewAmong("ba", -1, -1),
	snowball.NewAmong("ra", -1, -1),
	snowball.NewAmong("be", -1, -1),
	snowball.NewAmong("re", -1, -1),
	snowball.NewAmong("ig", -1, -1),
	snowball.NewAmong("nak", -1, -1),
	snowball.NewAmong("nek", -1, -1),
	snowball.NewAmong("val", -1, -1),
	snowball.NewAmong("vel", -1, -1),
	snowball.NewAmong("ul", -1, -1),
	snowball.NewAmong("nál", -1, -1),
	snowball.NewAmong("nél", -1, -1),
	snowball.NewAmong("ból", -1, -1),
	snowball.NewAmong("ról", -1, -1),
	snowball.NewAmong("tól", -1, -1),
	snowball.NewAmong("ül", -1, -1),
	snowball.NewAmong("ből", -1, -1),
	snowball.NewAmong("ről", -1, -1),
	snowball.NewAmong("től", -1, -1),
	snowball.NewAmong("n", -1, -1),
	snowball.NewAmong("an", 19, -1),
	snowball.NewAmong("ban", 20, -1),
	snowball.NewAmong("en", 19, -1),
	snowball.NewAmong("ben", 22, -1),
	snowball.NewAmong("képpen", 22, -1),
	snowball.NewAmong("on", 19, -1),
	snowball.NewAmong("ön", 19, -1),
	snowball.NewAmong("képp", -1, -1),
	snowball.NewAmong("kor", -1, -1),
	snowball.NewAmong("t", -1, -1),
	snowball.NewAmong("at", 29, -1),
	snowball.NewAmong("et", 29, -1),
	snowball.NewAmong("ként", 29, -1),
	snowball.NewAmong("anként", 32, -1),
	snowball.NewAmong("enként", 32, -1),
	snowball.NewAmong("onként", 32, -1),
	snowball.NewAmong("ot", 29, -1),
	snowball.NewAmong("ért", 29, -1),
	snowball.NewAmong("öt", 29, -1),
	snowball.NewAmong("hez", -1, -1),
	snowball.NewAmong("hoz", -1, -1),
	snowball.NewAmong("höz", -1, -1),
	snowball.NewAmong("vá", -1, -1),
	snowball.NewAmong("vé", -1, -1),
}

var hungarianA5 = []*snowball.Among{
	snowball.NewAmong("án", -1, 2),
	snowball.NewAmong("én", -1, 1),
	snowball.NewAmong("ánként", -1, 2),
}

var hungarianA6 = []*snowball.Among{
	snowball.NewAmong("stul", -1, 1),
	snowball.NewAmong("astul", 0, 1),
	snowball.NewAmong("ástul", 0, 2),
	snowball.NewAmong("stül", -1, 1),
	snowball.NewAmong("estül", 3, 1),
	snowball.NewAmong("éstül", 3, 3),
}

var hungarianA7 = []*snowball.Among{
	snowball.NewAmong("á", -1, 1),
	snowball.NewAmong("é", -1, 1),
}

var hungarianA8 = []*snowball.Among{
	snowball.NewAmong("k", -1, 3),
	snowball.NewAmong("ak", 0, 3),
	snowball.NewAmong("ek", 0, 3),
	snowball.NewAmong("ok", 0, 3),
	snowball.NewAmong("ák", 0, 1),
	snowball.NewAmong("ék", 0, 2),
	snowball.NewAmong("ök", 0, 3),
}

var hungarianA9 = []*snowball.Among{
	snowball.NewAmong("éi", -1, 1),
	snowball.NewAmong("áéi", 0, 3),
	snowball.NewAmong("ééi", 0, 2),
	snowball.NewAmong("é", -1, 1),
	snowball.NewAmong("ké", 3, 1),
	snowball.NewAmong("aké", 4, 1),
	snowball.NewAmong("eké", 4, 1),
	snowball.NewAmong("oké", 4, 1),
	snowball.NewAmong("áké", 4, 3),
	snowball.NewAmong("éké", 4, 2),
	snowball.NewAmong("öké", 4, 1),
	snowball.NewAmong("éé", 3, 2),
}

var hungarianA10 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("ja", 0, 1),
	snowball.NewAmong("d", -1, 1),
	snowball.NewAmong("ad", 2, 1),
	snowball.NewAmong("ed", 2, 1),
	snowball.NewAmong("od", 2, 1),
	snowball.NewAmong("ád", 2, 2),
	snowball.NewAmong("éd", 2, 3),
	snowball.NewAmong("öd", 2, 1),
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("je", 9, 1),
	snowball.NewAmong("nk", -1, 1),
	snowball.NewAmong("unk", 11, 1),
	snowball.NewAmong("ánk", 11, 2),
	snowball.NewAmong("énk", 11, 3),
	snowball.NewAmong("ünk", 11, 1),
	snowball.NewAmong("uk", -1, 1),
	snowball.NewAmong("juk", 16, 1),
	snowball.NewAmong("ájuk", 17, 2),
	snowball.NewAmong("ük", -1, 1),
	snowball.NewAmong("jük", 19, 1),
	snowball.NewAmong("éjük", 20, 3),
	snowball.NewAmong("m", -1, 1),
	snowball.NewAmong("am", 22, 1),
	snowball.NewAmong("em", 22, 1),
	snowball.NewAmong("om", 22, 1),
	snowball.NewAmong("ám", 22, 2),
	snowball.NewAmong("ém", 22, 3),
	snowball.NewAmong("o", -1, 1),
	snowball.NewAmong("á", -1, 2),
	snowball.NewAmong("é", -1, 3),
}

var hungarianA11 = []*snowball.Among{
	snowball.NewAmong("id", -1, 1),
	snowball.NewAmong("aid", 0, 1),
	snowball.NewAmong("jaid", 1, 1),
	snowball.NewAmong("eid", 0, 1),
	snowball.NewAmong("jeid", 3, 1),
	snowball.NewAmong("áid", 0, 2),
	snowball.NewAmong("éid", 0, 3),
	snowball.NewAmong("i", -1, 1),
	snowball.NewAmong("ai", 7, 1),
	snowball.NewAmong("jai", 8, 1),
	snowball.NewAmong("ei", 7, 1),
	snowball.NewAmong("jei", 10, 1),
	snowball.NewAmong("ái", 7, 2),
	snowball.NewAmong("éi", 7, 3),
	snowball.NewAmong("itek", -1, 1),
	snowball.NewAmong("eitek", 14, 1),
	snowball.NewAmong("jeitek", 15, 1),
	snowball.NewAmong("éitek", 14, 3),
	snowball.NewAmong("ik", -1, 1),
	snowball.NewAmong("aik", 18, 1),
	snowball.NewAmong("jaik", 19, 1),
	snowball.NewAmong("eik", 18, 1),
	snowball.NewAmong("jeik", 21, 1),
	snowball.NewAmong("áik", 18, 2),
	snowball.NewAmong("éik", 18, 3),
	snowball.NewAmong("ink", -1, 1),
	snowball.NewAmong("aink", 25, 1),
	snowball.NewAmong("jaink", 26, 1),
	snowball.NewAmong("eink", 25, 1),
	snowball.NewAmong("jeink", 28, 1),
	snowball.NewAmong("áink", 25, 2),
	snowball.NewAmong("éink", 25, 3),
	snowball.NewAmong("aitok", -1, 1),
	snowball.NewAmong("jaitok", 32, 1),
	snowball.NewAmong("áitok", -1, 2),
	snowball.NewAmong("im", -1, 1),
	snowball.NewAmong("aim", 35, 1),
	snowball.NewAmong("jaim", 36, 1),
	snowball.NewAmong("eim", 35, 1),
	snowball.NewAmong("jeim", 38, 1),
	snowball.NewAmong("áim", 35, 2),
	snowball.NewAmong("éim", 35, 3),
}

// hungarianGV is the vowel grouping (a e i o u á é í ó ö ő ú ü ű).
var hungarianGV = []byte{
	17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 36, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 1,
}

func (s *HungarianStemmer) rMarkRegions() bool {
	s.iP1 = s.Limit
	lab0: for {
		v1 := s.Cursor
		lab1: for {
			if !s.InGrouping(hungarianGV, 97, 369) {
				break lab1
			}
		golab2:
			for {
				v2 := s.Cursor
				lab3: for {
					if !s.OutGrouping(hungarianGV, 97, 369) {
						break lab3
					}
					s.Cursor = v2
					break golab2
				}
				s.Cursor = v2
				if s.Cursor >= s.Limit {
					break lab1
				}
				s.Cursor++
			}
			lab4: for {
				v3 := s.Cursor
				lab5: for {
					if s.FindAmong(hungarianA0) == 0 {
						break lab5
					}
					break lab4
				}
				s.Cursor = v3
				if s.Cursor >= s.Limit {
					break lab1
				}
				s.Cursor++
			}
			s.iP1 = s.Cursor
			break lab0
		}
		s.Cursor = v1
		if !s.OutGrouping(hungarianGV, 97, 369) {
			return false
		}
	golab6:
		for {
			lab7: for {
				if !s.InGrouping(hungarianGV, 97, 369) {
					break lab7
				}
				break golab6
			}
			if s.Cursor >= s.Limit {
				return false
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
		break lab0
	}
	return true
}

func (s *HungarianStemmer) rR1() bool {
	return s.iP1 <= s.Cursor
}

func (s *HungarianStemmer) rVEnding() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA1)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceFromStr("a")
	case 2:
		s.SliceFromStr("e")
	}
	return true
}

func (s *HungarianStemmer) rDouble() bool {
	v1 := s.Limit - s.Cursor
	if s.FindAmongB(hungarianA2) == 0 {
		return false
	}
	s.Cursor = s.Limit - v1
	return true
}

func (s *HungarianStemmer) rUndouble() bool {
	if s.Cursor <= s.LimitBackward {
		return false
	}
	s.Cursor--
	s.Ket = s.Cursor
	c := s.Cursor - 1
	if c < s.LimitBackward {
		return false
	}
	s.Cursor = c
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

func (s *HungarianStemmer) rInstrum() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(hungarianA3) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	if !s.rDouble() {
		return false
	}
	s.SliceDel()
	if !s.rUndouble() {
		return false
	}
	return true
}

func (s *HungarianStemmer) rCase() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(hungarianA4) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	s.SliceDel()
	if !s.rVEnding() {
		return false
	}
	return true
}

func (s *HungarianStemmer) rCaseSpecial() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA5)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceFromStr("e")
	case 2:
		s.SliceFromStr("a")
	}
	return true
}

func (s *HungarianStemmer) rCaseOther() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA6)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("a")
	case 3:
		s.SliceFromStr("e")
	}
	return true
}

func (s *HungarianStemmer) rFactive() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(hungarianA7) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	if !s.rDouble() {
		return false
	}
	s.SliceDel()
	if !s.rUndouble() {
		return false
	}
	return true
}

func (s *HungarianStemmer) rPlural() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA8)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceFromStr("a")
	case 2:
		s.SliceFromStr("e")
	case 3:
		s.SliceDel()
	}
	return true
}

func (s *HungarianStemmer) rOwned() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA9)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("e")
	case 3:
		s.SliceFromStr("a")
	}
	return true
}

func (s *HungarianStemmer) rSingOwner() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA10)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("a")
	case 3:
		s.SliceFromStr("e")
	}
	return true
}

func (s *HungarianStemmer) rPlurOwner() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(hungarianA11)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("a")
	case 3:
		s.SliceFromStr("e")
	}
	return true
}

// Stem applies the Hungarian stemming algorithm to the current word.
func (s *HungarianStemmer) Stem() bool {
	v1 := s.Cursor
	s.rMarkRegions()
	s.Cursor = v1
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit

	v2 := s.Limit - s.Cursor
	s.rInstrum()
	s.Cursor = s.Limit - v2

	v3 := s.Limit - s.Cursor
	s.rCase()
	s.Cursor = s.Limit - v3

	v4 := s.Limit - s.Cursor
	s.rCaseSpecial()
	s.Cursor = s.Limit - v4

	v5 := s.Limit - s.Cursor
	s.rCaseOther()
	s.Cursor = s.Limit - v5

	v6 := s.Limit - s.Cursor
	s.rFactive()
	s.Cursor = s.Limit - v6

	v7 := s.Limit - s.Cursor
	s.rOwned()
	s.Cursor = s.Limit - v7

	v8 := s.Limit - s.Cursor
	s.rSingOwner()
	s.Cursor = s.Limit - v8

	v9 := s.Limit - s.Cursor
	s.rPlurOwner()
	s.Cursor = s.Limit - v9

	v10 := s.Limit - s.Cursor
	s.rPlural()
	s.Cursor = s.Limit - v10

	s.Cursor = s.LimitBackward
	return true
}
