// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// IrishStemmer implements the Irish Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.IrishStemmer
// from Apache Lucene 10.4.0.
type IrishStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewIrishStemmer creates a new IrishStemmer.
func NewIrishStemmer() *IrishStemmer {
	return &IrishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var irishA0 = []*snowball.Among{
	snowball.NewAmong("b'", -1, 1),
	snowball.NewAmong("bh", -1, 4),
	snowball.NewAmong("bhf", 1, 2),
	snowball.NewAmong("bp", -1, 8),
	snowball.NewAmong("ch", -1, 5),
	snowball.NewAmong("d'", -1, 1),
	snowball.NewAmong("d'fh", 5, 2),
	snowball.NewAmong("dh", -1, 6),
	snowball.NewAmong("dt", -1, 9),
	snowball.NewAmong("fh", -1, 2),
	snowball.NewAmong("gc", -1, 5),
	snowball.NewAmong("gh", -1, 7),
	snowball.NewAmong("h-", -1, 1),
	snowball.NewAmong("m'", -1, 1),
	snowball.NewAmong("mb", -1, 4),
	snowball.NewAmong("mh", -1, 10),
	snowball.NewAmong("n-", -1, 1),
	snowball.NewAmong("nd", -1, 6),
	snowball.NewAmong("ng", -1, 7),
	snowball.NewAmong("ph", -1, 8),
	snowball.NewAmong("sh", -1, 3),
	snowball.NewAmong("t-", -1, 1),
	snowball.NewAmong("th", -1, 9),
	snowball.NewAmong("ts", -1, 3),
}

var irishA1 = []*snowball.Among{
	snowball.NewAmong("íochta", -1, 1),
	snowball.NewAmong("aíochta", 0, 1),
	snowball.NewAmong("ire", -1, 2),
	snowball.NewAmong("aire", 2, 2),
	snowball.NewAmong("abh", -1, 1),
	snowball.NewAmong("eabh", 4, 1),
	snowball.NewAmong("ibh", -1, 1),
	snowball.NewAmong("aibh", 6, 1),
	snowball.NewAmong("amh", -1, 1),
	snowball.NewAmong("eamh", 8, 1),
	snowball.NewAmong("imh", -1, 1),
	snowball.NewAmong("aimh", 10, 1),
	snowball.NewAmong("íocht", -1, 1),
	snowball.NewAmong("aíocht", 12, 1),
	snowball.NewAmong("irí", -1, 2),
	snowball.NewAmong("airí", 14, 2),
}

var irishA2 = []*snowball.Among{
	snowball.NewAmong("óideacha", -1, 6),
	snowball.NewAmong("patacha", -1, 5),
	snowball.NewAmong("achta", -1, 1),
	snowball.NewAmong("arcachta", 2, 2),
	snowball.NewAmong("eachta", 2, 1),
	snowball.NewAmong("grafaíochta", -1, 4),
	snowball.NewAmong("paite", -1, 5),
	snowball.NewAmong("ach", -1, 1),
	snowball.NewAmong("each", 7, 1),
	snowball.NewAmong("óideach", 8, 6),
	snowball.NewAmong("gineach", 8, 3),
	snowball.NewAmong("patach", 7, 5),
	snowball.NewAmong("grafaíoch", -1, 4),
	snowball.NewAmong("pataigh", -1, 5),
	snowball.NewAmong("óidigh", -1, 6),
	snowball.NewAmong("achtúil", -1, 1),
	snowball.NewAmong("eachtúil", 15, 1),
	snowball.NewAmong("gineas", -1, 3),
	snowball.NewAmong("ginis", -1, 3),
	snowball.NewAmong("acht", -1, 1),
	snowball.NewAmong("arcacht", 19, 2),
	snowball.NewAmong("eacht", 19, 1),
	snowball.NewAmong("grafaíocht", -1, 4),
	snowball.NewAmong("arcachtaí", -1, 2),
	snowball.NewAmong("grafaíochtaí", -1, 4),
}

var irishA3 = []*snowball.Among{
	snowball.NewAmong("imid", -1, 1),
	snowball.NewAmong("aimid", 0, 1),
	snowball.NewAmong("ímid", -1, 1),
	snowball.NewAmong("aímid", 2, 1),
	snowball.NewAmong("adh", -1, 2),
	snowball.NewAmong("eadh", 4, 2),
	snowball.NewAmong("faidh", -1, 1),
	snowball.NewAmong("fidh", -1, 1),
	snowball.NewAmong("áil", -1, 2),
	snowball.NewAmong("ain", -1, 2),
	snowball.NewAmong("tear", -1, 2),
	snowball.NewAmong("tar", -1, 2),
}

var irishGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 2}

func (s *IrishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iPV = p.Limit
	s.iP1 = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
lab0:
	for {
	golab1:
		for {
			if p.InGrouping(irishGV, 97, 250) {
				break golab1
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iPV = p.Cursor
	golab3:
		for {
			if p.OutGrouping(irishGV, 97, 250) {
				break golab3
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iP1 = p.Cursor
	golab5:
		for {
			if p.InGrouping(irishGV, 97, 250) {
				break golab5
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
	golab7:
		for {
			if p.OutGrouping(irishGV, 97, 250) {
				break golab7
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iP2 = p.Cursor
		break
	}
	p.Cursor = v1
	return true
}

func (s *IrishStemmer) rInitialMorph() bool {
	p := s.SnowballProgram
	p.Bra = p.Cursor
	amongVar := p.FindAmong(irishA0)
	if amongVar == 0 {
		return false
	}
	p.Ket = p.Cursor
	switch amongVar {
	case 1:
		p.SliceDel()
	case 2:
		p.SliceFromStr("f")
	case 3:
		p.SliceFromStr("s")
	case 4:
		p.SliceFromStr("b")
	case 5:
		p.SliceFromStr("c")
	case 6:
		p.SliceFromStr("d")
	case 7:
		p.SliceFromStr("g")
	case 8:
		p.SliceFromStr("p")
	case 9:
		p.SliceFromStr("t")
	case 10:
		p.SliceFromStr("m")
	}
	return true
}

func (s *IrishStemmer) rRV() bool { return s.iPV <= s.SnowballProgram.Cursor }
func (s *IrishStemmer) rR1() bool { return s.iP1 <= s.SnowballProgram.Cursor }
func (s *IrishStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *IrishStemmer) rNounSfx() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(irishA1)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rR1() {
			return false
		}
		p.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *IrishStemmer) rDeriv() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(irishA2)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
	case 2:
		p.SliceFromStr("arc")
	case 3:
		p.SliceFromStr("gin")
	case 4:
		p.SliceFromStr("graf")
	case 5:
		p.SliceFromStr("paite")
	case 6:
		p.SliceFromStr("óid")
	}
	return true
}

func (s *IrishStemmer) rVerbSfx() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(irishA3)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		p.SliceDel()
	case 2:
		if !s.rR1() {
			return false
		}
		p.SliceDel()
	}
	return true
}

// Stem applies the Irish Snowball stemming algorithm.
func (s *IrishStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rInitialMorph()
	p.Cursor = v1
	s.rMarkRegions()
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v3 := p.Limit - p.Cursor
	s.rNounSfx()
	p.Cursor = p.Limit - v3
	v4 := p.Limit - p.Cursor
	s.rDeriv()
	p.Cursor = p.Limit - v4
	v5 := p.Limit - p.Cursor
	s.rVerbSfx()
	p.Cursor = p.Limit - v5
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*IrishStemmer)(nil)
