// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from org.tartarus.snowball.ext.ItalianStemmer.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

var italianA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 7),
	snowball.NewAmong("qu", 0, 6),
	snowball.NewAmong("á", 0, 1),
	snowball.NewAmong("é", 0, 2),
	snowball.NewAmong("í", 0, 3),
	snowball.NewAmong("ó", 0, 4),
	snowball.NewAmong("ú", 0, 5),
}

var italianA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("I", 0, 1),
	snowball.NewAmong("U", 0, 2),
}

var italianA2 = []*snowball.Among{
	snowball.NewAmong("la", -1, -1),
	snowball.NewAmong("cela", 0, -1),
	snowball.NewAmong("gliela", 0, -1),
	snowball.NewAmong("mela", 0, -1),
	snowball.NewAmong("tela", 0, -1),
	snowball.NewAmong("vela", 0, -1),
	snowball.NewAmong("le", -1, -1),
	snowball.NewAmong("cele", 6, -1),
	snowball.NewAmong("gliele", 6, -1),
	snowball.NewAmong("mele", 6, -1),
	snowball.NewAmong("tele", 6, -1),
	snowball.NewAmong("vele", 6, -1),
	snowball.NewAmong("ne", -1, -1),
	snowball.NewAmong("cene", 12, -1),
	snowball.NewAmong("gliene", 12, -1),
	snowball.NewAmong("mene", 12, -1),
	snowball.NewAmong("sene", 12, -1),
	snowball.NewAmong("tene", 12, -1),
	snowball.NewAmong("vene", 12, -1),
	snowball.NewAmong("ci", -1, -1),
	snowball.NewAmong("li", -1, -1),
	snowball.NewAmong("celi", 20, -1),
	snowball.NewAmong("glieli", 20, -1),
	snowball.NewAmong("meli", 20, -1),
	snowball.NewAmong("teli", 20, -1),
	snowball.NewAmong("veli", 20, -1),
	snowball.NewAmong("gli", 20, -1),
	snowball.NewAmong("mi", -1, -1),
	snowball.NewAmong("si", -1, -1),
	snowball.NewAmong("ti", -1, -1),
	snowball.NewAmong("vi", -1, -1),
	snowball.NewAmong("lo", -1, -1),
	snowball.NewAmong("celo", 31, -1),
	snowball.NewAmong("glielo", 31, -1),
	snowball.NewAmong("melo", 31, -1),
	snowball.NewAmong("telo", 31, -1),
	snowball.NewAmong("velo", 31, -1),
}

var italianA3 = []*snowball.Among{
	snowball.NewAmong("ando", -1, 1),
	snowball.NewAmong("endo", -1, 1),
	snowball.NewAmong("ar", -1, 2),
	snowball.NewAmong("er", -1, 2),
	snowball.NewAmong("ir", -1, 2),
}

var italianA4 = []*snowball.Among{
	snowball.NewAmong("ic", -1, -1),
	snowball.NewAmong("abil", -1, -1),
	snowball.NewAmong("os", -1, -1),
	snowball.NewAmong("iv", -1, 1),
}

var italianA5 = []*snowball.Among{
	snowball.NewAmong("ic", -1, 1),
	snowball.NewAmong("abil", -1, 1),
	snowball.NewAmong("iv", -1, 1),
}

var italianA6 = []*snowball.Among{
	snowball.NewAmong("ica", -1, 1),
	snowball.NewAmong("logia", -1, 3),
	snowball.NewAmong("osa", -1, 1),
	snowball.NewAmong("ista", -1, 1),
	snowball.NewAmong("iva", -1, 9),
	snowball.NewAmong("anza", -1, 1),
	snowball.NewAmong("enza", -1, 5),
	snowball.NewAmong("ice", -1, 1),
	snowball.NewAmong("atrice", 7, 1),
	snowball.NewAmong("iche", -1, 1),
	snowball.NewAmong("logie", -1, 3),
	snowball.NewAmong("abile", -1, 1),
	snowball.NewAmong("ibile", -1, 1),
	snowball.NewAmong("usione", -1, 4),
	snowball.NewAmong("azione", -1, 2),
	snowball.NewAmong("uzione", -1, 4),
	snowball.NewAmong("atore", -1, 2),
	snowball.NewAmong("ose", -1, 1),
	snowball.NewAmong("ante", -1, 1),
	snowball.NewAmong("mente", -1, 1),
	snowball.NewAmong("amente", 19, 7),
	snowball.NewAmong("iste", -1, 1),
	snowball.NewAmong("ive", -1, 9),
	snowball.NewAmong("anze", -1, 1),
	snowball.NewAmong("enze", -1, 5),
	snowball.NewAmong("ici", -1, 1),
	snowball.NewAmong("atrici", 25, 1),
	snowball.NewAmong("ichi", -1, 1),
	snowball.NewAmong("abili", -1, 1),
	snowball.NewAmong("ibili", -1, 1),
	snowball.NewAmong("ismi", -1, 1),
	snowball.NewAmong("usioni", -1, 4),
	snowball.NewAmong("azioni", -1, 2),
	snowball.NewAmong("uzioni", -1, 4),
	snowball.NewAmong("atori", -1, 2),
	snowball.NewAmong("osi", -1, 1),
	snowball.NewAmong("anti", -1, 1),
	snowball.NewAmong("amenti", -1, 6),
	snowball.NewAmong("imenti", -1, 6),
	snowball.NewAmong("isti", -1, 1),
	snowball.NewAmong("ivi", -1, 9),
	snowball.NewAmong("ico", -1, 1),
	snowball.NewAmong("ismo", -1, 1),
	snowball.NewAmong("oso", -1, 1),
	snowball.NewAmong("amento", -1, 6),
	snowball.NewAmong("imento", -1, 6),
	snowball.NewAmong("ivo", -1, 9),
	snowball.NewAmong("ità", -1, 8),
	snowball.NewAmong("istà", -1, 1),
	snowball.NewAmong("istè", -1, 1),
	snowball.NewAmong("istì", -1, 1),
}

var italianA7 = []*snowball.Among{
	snowball.NewAmong("isca", -1, 1),
	snowball.NewAmong("enda", -1, 1),
	snowball.NewAmong("ata", -1, 1),
	snowball.NewAmong("ita", -1, 1),
	snowball.NewAmong("uta", -1, 1),
	snowball.NewAmong("ava", -1, 1),
	snowball.NewAmong("eva", -1, 1),
	snowball.NewAmong("iva", -1, 1),
	snowball.NewAmong("erebbe", -1, 1),
	snowball.NewAmong("irebbe", -1, 1),
	snowball.NewAmong("isce", -1, 1),
	snowball.NewAmong("ende", -1, 1),
	snowball.NewAmong("are", -1, 1),
	snowball.NewAmong("ere", -1, 1),
	snowball.NewAmong("ire", -1, 1),
	snowball.NewAmong("asse", -1, 1),
	snowball.NewAmong("ate", -1, 1),
	snowball.NewAmong("avate", 16, 1),
	snowball.NewAmong("evate", 16, 1),
	snowball.NewAmong("ivate", 16, 1),
	snowball.NewAmong("ete", -1, 1),
	snowball.NewAmong("erete", 20, 1),
	snowball.NewAmong("irete", 20, 1),
	snowball.NewAmong("ite", -1, 1),
	snowball.NewAmong("ereste", -1, 1),
	snowball.NewAmong("ireste", -1, 1),
	snowball.NewAmong("ute", -1, 1),
	snowball.NewAmong("erai", -1, 1),
	snowball.NewAmong("irai", -1, 1),
	snowball.NewAmong("isci", -1, 1),
	snowball.NewAmong("endi", -1, 1),
	snowball.NewAmong("erei", -1, 1),
	snowball.NewAmong("irei", -1, 1),
	snowball.NewAmong("assi", -1, 1),
	snowball.NewAmong("ati", -1, 1),
	snowball.NewAmong("iti", -1, 1),
	snowball.NewAmong("eresti", -1, 1),
	snowball.NewAmong("iresti", -1, 1),
	snowball.NewAmong("uti", -1, 1),
	snowball.NewAmong("avi", -1, 1),
	snowball.NewAmong("evi", -1, 1),
	snowball.NewAmong("ivi", -1, 1),
	snowball.NewAmong("isco", -1, 1),
	snowball.NewAmong("ando", -1, 1),
	snowball.NewAmong("endo", -1, 1),
	snowball.NewAmong("Yamo", -1, 1),
	snowball.NewAmong("iamo", -1, 1),
	snowball.NewAmong("avamo", -1, 1),
	snowball.NewAmong("evamo", -1, 1),
	snowball.NewAmong("ivamo", -1, 1),
	snowball.NewAmong("eremo", -1, 1),
	snowball.NewAmong("iremo", -1, 1),
	snowball.NewAmong("assimo", -1, 1),
	snowball.NewAmong("ammo", -1, 1),
	snowball.NewAmong("emmo", -1, 1),
	snowball.NewAmong("eremmo", 54, 1),
	snowball.NewAmong("iremmo", 54, 1),
	snowball.NewAmong("immo", -1, 1),
	snowball.NewAmong("ano", -1, 1),
	snowball.NewAmong("iscano", 58, 1),
	snowball.NewAmong("avano", 58, 1),
	snowball.NewAmong("evano", 58, 1),
	snowball.NewAmong("ivano", 58, 1),
	snowball.NewAmong("eranno", -1, 1),
	snowball.NewAmong("iranno", -1, 1),
	snowball.NewAmong("ono", -1, 1),
	snowball.NewAmong("iscono", 65, 1),
	snowball.NewAmong("arono", 65, 1),
	snowball.NewAmong("erono", 65, 1),
	snowball.NewAmong("irono", 65, 1),
	snowball.NewAmong("erebbero", -1, 1),
	snowball.NewAmong("irebbero", -1, 1),
	snowball.NewAmong("assero", -1, 1),
	snowball.NewAmong("essero", -1, 1),
	snowball.NewAmong("issero", -1, 1),
	snowball.NewAmong("ato", -1, 1),
	snowball.NewAmong("ito", -1, 1),
	snowball.NewAmong("uto", -1, 1),
	snowball.NewAmong("avo", -1, 1),
	snowball.NewAmong("evo", -1, 1),
	snowball.NewAmong("ivo", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("ir", -1, 1),
	snowball.NewAmong("erà", -1, 1),
	snowball.NewAmong("irà", -1, 1),
	snowball.NewAmong("erò", -1, 1),
	snowball.NewAmong("irò", -1, 1),
}

// italianGV is the vowel grouping for Italian (a–ù, range 97–249).
var italianGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2, 1}

// italianGAEIO is the AEIO grouping (range 97–242).
var italianGAEIO = []byte{17, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2}

// italianGCG is the C/G grouping (range 99–103).
var italianGCG = []byte{17}

// ItalianStemmer implements the Snowball stemming algorithm for Italian.
// It mirrors org.tartarus.snowball.ext.ItalianStemmer.
type ItalianStemmer struct {
	snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewItalianStemmer constructs an ItalianStemmer.
func NewItalianStemmer() *ItalianStemmer {
	return &ItalianStemmer{}
}

func (s *ItalianStemmer) rPrelude() bool {
	v1 := s.Cursor
	for {
		v2 := s.Cursor
		lab0:
		for {
			s.Bra = s.Cursor
			amongVar := s.FindAmong(italianA0)
			s.Ket = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("à")
			case 2:
				s.SliceFromStr("è")
			case 3:
				s.SliceFromStr("ì")
			case 4:
				s.SliceFromStr("ò")
			case 5:
				s.SliceFromStr("ù")
			case 6:
				s.SliceFromStr("qU")
			case 7:
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v2
		break
	}
	s.Cursor = v1
	for {
		v3 := s.Cursor
		lab1:
		for {
		golab2:
			for {
				v4 := s.Cursor
				lab3:
				for {
					if !s.InGrouping(italianGV, 97, 249) {
						break lab3
					}
					s.Bra = s.Cursor
					lab4:
					for {
						v5 := s.Cursor
						lab5:
						for {
							if !s.EqSStr("u") {
								break lab5
							}
							s.Ket = s.Cursor
							if !s.InGrouping(italianGV, 97, 249) {
								break lab5
							}
							s.SliceFromStr("U")
							break lab4
						}
						s.Cursor = v5
						if !s.EqSStr("i") {
							break lab3
						}
						s.Ket = s.Cursor
						if !s.InGrouping(italianGV, 97, 249) {
							break lab3
						}
						s.SliceFromStr("I")
						break lab4
					}
					s.Cursor = v4
					break golab2
				}
				s.Cursor = v4
				if s.Cursor >= s.Limit {
					break lab1
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v3
		break
	}
	return true
}

func (s *ItalianStemmer) rMarkRegions() bool {
	s.iPV = s.Limit
	s.iP1 = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
lab0:
	for {
		lab1:
		for {
			v2 := s.Cursor
			lab2:
			for {
				if !s.InGrouping(italianGV, 97, 249) {
					break lab2
				}
				lab3:
				for {
					v3 := s.Cursor
					lab4:
					for {
						if !s.OutGrouping(italianGV, 97, 249) {
							break lab4
						}
					golab5:
						for {
							lab6:
							for {
								if !s.InGrouping(italianGV, 97, 249) {
									break lab6
								}
								break golab5
							}
							if s.Cursor >= s.Limit {
								break lab4
							}
							s.Cursor++
						}
						break lab3
					}
					s.Cursor = v3
					if !s.InGrouping(italianGV, 97, 249) {
						break lab2
					}
				golab7:
					for {
						lab8:
						for {
							if !s.OutGrouping(italianGV, 97, 249) {
								break lab8
							}
							break golab7
						}
						if s.Cursor >= s.Limit {
							break lab2
						}
						s.Cursor++
					}
					break lab3
				}
				break lab1
			}
			s.Cursor = v2
			if !s.OutGrouping(italianGV, 97, 249) {
				break lab0
			}
			lab9:
			for {
				v6 := s.Cursor
				lab10:
				for {
					if !s.OutGrouping(italianGV, 97, 249) {
						break lab10
					}
				golab11:
					for {
						lab12:
						for {
							if !s.InGrouping(italianGV, 97, 249) {
								break lab12
							}
							break golab11
						}
						if s.Cursor >= s.Limit {
							break lab10
						}
						s.Cursor++
					}
					break lab9
				}
				s.Cursor = v6
				if !s.InGrouping(italianGV, 97, 249) {
					break lab0
				}
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
				break lab9
			}
			break lab1
		}
		s.iPV = s.Cursor
		break lab0
	}
	s.Cursor = v1
	v8 := s.Cursor
lab13:
	for {
	golab14:
		for {
			lab15:
			for {
				if !s.InGrouping(italianGV, 97, 249) {
					break lab15
				}
				break golab14
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab16:
		for {
			lab17:
			for {
				if !s.OutGrouping(italianGV, 97, 249) {
					break lab17
				}
				break golab16
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
	golab18:
		for {
			lab19:
			for {
				if !s.InGrouping(italianGV, 97, 249) {
					break lab19
				}
				break golab18
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab20:
		for {
			lab21:
			for {
				if !s.OutGrouping(italianGV, 97, 249) {
					break lab21
				}
				break golab20
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab13
	}
	s.Cursor = v8
	return true
}

func (s *ItalianStemmer) rPostlude() bool {
	for {
		v1 := s.Cursor
		lab0:
		for {
			s.Bra = s.Cursor
			amongVar := s.FindAmong(italianA1)
			s.Ket = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("i")
			case 2:
				s.SliceFromStr("u")
			case 3:
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *ItalianStemmer) rRV() bool { return s.iPV <= s.Cursor }
func (s *ItalianStemmer) rR1() bool { return s.iP1 <= s.Cursor }
func (s *ItalianStemmer) rR2() bool { return s.iP2 <= s.Cursor }

func (s *ItalianStemmer) rAttachedPronoun() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(italianA2) == 0 {
		return false
	}
	s.Bra = s.Cursor
	amongVar := s.FindAmongB(italianA3)
	if amongVar == 0 {
		return false
	}
	if !s.rRV() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("e")
	}
	return true
}

func (s *ItalianStemmer) rStandardSuffix() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(italianA6)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v1 := s.Limit - s.Cursor
		lab0:
		for {
			s.Ket = s.Cursor
			if !s.EqSBStr("ic") {
				s.Cursor = s.Limit - v1
				break lab0
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v1
				break lab0
			}
			s.SliceDel()
			break lab0
		}
	case 3:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("log")
	case 4:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("u")
	case 5:
		if !s.rR2() {
			return false
		}
		s.SliceFromStr("ente")
	case 6:
		if !s.rRV() {
			return false
		}
		s.SliceDel()
	case 7:
		if !s.rR1() {
			return false
		}
		s.SliceDel()
		v2 := s.Limit - s.Cursor
		lab1:
		for {
			s.Ket = s.Cursor
			av := s.FindAmongB(italianA4)
			if av == 0 {
				s.Cursor = s.Limit - v2
				break lab1
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v2
				break lab1
			}
			s.SliceDel()
			switch av {
			case 1:
				s.Ket = s.Cursor
				if !s.EqSBStr("at") {
					s.Cursor = s.Limit - v2
					break lab1
				}
				s.Bra = s.Cursor
				if !s.rR2() {
					s.Cursor = s.Limit - v2
					break lab1
				}
				s.SliceDel()
			}
			break lab1
		}
	case 8:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v3 := s.Limit - s.Cursor
		lab2:
		for {
			s.Ket = s.Cursor
			if s.FindAmongB(italianA5) == 0 {
				s.Cursor = s.Limit - v3
				break lab2
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v3
				break lab2
			}
			s.SliceDel()
			break lab2
		}
	case 9:
		if !s.rR2() {
			return false
		}
		s.SliceDel()
		v4 := s.Limit - s.Cursor
		lab3:
		for {
			s.Ket = s.Cursor
			if !s.EqSBStr("at") {
				s.Cursor = s.Limit - v4
				break lab3
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v4
				break lab3
			}
			s.SliceDel()
			s.Ket = s.Cursor
			if !s.EqSBStr("ic") {
				s.Cursor = s.Limit - v4
				break lab3
			}
			s.Bra = s.Cursor
			if !s.rR2() {
				s.Cursor = s.Limit - v4
				break lab3
			}
			s.SliceDel()
			break lab3
		}
	}
	return true
}

func (s *ItalianStemmer) rVerbSuffix() bool {
	if s.Cursor < s.iPV {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iPV
	s.Ket = s.Cursor
	if s.FindAmongB(italianA7) == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	s.LimitBackward = v2
	return true
}

func (s *ItalianStemmer) rVowelSuffix() bool {
	v1 := s.Limit - s.Cursor
	lab0:
	for {
		s.Ket = s.Cursor
		if !s.InGroupingB(italianGAEIO, 97, 242) {
			s.Cursor = s.Limit - v1
			break lab0
		}
		s.Bra = s.Cursor
		if !s.rRV() {
			s.Cursor = s.Limit - v1
			break lab0
		}
		s.SliceDel()
		s.Ket = s.Cursor
		if !s.EqSBStr("i") {
			s.Cursor = s.Limit - v1
			break lab0
		}
		s.Bra = s.Cursor
		if !s.rRV() {
			s.Cursor = s.Limit - v1
			break lab0
		}
		s.SliceDel()
		break lab0
	}
	v2 := s.Limit - s.Cursor
	lab1:
	for {
		s.Ket = s.Cursor
		if !s.EqSBStr("h") {
			s.Cursor = s.Limit - v2
			break lab1
		}
		s.Bra = s.Cursor
		if !s.InGroupingB(italianGCG, 99, 103) {
			s.Cursor = s.Limit - v2
			break lab1
		}
		if !s.rRV() {
			s.Cursor = s.Limit - v2
			break lab1
		}
		s.SliceDel()
		break lab1
	}
	return true
}

func (s *ItalianStemmer) rExceptions() bool {
	s.Bra = s.Cursor
	if !s.EqSStr("divano") {
		return false
	}
	if s.Cursor < s.Limit {
		return false
	}
	s.Ket = s.Cursor
	s.SliceFromStr("divan")
	return true
}

// Stem applies the Italian stemming algorithm to the current word.
func (s *ItalianStemmer) Stem() bool {
lab0:
	for {
		v1 := s.Cursor
		lab1:
		for {
			if !s.rExceptions() {
				break lab1
			}
			break lab0
		}
		s.Cursor = v1
		v2 := s.Cursor
		s.rPrelude()
		s.Cursor = v2
		s.rMarkRegions()
		s.LimitBackward = s.Cursor
		s.Cursor = s.Limit
		v4 := s.Limit - s.Cursor
		s.rAttachedPronoun()
		s.Cursor = s.Limit - v4
		v5 := s.Limit - s.Cursor
		lab2:
		for {
			lab3:
			for {
				v6 := s.Limit - s.Cursor
				lab4:
				for {
					if !s.rStandardSuffix() {
						break lab4
					}
					break lab3
				}
				s.Cursor = s.Limit - v6
				if !s.rVerbSuffix() {
					break lab2
				}
				break lab3
			}
			break lab2
		}
		s.Cursor = s.Limit - v5
		v7 := s.Limit - s.Cursor
		s.rVowelSuffix()
		s.Cursor = s.Limit - v7
		s.Cursor = s.LimitBackward
		v8 := s.Cursor
		s.rPostlude()
		s.Cursor = v8
		break lab0
	}
	return true
}
