// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

// LithuanianStemmer mirrors org.tartarus.snowball.ext.LithuanianStemmer.
type LithuanianStemmer struct {
	*snowball.SnowballProgram
	iP1 int
}

// NewLithuanianStemmer builds a LithuanianStemmer.
func NewLithuanianStemmer() *LithuanianStemmer {
	return &LithuanianStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

// lithuanianA0: inflectional endings for step 1.
var lithuanianA0 = []*snowball.Among{
	snowball.NewAmong("a", -1, -1),
	snowball.NewAmong("ia", 0, -1),
	snowball.NewAmong("eria", 1, -1),
	snowball.NewAmong("osna", 0, -1),
	snowball.NewAmong("iosna", 3, -1),
	snowball.NewAmong("uosna", 3, -1),
	snowball.NewAmong("iuosna", 5, -1),
	snowball.NewAmong("ysna", 0, -1),
	snowball.NewAmong("ėsna", 0, -1),
	snowball.NewAmong("e", -1, -1),
	snowball.NewAmong("ie", 9, -1),
	snowball.NewAmong("enie", 10, -1),
	snowball.NewAmong("erie", 10, -1),
	snowball.NewAmong("oje", 9, -1),
	snowball.NewAmong("ioje", 13, -1),
	snowball.NewAmong("uje", 9, -1),
	snowball.NewAmong("iuje", 15, -1),
	snowball.NewAmong("yje", 9, -1),
	snowball.NewAmong("enyje", 17, -1),
	snowball.NewAmong("eryje", 17, -1),
	snowball.NewAmong("ėje", 9, -1),
	snowball.NewAmong("ame", 9, -1),
	snowball.NewAmong("iame", 21, -1),
	snowball.NewAmong("sime", 9, -1),
	snowball.NewAmong("ome", 9, -1),
	snowball.NewAmong("ėme", 9, -1),
	snowball.NewAmong("tumėme", 25, -1),
	snowball.NewAmong("ose", 9, -1),
	snowball.NewAmong("iose", 27, -1),
	snowball.NewAmong("uose", 27, -1),
	snowball.NewAmong("iuose", 29, -1),
	snowball.NewAmong("yse", 9, -1),
	snowball.NewAmong("enyse", 31, -1),
	snowball.NewAmong("eryse", 31, -1),
	snowball.NewAmong("ėse", 9, -1),
	snowball.NewAmong("ate", 9, -1),
	snowball.NewAmong("iate", 35, -1),
	snowball.NewAmong("ite", 9, -1),
	snowball.NewAmong("kite", 37, -1),
	snowball.NewAmong("site", 37, -1),
	snowball.NewAmong("ote", 9, -1),
	snowball.NewAmong("tute", 9, -1),
	snowball.NewAmong("ėte", 9, -1),
	snowball.NewAmong("tumėte", 42, -1),
	snowball.NewAmong("i", -1, -1),
	snowball.NewAmong("ai", 44, -1),
	snowball.NewAmong("iai", 45, -1),
	snowball.NewAmong("eriai", 46, -1),
	snowball.NewAmong("ei", 44, -1),
	snowball.NewAmong("tumei", 48, -1),
	snowball.NewAmong("ki", 44, -1),
	snowball.NewAmong("imi", 44, -1),
	snowball.NewAmong("erimi", 51, -1),
	snowball.NewAmong("umi", 44, -1),
	snowball.NewAmong("iumi", 53, -1),
	snowball.NewAmong("si", 44, -1),
	snowball.NewAmong("asi", 55, -1),
	snowball.NewAmong("iasi", 56, -1),
	snowball.NewAmong("esi", 55, -1),
	snowball.NewAmong("iesi", 58, -1),
	snowball.NewAmong("siesi", 59, -1),
	snowball.NewAmong("isi", 55, -1),
	snowball.NewAmong("aisi", 61, -1),
	snowball.NewAmong("eisi", 61, -1),
	snowball.NewAmong("tumeisi", 63, -1),
	snowball.NewAmong("uisi", 61, -1),
	snowball.NewAmong("osi", 55, -1),
	snowball.NewAmong("ėjosi", 66, -1),
	snowball.NewAmong("uosi", 66, -1),
	snowball.NewAmong("iuosi", 68, -1),
	snowball.NewAmong("siuosi", 69, -1),
	snowball.NewAmong("usi", 55, -1),
	snowball.NewAmong("ausi", 71, -1),
	snowball.NewAmong("čiausi", 72, -1),
	snowball.NewAmong("ąsi", 55, -1),
	snowball.NewAmong("ėsi", 55, -1),
	snowball.NewAmong("ųsi", 55, -1),
	snowball.NewAmong("tųsi", 76, -1),
	snowball.NewAmong("ti", 44, -1),
	snowball.NewAmong("enti", 78, -1),
	snowball.NewAmong("inti", 78, -1),
	snowball.NewAmong("oti", 78, -1),
	snowball.NewAmong("ioti", 81, -1),
	snowball.NewAmong("uoti", 81, -1),
	snowball.NewAmong("iuoti", 83, -1),
	snowball.NewAmong("auti", 78, -1),
	snowball.NewAmong("iauti", 85, -1),
	snowball.NewAmong("yti", 78, -1),
	snowball.NewAmong("ėti", 78, -1),
	snowball.NewAmong("telėti", 88, -1),
	snowball.NewAmong("inėti", 88, -1),
	snowball.NewAmong("terėti", 88, -1),
	snowball.NewAmong("ui", 44, -1),
	snowball.NewAmong("iui", 92, -1),
	snowball.NewAmong("eniui", 93, -1),
	snowball.NewAmong("oj", -1, -1),
	snowball.NewAmong("ėj", -1, -1),
	snowball.NewAmong("k", -1, -1),
	snowball.NewAmong("am", -1, -1),
	snowball.NewAmong("iam", 98, -1),
	snowball.NewAmong("iem", -1, -1),
	snowball.NewAmong("im", -1, -1),
	snowball.NewAmong("sim", 101, -1),
	snowball.NewAmong("om", -1, -1),
	snowball.NewAmong("tum", -1, -1),
	snowball.NewAmong("ėm", -1, -1),
	snowball.NewAmong("tumėm", 105, -1),
	snowball.NewAmong("an", -1, -1),
	snowball.NewAmong("on", -1, -1),
	snowball.NewAmong("ion", 108, -1),
	snowball.NewAmong("un", -1, -1),
	snowball.NewAmong("iun", 110, -1),
	snowball.NewAmong("ėn", -1, -1),
	snowball.NewAmong("o", -1, -1),
	snowball.NewAmong("io", 113, -1),
	snowball.NewAmong("enio", 114, -1),
	snowball.NewAmong("ėjo", 113, -1),
	snowball.NewAmong("uo", 113, -1),
	snowball.NewAmong("s", -1, -1),
	snowball.NewAmong("as", 118, -1),
	snowball.NewAmong("ias", 119, -1),
	snowball.NewAmong("es", 118, -1),
	snowball.NewAmong("ies", 121, -1),
	snowball.NewAmong("is", 118, -1),
	snowball.NewAmong("ais", 123, -1),
	snowball.NewAmong("iais", 124, -1),
	snowball.NewAmong("tumeis", 123, -1),
	snowball.NewAmong("imis", 123, -1),
	snowball.NewAmong("enimis", 127, -1),
	snowball.NewAmong("omis", 123, -1),
	snowball.NewAmong("iomis", 129, -1),
	snowball.NewAmong("umis", 123, -1),
	snowball.NewAmong("ėmis", 123, -1),
	snowball.NewAmong("enis", 123, -1),
	snowball.NewAmong("asis", 123, -1),
	snowball.NewAmong("ysis", 123, -1),
	snowball.NewAmong("ams", 118, -1),
	snowball.NewAmong("iams", 136, -1),
	snowball.NewAmong("iems", 118, -1),
	snowball.NewAmong("ims", 118, -1),
	snowball.NewAmong("enims", 139, -1),
	snowball.NewAmong("erims", 139, -1),
	snowball.NewAmong("oms", 118, -1),
	snowball.NewAmong("ioms", 142, -1),
	snowball.NewAmong("ums", 118, -1),
	snowball.NewAmong("ėms", 118, -1),
	snowball.NewAmong("ens", 118, -1),
	snowball.NewAmong("os", 118, -1),
	snowball.NewAmong("ios", 147, -1),
	snowball.NewAmong("uos", 147, -1),
	snowball.NewAmong("iuos", 149, -1),
	snowball.NewAmong("ers", 118, -1),
	snowball.NewAmong("us", 118, -1),
	snowball.NewAmong("aus", 152, -1),
	snowball.NewAmong("iaus", 153, -1),
	snowball.NewAmong("ius", 152, -1),
	snowball.NewAmong("ys", 118, -1),
	snowball.NewAmong("enys", 156, -1),
	snowball.NewAmong("erys", 156, -1),
	snowball.NewAmong("ąs", 118, -1),
	snowball.NewAmong("iąs", 159, -1),
	snowball.NewAmong("ės", 118, -1),
	snowball.NewAmong("amės", 161, -1),
	snowball.NewAmong("iamės", 162, -1),
	snowball.NewAmong("imės", 161, -1),
	snowball.NewAmong("kimės", 164, -1),
	snowball.NewAmong("simės", 164, -1),
	snowball.NewAmong("omės", 161, -1),
	snowball.NewAmong("ėmės", 161, -1),
	snowball.NewAmong("tumėmės", 168, -1),
	snowball.NewAmong("atės", 161, -1),
	snowball.NewAmong("iatės", 170, -1),
	snowball.NewAmong("sitės", 161, -1),
	snowball.NewAmong("otės", 161, -1),
	snowball.NewAmong("ėtės", 161, -1),
	snowball.NewAmong("tumėtės", 174, -1),
	snowball.NewAmong("įs", 118, -1),
	snowball.NewAmong("ūs", 118, -1),
	snowball.NewAmong("tųs", 118, -1),
	snowball.NewAmong("at", -1, -1),
	snowball.NewAmong("iat", 179, -1),
	snowball.NewAmong("it", -1, -1),
	snowball.NewAmong("sit", 181, -1),
	snowball.NewAmong("ot", -1, -1),
	snowball.NewAmong("ėt", -1, -1),
	snowball.NewAmong("tumėt", 184, -1),
	snowball.NewAmong("u", -1, -1),
	snowball.NewAmong("au", 186, -1),
	snowball.NewAmong("iau", 187, -1),
	snowball.NewAmong("čiau", 188, -1),
	snowball.NewAmong("iu", 186, -1),
	snowball.NewAmong("eniu", 190, -1),
	snowball.NewAmong("siu", 190, -1),
	snowball.NewAmong("y", -1, -1),
	snowball.NewAmong("ą", -1, -1),
	snowball.NewAmong("ią", 194, -1),
	snowball.NewAmong("ė", -1, -1),
	snowball.NewAmong("ę", -1, -1),
	snowball.NewAmong("į", -1, -1),
	snowball.NewAmong("enį", 198, -1),
	snowball.NewAmong("erį", 198, -1),
	snowball.NewAmong("ų", -1, -1),
	snowball.NewAmong("ių", 201, -1),
	snowball.NewAmong("erų", 201, -1),
}

// lithuanianA1: secondary suffixes for step 2.
var lithuanianA1 = []*snowball.Among{
	snowball.NewAmong("ing", -1, -1),
	snowball.NewAmong("aj", -1, -1),
	snowball.NewAmong("iaj", 1, -1),
	snowball.NewAmong("iej", -1, -1),
	snowball.NewAmong("oj", -1, -1),
	snowball.NewAmong("ioj", 4, -1),
	snowball.NewAmong("uoj", 4, -1),
	snowball.NewAmong("iuoj", 6, -1),
	snowball.NewAmong("auj", -1, -1),
	snowball.NewAmong("ąj", -1, -1),
	snowball.NewAmong("iąj", 9, -1),
	snowball.NewAmong("ėj", -1, -1),
	snowball.NewAmong("ųj", -1, -1),
	snowball.NewAmong("iųj", 12, -1),
	snowball.NewAmong("ok", -1, -1),
	snowball.NewAmong("iok", 14, -1),
	snowball.NewAmong("iuk", -1, -1),
	snowball.NewAmong("uliuk", 16, -1),
	snowball.NewAmong("učiuk", 16, -1),
	snowball.NewAmong("išk", -1, -1),
	snowball.NewAmong("iul", -1, -1),
	snowball.NewAmong("yl", -1, -1),
	snowball.NewAmong("ėl", -1, -1),
	snowball.NewAmong("am", -1, -1),
	snowball.NewAmong("dam", 23, -1),
	snowball.NewAmong("jam", 23, -1),
	snowball.NewAmong("zgan", -1, -1),
	snowball.NewAmong("ain", -1, -1),
	snowball.NewAmong("esn", -1, -1),
	snowball.NewAmong("op", -1, -1),
	snowball.NewAmong("iop", 29, -1),
	snowball.NewAmong("ias", -1, -1),
	snowball.NewAmong("ies", -1, -1),
	snowball.NewAmong("ais", -1, -1),
	snowball.NewAmong("iais", 33, -1),
	snowball.NewAmong("os", -1, -1),
	snowball.NewAmong("ios", 35, -1),
	snowball.NewAmong("uos", 35, -1),
	snowball.NewAmong("iuos", 37, -1),
	snowball.NewAmong("aus", -1, -1),
	snowball.NewAmong("iaus", 39, -1),
	snowball.NewAmong("ąs", -1, -1),
	snowball.NewAmong("iąs", 41, -1),
	snowball.NewAmong("ęs", -1, -1),
	snowball.NewAmong("utėait", -1, -1),
	snowball.NewAmong("ant", -1, -1),
	snowball.NewAmong("iant", 45, -1),
	snowball.NewAmong("siant", 46, -1),
	snowball.NewAmong("int", -1, -1),
	snowball.NewAmong("ot", -1, -1),
	snowball.NewAmong("uot", 49, -1),
	snowball.NewAmong("iuot", 50, -1),
	snowball.NewAmong("yt", -1, -1),
	snowball.NewAmong("ėt", -1, -1),
	snowball.NewAmong("ykšt", -1, -1),
	snowball.NewAmong("iau", -1, -1),
	snowball.NewAmong("dav", -1, -1),
	snowball.NewAmong("sv", -1, -1),
	snowball.NewAmong("šv", -1, -1),
	snowball.NewAmong("ykšč", -1, -1),
	snowball.NewAmong("ę", -1, -1),
	snowball.NewAmong("ėję", 60, -1),
}

// lithuanianA2: conflict-resolution replacements.
var lithuanianA2 = []*snowball.Among{
	snowball.NewAmong("ojime", -1, 7),
	snowball.NewAmong("ėjime", -1, 3),
	snowball.NewAmong("avime", -1, 6),
	snowball.NewAmong("okate", -1, 8),
	snowball.NewAmong("aite", -1, 1),
	snowball.NewAmong("uote", -1, 2),
	snowball.NewAmong("asius", -1, 5),
	snowball.NewAmong("okatės", -1, 8),
	snowball.NewAmong("aitės", -1, 1),
	snowball.NewAmong("uotės", -1, 2),
	snowball.NewAmong("esiu", -1, 4),
}

// lithuanianA3: č/dž reversion suffixes.
var lithuanianA3 = []*snowball.Among{
	snowball.NewAmong("č", -1, 1),
	snowball.NewAmong("dž", -1, 2),
}

// lithuanianA4: gd reversion suffix.
var lithuanianA4 = []*snowball.Among{
	snowball.NewAmong("gd", -1, 1),
}

// lithuanianGV: vowels.
var lithuanianGV = []byte{
	17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 64, 1, 0, 64, 0, 0, 0, 0,
	0, 0, 0, 4, 4,
}

// rStep1 removes primary inflectional suffixes bounded by iP1.
func (s *LithuanianStemmer) rStep1() bool {
	if s.Cursor < s.iP1 {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iP1
	s.Ket = s.Cursor
	if s.FindAmongB(lithuanianA0) == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	s.LimitBackward = v2
	s.SliceDel()
	return true
}

// rStep2 repeatedly removes secondary suffixes bounded by iP1.
func (s *LithuanianStemmer) rStep2() bool {
	for {
		v1 := s.Limit - s.Cursor
		lab0:
		for {
			if s.Cursor < s.iP1 {
				break lab0
			}
			v3 := s.LimitBackward
			s.LimitBackward = s.iP1
			s.Ket = s.Cursor
			if s.FindAmongB(lithuanianA1) == 0 {
				s.LimitBackward = v3
				break lab0
			}
			s.Bra = s.Cursor
			s.LimitBackward = v3
			s.SliceDel()
			continue
		}
		s.Cursor = s.Limit - v1
		break
	}
	return true
}

// rFixConflicts resolves ambiguous suffixes.
func (s *LithuanianStemmer) rFixConflicts() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(lithuanianA2)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		s.SliceFromStr("aitė")
	case 2:
		s.SliceFromStr("uotė")
	case 3:
		s.SliceFromStr("ėjimas")
	case 4:
		s.SliceFromStr("esys")
	case 5:
		s.SliceFromStr("asys")
	case 6:
		s.SliceFromStr("avimas")
	case 7:
		s.SliceFromStr("ojimas")
	case 8:
		s.SliceFromStr("okatė")
	}
	return true
}

// rFixChdz reverts č→t and dž→d.
func (s *LithuanianStemmer) rFixChdz() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(lithuanianA3)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		s.SliceFromStr("t")
	case 2:
		s.SliceFromStr("d")
	}
	return true
}

// rFixGd reverts gd→g.
func (s *LithuanianStemmer) rFixGd() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(lithuanianA4) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceFromStr("g")
	return true
}

// Stem performs Lithuanian stemming.
func (s *LithuanianStemmer) Stem() bool {
	s.iP1 = s.Limit
	v1 := s.Cursor
	lab0:
	for {
		v2 := s.Cursor
		lab1:
		for {
			v3 := s.Cursor
			if !s.EqSStr("a") {
				s.Cursor = v2
				break lab1
			}
			s.Cursor = v3
			if s.Limit <= 6 {
				s.Cursor = v2
				break lab1
			}
			c := s.Cursor + 1
			if c > s.Limit {
				s.Cursor = v2
				break lab1
			}
			s.Cursor = c
			break lab1
		}
	golab2:
		for {
			lab3:
			for {
				if !s.InGrouping(lithuanianGV, 97, 371) {
					break lab3
				}
				break golab2
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
	golab4:
		for {
			lab5:
			for {
				if !s.OutGrouping(lithuanianGV, 97, 371) {
					break lab5
				}
				break golab4
			}
			if s.Cursor >= s.Limit {
				break lab0
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
		break lab0
	}
	s.Cursor = v1
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	v6 := s.Limit - s.Cursor
	s.rFixConflicts()
	s.Cursor = s.Limit - v6
	v7 := s.Limit - s.Cursor
	s.rStep1()
	s.Cursor = s.Limit - v7
	v8 := s.Limit - s.Cursor
	s.rFixChdz()
	s.Cursor = s.Limit - v8
	v9 := s.Limit - s.Cursor
	s.rStep2()
	s.Cursor = s.Limit - v9
	v10 := s.Limit - s.Cursor
	s.rFixChdz()
	s.Cursor = s.Limit - v10
	v11 := s.Limit - s.Cursor
	s.rFixGd()
	s.Cursor = s.Limit - v11
	s.Cursor = s.LimitBackward
	return true
}
