// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from org.tartarus.snowball.ext.NepaliStemmer.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

var nepaliA0 = []*snowball.Among{
	snowball.NewAmong("लाई", -1, 1),
	snowball.NewAmong("लाईं", -1, 1),
	snowball.NewAmong("सँग", -1, 1),
	snowball.NewAmong("संग", -1, 1),
	snowball.NewAmong("मार्फत", -1, 1),
	snowball.NewAmong("रत", -1, 1),
	snowball.NewAmong("का", -1, 2),
	snowball.NewAmong("मा", -1, 1),
	snowball.NewAmong("द्वारा", -1, 1),
	snowball.NewAmong("कि", -1, 2),
	snowball.NewAmong("पछि", -1, 1),
	snowball.NewAmong("की", -1, 2),
	snowball.NewAmong("ले", -1, 1),
	snowball.NewAmong("कै", -1, 2),
	snowball.NewAmong("सँगै", -1, 1),
	snowball.NewAmong("मै", -1, 1),
	snowball.NewAmong("को", -1, 2),
}

var nepaliA1 = []*snowball.Among{
	snowball.NewAmong("ँ", -1, -1),
	snowball.NewAmong("ं", -1, -1),
	snowball.NewAmong("ै", -1, -1),
}

var nepaliA2 = []*snowball.Among{
	snowball.NewAmong("ँ", -1, 1),
	snowball.NewAmong("ं", -1, 1),
	snowball.NewAmong("ै", -1, 2),
}

var nepaliA3 = []*snowball.Among{
	snowball.NewAmong("थिए", -1, 1),
	snowball.NewAmong("छ", -1, 1),
	snowball.NewAmong("इछ", 1, 1),
	snowball.NewAmong("एछ", 1, 1),
	snowball.NewAmong("िछ", 1, 1),
	snowball.NewAmong("ेछ", 1, 1),
	snowball.NewAmong("नेछ", 5, 1),
	snowball.NewAmong("हुनेछ", 6, 1),
	snowball.NewAmong("इन्छ", 1, 1),
	snowball.NewAmong("िन्छ", 1, 1),
	snowball.NewAmong("हुन्छ", 1, 1),
	snowball.NewAmong("एका", -1, 1),
	snowball.NewAmong("इएका", 11, 1),
	snowball.NewAmong("िएका", 11, 1),
	snowball.NewAmong("ेका", -1, 1),
	snowball.NewAmong("नेका", 14, 1),
	snowball.NewAmong("दा", -1, 1),
	snowball.NewAmong("इदा", 16, 1),
	snowball.NewAmong("िदा", 16, 1),
	snowball.NewAmong("देखि", -1, 1),
	snowball.NewAmong("माथि", -1, 1),
	snowball.NewAmong("एकी", -1, 1),
	snowball.NewAmong("इएकी", 21, 1),
	snowball.NewAmong("िएकी", 21, 1),
	snowball.NewAmong("ेकी", -1, 1),
	snowball.NewAmong("देखी", -1, 1),
	snowball.NewAmong("थी", -1, 1),
	snowball.NewAmong("दी", -1, 1),
	snowball.NewAmong("छु", -1, 1),
	snowball.NewAmong("एछु", 28, 1),
	snowball.NewAmong("ेछु", 28, 1),
	snowball.NewAmong("नेछु", 30, 1),
	snowball.NewAmong("नु", -1, 1),
	snowball.NewAmong("हरु", -1, 1),
	snowball.NewAmong("हरू", -1, 1),
	snowball.NewAmong("छे", -1, 1),
	snowball.NewAmong("थे", -1, 1),
	snowball.NewAmong("ने", -1, 1),
	snowball.NewAmong("एकै", -1, 1),
	snowball.NewAmong("ेकै", -1, 1),
	snowball.NewAmong("नेकै", 39, 1),
	snowball.NewAmong("दै", -1, 1),
	snowball.NewAmong("इदै", 41, 1),
	snowball.NewAmong("िदै", 41, 1),
	snowball.NewAmong("एको", -1, 1),
	snowball.NewAmong("इएको", 44, 1),
	snowball.NewAmong("िएको", 44, 1),
	snowball.NewAmong("ेको", -1, 1),
	snowball.NewAmong("नेको", 47, 1),
	snowball.NewAmong("दो", -1, 1),
	snowball.NewAmong("इदो", 49, 1),
	snowball.NewAmong("िदो", 49, 1),
	snowball.NewAmong("यो", -1, 1),
	snowball.NewAmong("इयो", 52, 1),
	snowball.NewAmong("भयो", 52, 1),
	snowball.NewAmong("ियो", 52, 1),
	snowball.NewAmong("थियो", 55, 1),
	snowball.NewAmong("दियो", 55, 1),
	snowball.NewAmong("थ्यो", 52, 1),
	snowball.NewAmong("छौ", -1, 1),
	snowball.NewAmong("इछौ", 59, 1),
	snowball.NewAmong("एछौ", 59, 1),
	snowball.NewAmong("िछौ", 59, 1),
	snowball.NewAmong("ेछौ", 59, 1),
	snowball.NewAmong("नेछौ", 63, 1),
	snowball.NewAmong("यौ", -1, 1),
	snowball.NewAmong("थियौ", 65, 1),
	snowball.NewAmong("छ्यौ", 65, 1),
	snowball.NewAmong("थ्यौ", 65, 1),
	snowball.NewAmong("छन्", -1, 1),
	snowball.NewAmong("इछन्", 69, 1),
	snowball.NewAmong("एछन्", 69, 1),
	snowball.NewAmong("िछन्", 69, 1),
	snowball.NewAmong("ेछन्", 69, 1),
	snowball.NewAmong("नेछन्", 73, 1),
	snowball.NewAmong("लान्", -1, 1),
	snowball.NewAmong("छिन्", -1, 1),
	snowball.NewAmong("थिन्", -1, 1),
	snowball.NewAmong("पर्", -1, 1),
	snowball.NewAmong("इस्", -1, 1),
	snowball.NewAmong("थिइस्", 79, 1),
	snowball.NewAmong("छस्", -1, 1),
	snowball.NewAmong("इछस्", 81, 1),
	snowball.NewAmong("एछस्", 81, 1),
	snowball.NewAmong("िछस्", 81, 1),
	snowball.NewAmong("ेछस्", 81, 1),
	snowball.NewAmong("नेछस्", 85, 1),
	snowball.NewAmong("िस्", -1, 1),
	snowball.NewAmong("थिस्", 87, 1),
	snowball.NewAmong("छेस्", -1, 1),
	snowball.NewAmong("होस्", -1, 1),
}

// NepaliStemmer implements the Snowball stemming algorithm for Nepali.
// It mirrors org.tartarus.snowball.ext.NepaliStemmer.
type NepaliStemmer struct {
	snowball.SnowballProgram
}

// NewNepaliStemmer constructs a NepaliStemmer.
func NewNepaliStemmer() *NepaliStemmer {
	return &NepaliStemmer{}
}

func (s *NepaliStemmer) rRemoveCategory1() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(nepaliA0)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
	lab0:
		for {
			v1 := s.Limit - s.Cursor
			lab1:
			for {
				lab2:
				for {
					v2 := s.Limit - s.Cursor
					lab3:
					for {
						if !s.EqSBStr("ए") {
							break lab3
						}
						break lab2
					}
					s.Cursor = s.Limit - v2
					if !s.EqSBStr("े") {
						break lab1
					}
					break lab2
				}
				break lab0
			}
			s.Cursor = s.Limit - v1
			s.SliceDel()
			break lab0
		}
	}
	return true
}

func (s *NepaliStemmer) rCheckCategory2() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(nepaliA1) == 0 {
		return false
	}
	s.Bra = s.Cursor
	return true
}

func (s *NepaliStemmer) rRemoveCategory2() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(nepaliA2)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
	lab0:
		for {
			v1 := s.Limit - s.Cursor
			lab1:
			for {
				if !s.EqSBStr("यौ") {
					break lab1
				}
				break lab0
			}
			s.Cursor = s.Limit - v1
			lab2:
			for {
				if !s.EqSBStr("छौ") {
					break lab2
				}
				break lab0
			}
			s.Cursor = s.Limit - v1
			lab3:
			for {
				if !s.EqSBStr("नौ") {
					break lab3
				}
				break lab0
			}
			s.Cursor = s.Limit - v1
			if !s.EqSBStr("थे") {
				return false
			}
			break lab0
		}
		s.SliceDel()
	case 2:
		if !s.EqSBStr("त्र") {
			return false
		}
		s.SliceDel()
	}
	return true
}

func (s *NepaliStemmer) rRemoveCategory3() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(nepaliA3) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	return true
}

// Stem applies the Nepali stemming algorithm to the current word.
func (s *NepaliStemmer) Stem() bool {
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	v1 := s.Limit - s.Cursor
	s.rRemoveCategory1()
	s.Cursor = s.Limit - v1
	v2 := s.Limit - s.Cursor
lab0:
	for {
		for {
			v3 := s.Limit - s.Cursor
			lab1:
			for {
				v4 := s.Limit - s.Cursor
				lab2:
				for {
					v5 := s.Limit - s.Cursor
					if !s.rCheckCategory2() {
						break lab2
					}
					s.Cursor = s.Limit - v5
					if !s.rRemoveCategory2() {
						break lab2
					}
					break lab2
				}
				s.Cursor = s.Limit - v4
				if !s.rRemoveCategory3() {
					break lab1
				}
				continue
			}
			s.Cursor = s.Limit - v3
			break
		}
		break lab0
	}
	s.Cursor = s.Limit - v2
	s.Cursor = s.LimitBackward
	return true
}
