// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// PortugueseStemmer implements the Portuguese Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.PortugueseStemmer
// from Apache Lucene 10.4.0.
type PortugueseStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewPortugueseStemmer creates a new PortugueseStemmer.
func NewPortugueseStemmer() *PortugueseStemmer {
	return &PortugueseStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var portugueseA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("ã", 0, 1),
	snowball.NewAmong("õ", 0, 2),
}

var portugueseA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("a~", 0, 1),
	snowball.NewAmong("o~", 0, 2),
}

var portugueseA2 = []*snowball.Among{
	snowball.NewAmong("ic", -1, -1),
	snowball.NewAmong("ad", -1, -1),
	snowball.NewAmong("os", -1, -1),
	snowball.NewAmong("iv", -1, 1),
}

var portugueseA3 = []*snowball.Among{
	snowball.NewAmong("ante", -1, 1),
	snowball.NewAmong("avel", -1, 1),
	snowball.NewAmong("ível", -1, 1),
}

var portugueseA4 = []*snowball.Among{
	snowball.NewAmong("ic", -1, 1),
	snowball.NewAmong("abil", -1, 1),
	snowball.NewAmong("iv", -1, 1),
}

var portugueseA5 = []*snowball.Among{
	snowball.NewAmong("ica", -1, 1),
	snowball.NewAmong("ância", -1, 1),
	snowball.NewAmong("ência", -1, 4),
	snowball.NewAmong("logia", -1, 2),
	snowball.NewAmong("ira", -1, 9),
	snowball.NewAmong("adora", -1, 1),
	snowball.NewAmong("osa", -1, 1),
	snowball.NewAmong("ista", -1, 1),
	snowball.NewAmong("iva", -1, 8),
	snowball.NewAmong("eza", -1, 1),
	snowball.NewAmong("idade", -1, 7),
	snowball.NewAmong("ante", -1, 1),
	snowball.NewAmong("mente", -1, 6),
	snowball.NewAmong("amente", 12, 5),
	snowball.NewAmong("ável", -1, 1),
	snowball.NewAmong("ível", -1, 1),
	snowball.NewAmong("ico", -1, 1),
	snowball.NewAmong("ismo", -1, 1),
	snowball.NewAmong("oso", -1, 1),
	snowball.NewAmong("amento", -1, 1),
	snowball.NewAmong("imento", -1, 1),
	snowball.NewAmong("ivo", -1, 8),
	snowball.NewAmong("aça~o", -1, 1),
	snowball.NewAmong("uça~o", -1, 3),
	snowball.NewAmong("ador", -1, 1),
	snowball.NewAmong("icas", -1, 1),
	snowball.NewAmong("ências", -1, 4),
	snowball.NewAmong("logias", -1, 2),
	snowball.NewAmong("iras", -1, 9),
	snowball.NewAmong("adoras", -1, 1),
	snowball.NewAmong("osas", -1, 1),
	snowball.NewAmong("istas", -1, 1),
	snowball.NewAmong("ivas", -1, 8),
	snowball.NewAmong("ezas", -1, 1),
	snowball.NewAmong("idades", -1, 7),
	snowball.NewAmong("adores", -1, 1),
	snowball.NewAmong("antes", -1, 1),
	snowball.NewAmong("aço~es", -1, 1),
	snowball.NewAmong("uço~es", -1, 3),
	snowball.NewAmong("icos", -1, 1),
	snowball.NewAmong("ismos", -1, 1),
	snowball.NewAmong("osos", -1, 1),
	snowball.NewAmong("amentos", -1, 1),
	snowball.NewAmong("imentos", -1, 1),
	snowball.NewAmong("ivos", -1, 8),
}

var portugueseA6 = []*snowball.Among{
	snowball.NewAmong("ada", -1, 1),
	snowball.NewAmong("ida", -1, 1),
	snowball.NewAmong("ia", -1, 1),
	snowball.NewAmong("aria", 2, 1),
	snowball.NewAmong("eria", 2, 1),
	snowball.NewAmong("iria", 2, 1),
	snowball.NewAmong("ara", -1, 1),
	snowball.NewAmong("era", -1, 1),
	snowball.NewAmong("ira", -1, 1),
	snowball.NewAmong("ava", -1, 1),
	snowball.NewAmong("asse", -1, 1),
	snowball.NewAmong("esse", -1, 1),
	snowball.NewAmong("isse", -1, 1),
	snowball.NewAmong("aste", -1, 1),
	snowball.NewAmong("este", -1, 1),
	snowball.NewAmong("iste", -1, 1),
	snowball.NewAmong("ei", -1, 1),
	snowball.NewAmong("arei", 16, 1),
	snowball.NewAmong("erei", 16, 1),
	snowball.NewAmong("irei", 16, 1),
	snowball.NewAmong("am", -1, 1),
	snowball.NewAmong("iam", 20, 1),
	snowball.NewAmong("ariam", 21, 1),
	snowball.NewAmong("eriam", 21, 1),
	snowball.NewAmong("iriam", 21, 1),
	snowball.NewAmong("aram", 20, 1),
	snowball.NewAmong("eram", 20, 1),
	snowball.NewAmong("iram", 20, 1),
	snowball.NewAmong("avam", 20, 1),
	snowball.NewAmong("em", -1, 1),
	snowball.NewAmong("arem", 29, 1),
	snowball.NewAmong("erem", 29, 1),
	snowball.NewAmong("irem", 29, 1),
	snowball.NewAmong("assem", 29, 1),
	snowball.NewAmong("essem", 29, 1),
	snowball.NewAmong("issem", 29, 1),
	snowball.NewAmong("ado", -1, 1),
	snowball.NewAmong("ido", -1, 1),
	snowball.NewAmong("ando", -1, 1),
	snowball.NewAmong("endo", -1, 1),
	snowball.NewAmong("indo", -1, 1),
	snowball.NewAmong("ara~o", -1, 1),
	snowball.NewAmong("era~o", -1, 1),
	snowball.NewAmong("ira~o", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("ir", -1, 1),
	snowball.NewAmong("as", -1, 1),
	snowball.NewAmong("adas", 47, 1),
	snowball.NewAmong("idas", 47, 1),
	snowball.NewAmong("ias", 47, 1),
	snowball.NewAmong("arias", 50, 1),
	snowball.NewAmong("erias", 50, 1),
	snowball.NewAmong("irias", 50, 1),
	snowball.NewAmong("aras", 47, 1),
	snowball.NewAmong("eras", 47, 1),
	snowball.NewAmong("iras", 47, 1),
	snowball.NewAmong("avas", 47, 1),
	snowball.NewAmong("es", -1, 1),
	snowball.NewAmong("ardes", 58, 1),
	snowball.NewAmong("erdes", 58, 1),
	snowball.NewAmong("irdes", 58, 1),
	snowball.NewAmong("ares", 58, 1),
	snowball.NewAmong("eres", 58, 1),
	snowball.NewAmong("ires", 58, 1),
	snowball.NewAmong("asses", 58, 1),
	snowball.NewAmong("esses", 58, 1),
	snowball.NewAmong("isses", 58, 1),
	snowball.NewAmong("astes", 58, 1),
	snowball.NewAmong("estes", 58, 1),
	snowball.NewAmong("istes", 58, 1),
	snowball.NewAmong("is", -1, 1),
	snowball.NewAmong("ais", 71, 1),
	snowball.NewAmong("eis", 71, 1),
	snowball.NewAmong("areis", 73, 1),
	snowball.NewAmong("ereis", 73, 1),
	snowball.NewAmong("ireis", 73, 1),
	snowball.NewAmong("áreis", 73, 1),
	snowball.NewAmong("éreis", 73, 1),
	snowball.NewAmong("íreis", 73, 1),
	snowball.NewAmong("ásseis", 73, 1),
	snowball.NewAmong("ésseis", 73, 1),
	snowball.NewAmong("ísseis", 73, 1),
	snowball.NewAmong("áveis", 73, 1),
	snowball.NewAmong("íeis", 73, 1),
	snowball.NewAmong("aríeis", 84, 1),
	snowball.NewAmong("eríeis", 84, 1),
	snowball.NewAmong("iríeis", 84, 1),
	snowball.NewAmong("ados", -1, 1),
	snowball.NewAmong("idos", -1, 1),
	snowball.NewAmong("amos", -1, 1),
	snowball.NewAmong("áramos", 90, 1),
	snowball.NewAmong("éramos", 90, 1),
	snowball.NewAmong("íramos", 90, 1),
	snowball.NewAmong("ávamos", 90, 1),
	snowball.NewAmong("íamos", 90, 1),
	snowball.NewAmong("aríamos", 95, 1),
	snowball.NewAmong("eríamos", 95, 1),
	snowball.NewAmong("iríamos", 95, 1),
	snowball.NewAmong("emos", -1, 1),
	snowball.NewAmong("aremos", 99, 1),
	snowball.NewAmong("eremos", 99, 1),
	snowball.NewAmong("iremos", 99, 1),
	snowball.NewAmong("ássemos", 99, 1),
	snowball.NewAmong("êssemos", 99, 1),
	snowball.NewAmong("íssemos", 99, 1),
	snowball.NewAmong("imos", -1, 1),
	snowball.NewAmong("armos", -1, 1),
	snowball.NewAmong("ermos", -1, 1),
	snowball.NewAmong("irmos", -1, 1),
	snowball.NewAmong("ámos", -1, 1),
	snowball.NewAmong("arás", -1, 1),
	snowball.NewAmong("erás", -1, 1),
	snowball.NewAmong("irás", -1, 1),
	snowball.NewAmong("eu", -1, 1),
	snowball.NewAmong("iu", -1, 1),
	snowball.NewAmong("ou", -1, 1),
	snowball.NewAmong("ará", -1, 1),
	snowball.NewAmong("erá", -1, 1),
	snowball.NewAmong("irá", -1, 1),
}

var portugueseA7 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("i", -1, 1),
	snowball.NewAmong("o", -1, 1),
	snowball.NewAmong("os", -1, 1),
	snowball.NewAmong("á", -1, 1),
	snowball.NewAmong("í", -1, 1),
	snowball.NewAmong("ó", -1, 1),
}

var portugueseA8 = []*snowball.Among{
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("ç", -1, 2),
	snowball.NewAmong("é", -1, 1),
	snowball.NewAmong("ê", -1, 1),
}

var portugueseGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 19, 12, 2}

func (s *PortugueseStemmer) rPrelude() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(portugueseA0)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("a~")
			case 2:
				p.SliceFromStr("o~")
			case 3:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			default:
				break lab0
			}
			break
		}
		if p.Cursor == v1 {
			break
		}
	}
	return true
}

func (s *PortugueseStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iPV = p.Limit
	s.iP1 = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
lab0:
	for {
	lab1:
		for {
			v2 := p.Cursor
		lab2:
			for {
				if !p.InGrouping(portugueseGV, 97, 250) {
					break lab2
				}
				v3 := p.Cursor
			lab4:
				for {
					if !p.OutGrouping(portugueseGV, 97, 250) {
						break lab4
					}
				golab5:
					for {
						if p.InGrouping(portugueseGV, 97, 250) {
							break golab5
						}
						if p.Cursor >= p.Limit {
							break lab4
						}
						p.Cursor++
					}
					break lab1
				}
				p.Cursor = v3
				if !p.InGrouping(portugueseGV, 97, 250) {
					break lab2
				}
			golab7:
				for {
					if p.OutGrouping(portugueseGV, 97, 250) {
						break golab7
					}
					if p.Cursor >= p.Limit {
						break lab0
					}
					p.Cursor++
				}
				break lab1
			}
			p.Cursor = v2
			if !p.OutGrouping(portugueseGV, 97, 250) {
				break lab0
			}
			v6 := p.Cursor
		lab10:
			for {
				if !p.OutGrouping(portugueseGV, 97, 250) {
					break lab10
				}
			golab11:
				for {
					if p.InGrouping(portugueseGV, 97, 250) {
						break golab11
					}
					if p.Cursor >= p.Limit {
						break lab10
					}
					p.Cursor++
				}
				break lab1
			}
			p.Cursor = v6
			if !p.InGrouping(portugueseGV, 97, 250) {
				break lab0
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
			break
		}
		s.iPV = p.Cursor
		break
	}
	p.Cursor = v1
	v8 := p.Cursor
lab13:
	for {
	golab14:
		for {
			if p.InGrouping(portugueseGV, 97, 250) {
				break golab14
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
	golab16:
		for {
			if p.OutGrouping(portugueseGV, 97, 250) {
				break golab16
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
		s.iP1 = p.Cursor
	golab18:
		for {
			if p.InGrouping(portugueseGV, 97, 250) {
				break golab18
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
	golab20:
		for {
			if p.OutGrouping(portugueseGV, 97, 250) {
				break golab20
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
		s.iP2 = p.Cursor
		break
	}
	p.Cursor = v8
	return true
}

func (s *PortugueseStemmer) rPostlude() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(portugueseA1)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("ã")
			case 2:
				p.SliceFromStr("õ")
			case 3:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			default:
				break lab0
			}
			break
		}
		if p.Cursor == v1 {
			break
		}
	}
	return true
}

func (s *PortugueseStemmer) rRV() bool {
	return s.iPV <= s.SnowballProgram.Cursor
}

func (s *PortugueseStemmer) rR1() bool {
	return s.iP1 <= s.SnowballProgram.Cursor
}

func (s *PortugueseStemmer) rR2() bool {
	return s.iP2 <= s.SnowballProgram.Cursor
}

func (s *PortugueseStemmer) rStandardSuffix() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(portugueseA5)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("log")
	case 3:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("u")
	case 4:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("ente")
	case 5:
		if !s.rR1() {
			return false
		}
		p.SliceDel()
		v1 := p.Limit - p.Cursor
	lab0:
		for {
			p.Ket = p.Cursor
			av := p.FindAmongB(portugueseA2)
			if av == 0 {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.SliceDel()
			if av == 1 {
			lab5a:
				for {
					p.Ket = p.Cursor
					if !p.EqSBStr("at") {
						p.Cursor = p.Limit - v1
						break lab5a
					}
					p.Bra = p.Cursor
					if !s.rR2() {
						p.Cursor = p.Limit - v1
						break lab5a
					}
					p.SliceDel()
					break
				}
			}
			break
		}
	case 6:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v2 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			if p.FindAmongB(portugueseA3) == 0 {
				p.Cursor = p.Limit - v2
				break lab1
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v2
				break lab1
			}
			p.SliceDel()
			break
		}
	case 7:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v3 := p.Limit - p.Cursor
	lab2:
		for {
			p.Ket = p.Cursor
			if p.FindAmongB(portugueseA4) == 0 {
				p.Cursor = p.Limit - v3
				break lab2
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v3
				break lab2
			}
			p.SliceDel()
			break
		}
	case 8:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v4 := p.Limit - p.Cursor
	lab3:
		for {
			p.Ket = p.Cursor
			if !p.EqSBStr("at") {
				p.Cursor = p.Limit - v4
				break lab3
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v4
				break lab3
			}
			p.SliceDel()
			break
		}
	case 9:
		if !s.rRV() {
			return false
		}
		if !p.EqSBStr("e") {
			return false
		}
		p.SliceFromStr("ir")
	}
	return true
}

func (s *PortugueseStemmer) rVerbSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iPV {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iPV
	p.Ket = p.Cursor
	if p.FindAmongB(portugueseA6) == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	p.LimitBackward = v2
	return true
}

func (s *PortugueseStemmer) rResidualSuffix() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(portugueseA7) == 0 {
		return false
	}
	p.Bra = p.Cursor
	if !s.rRV() {
		return false
	}
	p.SliceDel()
	return true
}

func (s *PortugueseStemmer) rResidualForm() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(portugueseA8)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		p.SliceDel()
		p.Ket = p.Cursor
		v1 := p.Limit - p.Cursor
	lab0:
		for {
		lab1:
			for {
				if !p.EqSBStr("u") {
					break lab1
				}
				p.Bra = p.Cursor
				v2 := p.Limit - p.Cursor
				if !p.EqSBStr("g") {
					break lab1
				}
				p.Cursor = p.Limit - v2
				break lab0
			}
			p.Cursor = p.Limit - v1
			if !p.EqSBStr("i") {
				return false
			}
			p.Bra = p.Cursor
			v3 := p.Limit - p.Cursor
			if !p.EqSBStr("c") {
				return false
			}
			p.Cursor = p.Limit - v3
			break
		}
		if !s.rRV() {
			return false
		}
		p.SliceDel()
	case 2:
		p.SliceFromStr("c")
	}
	return true
}

// Stem applies the Portuguese Snowball stemming algorithm.
func (s *PortugueseStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rPrelude()
	p.Cursor = v1
	s.rMarkRegions()
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v3 := p.Limit - p.Cursor
lab0:
	for {
	lab1:
		for {
			v4 := p.Limit - p.Cursor
		lab2:
			for {
				v5 := p.Limit - p.Cursor
			lab3:
				for {
					v6 := p.Limit - p.Cursor
					if s.rStandardSuffix() {
						break lab3
					}
					p.Cursor = p.Limit - v6
					if !s.rVerbSuffix() {
						break lab2
					}
					break
				}
				p.Cursor = p.Limit - v5
				v7 := p.Limit - p.Cursor
			lab5:
				for {
					p.Ket = p.Cursor
					if !p.EqSBStr("i") {
						p.Cursor = p.Limit - v7
						break lab5
					}
					p.Bra = p.Cursor
					v8 := p.Limit - p.Cursor
					if !p.EqSBStr("c") {
						p.Cursor = p.Limit - v7
						break lab5
					}
					p.Cursor = p.Limit - v8
					if !s.rRV() {
						p.Cursor = p.Limit - v7
						break lab5
					}
					p.SliceDel()
					break
				}
				break lab1
			}
			p.Cursor = p.Limit - v4
			if !s.rResidualSuffix() {
				break lab0
			}
			break
		}
		break
	}
	p.Cursor = p.Limit - v3
	v9 := p.Limit - p.Cursor
	s.rResidualForm()
	p.Cursor = p.Limit - v9
	p.Cursor = p.LimitBackward
	v10 := p.Cursor
	s.rPostlude()
	p.Cursor = v10
	return true
}

// Ensure PortugueseStemmer satisfies the Stemmer interface.
var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*PortugueseStemmer)(nil)
