// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// RomanianStemmer implements the Romanian Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.RomanianStemmer
// from Apache Lucene 10.4.0.
type RomanianStemmer struct {
	*snowball.SnowballProgram
	bStandardSuffixRemoved bool
	iP2                    int
	iP1                    int
	iPV                    int
}

// NewRomanianStemmer constructs a RomanianStemmer.
func NewRomanianStemmer() *RomanianStemmer {
	return &RomanianStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*RomanianStemmer)(nil)

var romanianA0 = []*snowball.Among{
	snowball.NewAmong("ş", -1, 1),
	snowball.NewAmong("ţ", -1, 2),
}

var romanianA1 = []*snowball.Among{
	snowball.NewAmong("", -1, 3),
	snowball.NewAmong("I", 0, 1),
	snowball.NewAmong("U", 0, 2),
}

var romanianA2 = []*snowball.Among{
	snowball.NewAmong("ea", -1, 3),
	snowball.NewAmong("aţia", -1, 7),
	snowball.NewAmong("aua", -1, 2),
	snowball.NewAmong("iua", -1, 4),
	snowball.NewAmong("aţie", -1, 7),
	snowball.NewAmong("ele", -1, 3),
	snowball.NewAmong("ile", -1, 5),
	snowball.NewAmong("iile", 6, 4),
	snowball.NewAmong("iei", -1, 4),
	snowball.NewAmong("atei", -1, 6),
	snowball.NewAmong("ii", -1, 4),
	snowball.NewAmong("ului", -1, 1),
	snowball.NewAmong("ul", -1, 1),
	snowball.NewAmong("elor", -1, 3),
	snowball.NewAmong("ilor", -1, 4),
	snowball.NewAmong("iilor", 14, 4),
}

var romanianA3 = []*snowball.Among{
	snowball.NewAmong("icala", -1, 4),
	snowball.NewAmong("iciva", -1, 4),
	snowball.NewAmong("ativa", -1, 5),
	snowball.NewAmong("itiva", -1, 6),
	snowball.NewAmong("icale", -1, 4),
	snowball.NewAmong("aţiune", -1, 5),
	snowball.NewAmong("iţiune", -1, 6),
	snowball.NewAmong("atoare", -1, 5),
	snowball.NewAmong("itoare", -1, 6),
	snowball.NewAmong("ătoare", -1, 5),
	snowball.NewAmong("icitate", -1, 4),
	snowball.NewAmong("abilitate", -1, 1),
	snowball.NewAmong("ibilitate", -1, 2),
	snowball.NewAmong("ivitate", -1, 3),
	snowball.NewAmong("icive", -1, 4),
	snowball.NewAmong("ative", -1, 5),
	snowball.NewAmong("itive", -1, 6),
	snowball.NewAmong("icali", -1, 4),
	snowball.NewAmong("atori", -1, 5),
	snowball.NewAmong("icatori", 18, 4),
	snowball.NewAmong("itori", -1, 6),
	snowball.NewAmong("ători", -1, 5),
	snowball.NewAmong("icitati", -1, 4),
	snowball.NewAmong("abilitati", -1, 1),
	snowball.NewAmong("ivitati", -1, 3),
	snowball.NewAmong("icivi", -1, 4),
	snowball.NewAmong("ativi", -1, 5),
	snowball.NewAmong("itivi", -1, 6),
	snowball.NewAmong("icităi", -1, 4),
	snowball.NewAmong("abilitări", -1, 1),
	snowball.NewAmong("ivitări", -1, 3),
	snowball.NewAmong("icităţi", -1, 4),
	snowball.NewAmong("abilitaţi", -1, 1),
	snowball.NewAmong("ivitaţi", -1, 3),
	snowball.NewAmong("ical", -1, 4),
	snowball.NewAmong("ator", -1, 5),
	snowball.NewAmong("icator", 35, 4),
	snowball.NewAmong("itor", -1, 6),
	snowball.NewAmong("ător", -1, 5),
	snowball.NewAmong("iciv", -1, 4),
	snowball.NewAmong("ativ", -1, 5),
	snowball.NewAmong("itiv", -1, 6),
	snowball.NewAmong("icală", -1, 4),
	snowball.NewAmong("icivă", -1, 4),
	snowball.NewAmong("ativă", -1, 5),
	snowball.NewAmong("itivă", -1, 6),
}

var romanianA4 = []*snowball.Among{
	snowball.NewAmong("ica", -1, 1),
	snowball.NewAmong("abila", -1, 1),
	snowball.NewAmong("ibila", -1, 1),
	snowball.NewAmong("oasa", -1, 1),
	snowball.NewAmong("ata", -1, 1),
	snowball.NewAmong("ita", -1, 1),
	snowball.NewAmong("anta", -1, 1),
	snowball.NewAmong("ista", -1, 3),
	snowball.NewAmong("uta", -1, 1),
	snowball.NewAmong("iva", -1, 1),
	snowball.NewAmong("ic", -1, 1),
	snowball.NewAmong("ice", -1, 1),
	snowball.NewAmong("abile", -1, 1),
	snowball.NewAmong("ibile", -1, 1),
	snowball.NewAmong("isme", -1, 3),
	snowball.NewAmong("iune", -1, 2),
	snowball.NewAmong("oase", -1, 1),
	snowball.NewAmong("ate", -1, 1),
	snowball.NewAmong("itate", 17, 1),
	snowball.NewAmong("ite", -1, 1),
	snowball.NewAmong("ante", -1, 1),
	snowball.NewAmong("iste", -1, 3),
	snowball.NewAmong("ute", -1, 1),
	snowball.NewAmong("ive", -1, 1),
	snowball.NewAmong("ici", -1, 1),
	snowball.NewAmong("abili", -1, 1),
	snowball.NewAmong("ibili", -1, 1),
	snowball.NewAmong("iuni", -1, 2),
	snowball.NewAmong("atori", -1, 1),
	snowball.NewAmong("osi", -1, 1),
	snowball.NewAmong("ati", -1, 1),
	snowball.NewAmong("itati", 30, 1),
	snowball.NewAmong("iti", -1, 1),
	snowball.NewAmong("anti", -1, 1),
	snowball.NewAmong("isti", -1, 3),
	snowball.NewAmong("uti", -1, 1),
	snowball.NewAmong("işti", -1, 3),
	snowball.NewAmong("ivi", -1, 1),
	snowball.NewAmong("ităi", -1, 1),
	snowball.NewAmong("oşi", -1, 1),
	snowball.NewAmong("itaţi", -1, 1),
	snowball.NewAmong("abil", -1, 1),
	snowball.NewAmong("ibil", -1, 1),
	snowball.NewAmong("ism", -1, 3),
	snowball.NewAmong("ator", -1, 1),
	snowball.NewAmong("os", -1, 1),
	snowball.NewAmong("at", -1, 1),
	snowball.NewAmong("it", -1, 1),
	snowball.NewAmong("ant", -1, 1),
	snowball.NewAmong("ist", -1, 3),
	snowball.NewAmong("ut", -1, 1),
	snowball.NewAmong("iv", -1, 1),
	snowball.NewAmong("ică", -1, 1),
	snowball.NewAmong("abilă", -1, 1),
	snowball.NewAmong("ibilă", -1, 1),
	snowball.NewAmong("oasă", -1, 1),
	snowball.NewAmong("ată", -1, 1),
	snowball.NewAmong("ită", -1, 1),
	snowball.NewAmong("antă", -1, 1),
	snowball.NewAmong("istă", -1, 3),
	snowball.NewAmong("ută", -1, 1),
	snowball.NewAmong("ivă", -1, 1),
}

var romanianA5 = []*snowball.Among{
	snowball.NewAmong("ea", -1, 1),
	snowball.NewAmong("ia", -1, 1),
	snowball.NewAmong("esc", -1, 1),
	snowball.NewAmong("ăsc", -1, 1),
	snowball.NewAmong("ind", -1, 1),
	snowball.NewAmong("ând", -1, 1),
	snowball.NewAmong("are", -1, 1),
	snowball.NewAmong("ere", -1, 1),
	snowball.NewAmong("ire", -1, 1),
	snowball.NewAmong("âre", -1, 1),
	snowball.NewAmong("se", -1, 2),
	snowball.NewAmong("ase", 10, 1),
	snowball.NewAmong("sese", 10, 2),
	snowball.NewAmong("ise", 10, 1),
	snowball.NewAmong("use", 10, 1),
	snowball.NewAmong("âse", 10, 1),
	snowball.NewAmong("eşte", -1, 1),
	snowball.NewAmong("ăşte", -1, 1),
	snowball.NewAmong("eze", -1, 1),
	snowball.NewAmong("ai", -1, 1),
	snowball.NewAmong("eai", 19, 1),
	snowball.NewAmong("iai", 19, 1),
	snowball.NewAmong("sei", -1, 2),
	snowball.NewAmong("eşti", -1, 1),
	snowball.NewAmong("ăşti", -1, 1),
	snowball.NewAmong("ui", -1, 1),
	snowball.NewAmong("ezi", -1, 1),
	snowball.NewAmong("âi", -1, 1),
	snowball.NewAmong("aşi", -1, 1),
	snowball.NewAmong("seşi", -1, 2),
	snowball.NewAmong("aseşi", 29, 1),
	snowball.NewAmong("seseşi", 29, 2),
	snowball.NewAmong("iseşi", 29, 1),
	snowball.NewAmong("useşi", 29, 1),
	snowball.NewAmong("âseşi", 29, 1),
	snowball.NewAmong("işi", -1, 1),
	snowball.NewAmong("uşi", -1, 1),
	snowball.NewAmong("âşi", -1, 1),
	snowball.NewAmong("aţi", -1, 2),
	snowball.NewAmong("eaţi", 38, 1),
	snowball.NewAmong("iaţi", 38, 1),
	snowball.NewAmong("eţi", -1, 2),
	snowball.NewAmong("iţi", -1, 2),
	snowball.NewAmong("âţi", -1, 2),
	snowball.NewAmong("arăţi", -1, 1),
	snowball.NewAmong("serăţi", -1, 2),
	snowball.NewAmong("aserăţi", 45, 1),
	snowball.NewAmong("seserăţi", 45, 2),
	snowball.NewAmong("iserăţi", 45, 1),
	snowball.NewAmong("userăţi", 45, 1),
	snowball.NewAmong("âserăţi", 45, 1),
	snowball.NewAmong("irăţi", -1, 1),
	snowball.NewAmong("urăţi", -1, 1),
	snowball.NewAmong("ârăţi", -1, 1),
	snowball.NewAmong("am", -1, 1),
	snowball.NewAmong("eam", 54, 1),
	snowball.NewAmong("iam", 54, 1),
	snowball.NewAmong("em", -1, 2),
	snowball.NewAmong("asem", 57, 1),
	snowball.NewAmong("sesem", 57, 2),
	snowball.NewAmong("isem", 57, 1),
	snowball.NewAmong("usem", 57, 1),
	snowball.NewAmong("âsem", 57, 1),
	snowball.NewAmong("im", -1, 2),
	snowball.NewAmong("âm", -1, 2),
	snowball.NewAmong("ăm", -1, 2),
	snowball.NewAmong("arăm", 65, 1),
	snowball.NewAmong("serăm", 65, 2),
	snowball.NewAmong("aserăm", 67, 1),
	snowball.NewAmong("seserăm", 67, 2),
	snowball.NewAmong("iserăm", 67, 1),
	snowball.NewAmong("userăm", 67, 1),
	snowball.NewAmong("âserăm", 67, 1),
	snowball.NewAmong("irăm", 65, 1),
	snowball.NewAmong("urăm", 65, 1),
	snowball.NewAmong("ârăm", 65, 1),
	snowball.NewAmong("au", -1, 1),
	snowball.NewAmong("eau", 76, 1),
	snowball.NewAmong("iau", 76, 1),
	snowball.NewAmong("indu", -1, 1),
	snowball.NewAmong("ându", -1, 1),
	snowball.NewAmong("ez", -1, 1),
	snowball.NewAmong("eascǎ", -1, 1),
	snowball.NewAmong("ară", -1, 1),
	snowball.NewAmong("seră", -1, 2),
	snowball.NewAmong("aseră", 84, 1),
	snowball.NewAmong("seseră", 84, 2),
	snowball.NewAmong("iseră", 84, 1),
	snowball.NewAmong("useră", 84, 1),
	snowball.NewAmong("âseră", 84, 1),
	snowball.NewAmong("iră", -1, 1),
	snowball.NewAmong("ură", -1, 1),
	snowball.NewAmong("âră", -1, 1),
	snowball.NewAmong("eazǎ", -1, 1),
}

var romanianA6 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("ie", 1, 1),
	snowball.NewAmong("i", -1, 1),
	snowball.NewAmong("ă", -1, 1),
}

// romanianGV: vowels (a e i o u ă â î)
var romanianGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 4}

func (s *RomanianStemmer) rNorm() bool {
	v1 := s.Cursor
	for {
		v2 := s.Cursor
		lab1: for {
		golab2:
			for {
				v3 := s.Cursor
				lab3: for {
					s.Bra = s.Cursor
					amongVar := s.FindAmong(romanianA0)
					if amongVar == 0 {
						break lab3
					}
					s.Ket = s.Cursor
					switch amongVar {
					case 1:
						s.SliceFromStr("ș")
					case 2:
						s.SliceFromStr("ț")
					}
					s.Cursor = v3
					break golab2
				}
				s.Cursor = v3
				if s.Cursor >= s.Limit {
					break lab1
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v2
		break
	}
	s.Cursor = v1
	return true
}

func (s *RomanianStemmer) rPrelude() bool {
	for {
		v1 := s.Cursor
		lab0: for {
		golab1:
			for {
				v2 := s.Cursor
				lab2: for {
					if !s.InGrouping(romanianGV, 97, 259) {
						break lab2
					}
					s.Bra = s.Cursor
					lab3: for {
						v3 := s.Cursor
						lab4: for {
							if !s.EqSStr("u") {
								break lab4
							}
							s.Ket = s.Cursor
							if !s.InGrouping(romanianGV, 97, 259) {
								break lab4
							}
							s.SliceFromStr("U")
							break lab3
						}
						s.Cursor = v3
						if !s.EqSStr("i") {
							break lab2
						}
						s.Ket = s.Cursor
						if !s.InGrouping(romanianGV, 97, 259) {
							break lab2
						}
						s.SliceFromStr("I")
						break lab3
					}
					s.Cursor = v2
					break golab1
				}
				s.Cursor = v2
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *RomanianStemmer) rMarkRegions() bool {
	s.iPV = s.Limit
	s.iP1 = s.Limit
	s.iP2 = s.Limit
	v1 := s.Cursor
	lab0: for {
		lab1: for {
			v2 := s.Cursor
			lab2: for {
				if !s.InGrouping(romanianGV, 97, 259) {
					break lab2
				}
				lab3: for {
					v3 := s.Cursor
					lab4: for {
						if !s.OutGrouping(romanianGV, 97, 259) {
							break lab4
						}
					golab5:
						for {
							lab6: for {
								if !s.InGrouping(romanianGV, 97, 259) {
									break lab6
								}
								break golab5
							}
							if s.Cursor >= s.Limit {
								break lab4
							}
							s.Cursor++
						}
						break lab3
					}
					s.Cursor = v3
					if !s.InGrouping(romanianGV, 97, 259) {
						break lab2
					}
				golab7:
					for {
						lab8: for {
							if !s.OutGrouping(romanianGV, 97, 259) {
								break lab8
							}
							break golab7
						}
						if s.Cursor >= s.Limit {
							break lab2
						}
						s.Cursor++
					}
					break lab3
				}
				break lab1
			}
			s.Cursor = v2
			if !s.OutGrouping(romanianGV, 97, 259) {
				break lab0
			}
			lab9: for {
				v6 := s.Cursor
				lab10: for {
					if !s.OutGrouping(romanianGV, 97, 259) {
						break lab10
					}
				golab11:
					for {
						lab12: for {
							if !s.InGrouping(romanianGV, 97, 259) {
								break lab12
							}
							break golab11
						}
						if s.Cursor >= s.Limit {
							break lab10
						}
						s.Cursor++
					}
					break lab9
				}
				s.Cursor = v6
				if !s.InGrouping(romanianGV, 97, 259) {
					break lab0
				}
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
				break lab9
			}
			break lab1
		}
		s.iPV = s.Cursor
		break lab0
	}
	s.Cursor = v1
	v8 := s.Cursor
	lab13: for {
	golab14:
		for {
			lab15: for {
				if !s.InGrouping(romanianGV, 97, 259) {
					break lab15
				}
				break golab14
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab16:
		for {
			lab17: for {
				if !s.OutGrouping(romanianGV, 97, 259) {
					break lab17
				}
				break golab16
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP1 = s.Cursor
	golab18:
		for {
			lab19: for {
				if !s.InGrouping(romanianGV, 97, 259) {
					break lab19
				}
				break golab18
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
	golab20:
		for {
			lab21: for {
				if !s.OutGrouping(romanianGV, 97, 259) {
					break lab21
				}
				break golab20
			}
			if s.Cursor >= s.Limit {
				break lab13
			}
			s.Cursor++
		}
		s.iP2 = s.Cursor
		break lab13
	}
	s.Cursor = v8
	return true
}

func (s *RomanianStemmer) rPostlude() bool {
	for {
		v1 := s.Cursor
		lab0: for {
			s.Bra = s.Cursor
			amongVar := s.FindAmong(romanianA1)
			s.Ket = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("i")
			case 2:
				s.SliceFromStr("u")
			case 3:
				if s.Cursor >= s.Limit {
					break lab0
				}
				s.Cursor++
			}
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *RomanianStemmer) rRV() bool {
	return s.iPV <= s.Cursor
}

func (s *RomanianStemmer) rR1() bool {
	return s.iP1 <= s.Cursor
}

func (s *RomanianStemmer) rR2() bool {
	return s.iP2 <= s.Cursor
}

func (s *RomanianStemmer) rStep0() bool {
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(romanianA2)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		s.SliceFromStr("a")
	case 3:
		s.SliceFromStr("e")
	case 4:
		s.SliceFromStr("i")
	case 5:
		v1 := s.Limit - s.Cursor
		lab0: for {
			if !s.EqSBStr("ab") {
				break lab0
			}
			return false
		}
		s.Cursor = s.Limit - v1
		s.SliceFromStr("i")
	case 6:
		s.SliceFromStr("at")
	case 7:
		s.SliceFromStr("aţi")
	}
	return true
}

func (s *RomanianStemmer) rComboSuffix() bool {
	v1 := s.Limit - s.Cursor
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(romanianA3)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR1() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceFromStr("abil")
	case 2:
		s.SliceFromStr("ibil")
	case 3:
		s.SliceFromStr("iv")
	case 4:
		s.SliceFromStr("ic")
	case 5:
		s.SliceFromStr("at")
	case 6:
		s.SliceFromStr("it")
	}
	s.bStandardSuffixRemoved = true
	s.Cursor = s.Limit - v1
	return true
}

func (s *RomanianStemmer) rStandardSuffix() bool {
	s.bStandardSuffixRemoved = false
	for {
		v1 := s.Limit - s.Cursor
		lab0: for {
			if !s.rComboSuffix() {
				break lab0
			}
			continue
		}
		s.Cursor = s.Limit - v1
		break
	}
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(romanianA4)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rR2() {
		return false
	}
	switch amongVar {
	case 1:
		s.SliceDel()
	case 2:
		if !s.EqSBStr("ţ") {
			return false
		}
		s.Bra = s.Cursor
		s.SliceFromStr("t")
	case 3:
		s.SliceFromStr("ist")
	}
	s.bStandardSuffixRemoved = true
	return true
}

func (s *RomanianStemmer) rVerbSuffix() bool {
	if s.Cursor < s.iPV {
		return false
	}
	v2 := s.LimitBackward
	s.LimitBackward = s.iPV
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(romanianA5)
	if amongVar == 0 {
		s.LimitBackward = v2
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		lab0: for {
			v3 := s.Limit - s.Cursor
			lab1: for {
				if !s.OutGroupingB(romanianGV, 97, 259) {
					break lab1
				}
				break lab0
			}
			s.Cursor = s.Limit - v3
			if !s.EqSBStr("u") {
				s.LimitBackward = v2
				return false
			}
			break lab0
		}
		s.SliceDel()
	case 2:
		s.SliceDel()
	}
	s.LimitBackward = v2
	return true
}

func (s *RomanianStemmer) rVowelSuffix() bool {
	s.Ket = s.Cursor
	if s.FindAmongB(romanianA6) == 0 {
		return false
	}
	s.Bra = s.Cursor
	if !s.rRV() {
		return false
	}
	s.SliceDel()
	return true
}

// Stem applies the Romanian stemming algorithm to the current word.
func (s *RomanianStemmer) Stem() bool {
	s.rNorm()
	v2 := s.Cursor
	s.rPrelude()
	s.Cursor = v2
	s.rMarkRegions()
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit

	v4 := s.Limit - s.Cursor
	s.rStep0()
	s.Cursor = s.Limit - v4

	v5 := s.Limit - s.Cursor
	s.rStandardSuffix()
	s.Cursor = s.Limit - v5

	v6 := s.Limit - s.Cursor
	lab0: for {
		lab1: for {
			v7 := s.Limit - s.Cursor
			lab2: for {
				if !s.bStandardSuffixRemoved {
					break lab2
				}
				break lab1
			}
			s.Cursor = s.Limit - v7
			if !s.rVerbSuffix() {
				break lab0
			}
			break lab1
		}
		break lab0
	}
	s.Cursor = s.Limit - v6

	v8 := s.Limit - s.Cursor
	s.rVowelSuffix()
	s.Cursor = s.Limit - v8

	s.Cursor = s.LimitBackward
	v9 := s.Cursor
	s.rPostlude()
	s.Cursor = v9
	return true
}
