// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// RussianStemmer implements the Russian Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.RussianStemmer
// from Apache Lucene 10.4.0.
type RussianStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iPV int
}

// NewRussianStemmer creates a new RussianStemmer.
func NewRussianStemmer() *RussianStemmer {
	return &RussianStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var russianA0 = []*snowball.Among{
	snowball.NewAmong("в", -1, 1),
	snowball.NewAmong("ив", 0, 2),
	snowball.NewAmong("ыв", 0, 2),
	snowball.NewAmong("вши", -1, 1),
	snowball.NewAmong("ивши", 3, 2),
	snowball.NewAmong("ывши", 3, 2),
	snowball.NewAmong("вшись", -1, 1),
	snowball.NewAmong("ившись", 6, 2),
	snowball.NewAmong("ывшись", 6, 2),
}

var russianA1 = []*snowball.Among{
	snowball.NewAmong("ее", -1, 1),
	snowball.NewAmong("ие", -1, 1),
	snowball.NewAmong("ое", -1, 1),
	snowball.NewAmong("ые", -1, 1),
	snowball.NewAmong("ими", -1, 1),
	snowball.NewAmong("ыми", -1, 1),
	snowball.NewAmong("ей", -1, 1),
	snowball.NewAmong("ий", -1, 1),
	snowball.NewAmong("ой", -1, 1),
	snowball.NewAmong("ый", -1, 1),
	snowball.NewAmong("ем", -1, 1),
	snowball.NewAmong("им", -1, 1),
	snowball.NewAmong("ом", -1, 1),
	snowball.NewAmong("ым", -1, 1),
	snowball.NewAmong("его", -1, 1),
	snowball.NewAmong("ого", -1, 1),
	snowball.NewAmong("ему", -1, 1),
	snowball.NewAmong("ому", -1, 1),
	snowball.NewAmong("их", -1, 1),
	snowball.NewAmong("ых", -1, 1),
	snowball.NewAmong("ею", -1, 1),
	snowball.NewAmong("ою", -1, 1),
	snowball.NewAmong("ую", -1, 1),
	snowball.NewAmong("юю", -1, 1),
	snowball.NewAmong("ая", -1, 1),
	snowball.NewAmong("яя", -1, 1),
}

var russianA2 = []*snowball.Among{
	snowball.NewAmong("ем", -1, 1),
	snowball.NewAmong("нн", -1, 1),
	snowball.NewAmong("вш", -1, 1),
	snowball.NewAmong("ивш", 2, 2),
	snowball.NewAmong("ывш", 2, 2),
	snowball.NewAmong("щ", -1, 1),
	snowball.NewAmong("ющ", 5, 1),
	snowball.NewAmong("уюш", 6, 2),
}

var russianA3 = []*snowball.Among{
	snowball.NewAmong("сь", -1, 1),
	snowball.NewAmong("ся", -1, 1),
}

var russianA4 = []*snowball.Among{
	snowball.NewAmong("ла", -1, 1),
	snowball.NewAmong("ила", 0, 2),
	snowball.NewAmong("ыла", 0, 2),
	snowball.NewAmong("на", -1, 1),
	snowball.NewAmong("ена", 3, 2),
	snowball.NewAmong("ете", -1, 1),
	snowball.NewAmong("ите", -1, 2),
	snowball.NewAmong("йте", -1, 1),
	snowball.NewAmong("ейте", 7, 2),
	snowball.NewAmong("уйте", 7, 2),
	snowball.NewAmong("ли", -1, 1),
	snowball.NewAmong("или", 10, 2),
	snowball.NewAmong("ыли", 10, 2),
	snowball.NewAmong("й", -1, 1),
	snowball.NewAmong("ей", 13, 2),
	snowball.NewAmong("уй", 13, 2),
	snowball.NewAmong("л", -1, 1),
	snowball.NewAmong("ил", 16, 2),
	snowball.NewAmong("ыл", 16, 2),
	snowball.NewAmong("ем", -1, 1),
	snowball.NewAmong("им", -1, 2),
	snowball.NewAmong("ым", -1, 2),
	snowball.NewAmong("н", -1, 1),
	snowball.NewAmong("ен", 22, 2),
	snowball.NewAmong("ло", -1, 1),
	snowball.NewAmong("ило", 24, 2),
	snowball.NewAmong("ыло", 24, 2),
	snowball.NewAmong("но", -1, 1),
	snowball.NewAmong("ено", 27, 2),
	snowball.NewAmong("нно", 27, 1),
	snowball.NewAmong("ет", -1, 1),
	snowball.NewAmong("ует", 30, 2),
	snowball.NewAmong("ит", -1, 2),
	snowball.NewAmong("ыт", -1, 2),
	snowball.NewAmong("ют", -1, 1),
	snowball.NewAmong("уют", 34, 2),
	snowball.NewAmong("ят", -1, 2),
	snowball.NewAmong("ны", -1, 1),
	snowball.NewAmong("ены", 37, 2),
	snowball.NewAmong("ть", -1, 1),
	snowball.NewAmong("ить", 39, 2),
	snowball.NewAmong("ыть", 39, 2),
	snowball.NewAmong("ешь", -1, 1),
	snowball.NewAmong("ишь", -1, 2),
	snowball.NewAmong("ю", -1, 2),
	snowball.NewAmong("ую", 44, 2),
}

var russianA5 = []*snowball.Among{
	snowball.NewAmong("а", -1, 1),
	snowball.NewAmong("ев", -1, 1),
	snowball.NewAmong("ов", -1, 1),
	snowball.NewAmong("е", -1, 1),
	snowball.NewAmong("ие", 3, 1),
	snowball.NewAmong("ье", 3, 1),
	snowball.NewAmong("и", -1, 1),
	snowball.NewAmong("еи", 6, 1),
	snowball.NewAmong("ии", 6, 1),
	snowball.NewAmong("ами", 6, 1),
	snowball.NewAmong("ями", 6, 1),
	snowball.NewAmong("иями", 10, 1),
	snowball.NewAmong("й", -1, 1),
	snowball.NewAmong("ей", 12, 1),
	snowball.NewAmong("ией", 13, 1),
	snowball.NewAmong("ий", 12, 1),
	snowball.NewAmong("ой", 12, 1),
	snowball.NewAmong("ам", -1, 1),
	snowball.NewAmong("ем", -1, 1),
	snowball.NewAmong("ием", 18, 1),
	snowball.NewAmong("ом", -1, 1),
	snowball.NewAmong("ям", -1, 1),
	snowball.NewAmong("иям", 21, 1),
	snowball.NewAmong("о", -1, 1),
	snowball.NewAmong("у", -1, 1),
	snowball.NewAmong("ах", -1, 1),
	snowball.NewAmong("ях", -1, 1),
	snowball.NewAmong("иях", 26, 1),
	snowball.NewAmong("ы", -1, 1),
	snowball.NewAmong("ь", -1, 1),
	snowball.NewAmong("ю", -1, 1),
	snowball.NewAmong("ию", 30, 1),
	snowball.NewAmong("ью", 30, 1),
	snowball.NewAmong("я", -1, 1),
	snowball.NewAmong("ия", 33, 1),
	snowball.NewAmong("ья", 33, 1),
}

var russianA6 = []*snowball.Among{
	snowball.NewAmong("ост", -1, 1),
	snowball.NewAmong("ость", -1, 1),
}

var russianA7 = []*snowball.Among{
	snowball.NewAmong("ейше", -1, 1),
	snowball.NewAmong("н", -1, 2),
	snowball.NewAmong("ейш", -1, 1),
	snowball.NewAmong("ь", -1, 3),
}

var russianGV = []byte{33, 65, 8, 232}

func (s *RussianStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iPV = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
lab0:
	for {
	golab1:
		for {
			if p.InGrouping(russianGV, 1072, 1103) {
				break golab1
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iPV = p.Cursor
	golab3:
		for {
			if p.OutGrouping(russianGV, 1072, 1103) {
				break golab3
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
	golab5:
		for {
			if p.InGrouping(russianGV, 1072, 1103) {
				break golab5
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
	golab7:
		for {
			if p.OutGrouping(russianGV, 1072, 1103) {
				break golab7
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
		}
		s.iP2 = p.Cursor
		break
	}
	p.Cursor = v1
	return true
}

func (s *RussianStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *RussianStemmer) rPerfectiveGerund() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(russianA0)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
	lab0:
		for {
			v1 := p.Limit - p.Cursor
		lab1:
			for {
				if !p.EqSBStr("а") {
					break lab1
				}
				break lab0
			}
			p.Cursor = p.Limit - v1
			if !p.EqSBStr("я") {
				return false
			}
			break
		}
		p.SliceDel()
	case 2:
		p.SliceDel()
	}
	return true
}

func (s *RussianStemmer) rAdjective() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(russianA1) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *RussianStemmer) rAdjectival() bool {
	p := s.SnowballProgram
	if !s.rAdjective() {
		return false
	}
	v1 := p.Limit - p.Cursor
lab0:
	for {
		p.Ket = p.Cursor
		amongVar := p.FindAmongB(russianA2)
		if amongVar == 0 {
			p.Cursor = p.Limit - v1
			break lab0
		}
		p.Bra = p.Cursor
		switch amongVar {
		case 1:
		lab1:
			for {
				v2 := p.Limit - p.Cursor
			lab2:
				for {
					if !p.EqSBStr("а") {
						break lab2
					}
					break lab1
				}
				p.Cursor = p.Limit - v2
				if !p.EqSBStr("я") {
					p.Cursor = p.Limit - v1
					break lab0
				}
				break
			}
			p.SliceDel()
		case 2:
			p.SliceDel()
		}
		break
	}
	return true
}

func (s *RussianStemmer) rReflexive() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(russianA3) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *RussianStemmer) rVerb() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(russianA4)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
	lab0:
		for {
			v1 := p.Limit - p.Cursor
		lab1:
			for {
				if !p.EqSBStr("а") {
					break lab1
				}
				break lab0
			}
			p.Cursor = p.Limit - v1
			if !p.EqSBStr("я") {
				return false
			}
			break
		}
		p.SliceDel()
	case 2:
		p.SliceDel()
	}
	return true
}

func (s *RussianStemmer) rNoun() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(russianA5) == 0 {
		return false
	}
	p.Bra = p.Cursor
	p.SliceDel()
	return true
}

func (s *RussianStemmer) rDerivational() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(russianA6) == 0 {
		return false
	}
	p.Bra = p.Cursor
	if !s.rR2() {
		return false
	}
	p.SliceDel()
	return true
}

func (s *RussianStemmer) rTidyUp() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(russianA7)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		p.SliceDel()
		p.Ket = p.Cursor
		if !p.EqSBStr("н") {
			return false
		}
		p.Bra = p.Cursor
		if !p.EqSBStr("н") {
			return false
		}
		p.SliceDel()
	case 2:
		if !p.EqSBStr("н") {
			return false
		}
		p.SliceDel()
	case 3:
		p.SliceDel()
	}
	return true
}

// Stem applies the Russian Snowball stemming algorithm.
func (s *RussianStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	// replace ё with е
	for {
		v2 := p.Cursor
	lab1:
		for {
		golab2:
			for {
				v3 := p.Cursor
			lab3:
				for {
					p.Bra = p.Cursor
					if !p.EqSStr("ё") {
						break lab3
					}
					p.Ket = p.Cursor
					p.Cursor = v3
					break golab2
				}
				p.Cursor = v3
				if p.Cursor >= p.Limit {
					break lab1
				}
				p.Cursor++
			}
			p.SliceFromStr("е")
			continue
		}
		p.Cursor = v2
		break
	}
	p.Cursor = v1
	s.rMarkRegions()
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	if p.Cursor < s.iPV {
		return false
	}
	v6 := p.LimitBackward
	p.LimitBackward = s.iPV
	v7 := p.Limit - p.Cursor
lab4:
	for {
	lab5:
		for {
			v8 := p.Limit - p.Cursor
		lab6:
			for {
				if !s.rPerfectiveGerund() {
					break lab6
				}
				break lab5
			}
			p.Cursor = p.Limit - v8
			v9 := p.Limit - p.Cursor
		lab7:
			for {
				if !s.rReflexive() {
					p.Cursor = p.Limit - v9
					break lab7
				}
				break
			}
		lab8:
			for {
				v10 := p.Limit - p.Cursor
			lab9:
				for {
					if !s.rAdjectival() {
						break lab9
					}
					break lab8
				}
				p.Cursor = p.Limit - v10
			lab10:
				for {
					if !s.rVerb() {
						break lab10
					}
					break lab8
				}
				p.Cursor = p.Limit - v10
				if !s.rNoun() {
					break lab4
				}
				break
			}
			break
		}
		break
	}
	p.Cursor = p.Limit - v7
	v11 := p.Limit - p.Cursor
lab11:
	for {
		p.Ket = p.Cursor
		if !p.EqSBStr("и") {
			p.Cursor = p.Limit - v11
			break lab11
		}
		p.Bra = p.Cursor
		p.SliceDel()
		break
	}
	v12 := p.Limit - p.Cursor
	s.rDerivational()
	p.Cursor = p.Limit - v12
	v13 := p.Limit - p.Cursor
	s.rTidyUp()
	p.Cursor = p.Limit - v13
	p.LimitBackward = v6
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*RussianStemmer)(nil)
