// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// SpanishStemmer implements the Spanish Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.SpanishStemmer
// from Apache Lucene 10.4.0.
type SpanishStemmer struct {
	*snowball.SnowballProgram
	iP2 int
	iP1 int
	iPV int
}

// NewSpanishStemmer creates a new SpanishStemmer.
func NewSpanishStemmer() *SpanishStemmer {
	return &SpanishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var spanishA0 = []*snowball.Among{
	snowball.NewAmong("", -1, 6),
	snowball.NewAmong("á", 0, 1),
	snowball.NewAmong("é", 0, 2),
	snowball.NewAmong("í", 0, 3),
	snowball.NewAmong("ó", 0, 4),
	snowball.NewAmong("ú", 0, 5),
}

var spanishA1 = []*snowball.Among{
	snowball.NewAmong("la", -1, -1),
	snowball.NewAmong("sela", 0, -1),
	snowball.NewAmong("le", -1, -1),
	snowball.NewAmong("me", -1, -1),
	snowball.NewAmong("se", -1, -1),
	snowball.NewAmong("lo", -1, -1),
	snowball.NewAmong("selo", 5, -1),
	snowball.NewAmong("las", -1, -1),
	snowball.NewAmong("selas", 7, -1),
	snowball.NewAmong("les", -1, -1),
	snowball.NewAmong("los", -1, -1),
	snowball.NewAmong("selos", 10, -1),
	snowball.NewAmong("nos", -1, -1),
}

var spanishA2 = []*snowball.Among{
	snowball.NewAmong("ando", -1, 6),
	snowball.NewAmong("iendo", -1, 6),
	snowball.NewAmong("yendo", -1, 7),
	snowball.NewAmong("ándo", -1, 2),
	snowball.NewAmong("iéndo", -1, 1),
	snowball.NewAmong("ar", -1, 6),
	snowball.NewAmong("er", -1, 6),
	snowball.NewAmong("ir", -1, 6),
	snowball.NewAmong("ár", -1, 3),
	snowball.NewAmong("ér", -1, 4),
	snowball.NewAmong("ír", -1, 5),
}

var spanishA3 = []*snowball.Among{
	snowball.NewAmong("ic", -1, -1),
	snowball.NewAmong("ad", -1, -1),
	snowball.NewAmong("os", -1, -1),
	snowball.NewAmong("iv", -1, 1),
}

var spanishA4 = []*snowball.Among{
	snowball.NewAmong("able", -1, 1),
	snowball.NewAmong("ible", -1, 1),
	snowball.NewAmong("ante", -1, 1),
}

var spanishA5 = []*snowball.Among{
	snowball.NewAmong("ic", -1, 1),
	snowball.NewAmong("abil", -1, 1),
	snowball.NewAmong("iv", -1, 1),
}

var spanishA6 = []*snowball.Among{
	snowball.NewAmong("ica", -1, 1),
	snowball.NewAmong("ancia", -1, 2),
	snowball.NewAmong("encia", -1, 5),
	snowball.NewAmong("adora", -1, 2),
	snowball.NewAmong("osa", -1, 1),
	snowball.NewAmong("ista", -1, 1),
	snowball.NewAmong("iva", -1, 9),
	snowball.NewAmong("anza", -1, 1),
	snowball.NewAmong("logía", -1, 3),
	snowball.NewAmong("idad", -1, 8),
	snowball.NewAmong("able", -1, 1),
	snowball.NewAmong("ible", -1, 1),
	snowball.NewAmong("ante", -1, 2),
	snowball.NewAmong("mente", -1, 7),
	snowball.NewAmong("amente", 13, 6),
	snowball.NewAmong("ación", -1, 2),
	snowball.NewAmong("ución", -1, 4),
	snowball.NewAmong("ico", -1, 1),
	snowball.NewAmong("ismo", -1, 1),
	snowball.NewAmong("oso", -1, 1),
	snowball.NewAmong("amiento", -1, 1),
	snowball.NewAmong("imiento", -1, 1),
	snowball.NewAmong("ivo", -1, 9),
	snowball.NewAmong("ador", -1, 2),
	snowball.NewAmong("icas", -1, 1),
	snowball.NewAmong("ancias", -1, 2),
	snowball.NewAmong("encias", -1, 5),
	snowball.NewAmong("adoras", -1, 2),
	snowball.NewAmong("osas", -1, 1),
	snowball.NewAmong("istas", -1, 1),
	snowball.NewAmong("ivas", -1, 9),
	snowball.NewAmong("anzas", -1, 1),
	snowball.NewAmong("logías", -1, 3),
	snowball.NewAmong("idades", -1, 8),
	snowball.NewAmong("ables", -1, 1),
	snowball.NewAmong("ibles", -1, 1),
	snowball.NewAmong("aciones", -1, 2),
	snowball.NewAmong("uciones", -1, 4),
	snowball.NewAmong("adores", -1, 2),
	snowball.NewAmong("antes", -1, 2),
	snowball.NewAmong("icos", -1, 1),
	snowball.NewAmong("ismos", -1, 1),
	snowball.NewAmong("osos", -1, 1),
	snowball.NewAmong("amientos", -1, 1),
	snowball.NewAmong("imientos", -1, 1),
	snowball.NewAmong("ivos", -1, 9),
}

var spanishA7 = []*snowball.Among{
	snowball.NewAmong("ya", -1, 1),
	snowball.NewAmong("ye", -1, 1),
	snowball.NewAmong("yan", -1, 1),
	snowball.NewAmong("yen", -1, 1),
	snowball.NewAmong("yeron", -1, 1),
	snowball.NewAmong("yendo", -1, 1),
	snowball.NewAmong("yo", -1, 1),
	snowball.NewAmong("yas", -1, 1),
	snowball.NewAmong("yes", -1, 1),
	snowball.NewAmong("yais", -1, 1),
	snowball.NewAmong("yamos", -1, 1),
	snowball.NewAmong("yó", -1, 1),
}

var spanishA8 = []*snowball.Among{
	snowball.NewAmong("aba", -1, 2),
	snowball.NewAmong("ada", -1, 2),
	snowball.NewAmong("ida", -1, 2),
	snowball.NewAmong("ara", -1, 2),
	snowball.NewAmong("iera", -1, 2),
	snowball.NewAmong("ía", -1, 2),
	snowball.NewAmong("aría", 5, 2),
	snowball.NewAmong("ería", 5, 2),
	snowball.NewAmong("iría", 5, 2),
	snowball.NewAmong("ad", -1, 2),
	snowball.NewAmong("ed", -1, 2),
	snowball.NewAmong("id", -1, 2),
	snowball.NewAmong("ase", -1, 2),
	snowball.NewAmong("iese", -1, 2),
	snowball.NewAmong("aste", -1, 2),
	snowball.NewAmong("iste", -1, 2),
	snowball.NewAmong("an", -1, 2),
	snowball.NewAmong("aban", 16, 2),
	snowball.NewAmong("aran", 16, 2),
	snowball.NewAmong("ieran", 16, 2),
	snowball.NewAmong("ían", 16, 2),
	snowball.NewAmong("arían", 20, 2),
	snowball.NewAmong("erían", 20, 2),
	snowball.NewAmong("irían", 20, 2),
	snowball.NewAmong("en", -1, 1),
	snowball.NewAmong("asen", 24, 2),
	snowball.NewAmong("iesen", 24, 2),
	snowball.NewAmong("aron", -1, 2),
	snowball.NewAmong("ieron", -1, 2),
	snowball.NewAmong("arán", -1, 2),
	snowball.NewAmong("erán", -1, 2),
	snowball.NewAmong("irán", -1, 2),
	snowball.NewAmong("ado", -1, 2),
	snowball.NewAmong("ido", -1, 2),
	snowball.NewAmong("ando", -1, 2),
	snowball.NewAmong("iendo", -1, 2),
	snowball.NewAmong("ar", -1, 2),
	snowball.NewAmong("er", -1, 2),
	snowball.NewAmong("ir", -1, 2),
	snowball.NewAmong("as", -1, 2),
	snowball.NewAmong("abas", 39, 2),
	snowball.NewAmong("adas", 39, 2),
	snowball.NewAmong("idas", 39, 2),
	snowball.NewAmong("aras", 39, 2),
	snowball.NewAmong("ieras", 39, 2),
	snowball.NewAmong("ías", 39, 2),
	snowball.NewAmong("arías", 45, 2),
	snowball.NewAmong("erías", 45, 2),
	snowball.NewAmong("irías", 45, 2),
	snowball.NewAmong("es", -1, 1),
	snowball.NewAmong("ases", 49, 2),
	snowball.NewAmong("ieses", 49, 2),
	snowball.NewAmong("abais", -1, 2),
	snowball.NewAmong("arais", -1, 2),
	snowball.NewAmong("ierais", -1, 2),
	snowball.NewAmong("íais", -1, 2),
	snowball.NewAmong("aríais", 55, 2),
	snowball.NewAmong("eríais", 55, 2),
	snowball.NewAmong("iríais", 55, 2),
	snowball.NewAmong("aseis", -1, 2),
	snowball.NewAmong("ieseis", -1, 2),
	snowball.NewAmong("asteis", -1, 2),
	snowball.NewAmong("isteis", -1, 2),
	snowball.NewAmong("áis", -1, 2),
	snowball.NewAmong("éis", -1, 1),
	snowball.NewAmong("aréis", 64, 2),
	snowball.NewAmong("eréis", 64, 2),
	snowball.NewAmong("iréis", 64, 2),
	snowball.NewAmong("ados", -1, 2),
	snowball.NewAmong("idos", -1, 2),
	snowball.NewAmong("amos", -1, 2),
	snowball.NewAmong("ábamos", 70, 2),
	snowball.NewAmong("áramos", 70, 2),
	snowball.NewAmong("iéramos", 70, 2),
	snowball.NewAmong("íamos", 70, 2),
	snowball.NewAmong("aríamos", 74, 2),
	snowball.NewAmong("eríamos", 74, 2),
	snowball.NewAmong("iríamos", 74, 2),
	snowball.NewAmong("emos", -1, 1),
	snowball.NewAmong("aremos", 78, 2),
	snowball.NewAmong("eremos", 78, 2),
	snowball.NewAmong("iremos", 78, 2),
	snowball.NewAmong("ásemos", 78, 2),
	snowball.NewAmong("iésemos", 78, 2),
	snowball.NewAmong("imos", -1, 2),
	snowball.NewAmong("arás", -1, 2),
	snowball.NewAmong("erás", -1, 2),
	snowball.NewAmong("irás", -1, 2),
	snowball.NewAmong("ís", -1, 2),
	snowball.NewAmong("ará", -1, 2),
	snowball.NewAmong("erá", -1, 2),
	snowball.NewAmong("irá", -1, 2),
	snowball.NewAmong("aré", -1, 2),
	snowball.NewAmong("eré", -1, 2),
	snowball.NewAmong("iré", -1, 2),
	snowball.NewAmong("ió", -1, 2),
}

var spanishA9 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("e", -1, 2),
	snowball.NewAmong("o", -1, 1),
	snowball.NewAmong("os", -1, 1),
	snowball.NewAmong("á", -1, 1),
	snowball.NewAmong("é", -1, 2),
	snowball.NewAmong("í", -1, 1),
	snowball.NewAmong("ó", -1, 1),
}

var spanishGV = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 10}

func (s *SpanishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iPV = p.Limit
	s.iP1 = p.Limit
	s.iP2 = p.Limit
	v1 := p.Cursor
lab0:
	for {
	lab1:
		for {
			v2 := p.Cursor
		lab2:
			for {
				if !p.InGrouping(spanishGV, 97, 252) {
					break lab2
				}
				v3 := p.Cursor
			lab4:
				for {
					if !p.OutGrouping(spanishGV, 97, 252) {
						break lab4
					}
				golab5:
					for {
						if p.InGrouping(spanishGV, 97, 252) {
							break golab5
						}
						if p.Cursor >= p.Limit {
							break lab4
						}
						p.Cursor++
					}
					break lab1
				}
				p.Cursor = v3
				if !p.InGrouping(spanishGV, 97, 252) {
					break lab2
				}
			golab7:
				for {
					if p.OutGrouping(spanishGV, 97, 252) {
						break golab7
					}
					if p.Cursor >= p.Limit {
						break lab2
					}
					p.Cursor++
				}
				break lab1
			}
			p.Cursor = v2
			if !p.OutGrouping(spanishGV, 97, 252) {
				break lab0
			}
			v6 := p.Cursor
		lab10:
			for {
				if !p.OutGrouping(spanishGV, 97, 252) {
					break lab10
				}
			golab11:
				for {
					if p.InGrouping(spanishGV, 97, 252) {
						break golab11
					}
					if p.Cursor >= p.Limit {
						break lab10
					}
					p.Cursor++
				}
				break lab1
			}
			p.Cursor = v6
			if !p.InGrouping(spanishGV, 97, 252) {
				break lab0
			}
			if p.Cursor >= p.Limit {
				break lab0
			}
			p.Cursor++
			break
		}
		s.iPV = p.Cursor
		break
	}
	p.Cursor = v1
	v8 := p.Cursor
lab13:
	for {
	golab14:
		for {
			if p.InGrouping(spanishGV, 97, 252) {
				break golab14
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
	golab16:
		for {
			if p.OutGrouping(spanishGV, 97, 252) {
				break golab16
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
		s.iP1 = p.Cursor
	golab18:
		for {
			if p.InGrouping(spanishGV, 97, 252) {
				break golab18
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
	golab20:
		for {
			if p.OutGrouping(spanishGV, 97, 252) {
				break golab20
			}
			if p.Cursor >= p.Limit {
				break lab13
			}
			p.Cursor++
		}
		s.iP2 = p.Cursor
		break
	}
	p.Cursor = v8
	return true
}

func (s *SpanishStemmer) rPostlude() bool {
	p := s.SnowballProgram
	for {
		v1 := p.Cursor
	lab0:
		for {
			p.Bra = p.Cursor
			amongVar := p.FindAmong(spanishA0)
			p.Ket = p.Cursor
			switch amongVar {
			case 1:
				p.SliceFromStr("a")
			case 2:
				p.SliceFromStr("e")
			case 3:
				p.SliceFromStr("i")
			case 4:
				p.SliceFromStr("o")
			case 5:
				p.SliceFromStr("u")
			case 6:
				if p.Cursor >= p.Limit {
					break lab0
				}
				p.Cursor++
			default:
				break lab0
			}
			continue
		}
		p.Cursor = v1
		break
	}
	return true
}

func (s *SpanishStemmer) rRV() bool { return s.iPV <= s.SnowballProgram.Cursor }
func (s *SpanishStemmer) rR1() bool { return s.iP1 <= s.SnowballProgram.Cursor }
func (s *SpanishStemmer) rR2() bool { return s.iP2 <= s.SnowballProgram.Cursor }

func (s *SpanishStemmer) rAttachedPronoun() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	if p.FindAmongB(spanishA1) == 0 {
		return false
	}
	p.Bra = p.Cursor
	amongVar := p.FindAmongB(spanishA2)
	if amongVar == 0 {
		return false
	}
	if !s.rRV() {
		return false
	}
	switch amongVar {
	case 1:
		p.Bra = p.Cursor
		p.SliceFromStr("iendo")
	case 2:
		p.Bra = p.Cursor
		p.SliceFromStr("ando")
	case 3:
		p.Bra = p.Cursor
		p.SliceFromStr("ar")
	case 4:
		p.Bra = p.Cursor
		p.SliceFromStr("er")
	case 5:
		p.Bra = p.Cursor
		p.SliceFromStr("ir")
	case 6:
		p.SliceDel()
	case 7:
		if !p.EqSBStr("u") {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *SpanishStemmer) rStandardSuffix() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(spanishA6)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
	case 2:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v1 := p.Limit - p.Cursor
	lab0:
		for {
			p.Ket = p.Cursor
			if !p.EqSBStr("ic") {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.SliceDel()
			break
		}
	case 3:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("log")
	case 4:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("u")
	case 5:
		if !s.rR2() {
			return false
		}
		p.SliceFromStr("ente")
	case 6:
		if !s.rR1() {
			return false
		}
		p.SliceDel()
		v2 := p.Limit - p.Cursor
	lab1:
		for {
			p.Ket = p.Cursor
			av := p.FindAmongB(spanishA3)
			if av == 0 {
				p.Cursor = p.Limit - v2
				break lab1
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v2
				break lab1
			}
			p.SliceDel()
			if av == 1 {
			lab6a:
				for {
					p.Ket = p.Cursor
					if !p.EqSBStr("at") {
						p.Cursor = p.Limit - v2
						break lab6a
					}
					p.Bra = p.Cursor
					if !s.rR2() {
						p.Cursor = p.Limit - v2
						break lab6a
					}
					p.SliceDel()
					break
				}
			}
			break
		}
	case 7:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v3 := p.Limit - p.Cursor
	lab2:
		for {
			p.Ket = p.Cursor
			if p.FindAmongB(spanishA4) == 0 {
				p.Cursor = p.Limit - v3
				break lab2
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v3
				break lab2
			}
			p.SliceDel()
			break
		}
	case 8:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v4 := p.Limit - p.Cursor
	lab3:
		for {
			p.Ket = p.Cursor
			if p.FindAmongB(spanishA5) == 0 {
				p.Cursor = p.Limit - v4
				break lab3
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v4
				break lab3
			}
			p.SliceDel()
			break
		}
	case 9:
		if !s.rR2() {
			return false
		}
		p.SliceDel()
		v5 := p.Limit - p.Cursor
	lab4:
		for {
			p.Ket = p.Cursor
			if !p.EqSBStr("at") {
				p.Cursor = p.Limit - v5
				break lab4
			}
			p.Bra = p.Cursor
			if !s.rR2() {
				p.Cursor = p.Limit - v5
				break lab4
			}
			p.SliceDel()
			break
		}
	}
	return true
}

func (s *SpanishStemmer) rYVerbSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iPV {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iPV
	p.Ket = p.Cursor
	if p.FindAmongB(spanishA7) == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	if !p.EqSBStr("u") {
		return false
	}
	p.SliceDel()
	return true
}

func (s *SpanishStemmer) rVerbSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iPV {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iPV
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(spanishA8)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		v3 := p.Limit - p.Cursor
	lab0:
		for {
			if !p.EqSBStr("u") {
				p.Cursor = p.Limit - v3
				break lab0
			}
			v4 := p.Limit - p.Cursor
			if !p.EqSBStr("g") {
				p.Cursor = p.Limit - v3
				break lab0
			}
			p.Cursor = p.Limit - v4
			break
		}
		p.Bra = p.Cursor
		p.SliceDel()
	case 2:
		p.SliceDel()
	}
	return true
}

func (s *SpanishStemmer) rResidualSuffix() bool {
	p := s.SnowballProgram
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(spanishA9)
	if amongVar == 0 {
		return false
	}
	p.Bra = p.Cursor
	switch amongVar {
	case 1:
		if !s.rRV() {
			return false
		}
		p.SliceDel()
	case 2:
		if !s.rRV() {
			return false
		}
		p.SliceDel()
		v1 := p.Limit - p.Cursor
	lab0:
		for {
			p.Ket = p.Cursor
			if !p.EqSBStr("u") {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.Bra = p.Cursor
			v2 := p.Limit - p.Cursor
			if !p.EqSBStr("g") {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.Cursor = p.Limit - v2
			if !s.rRV() {
				p.Cursor = p.Limit - v1
				break lab0
			}
			p.SliceDel()
			break
		}
	}
	return true
}

// Stem applies the Spanish Snowball stemming algorithm.
func (s *SpanishStemmer) Stem() bool {
	p := s.SnowballProgram
	s.rMarkRegions()
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v2 := p.Limit - p.Cursor
	s.rAttachedPronoun()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
lab0:
	for {
	lab1:
		for {
			v4 := p.Limit - p.Cursor
		lab2:
			for {
				if !s.rStandardSuffix() {
					break lab2
				}
				break lab1
			}
			p.Cursor = p.Limit - v4
		lab3:
			for {
				if !s.rYVerbSuffix() {
					break lab3
				}
				break lab1
			}
			p.Cursor = p.Limit - v4
			if !s.rVerbSuffix() {
				break lab0
			}
			break
		}
		break
	}
	p.Cursor = p.Limit - v3
	v5 := p.Limit - p.Cursor
	s.rResidualSuffix()
	p.Cursor = p.Limit - v5
	p.Cursor = p.LimitBackward
	v6 := p.Cursor
	s.rPostlude()
	p.Cursor = v6
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*SpanishStemmer)(nil)
