// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import (
	"github.com/FlavioCFOliveira/Gocene/snowball"
)

// SwedishStemmer implements the Swedish Snowball stemming algorithm.
//
// This is the Go port of org.tartarus.snowball.ext.SwedishStemmer
// from Apache Lucene 10.4.0.
type SwedishStemmer struct {
	*snowball.SnowballProgram
	iX  int
	iP1 int
}

// NewSwedishStemmer creates a new SwedishStemmer.
func NewSwedishStemmer() *SwedishStemmer {
	return &SwedishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

var swedishA0 = []*snowball.Among{
	snowball.NewAmong("a", -1, 1),
	snowball.NewAmong("arna", 0, 1),
	snowball.NewAmong("erna", 0, 1),
	snowball.NewAmong("heterna", 2, 1),
	snowball.NewAmong("orna", 0, 1),
	snowball.NewAmong("ad", -1, 1),
	snowball.NewAmong("e", -1, 1),
	snowball.NewAmong("ade", 6, 1),
	snowball.NewAmong("ande", 6, 1),
	snowball.NewAmong("arne", 6, 1),
	snowball.NewAmong("are", 6, 1),
	snowball.NewAmong("aste", 6, 1),
	snowball.NewAmong("en", -1, 1),
	snowball.NewAmong("anden", 12, 1),
	snowball.NewAmong("aren", 12, 1),
	snowball.NewAmong("heten", 12, 1),
	snowball.NewAmong("ern", -1, 1),
	snowball.NewAmong("ar", -1, 1),
	snowball.NewAmong("er", -1, 1),
	snowball.NewAmong("heter", 18, 1),
	snowball.NewAmong("or", -1, 1),
	snowball.NewAmong("s", -1, 2),
	snowball.NewAmong("as", 21, 1),
	snowball.NewAmong("arnas", 22, 1),
	snowball.NewAmong("ernas", 22, 1),
	snowball.NewAmong("ornas", 22, 1),
	snowball.NewAmong("es", 21, 1),
	snowball.NewAmong("ades", 26, 1),
	snowball.NewAmong("andes", 26, 1),
	snowball.NewAmong("ens", 21, 1),
	snowball.NewAmong("arens", 29, 1),
	snowball.NewAmong("hetens", 29, 1),
	snowball.NewAmong("erns", 21, 1),
	snowball.NewAmong("at", -1, 1),
	snowball.NewAmong("andet", -1, 1),
	snowball.NewAmong("het", -1, 1),
	snowball.NewAmong("ast", -1, 1),
}

var swedishA1 = []*snowball.Among{
	snowball.NewAmong("dd", -1, -1),
	snowball.NewAmong("gd", -1, -1),
	snowball.NewAmong("nn", -1, -1),
	snowball.NewAmong("dt", -1, -1),
	snowball.NewAmong("gt", -1, -1),
	snowball.NewAmong("kt", -1, -1),
	snowball.NewAmong("tt", -1, -1),
}

var swedishA2 = []*snowball.Among{
	snowball.NewAmong("ig", -1, 1),
	snowball.NewAmong("lig", 0, 1),
	snowball.NewAmong("els", -1, 1),
	snowball.NewAmong("fullt", -1, 3),
	snowball.NewAmong("öst", -1, 2),
}

var swedishGV = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 32}
var swedishGSEnding = []byte{119, 127, 149}
var swedishGOstEnding = []byte{173, 58}

func (s *SwedishStemmer) rMarkRegions() bool {
	p := s.SnowballProgram
	s.iP1 = p.Limit
	v1 := p.Cursor
	c := p.Cursor + 3
	if c > p.Limit {
		return false
	}
	p.Cursor = c
	s.iX = p.Cursor
	p.Cursor = v1
golab0:
	for {
		v2 := p.Cursor
	lab1:
		for {
			if !p.InGrouping(swedishGV, 97, 246) {
				break lab1
			}
			p.Cursor = v2
			break golab0
		}
		p.Cursor = v2
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
golab2:
	for {
		if p.OutGrouping(swedishGV, 97, 246) {
			break golab2
		}
		if p.Cursor >= p.Limit {
			return false
		}
		p.Cursor++
	}
	s.iP1 = p.Cursor
lab4:
	for {
		if s.iP1 >= s.iX {
			break lab4
		}
		s.iP1 = s.iX
		break
	}
	return true
}

func (s *SwedishStemmer) rMainSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(swedishA0)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		p.SliceDel()
	case 2:
		if !p.InGroupingB(swedishGSEnding, 98, 121) {
			return false
		}
		p.SliceDel()
	}
	return true
}

func (s *SwedishStemmer) rConsonantPair() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	v3 := p.Limit - p.Cursor
	if p.FindAmongB(swedishA1) == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Cursor = p.Limit - v3
	p.Ket = p.Cursor
	if p.Cursor <= p.LimitBackward {
		p.LimitBackward = v2
		return false
	}
	p.Cursor--
	p.Bra = p.Cursor
	p.SliceDel()
	p.LimitBackward = v2
	return true
}

func (s *SwedishStemmer) rOtherSuffix() bool {
	p := s.SnowballProgram
	if p.Cursor < s.iP1 {
		return false
	}
	v2 := p.LimitBackward
	p.LimitBackward = s.iP1
	p.Ket = p.Cursor
	amongVar := p.FindAmongB(swedishA2)
	if amongVar == 0 {
		p.LimitBackward = v2
		return false
	}
	p.Bra = p.Cursor
	p.LimitBackward = v2
	switch amongVar {
	case 1:
		p.SliceDel()
	case 2:
		if !p.InGroupingB(swedishGOstEnding, 105, 118) {
			return false
		}
		p.SliceFromStr("ös")
	case 3:
		p.SliceFromStr("full")
	}
	return true
}

// Stem applies the Swedish Snowball stemming algorithm.
func (s *SwedishStemmer) Stem() bool {
	p := s.SnowballProgram
	v1 := p.Cursor
	s.rMarkRegions()
	p.Cursor = v1
	p.LimitBackward = p.Cursor
	p.Cursor = p.Limit
	v2 := p.Limit - p.Cursor
	s.rMainSuffix()
	p.Cursor = p.Limit - v2
	v3 := p.Limit - p.Cursor
	s.rConsonantPair()
	p.Cursor = p.Limit - v3
	v4 := p.Limit - p.Cursor
	s.rOtherSuffix()
	p.Cursor = p.Limit - v4
	p.Cursor = p.LimitBackward
	return true
}

var _ interface {
	SetCurrent(string)
	Stem() bool
	GetCurrent() string
} = (*SwedishStemmer)(nil)
