// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

// TamilStemmer mirrors org.tartarus.snowball.ext.TamilStemmer.
type TamilStemmer struct {
	*snowball.SnowballProgram
	bFoundVetrmaiUrupu bool
	bFoundAMatch       bool
}

// NewTamilStemmer builds a TamilStemmer.
func NewTamilStemmer() *TamilStemmer {
	return &TamilStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

// SetCurrent sets the string to stem.
func (s *TamilStemmer) SetCurrent(word string) { s.SnowballProgram.SetCurrent(word) }

// GetCurrent returns the stemmed string.
func (s *TamilStemmer) GetCurrent() string { return s.SnowballProgram.GetCurrent() }

// tamilA0: வ-initial vowel replacement.
var tamilA0 = []*snowball.Among{
	snowball.NewAmong("வு", -1, 3),
	snowball.NewAmong("வூ", -1, 4),
	snowball.NewAmong("வொ", -1, 2),
	snowball.NewAmong("வோ", -1, 1),
}

// tamilA1: consonants after எ question prefix.
var tamilA1 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ங", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ஞ", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ந", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ம", -1, -1),
	snowball.NewAmong("ய", -1, -1),
	snowball.NewAmong("வ", -1, -1),
}

// tamilA2: vowel sign check after ந்த்/etc.
var tamilA2 = []*snowball.Among{
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA3: consonant guard for ு/ன ending removal.
var tamilA3 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA4: suffix sub-check for case 9 of a_5.
var tamilA4 = []*snowball.Among{
	snowball.NewAmong("", -1, 2),
	snowball.NewAmong("ை", 0, 1),
	snowball.NewAmong("்", 0, 1),
}

// tamilA5: ending fixup suffixes.
var tamilA5 = []*snowball.Among{
	snowball.NewAmong("ந்த", -1, 1),
	snowball.NewAmong("ய", -1, 1),
	snowball.NewAmong("வ", -1, 1),
	snowball.NewAmong("னு", -1, 8),
	snowball.NewAmong("ுக்", -1, 7),
	snowball.NewAmong("ுக்க்", -1, 7),
	snowball.NewAmong("ட்க்", -1, 3),
	snowball.NewAmong("ற்க்", -1, 4),
	snowball.NewAmong("ங்", -1, 9),
	snowball.NewAmong("ட்ட்", -1, 5),
	snowball.NewAmong("த்த்", -1, 6),
	snowball.NewAmong("ந்த்", -1, 1),
	snowball.NewAmong("ந்", -1, 1),
	snowball.NewAmong("ட்ப்", -1, 3),
	snowball.NewAmong("ய்", -1, 2),
	snowball.NewAmong("ன்ற்", -1, 4),
	snowball.NewAmong("வ்", -1, 1),
}

// tamilA6: hard consonants (vallinam).
var tamilA6 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ட", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ற", -1, -1),
}

// tamilA7: hard consonants (vallinam) variant.
var tamilA7 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ட", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ற", -1, -1),
}

// tamilA8: soft consonants (mellinam).
var tamilA8 = []*snowball.Among{
	snowball.NewAmong("ஞ", -1, -1),
	snowball.NewAmong("ண", -1, -1),
	snowball.NewAmong("ந", -1, -1),
	snowball.NewAmong("ன", -1, -1),
	snowball.NewAmong("ம", -1, -1),
	snowball.NewAmong("ய", -1, -1),
	snowball.NewAmong("ர", -1, -1),
	snowball.NewAmong("ல", -1, -1),
	snowball.NewAmong("ள", -1, -1),
	snowball.NewAmong("ழ", -1, -1),
	snowball.NewAmong("வ", -1, -1),
}

// tamilA9: vowel sign check set.
var tamilA9 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
	snowball.NewAmong("்", -1, -1),
}

// tamilA10: initial vowel letters for pronoun prefix.
var tamilA10 = []*snowball.Among{
	snowball.NewAmong("அ", -1, -1),
	snowball.NewAmong("இ", -1, -1),
	snowball.NewAmong("உ", -1, -1),
}

// tamilA11: consonants after pronoun prefix vowel.
var tamilA11 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ங", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ஞ", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ந", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ம", -1, -1),
	snowball.NewAmong("ய", -1, -1),
	snowball.NewAmong("வ", -1, -1),
}

// tamilA12: consonant group for plural suffix alt.
var tamilA12 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ட", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ற", -1, -1),
}

// tamilA13: plural suffix forms.
var tamilA13 = []*snowball.Among{
	snowball.NewAmong("கள்", -1, 4),
	snowball.NewAmong("ுங்கள்", 0, 1),
	snowball.NewAmong("ட்கள்", 0, 3),
	snowball.NewAmong("ற்கள்", 0, 2),
}

// tamilA14: question-suffix vowels.
var tamilA14 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ோ", -1, -1),
}

// tamilA15: command suffix pronouns.
var tamilA15 = []*snowball.Among{
	snowball.NewAmong("பி", -1, -1),
	snowball.NewAmong("வி", -1, -1),
}

// tamilA16: vowel signs for common-word-ending guard.
var tamilA16 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA17: common word endings.
var tamilA17 = []*snowball.Among{
	snowball.NewAmong("பட்ட", -1, 3),
	snowball.NewAmong("பட்டண", -1, 3),
	snowball.NewAmong("தான", -1, 3),
	snowball.NewAmong("படிதான", 2, 3),
	snowball.NewAmong("ென", -1, 1),
	snowball.NewAmong("ாகிய", -1, 1),
	snowball.NewAmong("குரிய", -1, 3),
	snowball.NewAmong("ுடைய", -1, 1),
	snowball.NewAmong("ல்ல", -1, 2),
	snowball.NewAmong("ுள்ள", -1, 1),
	snowball.NewAmong("ாகி", -1, 1),
	snowball.NewAmong("படி", -1, 3),
	snowball.NewAmong("ின்றி", -1, 1),
	snowball.NewAmong("பற்றி", -1, 3),
	snowball.NewAmong("படு", -1, 3),
	snowball.NewAmong("விடு", -1, 3),
	snowball.NewAmong("பட்டு", -1, 3),
	snowball.NewAmong("விட்டு", -1, 3),
	snowball.NewAmong("பட்டது", -1, 3),
	snowball.NewAmong("ென்று", -1, 1),
	snowball.NewAmong("ுடை", -1, 1),
	snowball.NewAmong("ில்லை", -1, 1),
	snowball.NewAmong("ுடன்", -1, 1),
	snowball.NewAmong("ிடம்", -1, 1),
	snowball.NewAmong("ெல்லாம்", -1, 3),
	snowball.NewAmong("ெனும்", -1, 1),
}

// tamilA18: vowel sign guard for vetrumai case 5.
var tamilA18 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA19: vowel sign guard for vetrumai case 6.
var tamilA19 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA20: vetrumai case endings.
var tamilA20 = []*snowball.Among{
	snowball.NewAmong("விட", -1, 2),
	snowball.NewAmong("ீ", -1, 7),
	snowball.NewAmong("ொடு", -1, 2),
	snowball.NewAmong("ோடு", -1, 2),
	snowball.NewAmong("து", -1, 6),
	snowball.NewAmong("ிருந்து", 4, 2),
	snowball.NewAmong("ின்று", -1, 2),
	snowball.NewAmong("ுடை", -1, 2),
	snowball.NewAmong("னை", -1, 1),
	snowball.NewAmong("கண்", -1, 1),
	snowball.NewAmong("ின்", -1, 3),
	snowball.NewAmong("முன்", -1, 1),
	snowball.NewAmong("ிடம்", -1, 4),
	snowball.NewAmong("ிற்", -1, 2),
	snowball.NewAmong("மேற்", -1, 1),
	snowball.NewAmong("ல்", -1, 5),
	snowball.NewAmong("ாமல்", 15, 2),
	snowball.NewAmong("ால்", 15, 2),
	snowball.NewAmong("ில்", 15, 2),
	snowball.NewAmong("மேல்", 15, 1),
	snowball.NewAmong("ுள்", -1, 2),
	snowball.NewAmong("கீழ்", -1, 1),
}

// tamilA21: consonant set for ை sub-check.
var tamilA21 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ட", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ற", -1, -1),
}

// tamilA22: consonant set for ை sub-check alt.
var tamilA22 = []*snowball.Among{
	snowball.NewAmong("க", -1, -1),
	snowball.NewAmong("ச", -1, -1),
	snowball.NewAmong("ட", -1, -1),
	snowball.NewAmong("த", -1, -1),
	snowball.NewAmong("ப", -1, -1),
	snowball.NewAmong("ற", -1, -1),
}

// tamilA23: vowel initial letters for tense suffix case 2 guard.
var tamilA23 = []*snowball.Among{
	snowball.NewAmong("அ", -1, -1),
	snowball.NewAmong("ஆ", -1, -1),
	snowball.NewAmong("இ", -1, -1),
	snowball.NewAmong("ஈ", -1, -1),
	snowball.NewAmong("உ", -1, -1),
	snowball.NewAmong("ஊ", -1, -1),
	snowball.NewAmong("எ", -1, -1),
	snowball.NewAmong("ஏ", -1, -1),
	snowball.NewAmong("ஐ", -1, -1),
	snowball.NewAmong("ஒ", -1, -1),
	snowball.NewAmong("ஓ", -1, -1),
	snowball.NewAmong("ஔ", -1, -1),
}

// tamilA24: vowel sign guard for tense suffix case 3.
var tamilA24 = []*snowball.Among{
	snowball.NewAmong("ா", -1, -1),
	snowball.NewAmong("ி", -1, -1),
	snowball.NewAmong("ீ", -1, -1),
	snowball.NewAmong("ு", -1, -1),
	snowball.NewAmong("ூ", -1, -1),
	snowball.NewAmong("ெ", -1, -1),
	snowball.NewAmong("ே", -1, -1),
	snowball.NewAmong("ை", -1, -1),
}

// tamilA25: tense suffixes.
var tamilA25 = []*snowball.Among{
	snowball.NewAmong("க", -1, 1),
	snowball.NewAmong("த", -1, 1),
	snowball.NewAmong("ன", -1, 1),
	snowball.NewAmong("ப", -1, 1),
	snowball.NewAmong("ய", -1, 1),
	snowball.NewAmong("ா", -1, 5),
	snowball.NewAmong("கு", -1, 6),
	snowball.NewAmong("படு", -1, 1),
	snowball.NewAmong("து", -1, 3),
	snowball.NewAmong("ிற்று", -1, 1),
	snowball.NewAmong("னை", -1, 1),
	snowball.NewAmong("வை", -1, 1),
	snowball.NewAmong("னன்", -1, 1),
	snowball.NewAmong("பன்", -1, 1),
	snowball.NewAmong("வன்", -1, 2),
	snowball.NewAmong("ான்", -1, 4),
	snowball.NewAmong("னான்", 15, 1),
	snowball.NewAmong("மின்", -1, 1),
	snowball.NewAmong("னென்", -1, 1),
	snowball.NewAmong("ேன்", -1, 5),
	snowball.NewAmong("னம்", -1, 1),
	snowball.NewAmong("பம்", -1, 1),
	snowball.NewAmong("ாம்", -1, 5),
	snowball.NewAmong("கும்", -1, 1),
	snowball.NewAmong("டும்", -1, 5),
	snowball.NewAmong("தும்", -1, 1),
	snowball.NewAmong("றும்", -1, 1),
	snowball.NewAmong("ெம்", -1, 5),
	snowball.NewAmong("ேம்", -1, 5),
	snowball.NewAmong("ோம்", -1, 5),
	snowball.NewAmong("ாய்", -1, 5),
	snowball.NewAmong("னர்", -1, 1),
	snowball.NewAmong("பர்", -1, 1),
	snowball.NewAmong("ீயர்", -1, 5),
	snowball.NewAmong("வர்", -1, 1),
	snowball.NewAmong("ார்", -1, 5),
	snowball.NewAmong("னார்", 35, 1),
	snowball.NewAmong("மார்", 35, 1),
	snowball.NewAmong("கொண்டிர்", -1, 1),
	snowball.NewAmong("னிர்", -1, 5),
	snowball.NewAmong("ீர்", -1, 5),
	snowball.NewAmong("னள்", -1, 1),
	snowball.NewAmong("பள்", -1, 1),
	snowball.NewAmong("வள்", -1, 1),
	snowball.NewAmong("ாள்", -1, 5),
	snowball.NewAmong("னாள்", 44, 1),
}

// tamilA26: present-tense markers.
var tamilA26 = []*snowball.Among{
	snowball.NewAmong("கிற", -1, -1),
	snowball.NewAmong("கின்ற", -1, -1),
	snowball.NewAmong("ாநின்ற", -1, -1),
	snowball.NewAmong("கிற்", -1, -1),
	snowball.NewAmong("கின்ற்", -1, -1),
	snowball.NewAmong("ாநின்ற்", -1, -1),
}

func (s *TamilStemmer) rHasMinLength() bool {
	return s.Limit > 4
}

func (s *TamilStemmer) rFixVaStart() bool {
	s.Bra = s.Cursor
	amongVar := s.FindAmong(tamilA0)
	if amongVar == 0 {
		return false
	}
	s.Ket = s.Cursor
	switch amongVar {
	case 1:
		s.SliceFromStr("ஓ")
	case 2:
		s.SliceFromStr("ஒ")
	case 3:
		s.SliceFromStr("உ")
	case 4:
		s.SliceFromStr("ஊ")
	}
	return true
}

func (s *TamilStemmer) rFixEndings() bool {
	v1 := s.Cursor
	lab0:
	for {
		for {
			v2 := s.Cursor
			lab1:
			for {
				if !s.rFixEnding() {
					break lab1
				}
				continue
			}
			s.Cursor = v2
			break lab0
		}
		break lab0
	}
	s.Cursor = v1
	return true
}

func (s *TamilStemmer) rRemoveQuestionPrefixes() bool {
	s.Bra = s.Cursor
	if !s.EqSStr("எ") {
		return false
	}
	if s.FindAmong(tamilA1) == 0 {
		return false
	}
	if !s.EqSStr("்") {
		return false
	}
	s.Ket = s.Cursor
	s.SliceDel()
	v1 := s.Cursor
	s.rFixVaStart()
	s.Cursor = v1
	return true
}

func (s *TamilStemmer) rFixEnding() bool {
	if s.Limit <= 3 {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	lab0:
	for {
		v1 := s.Limit - s.Cursor
		lab1:
		for {
			s.Ket = s.Cursor
			amongVar := s.FindAmongB(tamilA5)
			if amongVar == 0 {
				break lab1
			}
			s.Bra = s.Cursor
			switch amongVar {
			case 1:
				s.SliceDel()
			case 2:
				v2 := s.Limit - s.Cursor
				if s.FindAmongB(tamilA2) == 0 {
					break lab1
				}
				s.Cursor = s.Limit - v2
				s.SliceDel()
			case 3:
				s.SliceFromStr("ள்")
			case 4:
				s.SliceFromStr("ல்")
			case 5:
				s.SliceFromStr("டு")
			case 6:
				if !s.bFoundVetrmaiUrupu {
					break lab1
				}
				v3 := s.Limit - s.Cursor
				lab2:
				for {
					if !s.EqSBStr("ை") {
						break lab2
					}
					break lab1
				}
				s.Cursor = s.Limit - v3
				s.SliceFromStr("ம்")
			case 7:
				s.SliceFromStr("்")
			case 8:
				v4 := s.Limit - s.Cursor
				lab3:
				for {
					if s.FindAmongB(tamilA3) == 0 {
						break lab3
					}
					break lab1
				}
				s.Cursor = s.Limit - v4
				s.SliceDel()
			case 9:
				innerVar := s.FindAmongB(tamilA4)
				switch innerVar {
				case 1:
					s.SliceDel()
				case 2:
					s.SliceFromStr("ம்")
				}
			}
			break lab0
		}
		s.Cursor = s.Limit - v1
		s.Ket = s.Cursor
		if !s.EqSBStr("்") {
			return false
		}
		lab4:
		for {
			v5 := s.Limit - s.Cursor
			lab5:
			for {
				if s.FindAmongB(tamilA6) == 0 {
					break lab5
				}
				v6 := s.Limit - s.Cursor
				lab6:
				for {
					if !s.EqSBStr("்") {
						s.Cursor = s.Limit - v6
						break lab6
					}
					if s.FindAmongB(tamilA7) == 0 {
						s.Cursor = s.Limit - v6
						break lab6
					}
					break lab6
				}
				s.Bra = s.Cursor
				s.SliceDel()
				break lab4
			}
			s.Cursor = s.Limit - v5
			lab7:
			for {
				if s.FindAmongB(tamilA8) == 0 {
					break lab7
				}
				s.Bra = s.Cursor
				if !s.EqSBStr("்") {
					break lab7
				}
				s.SliceDel()
				break lab4
			}
			s.Cursor = s.Limit - v5
			v7 := s.Limit - s.Cursor
			if s.FindAmongB(tamilA9) == 0 {
				return false
			}
			s.Cursor = s.Limit - v7
			s.Bra = s.Cursor
			s.SliceDel()
			break lab4
		}
		break lab0
	}
	s.Cursor = s.LimitBackward
	return true
}

func (s *TamilStemmer) rRemovePronounPrefixes() bool {
	s.Bra = s.Cursor
	if s.FindAmong(tamilA10) == 0 {
		return false
	}
	if s.FindAmong(tamilA11) == 0 {
		return false
	}
	if !s.EqSStr("்") {
		return false
	}
	s.Ket = s.Cursor
	s.SliceDel()
	v1 := s.Cursor
	s.rFixVaStart()
	s.Cursor = v1
	return true
}

func (s *TamilStemmer) rRemovePluralSuffix() bool {
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(tamilA13)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		lab0:
		for {
			v1 := s.Limit - s.Cursor
			lab1:
			for {
				if s.FindAmongB(tamilA12) == 0 {
					break lab1
				}
				s.SliceFromStr("ுங்")
				break lab0
			}
			s.Cursor = s.Limit - v1
			s.SliceFromStr("்")
			break lab0
		}
	case 2:
		s.SliceFromStr("ல்")
	case 3:
		s.SliceFromStr("ள்")
	case 4:
		s.SliceDel()
	}
	s.Cursor = s.LimitBackward
	return true
}

func (s *TamilStemmer) rRemoveQuestionSuffixes() bool {
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	v1 := s.Limit - s.Cursor
	lab0:
	for {
		s.Ket = s.Cursor
		if s.FindAmongB(tamilA14) == 0 {
			break lab0
		}
		s.Bra = s.Cursor
		s.SliceFromStr("்")
		break lab0
	}
	s.Cursor = s.Limit - v1
	s.Cursor = s.LimitBackward
	s.rFixEndings()
	return true
}

func (s *TamilStemmer) rRemoveCommandSuffixes() bool {
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	s.Ket = s.Cursor
	if s.FindAmongB(tamilA15) == 0 {
		return false
	}
	s.Bra = s.Cursor
	s.SliceDel()
	s.Cursor = s.LimitBackward
	return true
}

func (s *TamilStemmer) rRemoveUm() bool {
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	s.Ket = s.Cursor
	if !s.EqSBStr("ும்") {
		return false
	}
	s.Bra = s.Cursor
	s.SliceFromStr("்")
	s.Cursor = s.LimitBackward
	v1 := s.Cursor
	s.rFixEnding()
	s.Cursor = v1
	return true
}

func (s *TamilStemmer) rRemoveCommonWordEndings() bool {
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	s.Ket = s.Cursor
	amongVar := s.FindAmongB(tamilA17)
	if amongVar == 0 {
		return false
	}
	s.Bra = s.Cursor
	switch amongVar {
	case 1:
		s.SliceFromStr("்")
	case 2:
		v1 := s.Limit - s.Cursor
		lab0:
		for {
			if s.FindAmongB(tamilA16) == 0 {
				break lab0
			}
			return false
		}
		s.Cursor = s.Limit - v1
		s.SliceFromStr("்")
	case 3:
		s.SliceDel()
	}
	s.Cursor = s.LimitBackward
	s.rFixEndings()
	return true
}

func (s *TamilStemmer) rRemoveVetrumaiUrupukal() bool {
	s.bFoundVetrmaiUrupu = false
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	lab0:
	for {
		v1 := s.Limit - s.Cursor
		lab1:
		for {
			v2 := s.Limit - s.Cursor
			s.Ket = s.Cursor
			amongVar := s.FindAmongB(tamilA20)
			if amongVar == 0 {
				break lab1
			}
			s.Bra = s.Cursor
			switch amongVar {
			case 1:
				s.SliceDel()
			case 2:
				s.SliceFromStr("்")
			case 3:
				v3 := s.Limit - s.Cursor
				lab2:
				for {
					if !s.EqSBStr("ம") {
						break lab2
					}
					break lab1
				}
				s.Cursor = s.Limit - v3
				s.SliceFromStr("்")
			case 4:
				if s.Limit < 7 {
					break lab1
				}
				s.SliceFromStr("்")
			case 5:
				v4 := s.Limit - s.Cursor
				lab3:
				for {
					if s.FindAmongB(tamilA18) == 0 {
						break lab3
					}
					break lab1
				}
				s.Cursor = s.Limit - v4
				s.SliceFromStr("்")
			case 6:
				v5 := s.Limit - s.Cursor
				lab4:
				for {
					if s.FindAmongB(tamilA19) == 0 {
						break lab4
					}
					break lab1
				}
				s.Cursor = s.Limit - v5
				s.SliceDel()
			case 7:
				s.SliceFromStr("ி")
			}
			s.Cursor = s.Limit - v2
			break lab0
		}
		s.Cursor = s.Limit - v1
		v6 := s.Limit - s.Cursor
		s.Ket = s.Cursor
		if !s.EqSBStr("ை") {
			return false
		}
		lab5:
		for {
			v7 := s.Limit - s.Cursor
			lab6:
			for {
				v8 := s.Limit - s.Cursor
				lab7:
				for {
					if s.FindAmongB(tamilA21) == 0 {
						break lab7
					}
					break lab6
				}
				s.Cursor = s.Limit - v8
				break lab5
			}
			s.Cursor = s.Limit - v7
			v9 := s.Limit - s.Cursor
			if s.FindAmongB(tamilA22) == 0 {
				return false
			}
			if !s.EqSBStr("்") {
				return false
			}
			s.Cursor = s.Limit - v9
			break lab5
		}
		s.Bra = s.Cursor
		s.SliceFromStr("்")
		s.Cursor = s.Limit - v6
		break lab0
	}
	s.bFoundVetrmaiUrupu = true
	v10 := s.Limit - s.Cursor
	lab8:
	for {
		s.Ket = s.Cursor
		if !s.EqSBStr("ின்") {
			break lab8
		}
		s.Bra = s.Cursor
		s.SliceFromStr("்")
		break lab8
	}
	s.Cursor = s.Limit - v10
	s.Cursor = s.LimitBackward
	s.rFixEndings()
	return true
}

func (s *TamilStemmer) rRemoveTenseSuffixes() bool {
	s.bFoundAMatch = true
	for {
		v1 := s.Cursor
		lab0:
		for {
			if !s.bFoundAMatch {
				break lab0
			}
			v2 := s.Cursor
			s.rRemoveTenseSuffix()
			s.Cursor = v2
			continue
		}
		s.Cursor = v1
		break
	}
	return true
}

func (s *TamilStemmer) rRemoveTenseSuffix() bool {
	s.bFoundAMatch = false
	if !s.rHasMinLength() {
		return false
	}
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	v1 := s.Limit - s.Cursor
	lab0:
	for {
		v2 := s.Limit - s.Cursor
		s.Ket = s.Cursor
		amongVar := s.FindAmongB(tamilA25)
		if amongVar == 0 {
			break lab0
		}
		s.Bra = s.Cursor
		switch amongVar {
		case 1:
			s.SliceDel()
		case 2:
			v3 := s.Limit - s.Cursor
			lab1:
			for {
				if s.FindAmongB(tamilA23) == 0 {
					break lab1
				}
				break lab0
			}
			s.Cursor = s.Limit - v3
			s.SliceDel()
		case 3:
			v4 := s.Limit - s.Cursor
			lab2:
			for {
				if s.FindAmongB(tamilA24) == 0 {
					break lab2
				}
				break lab0
			}
			s.Cursor = s.Limit - v4
			s.SliceDel()
		case 4:
			v5 := s.Limit - s.Cursor
			lab3:
			for {
				if !s.EqSBStr("ச") {
					break lab3
				}
				break lab0
			}
			s.Cursor = s.Limit - v5
			s.SliceFromStr("்")
		case 5:
			s.SliceFromStr("்")
		case 6:
			v6 := s.Limit - s.Cursor
			if !s.EqSBStr("்") {
				break lab0
			}
			s.Cursor = s.Limit - v6
			s.SliceDel()
		}
		s.bFoundAMatch = true
		s.Cursor = s.Limit - v2
		break lab0
	}
	s.Cursor = s.Limit - v1
	v7 := s.Limit - s.Cursor
	lab4:
	for {
		s.Ket = s.Cursor
		if s.FindAmongB(tamilA26) == 0 {
			break lab4
		}
		s.Bra = s.Cursor
		s.SliceDel()
		s.bFoundAMatch = true
		break lab4
	}
	s.Cursor = s.Limit - v7
	s.Cursor = s.LimitBackward
	s.rFixEndings()
	return true
}

// Stem performs Tamil stemming.
func (s *TamilStemmer) Stem() bool {
	s.bFoundVetrmaiUrupu = false
	v1 := s.Cursor
	s.rFixEnding()
	s.Cursor = v1
	if !s.rHasMinLength() {
		return false
	}
	v2 := s.Cursor
	s.rRemoveQuestionPrefixes()
	s.Cursor = v2
	v3 := s.Cursor
	s.rRemovePronounPrefixes()
	s.Cursor = v3
	v4 := s.Cursor
	s.rRemoveQuestionSuffixes()
	s.Cursor = v4
	v5 := s.Cursor
	s.rRemoveUm()
	s.Cursor = v5
	v6 := s.Cursor
	s.rRemoveCommonWordEndings()
	s.Cursor = v6
	v7 := s.Cursor
	s.rRemoveVetrumaiUrupukal()
	s.Cursor = v7
	v8 := s.Cursor
	s.rRemovePluralSuffix()
	s.Cursor = v8
	v9 := s.Cursor
	s.rRemoveCommandSuffixes()
	s.Cursor = v9
	v10 := s.Cursor
	s.rRemoveTenseSuffixes()
	s.Cursor = v10
	return true
}
