// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported to Go from Apache Lucene 10.4.0.

package ext

import "github.com/FlavioCFOliveira/Gocene/snowball"

// YiddishStemmer mirrors org.tartarus.snowball.ext.YiddishStemmer.
type YiddishStemmer struct {
	*snowball.SnowballProgram
	iX  int
	iP1 int
}

// NewYiddishStemmer builds a YiddishStemmer.
func NewYiddishStemmer() *YiddishStemmer {
	return &YiddishStemmer{SnowballProgram: snowball.NewSnowballProgram()}
}

// yiddishA0: niked/final-letter normalisation.
var yiddishA0 = []*snowball.Among{
	snowball.NewAmong("וו", -1, 1),
	snowball.NewAmong("וי", -1, 2),
	snowball.NewAmong("יי", -1, 3),
	snowball.NewAmong("ך", -1, 4),
	snowball.NewAmong("ם", -1, 5),
	snowball.NewAmong("ן", -1, 6),
	snowball.NewAmong("ף", -1, 7),
	snowball.NewAmong("ץ", -1, 8),
}

// yiddishA1: prefix table.
var yiddishA1 = []*snowball.Among{
	snowball.NewAmong("אדורכ", -1, 1),
	snowball.NewAmong("אהינ", -1, 1),
	snowball.NewAmong("אהער", -1, 1),
	snowball.NewAmong("אהײמ", -1, 1),
	snowball.NewAmong("אומ", -1, 1),
	snowball.NewAmong("אונטער", -1, 1),
	snowball.NewAmong("איבער", -1, 1),
	snowball.NewAmong("אנ", -1, 1),
	snowball.NewAmong("אנט", 7, 1),
	snowball.NewAmong("אנטקעגנ", 8, 1),
	snowball.NewAmong("אנידער", 7, 1),
	snowball.NewAmong("אפ", -1, 1),
	snowball.NewAmong("אפיר", 11, 1),
	snowball.NewAmong("אקעגנ", -1, 1),
	snowball.NewAmong("אראפ", -1, 1),
	snowball.NewAmong("ארומ", -1, 1),
	snowball.NewAmong("ארונטער", -1, 1),
	snowball.NewAmong("אריבער", -1, 1),
	snowball.NewAmong("ארױס", -1, 1),
	snowball.NewAmong("ארױפ", -1, 1),
	snowball.NewAmong("ארײנ", -1, 1),
	snowball.NewAmong("אװעק", -1, 1),
	snowball.NewAmong("אױס", -1, 1),
	snowball.NewAmong("אױפ", -1, 1),
	snowball.NewAmong("אײנ", -1, 1),
	snowball.NewAmong("בא", -1, 1),
	snowball.NewAmong("בײ", -1, 1),
	snowball.NewAmong("דורכ", -1, 1),
	snowball.NewAmong("דער", -1, 1),
	snowball.NewAmong("מיט", -1, 1),
	snowball.NewAmong("נאכ", -1, 1),
	snowball.NewAmong("פאר", -1, 1),
	snowball.NewAmong("פארבײ", 31, 1),
	snowball.NewAmong("פארױס", 31, 1),
	snowball.NewAmong("פונאנדער", -1, 1),
	snowball.NewAmong("צו", -1, 1),
	snowball.NewAmong("צוזאמענ", 35, 1),
	snowball.NewAmong("צונױפ", 35, 1),
	snowball.NewAmong("צוריק", 35, 1),
	snowball.NewAmong("צע", -1, 1),
}

// yiddishA2: consonant cluster disambiguation.
var yiddishA2 = []*snowball.Among{
	snowball.NewAmong("דזש", -1, -1),
	snowball.NewAmong("שטר", -1, -1),
	snowball.NewAmong("שטש", -1, -1),
	snowball.NewAmong("שפר", -1, -1),
}

// yiddishA3: irregular verb stems for nested step (after ענעמ/עמ removal).
var yiddishA3 = []*snowball.Among{
	snowball.NewAmong("קליב", -1, 9),
	snowball.NewAmong("ריב", -1, 10),
	snowball.NewAmong("טריב", 1, 7),
	snowball.NewAmong("שריב", 1, 15),
	snowball.NewAmong("הױב", -1, 23),
	snowball.NewAmong("שװיג", -1, 12),
	snowball.NewAmong("גאנג", -1, 1),
	snowball.NewAmong("זונג", -1, 18),
	snowball.NewAmong("שלונג", -1, 21),
	snowball.NewAmong("צװונג", -1, 20),
	snowball.NewAmong("בױג", -1, 22),
	snowball.NewAmong("בונד", -1, 16),
	snowball.NewAmong("װיז", -1, 6),
	snowball.NewAmong("ביט", -1, 4),
	snowball.NewAmong("ליט", -1, 8),
	snowball.NewAmong("מיט", -1, 3),
	snowball.NewAmong("שניט", -1, 14),
	snowball.NewAmong("נומ", -1, 2),
	snowball.NewAmong("שטאנ", -1, 25),
	snowball.NewAmong("ביס", -1, 5),
	snowball.NewAmong("שמיס", -1, 13),
	snowball.NewAmong("ריס", -1, 11),
	snowball.NewAmong("טרונק", -1, 19),
	snowball.NewAmong("פארלױר", -1, 24),
	snowball.NewAmong("שװױר", -1, 26),
	snowball.NewAmong("װוטש", -1, 17),
}

// yiddishA4: main suffix table.
var yiddishA4 = []*snowball.Among{
	snowball.NewAmong("ונג", -1, 1),
	snowball.NewAmong("סטו", -1, 1),
	snowball.NewAmong("ט", -1, 1),
	snowball.NewAmong("בראכט", 2, 31),
	snowball.NewAmong("סט", 2, 1),
	snowball.NewAmong("יסט", 4, 33),
	snowball.NewAmong("עט", 2, 1),
	snowball.NewAmong("שאפט", 2, 1),
	snowball.NewAmong("הײט", 2, 1),
	snowball.NewAmong("קײט", 2, 1),
	snowball.NewAmong("יקײט", 9, 1),
	snowball.NewAmong("לעכ", -1, 1),
	snowball.NewAmong("עלעכ", 11, 1),
	snowball.NewAmong("יזמ", -1, 1),
	snowball.NewAmong("ימ", -1, 1),
	snowball.NewAmong("עמ", -1, 1),
	snowball.NewAmong("ענעמ", 15, 3),
	snowball.NewAmong("טענעמ", 16, 4),
	snowball.NewAmong("נ", -1, 1),
	snowball.NewAmong("קליבנ", 18, 14),
	snowball.NewAmong("ריבנ", 18, 15),
	snowball.NewAmong("טריבנ", 20, 12),
	snowball.NewAmong("שריבנ", 20, 7),
	snowball.NewAmong("הױבנ", 18, 27),
	snowball.NewAmong("שװיגנ", 18, 17),
	snowball.NewAmong("זונגנ", 18, 22),
	snowball.NewAmong("שלונגנ", 18, 25),
	snowball.NewAmong("צװונגנ", 18, 24),
	snowball.NewAmong("בױגנ", 18, 26),
	snowball.NewAmong("בונדנ", 18, 20),
	snowball.NewAmong("װיזנ", 18, 11),
	snowball.NewAmong("טנ", 18, 4),
	snowball.NewAmong("GEביטנ", 31, 9),
	snowball.NewAmong("GEליטנ", 31, 13),
	snowball.NewAmong("GEמיטנ", 31, 8),
	snowball.NewAmong("שניטנ", 31, 19),
	snowball.NewAmong("סטנ", 31, 1),
	snowball.NewAmong("יסטנ", 36, 1),
	snowball.NewAmong("עטנ", 31, 1),
	snowball.NewAmong("GEביסנ", 18, 10),
	snowball.NewAmong("שמיסנ", 18, 18),
	snowball.NewAmong("GEריסנ", 18, 16),
	snowball.NewAmong("ענ", 18, 1),
	snowball.NewAmong("גאנגענ", 42, 5),
	snowball.NewAmong("עלענ", 42, 1),
	snowball.NewAmong("נומענ", 42, 6),
	snowball.NewAmong("יזמענ", 42, 1),
	snowball.NewAmong("שטאנענ", 42, 29),
	snowball.NewAmong("טרונקנ", 18, 23),
	snowball.NewAmong("פארלױרנ", 18, 28),
	snowball.NewAmong("שװױרנ", 18, 30),
	snowball.NewAmong("װוטשנ", 18, 21),
	snowball.NewAmong("גײנ", 18, 5),
	snowball.NewAmong("ס", -1, 1),
	snowball.NewAmong("טס", 53, 4),
	snowball.NewAmong("עטס", 54, 1),
	snowball.NewAmong("נס", 53, 1),
	snowball.NewAmong("טנס", 56, 4),
	snowball.NewAmong("ענס", 56, 3),
	snowball.NewAmong("עס", 53, 1),
	snowball.NewAmong("יעס", 59, 2),
	snowball.NewAmong("עלעס", 59, 1),
	snowball.NewAmong("ערס", 53, 1),
	snowball.NewAmong("ענערס", 62, 1),
	snowball.NewAmong("ע", -1, 1),
	snowball.NewAmong("טע", 64, 4),
	snowball.NewAmong("סטע", 65, 1),
	snowball.NewAmong("עטע", 65, 1),
	snowball.NewAmong("יע", 64, -1),
	snowball.NewAmong("עלע", 64, 1),
	snowball.NewAmong("ענע", 64, 3),
	snowball.NewAmong("טענע", 70, 4),
	snowball.NewAmong("ער", -1, 1),
	snowball.NewAmong("טער", 72, 4),
	snowball.NewAmong("סטער", 73, 1),
	snowball.NewAmong("עטער", 73, 1),
	snowball.NewAmong("ענער", 72, 3),
	snowball.NewAmong("טענער", 76, 4),
	snowball.NewAmong("ות", -1, 32),
}

// yiddishA5: secondary suffix table (after main suffixes removed).
var yiddishA5 = []*snowball.Among{
	snowball.NewAmong("ונג", -1, 1),
	snowball.NewAmong("שאפט", -1, 1),
	snowball.NewAmong("הײט", -1, 1),
	snowball.NewAmong("קײט", -1, 1),
	snowball.NewAmong("יקײט", 3, 1),
	snowball.NewAmong("ל", -1, 2),
}

// yiddishA6: adjectival/adverbial suffix table.
var yiddishA6 = []*snowball.Among{
	snowball.NewAmong("יג", -1, 1),
	snowball.NewAmong("יק", -1, 1),
	snowball.NewAmong("דיק", 1, 1),
	snowball.NewAmong("נדיק", 2, 1),
	snowball.NewAmong("ענדיק", 3, 1),
	snowball.NewAmong("בליק", 1, -1),
	snowball.NewAmong("גליק", 1, -1),
	snowball.NewAmong("ניק", 1, 1),
	snowball.NewAmong("יש", -1, 1),
}

// yiddishGNiked: niked (vowel-pointing) characters.
var yiddishGNiked = []byte{255, 155, 6}

// yiddishGVowel: vowel characters.
var yiddishGVowel = []byte{33, 2, 4, 0, 6}

// yiddishGConsonant: consonant characters.
var yiddishGConsonant = []byte{239, 254, 253, 131}

// rPrelude normalises niked marks and final-letter forms.
func (s *YiddishStemmer) rPrelude() bool {
	v1 := s.Cursor
outerLoop:
	for {
		v2 := s.Cursor
	golab2:
		for {
			v3 := s.Cursor
			lab3:
			for {
				s.Bra = s.Cursor
				amongVar := s.FindAmong(yiddishA0)
				if amongVar == 0 {
					break lab3
				}
				s.Ket = s.Cursor
				switch amongVar {
				case 1:
					v4 := s.Cursor
					lab4:
					for {
						if !s.EqSStr("ּ") {
							break lab4
						}
						break lab3
					}
					s.Cursor = v4
					s.SliceFromStr("װ")
				case 2:
					v5 := s.Cursor
					lab5:
					for {
						if !s.EqSStr("ִ") {
							break lab5
						}
						break lab3
					}
					s.Cursor = v5
					s.SliceFromStr("ױ")
				case 3:
					v6 := s.Cursor
					lab6:
					for {
						if !s.EqSStr("ִ") {
							break lab6
						}
						break lab3
					}
					s.Cursor = v6
					s.SliceFromStr("ײ")
				case 4:
					s.SliceFromStr("כ")
				case 5:
					s.SliceFromStr("מ")
				case 6:
					s.SliceFromStr("נ")
				case 7:
					s.SliceFromStr("פ")
				case 8:
					s.SliceFromStr("צ")
				}
				s.Cursor = v3
				break golab2
			}
			s.Cursor = v3
			if s.Cursor >= s.Limit {
				s.Cursor = v2
				break outerLoop
			}
			s.Cursor++
		}
		continue outerLoop
	}
	s.Cursor = v1
	v7 := s.Cursor
outerLoop7:
	for {
		v8 := s.Cursor
	golab9:
		for {
			v9 := s.Cursor
			lab10:
			for {
				s.Bra = s.Cursor
				if !s.InGrouping(yiddishGNiked, 1456, 1474) {
					break lab10
				}
				s.Ket = s.Cursor
				s.SliceDel()
				s.Cursor = v9
				break golab9
			}
			s.Cursor = v9
			if s.Cursor >= s.Limit {
				s.Cursor = v8
				break outerLoop7
			}
			s.Cursor++
		}
		continue outerLoop7
	}
	s.Cursor = v7
	return true
}

// rMarkRegions determines iX and iP1.
func (s *YiddishStemmer) rMarkRegions() bool {
	s.iP1 = s.Limit
	v1 := s.Cursor
	lab0:
	for {
		s.Bra = s.Cursor
		if !s.EqSStr("גע") {
			s.Cursor = v1
			break lab0
		}
		s.Ket = s.Cursor
		v2 := s.Cursor
		lab1:
		for {
			lab2:
			for {
				v3 := s.Cursor
				lab3:
				for {
					if !s.EqSStr("לט") {
						break lab3
					}
					break lab2
				}
				s.Cursor = v3
				if !s.EqSStr("בנ") {
					break lab1
				}
				break lab2
			}
			s.Cursor = v1
			break lab0
		}
		s.Cursor = v2
		s.SliceFromStr("GE")
		break lab0
	}
	v4 := s.Cursor
	lab4:
	for {
		if s.FindAmong(yiddishA1) == 0 {
			s.Cursor = v4
			break lab4
		}
		lab5:
		for {
			v5 := s.Cursor
			lab6:
			for {
				v6 := s.Cursor
				lab7:
				for {
					v7 := s.Cursor
					lab8:
					for {
						if !s.EqSStr("צוגנ") {
							break lab8
						}
						break lab7
					}
					s.Cursor = v7
					lab9:
					for {
						if !s.EqSStr("צוקט") {
							break lab9
						}
						break lab7
					}
					s.Cursor = v7
					if !s.EqSStr("צוקנ") {
						break lab6
					}
					break lab7
				}
				if s.Cursor < s.Limit {
					break lab6
				}
				s.Cursor = v6
				break lab5
			}
			s.Cursor = v5
			lab10:
			for {
				v8 := s.Cursor
				if !s.EqSStr("געבנ") {
					break lab10
				}
				s.Cursor = v8
				break lab5
			}
			s.Cursor = v5
			lab11:
			for {
				s.Bra = s.Cursor
				if !s.EqSStr("גע") {
					break lab11
				}
				s.Ket = s.Cursor
				s.SliceFromStr("GE")
				break lab5
			}
			s.Cursor = v5
			s.Bra = s.Cursor
			if !s.EqSStr("צו") {
				s.Cursor = v4
				break lab4
			}
			s.Ket = s.Cursor
			s.SliceFromStr("TSU")
			break lab5
		}
		break lab4
	}
	v9 := s.Cursor
	c := s.Cursor + 3
	if c > s.Limit {
		return false
	}
	s.Cursor = c
	s.iX = s.Cursor
	s.Cursor = v9
	v10 := s.Cursor
	lab12:
	for {
		if s.FindAmong(yiddishA2) == 0 {
			s.Cursor = v10
			break lab12
		}
		break lab12
	}
	v11 := s.Cursor
	lab13:
	for {
		if !s.InGrouping(yiddishGConsonant, 1489, 1520) {
			break lab13
		}
		if !s.InGrouping(yiddishGConsonant, 1489, 1520) {
			break lab13
		}
		if !s.InGrouping(yiddishGConsonant, 1489, 1520) {
			break lab13
		}
		s.iP1 = s.Cursor
		return false
	}
	s.Cursor = v11
golab14:
	for {
		v12 := s.Cursor
		lab15:
		for {
			if !s.InGrouping(yiddishGVowel, 1488, 1522) {
				break lab15
			}
			s.Cursor = v12
			break golab14
		}
		s.Cursor = v12
		if s.Cursor >= s.Limit {
			return false
		}
		s.Cursor++
	}
	for {
		lab16:
		for {
			if !s.InGrouping(yiddishGVowel, 1488, 1522) {
				break lab16
			}
			continue
		}
		break
	}
	s.iP1 = s.Cursor
	lab17:
	for {
		if s.iP1 >= s.iX {
			break lab17
		}
		s.iP1 = s.iX
		break lab17
	}
	return true
}

func (s *YiddishStemmer) rR1() bool {
	return s.iP1 <= s.Cursor
}

func (s *YiddishStemmer) rR1plus3() bool {
	return s.iP1 <= (s.Cursor + 3)
}

// rStandardSuffix removes derivational and inflectional suffixes.
func (s *YiddishStemmer) rStandardSuffix() bool {
	v1 := s.Limit - s.Cursor
	lab0:
	for {
		s.Ket = s.Cursor
		amongVar := s.FindAmongB(yiddishA4)
		if amongVar == 0 {
			break lab0
		}
		s.Bra = s.Cursor
		switch amongVar {
		case 1:
			if !s.rR1() {
				break lab0
			}
			s.SliceDel()
		case 2:
			if !s.rR1() {
				break lab0
			}
			s.SliceFromStr("יע")
		case 3:
			if !s.rR1() {
				break lab0
			}
			s.SliceDel()
			s.Ket = s.Cursor
			amongVar = s.FindAmongB(yiddishA3)
			if amongVar == 0 {
				break lab0
			}
			s.Bra = s.Cursor
			switch amongVar {
			case 1:
				s.SliceFromStr("גײ")
			case 2:
				s.SliceFromStr("נעמ")
			case 3:
				s.SliceFromStr("מײד")
			case 4:
				s.SliceFromStr("בײט")
			case 5:
				s.SliceFromStr("בײס")
			case 6:
				s.SliceFromStr("װײז")
			case 7:
				s.SliceFromStr("טרײב")
			case 8:
				s.SliceFromStr("לײט")
			case 9:
				s.SliceFromStr("קלײב")
			case 10:
				s.SliceFromStr("רײב")
			case 11:
				s.SliceFromStr("רײס")
			case 12:
				s.SliceFromStr("שװײג")
			case 13:
				s.SliceFromStr("שמײס")
			case 14:
				s.SliceFromStr("שנײד")
			case 15:
				s.SliceFromStr("שרײב")
			case 16:
				s.SliceFromStr("בינד")
			case 17:
				s.SliceFromStr("װיטש")
			case 18:
				s.SliceFromStr("זינג")
			case 19:
				s.SliceFromStr("טרינק")
			case 20:
				s.SliceFromStr("צװינג")
			case 21:
				s.SliceFromStr("שלינג")
			case 22:
				s.SliceFromStr("בײג")
			case 23:
				s.SliceFromStr("הײב")
			case 24:
				s.SliceFromStr("פארליר")
			case 25:
				s.SliceFromStr("שטײ")
			case 26:
				s.SliceFromStr("שװער")
			}
		case 4:
			lab1:
			for {
				v2 := s.Limit - s.Cursor
				lab2:
				for {
					if !s.rR1() {
						break lab2
					}
					s.SliceDel()
					break lab1
				}
				s.Cursor = s.Limit - v2
				s.SliceFromStr("ט")
				break lab1
			}
			s.Ket = s.Cursor
			if !s.EqSBStr("בראכ") {
				break lab0
			}
			v3 := s.Limit - s.Cursor
			lab3:
			for {
				if !s.EqSBStr("גע") {
					s.Cursor = s.Limit - v3
					break lab3
				}
				break lab3
			}
			s.Bra = s.Cursor
			s.SliceFromStr("ברענג")
		case 5:
			s.SliceFromStr("גײ")
		case 6:
			s.SliceFromStr("נעמ")
		case 7:
			s.SliceFromStr("שרײב")
		case 8:
			s.SliceFromStr("מײד")
		case 9:
			s.SliceFromStr("בײט")
		case 10:
			s.SliceFromStr("בײס")
		case 11:
			s.SliceFromStr("װײז")
		case 12:
			s.SliceFromStr("טרײב")
		case 13:
			s.SliceFromStr("לײט")
		case 14:
			s.SliceFromStr("קלײב")
		case 15:
			s.SliceFromStr("רײב")
		case 16:
			s.SliceFromStr("רײס")
		case 17:
			s.SliceFromStr("שװײג")
		case 18:
			s.SliceFromStr("שמײס")
		case 19:
			s.SliceFromStr("שנײד")
		case 20:
			s.SliceFromStr("בינד")
		case 21:
			s.SliceFromStr("װיטש")
		case 22:
			s.SliceFromStr("זינג")
		case 23:
			s.SliceFromStr("טרינק")
		case 24:
			s.SliceFromStr("צװינג")
		case 25:
			s.SliceFromStr("שלינג")
		case 26:
			s.SliceFromStr("בײג")
		case 27:
			s.SliceFromStr("הײב")
		case 28:
			s.SliceFromStr("פארליר")
		case 29:
			s.SliceFromStr("שטײ")
		case 30:
			s.SliceFromStr("שװער")
		case 31:
			s.SliceFromStr("ברענג")
		case 32:
			if !s.rR1() {
				break lab0
			}
			s.SliceFromStr("ה")
		case 33:
			lab4:
			for {
				v4 := s.Limit - s.Cursor
				lab5:
				for {
					lab6:
					for {
						v5 := s.Limit - s.Cursor
						lab7:
						for {
							if !s.EqSBStr("ג") {
								break lab7
							}
							break lab6
						}
						s.Cursor = s.Limit - v5
						if !s.EqSBStr("ש") {
							break lab5
						}
						break lab6
					}
					v6 := s.Limit - s.Cursor
					lab8:
					for {
						if !s.rR1plus3() {
							s.Cursor = s.Limit - v6
							break lab8
						}
						s.SliceFromStr("יס")
						break lab8
					}
					break lab4
				}
				s.Cursor = s.Limit - v4
				if !s.rR1() {
					break lab0
				}
				s.SliceDel()
				break lab4
			}
		}
		break lab0
	}
	s.Cursor = s.Limit - v1
	v7 := s.Limit - s.Cursor
	lab9:
	for {
		s.Ket = s.Cursor
		amongVar := s.FindAmongB(yiddishA5)
		if amongVar == 0 {
			break lab9
		}
		s.Bra = s.Cursor
		switch amongVar {
		case 1:
			if !s.rR1() {
				break lab9
			}
			s.SliceDel()
		case 2:
			if !s.rR1() {
				break lab9
			}
			if !s.InGroupingB(yiddishGConsonant, 1489, 1520) {
				break lab9
			}
			s.SliceDel()
		}
		break lab9
	}
	s.Cursor = s.Limit - v7
	v8 := s.Limit - s.Cursor
	lab10:
	for {
		s.Ket = s.Cursor
		amongVar := s.FindAmongB(yiddishA6)
		if amongVar == 0 {
			break lab10
		}
		s.Bra = s.Cursor
		switch amongVar {
		case 1:
			if !s.rR1() {
				break lab10
			}
			s.SliceDel()
		}
		break lab10
	}
	s.Cursor = s.Limit - v8
	v9 := s.Limit - s.Cursor
	lab11:
	for {
		v10 := s.Limit - s.Cursor
	outerLoop11:
		for {
		golab13:
			for {
				v11 := s.Limit - s.Cursor
				lab14:
				for {
					s.Ket = s.Cursor
					lab15:
					for {
						v12 := s.Limit - s.Cursor
						lab16:
						for {
							if !s.EqSBStr("GE") {
								break lab16
							}
							break lab15
						}
						s.Cursor = s.Limit - v12
						if !s.EqSBStr("TSU") {
							break lab14
						}
						break lab15
					}
					s.Bra = s.Cursor
					s.SliceDel()
					s.Cursor = s.Limit - v11
					break golab13
				}
				s.Cursor = s.Limit - v11
				if s.Cursor <= s.LimitBackward {
					s.Cursor = s.Limit - v10
					break lab11
				}
				s.Cursor--
			}
			continue outerLoop11
		}
	}
	s.Cursor = s.Limit - v9
	return true
}

// Stem performs Yiddish stemming.
func (s *YiddishStemmer) Stem() bool {
	s.rPrelude()
	v2 := s.Cursor
	s.rMarkRegions()
	s.Cursor = v2
	s.LimitBackward = s.Cursor
	s.Cursor = s.Limit
	s.rStandardSuffix()
	s.Cursor = s.LimitBackward
	return true
}
