// DO NOT EDIT THE WHITESPACE SET MANUALLY.
// It was generated from ICU4J v77.1.0.0, Unicode version 16.0.0.0, matching
// the Java UnicodeProps generated by "gradlew generateUnicodeProps".

// Copyright 2026 Gocene. All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the LICENSE file.

package util

// UnicodeVersion is the Unicode version used to generate the property tables.
// Mirrors UnicodeProps.UNICODE_VERSION.
const UnicodeVersion = "16.0.0.0"

// whitespaceSet is the set of code points classified as WHITESPACE by Unicode
// (as used by Lucene's CharTokenizer / WhitespaceTokenizer pipeline).
// Source: UnicodeProps.WHITESPACE in Apache Lucene 10.4.0.
var whitespaceSet = map[rune]struct{}{
	0x0009: {}, // CHARACTER TABULATION
	0x000A: {}, // LINE FEED
	0x000B: {}, // LINE TABULATION
	0x000C: {}, // FORM FEED
	0x000D: {}, // CARRIAGE RETURN
	0x0020: {}, // SPACE
	0x0085: {}, // NEXT LINE
	0x00A0: {}, // NO-BREAK SPACE
	0x1680: {}, // OGHAM SPACE MARK
	0x2000: {}, // EN QUAD
	0x2001: {}, // EM QUAD
	0x2002: {}, // EN SPACE
	0x2003: {}, // EM SPACE
	0x2004: {}, // THREE-PER-EM SPACE
	0x2005: {}, // FOUR-PER-EM SPACE
	0x2006: {}, // SIX-PER-EM SPACE
	0x2007: {}, // FIGURE SPACE
	0x2008: {}, // PUNCTUATION SPACE
	0x2009: {}, // THIN SPACE
	0x200A: {}, // HAIR SPACE
	0x2028: {}, // LINE SEPARATOR
	0x2029: {}, // PARAGRAPH SEPARATOR
	0x202F: {}, // NARROW NO-BREAK SPACE
	0x205F: {}, // MEDIUM MATHEMATICAL SPACE
	0x3000: {}, // IDEOGRAPHIC SPACE
}

// IsWhitespace reports whether r is a Unicode WHITESPACE code point as
// defined by the Lucene UnicodeProps table (ICU4J v77.1.0.0, Unicode 16.0.0).
func IsWhitespace(r rune) bool {
	_, ok := whitespaceSet[r]
	return ok
}
